package encapsulationsPrograming;

public class ATMDriver {

	public static void main(String[] args) {
		
		System.out.println("==============================Main Method Starts=====================================");
		
		ATM a1 = new ATM("Mohan Singh", "1234567890123456", "SBI", 1234, 25000.50);
		ATM a2 = new ATM("Rohan Sharma", "2345678901234567", "HDFC", 2345, 50000.00);
		ATM a3 = new ATM("Sohan Kumar", "3456789012345678", "ICICI", 3456, 35000.75);
		ATM a4 = new ATM("Rahul Verma", "4567890123456789", "Axis Bank", 4567, 45000.00);
		ATM a5 = new ATM("Shyam Gupta", "5678901234567890", "PNB", 5678, 60000.25);
		ATM a6 = new ATM("Manoj Singh", "6789012345678901", "SBI", 6789, 75000.50);
		ATM a7 = new ATM("Akash Kumar", "7890123456789012", "HDFC", 7890, 42000.00);
		ATM a8 = new ATM("Samarth Singh", "8901234567890123", "ICICI", 8901, 85000.75);
		ATM a9 = new ATM("Abhishek Sharma", "9012345678901234", "Axis Bank", 9012, 55000.00);
		ATM a10 = new ATM("Karan Singh", "0123456789012345", "PNB", 1122, 95000.50);

		ATM a11 = new ATM("Amit Kumar", "1234509876543210", "SBI", 2233, 32000.25);
		ATM a12 = new ATM("Sumit Verma", "2345610987654321", "HDFC", 3344, 48000.00);
		ATM a13 = new ATM("Ravi Sharma", "3456721098765432", "ICICI", 4455, 57000.75);
		ATM a14 = new ATM("Nitin Gupta", "4567832109876543", "Axis Bank", 5566, 29000.50);
		ATM a15 = new ATM("Varun Singh", "5678943210987654", "PNB", 6677, 68000.00);
		ATM a16 = new ATM("Ankit Kumar", "6789054321098765", "SBI", 7788, 72000.25);
		ATM a17 = new ATM("Deepak Verma", "7890165432109876", "HDFC", 8899, 39000.75);
		ATM a18 = new ATM("Pankaj Sharma", "8901276543210987", "ICICI", 9900, 81000.00);
		ATM a19 = new ATM("Sachin Kumar", "9012387654321098", "Axis Bank", 1357, 44000.50);
		ATM a20 = new ATM("Rakesh Singh", "0123498765432109", "PNB", 2468, 92000.75);

		ATM a21 = new ATM("Vivek Gupta", "1234567809876543", "SBI", 3579, 36000.00);
		ATM a22 = new ATM("Gaurav Sharma", "2345678910987654", "HDFC", 4680, 53000.25);
		ATM a23 = new ATM("Harish Kumar", "3456789021098765", "ICICI", 5791, 76000.50);
		ATM a24 = new ATM("Suresh Verma", "4567890132109876", "Axis Bank", 6802, 41000.75);
		ATM a25 = new ATM("Mahesh Singh", "5678901243210987", "PNB", 7913, 63000.00);
		ATM a26 = new ATM("Yash Kumar", "6789012354321098", "SBI", 8024, 88000.50);
		ATM a27 = new ATM("Ayush Sharma", "7890123465432109", "HDFC", 9135, 35000.25);
		ATM a28 = new ATM("Kunal Verma", "8901234576543210", "ICICI", 1246, 67000.75);
		ATM a29 = new ATM("Rohit Gupta", "9012345687654321", "Axis Bank", 2357, 46000.50);
		ATM a30 = new ATM("Mohit Singh", "0123456798765432", "PNB", 3468, 99000.00);

		ATM a31 = new ATM("Tarun Kumar", "1234567898765432", "SBI", 4579, 38000.75);
		ATM a32 = new ATM("Arjun Sharma", "2345678909876543", "HDFC", 5680, 59000.50);
		ATM a33 = new ATM("Naveen Verma", "3456789010987654", "ICICI", 6791, 78000.00);
		ATM a34 = new ATM("Prakash Singh", "4567890121098765", "Axis Bank", 7802, 43000.25);
		ATM a35 = new ATM("Shubham Kumar", "5678901232109876", "PNB", 8913, 71000.75);
		ATM a36 = new ATM("Aditya Sharma", "6789012343210987", "SBI", 9024, 83000.00);
		ATM a37 = new ATM("Raj Verma", "7890123454321098", "HDFC", 1135, 37000.50);
		ATM a38 = new ATM("Vishal Singh", "8901234565432109", "ICICI", 2246, 65000.25);
		ATM a39 = new ATM("Dev Kumar", "9012345676543210", "Axis Bank", 3357, 49000.75);
		ATM a40 = new ATM("Rajat Sharma", "0123456787654321", "PNB", 4468, 105000.00);

		ATM a41 = new ATM("Mukul Gupta", "1234567890123401", "SBI", 5579, 34000.50);
		ATM a42 = new ATM("Ashish Kumar", "2345678901234512", "HDFC", 6680, 58000.75);
		ATM a43 = new ATM("Lokesh Verma", "3456789012345623", "ICICI", 7791, 87000.00);
		ATM a44 = new ATM("Sanjay Singh", "4567890123456734", "Axis Bank", 8802, 45000.25);
		ATM a45 = new ATM("Manish Kumar", "5678901234567845", "PNB", 9913, 73000.50);
		ATM a46 = new ATM("Rishabh Sharma", "6789012345678956", "SBI", 1024, 91000.75);
		ATM a47 = new ATM("Shivam Gupta", "7890123456789067", "HDFC", 2135, 40000.00);
		ATM a48 = new ATM("Aman Verma", "8901234567890178", "ICICI", 3246, 69000.50);
		ATM a49 = new ATM("Neeraj Singh", "9012345678901289", "Axis Bank", 4357, 52000.25);
		ATM a50 = new ATM("Varun Singh", "0123456789012390", "PNB", 5468, 110000.00);
		
		System.out.println("===========================ATM 1 Details=================================");
		System.out.println("Object Reference is: " + a1);
		System.out.println("Card Holder Name is: " + a1.getCardHolderName());
		System.out.println("Card Number is: " + a1.getCardNumber());
		System.out.println("Bank Name is: " + a1.getBankName());
		System.out.println("Balance is: " + a1.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 1");
		System.out.println("PIN Verification Result: " + a1.verifyPin(1234));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 1");
		a1.deposit(5000);
		System.out.println("Total Balance is: " + a1.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 1");
		a1.withdraw(3000, 1234);
		System.out.println("Total Balance is: " + a1.getBalance());
		System.out.println("=====================================================");
		
		System.out.println("===========================ATM 2 Details=================================");
		System.out.println("Object Reference is: " + a2);
		System.out.println("Card Holder Name is: " + a2.getCardHolderName());
		System.out.println("Card Number is: " + a2.getCardNumber());
		System.out.println("Bank Name is: " + a2.getBankName());
		System.out.println("Balance is: " + a2.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 2");
		System.out.println("PIN Verification Result: " + a2.verifyPin(2345));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 2");
		a2.deposit(6000);
		System.out.println("Total Balance is: " + a2.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 2");
		a2.withdraw(3500, 2345);
		System.out.println("Total Balance is: " + a2.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 3 Details=================================");
		System.out.println("Object Reference is: " + a3);
		System.out.println("Card Holder Name is: " + a3.getCardHolderName());
		System.out.println("Card Number is: " + a3.getCardNumber());
		System.out.println("Bank Name is: " + a3.getBankName());
		System.out.println("Balance is: " + a3.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 3");
		System.out.println("PIN Verification Result: " + a3.verifyPin(3456));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 3");
		a3.deposit(7000);
		System.out.println("Total Balance is: " + a3.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 3");
		a3.withdraw(4000, 3456);
		System.out.println("Total Balance is: " + a3.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 4 Details=================================");
		System.out.println("Object Reference is: " + a4);
		System.out.println("Card Holder Name is: " + a4.getCardHolderName());
		System.out.println("Card Number is: " + a4.getCardNumber());
		System.out.println("Bank Name is: " + a4.getBankName());
		System.out.println("Balance is: " + a4.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 4");
		System.out.println("PIN Verification Result: " + a4.verifyPin(4567));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 4");
		a4.deposit(8000);
		System.out.println("Total Balance is: " + a4.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 4");
		a4.withdraw(4500, 4567);
		System.out.println("Total Balance is: " + a4.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 5 Details=================================");
		System.out.println("Object Reference is: " + a5);
		System.out.println("Card Holder Name is: " + a5.getCardHolderName());
		System.out.println("Card Number is: " + a5.getCardNumber());
		System.out.println("Bank Name is: " + a5.getBankName());
		System.out.println("Balance is: " + a5.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 5");
		System.out.println("PIN Verification Result: " + a5.verifyPin(5678));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 5");
		a5.deposit(9000);
		System.out.println("Total Balance is: " + a5.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 5");
		a5.withdraw(5000, 5678);
		System.out.println("Total Balance is: " + a5.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 6 Details=================================");
		System.out.println("Object Reference is: " + a6);
		System.out.println("Card Holder Name is: " + a6.getCardHolderName());
		System.out.println("Card Number is: " + a6.getCardNumber());
		System.out.println("Bank Name is: " + a6.getBankName());
		System.out.println("Balance is: " + a6.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 6");
		System.out.println("PIN Verification Result: " + a6.verifyPin(6789));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 6");
		a6.deposit(10000);
		System.out.println("Total Balance is: " + a6.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 6");
		a6.withdraw(5500, 6789);
		System.out.println("Total Balance is: " + a6.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 7 Details=================================");
		System.out.println("Object Reference is: " + a7);
		System.out.println("Card Holder Name is: " + a7.getCardHolderName());
		System.out.println("Card Number is: " + a7.getCardNumber());
		System.out.println("Bank Name is: " + a7.getBankName());
		System.out.println("Balance is: " + a7.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 7");
		System.out.println("PIN Verification Result: " + a7.verifyPin(7890));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 7");
		a7.deposit(11000);
		System.out.println("Total Balance is: " + a7.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 7");
		a7.withdraw(6000, 7890);
		System.out.println("Total Balance is: " + a7.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 8 Details=================================");
		System.out.println("Object Reference is: " + a8);
		System.out.println("Card Holder Name is: " + a8.getCardHolderName());
		System.out.println("Card Number is: " + a8.getCardNumber());
		System.out.println("Bank Name is: " + a8.getBankName());
		System.out.println("Balance is: " + a8.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 8");
		System.out.println("PIN Verification Result: " + a8.verifyPin(8901));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 8");
		a8.deposit(12000);
		System.out.println("Total Balance is: " + a8.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 8");
		a8.withdraw(6500, 8901);
		System.out.println("Total Balance is: " + a8.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 9 Details=================================");
		System.out.println("Object Reference is: " + a9);
		System.out.println("Card Holder Name is: " + a9.getCardHolderName());
		System.out.println("Card Number is: " + a9.getCardNumber());
		System.out.println("Bank Name is: " + a9.getBankName());
		System.out.println("Balance is: " + a9.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 9");
		System.out.println("PIN Verification Result: " + a9.verifyPin(9012));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 9");
		a9.deposit(13000);
		System.out.println("Total Balance is: " + a9.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 9");
		a9.withdraw(7000, 9012);
		System.out.println("Total Balance is: " + a9.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 10 Details=================================");
		System.out.println("Object Reference is: " + a10);
		System.out.println("Card Holder Name is: " + a10.getCardHolderName());
		System.out.println("Card Number is: " + a10.getCardNumber());
		System.out.println("Bank Name is: " + a10.getBankName());
		System.out.println("Balance is: " + a10.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 10");
		System.out.println("PIN Verification Result: " + a10.verifyPin(1122));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 10");
		a10.deposit(14000);
		System.out.println("Total Balance is: " + a10.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 10");
		a10.withdraw(7500, 1122);
		System.out.println("Total Balance is: " + a10.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 11 Details=================================");
		System.out.println("Object Reference is: " + a11);
		System.out.println("Card Holder Name is: " + a11.getCardHolderName());
		System.out.println("Card Number is: " + a11.getCardNumber());
		System.out.println("Bank Name is: " + a11.getBankName());
		System.out.println("Balance is: " + a11.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 11");
		System.out.println("PIN Verification Result: " + a11.verifyPin(2233));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 11");
		a11.deposit(15000);
		System.out.println("Total Balance is: " + a11.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 11");
		a11.withdraw(8000, 2233);
		System.out.println("Total Balance is: " + a11.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 12 Details=================================");
		System.out.println("Object Reference is: " + a12);
		System.out.println("Card Holder Name is: " + a12.getCardHolderName());
		System.out.println("Card Number is: " + a12.getCardNumber());
		System.out.println("Bank Name is: " + a12.getBankName());
		System.out.println("Balance is: " + a12.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 12");
		System.out.println("PIN Verification Result: " + a12.verifyPin(3344));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 12");
		a12.deposit(16000);
		System.out.println("Total Balance is: " + a12.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 12");
		a12.withdraw(8500, 3344);
		System.out.println("Total Balance is: " + a12.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 13 Details=================================");
		System.out.println("Object Reference is: " + a13);
		System.out.println("Card Holder Name is: " + a13.getCardHolderName());
		System.out.println("Card Number is: " + a13.getCardNumber());
		System.out.println("Bank Name is: " + a13.getBankName());
		System.out.println("Balance is: " + a13.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 13");
		System.out.println("PIN Verification Result: " + a13.verifyPin(4455));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 13");
		a13.deposit(17000);
		System.out.println("Total Balance is: " + a13.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 13");
		a13.withdraw(9000, 4455);
		System.out.println("Total Balance is: " + a13.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 14 Details=================================");
		System.out.println("Object Reference is: " + a14);
		System.out.println("Card Holder Name is: " + a14.getCardHolderName());
		System.out.println("Card Number is: " + a14.getCardNumber());
		System.out.println("Bank Name is: " + a14.getBankName());
		System.out.println("Balance is: " + a14.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 14");
		System.out.println("PIN Verification Result: " + a14.verifyPin(5566));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 14");
		a14.deposit(18000);
		System.out.println("Total Balance is: " + a14.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 14");
		a14.withdraw(9500, 5566);
		System.out.println("Total Balance is: " + a14.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 15 Details=================================");
		System.out.println("Object Reference is: " + a15);
		System.out.println("Card Holder Name is: " + a15.getCardHolderName());
		System.out.println("Card Number is: " + a15.getCardNumber());
		System.out.println("Bank Name is: " + a15.getBankName());
		System.out.println("Balance is: " + a15.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 15");
		System.out.println("PIN Verification Result: " + a15.verifyPin(6677));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 15");
		a15.deposit(19000);
		System.out.println("Total Balance is: " + a15.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 15");
		a15.withdraw(10000, 6677);
		System.out.println("Total Balance is: " + a15.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 16 Details=================================");
		System.out.println("Object Reference is: " + a16);
		System.out.println("Card Holder Name is: " + a16.getCardHolderName());
		System.out.println("Card Number is: " + a16.getCardNumber());
		System.out.println("Bank Name is: " + a16.getBankName());
		System.out.println("Balance is: " + a16.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 16");
		System.out.println("PIN Verification Result: " + a16.verifyPin(7788));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 16");
		a16.deposit(20000);
		System.out.println("Total Balance is: " + a16.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 16");
		a16.withdraw(10500, 7788);
		System.out.println("Total Balance is: " + a16.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 17 Details=================================");
		System.out.println("Object Reference is: " + a17);
		System.out.println("Card Holder Name is: " + a17.getCardHolderName());
		System.out.println("Card Number is: " + a17.getCardNumber());
		System.out.println("Bank Name is: " + a17.getBankName());
		System.out.println("Balance is: " + a17.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 17");
		System.out.println("PIN Verification Result: " + a17.verifyPin(8899));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 17");
		a17.deposit(21000);
		System.out.println("Total Balance is: " + a17.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 17");
		a17.withdraw(11000, 8899);
		System.out.println("Total Balance is: " + a17.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 18 Details=================================");
		System.out.println("Object Reference is: " + a18);
		System.out.println("Card Holder Name is: " + a18.getCardHolderName());
		System.out.println("Card Number is: " + a18.getCardNumber());
		System.out.println("Bank Name is: " + a18.getBankName());
		System.out.println("Balance is: " + a18.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 18");
		System.out.println("PIN Verification Result: " + a18.verifyPin(9900));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 18");
		a18.deposit(22000);
		System.out.println("Total Balance is: " + a18.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 18");
		a18.withdraw(11500, 9900);
		System.out.println("Total Balance is: " + a18.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 19 Details=================================");
		System.out.println("Object Reference is: " + a19);
		System.out.println("Card Holder Name is: " + a19.getCardHolderName());
		System.out.println("Card Number is: " + a19.getCardNumber());
		System.out.println("Bank Name is: " + a19.getBankName());
		System.out.println("Balance is: " + a19.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 19");
		System.out.println("PIN Verification Result: " + a19.verifyPin(1357));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 19");
		a19.deposit(23000);
		System.out.println("Total Balance is: " + a19.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 19");
		a19.withdraw(12000, 1357);
		System.out.println("Total Balance is: " + a19.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 20 Details=================================");
		System.out.println("Object Reference is: " + a20);
		System.out.println("Card Holder Name is: " + a20.getCardHolderName());
		System.out.println("Card Number is: " + a20.getCardNumber());
		System.out.println("Bank Name is: " + a20.getBankName());
		System.out.println("Balance is: " + a20.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 20");
		System.out.println("PIN Verification Result: " + a20.verifyPin(2468));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 20");
		a20.deposit(24000);
		System.out.println("Total Balance is: " + a20.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 20");
		a20.withdraw(12500, 2468);
		System.out.println("Total Balance is: " + a20.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 21 Details=================================");
		System.out.println("Object Reference is: " + a21);
		System.out.println("Card Holder Name is: " + a21.getCardHolderName());
		System.out.println("Card Number is: " + a21.getCardNumber());
		System.out.println("Bank Name is: " + a21.getBankName());
		System.out.println("Balance is: " + a21.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 21");
		System.out.println("PIN Verification Result: " + a21.verifyPin(3579));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 21");
		a21.deposit(25000);
		System.out.println("Total Balance is: " + a21.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 21");
		a21.withdraw(13000, 3579);
		System.out.println("Total Balance is: " + a21.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 22 Details=================================");
		System.out.println("Object Reference is: " + a22);
		System.out.println("Card Holder Name is: " + a22.getCardHolderName());
		System.out.println("Card Number is: " + a22.getCardNumber());
		System.out.println("Bank Name is: " + a22.getBankName());
		System.out.println("Balance is: " + a22.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 22");
		System.out.println("PIN Verification Result: " + a22.verifyPin(4680));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 22");
		a22.deposit(26000);
		System.out.println("Total Balance is: " + a22.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 22");
		a22.withdraw(13500, 4680);
		System.out.println("Total Balance is: " + a22.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 23 Details=================================");
		System.out.println("Object Reference is: " + a23);
		System.out.println("Card Holder Name is: " + a23.getCardHolderName());
		System.out.println("Card Number is: " + a23.getCardNumber());
		System.out.println("Bank Name is: " + a23.getBankName());
		System.out.println("Balance is: " + a23.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 23");
		System.out.println("PIN Verification Result: " + a23.verifyPin(5791));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 23");
		a23.deposit(27000);
		System.out.println("Total Balance is: " + a23.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 23");
		a23.withdraw(14000, 5791);
		System.out.println("Total Balance is: " + a23.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 24 Details=================================");
		System.out.println("Object Reference is: " + a24);
		System.out.println("Card Holder Name is: " + a24.getCardHolderName());
		System.out.println("Card Number is: " + a24.getCardNumber());
		System.out.println("Bank Name is: " + a24.getBankName());
		System.out.println("Balance is: " + a24.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 24");
		System.out.println("PIN Verification Result: " + a24.verifyPin(6802));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 24");
		a24.deposit(28000);
		System.out.println("Total Balance is: " + a24.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 24");
		a24.withdraw(14500, 6802);
		System.out.println("Total Balance is: " + a24.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 25 Details=================================");
		System.out.println("Object Reference is: " + a25);
		System.out.println("Card Holder Name is: " + a25.getCardHolderName());
		System.out.println("Card Number is: " + a25.getCardNumber());
		System.out.println("Bank Name is: " + a25.getBankName());
		System.out.println("Balance is: " + a25.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 25");
		System.out.println("PIN Verification Result: " + a25.verifyPin(7913));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 25");
		a25.deposit(29000);
		System.out.println("Total Balance is: " + a25.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 25");
		a25.withdraw(15000, 7913);
		System.out.println("Total Balance is: " + a25.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 26 Details=================================");
		System.out.println("Object Reference is: " + a26);
		System.out.println("Card Holder Name is: " + a26.getCardHolderName());
		System.out.println("Card Number is: " + a26.getCardNumber());
		System.out.println("Bank Name is: " + a26.getBankName());
		System.out.println("Balance is: " + a26.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 26");
		System.out.println("PIN Verification Result: " + a26.verifyPin(8024));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 26");
		a26.deposit(30000);
		System.out.println("Total Balance is: " + a26.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 26");
		a26.withdraw(15500, 8024);
		System.out.println("Total Balance is: " + a26.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 27 Details=================================");
		System.out.println("Object Reference is: " + a27);
		System.out.println("Card Holder Name is: " + a27.getCardHolderName());
		System.out.println("Card Number is: " + a27.getCardNumber());
		System.out.println("Bank Name is: " + a27.getBankName());
		System.out.println("Balance is: " + a27.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 27");
		System.out.println("PIN Verification Result: " + a27.verifyPin(9135));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 27");
		a27.deposit(31000);
		System.out.println("Total Balance is: " + a27.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 27");
		a27.withdraw(16000, 9135);
		System.out.println("Total Balance is: " + a27.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 28 Details=================================");
		System.out.println("Object Reference is: " + a28);
		System.out.println("Card Holder Name is: " + a28.getCardHolderName());
		System.out.println("Card Number is: " + a28.getCardNumber());
		System.out.println("Bank Name is: " + a28.getBankName());
		System.out.println("Balance is: " + a28.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 28");
		System.out.println("PIN Verification Result: " + a28.verifyPin(1246));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 28");
		a28.deposit(32000);
		System.out.println("Total Balance is: " + a28.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 28");
		a28.withdraw(16500, 1246);
		System.out.println("Total Balance is: " + a28.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 29 Details=================================");
		System.out.println("Object Reference is: " + a29);
		System.out.println("Card Holder Name is: " + a29.getCardHolderName());
		System.out.println("Card Number is: " + a29.getCardNumber());
		System.out.println("Bank Name is: " + a29.getBankName());
		System.out.println("Balance is: " + a29.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 29");
		System.out.println("PIN Verification Result: " + a29.verifyPin(2357));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 29");
		a29.deposit(33000);
		System.out.println("Total Balance is: " + a29.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 29");
		a29.withdraw(17000, 2357);
		System.out.println("Total Balance is: " + a29.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 30 Details=================================");
		System.out.println("Object Reference is: " + a30);
		System.out.println("Card Holder Name is: " + a30.getCardHolderName());
		System.out.println("Card Number is: " + a30.getCardNumber());
		System.out.println("Bank Name is: " + a30.getBankName());
		System.out.println("Balance is: " + a30.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 30");
		System.out.println("PIN Verification Result: " + a30.verifyPin(3468));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 30");
		a30.deposit(34000);
		System.out.println("Total Balance is: " + a30.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 30");
		a30.withdraw(17500, 3468);
		System.out.println("Total Balance is: " + a30.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 31 Details=================================");
		System.out.println("Object Reference is: " + a31);
		System.out.println("Card Holder Name is: " + a31.getCardHolderName());
		System.out.println("Card Number is: " + a31.getCardNumber());
		System.out.println("Bank Name is: " + a31.getBankName());
		System.out.println("Balance is: " + a31.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 31");
		System.out.println("PIN Verification Result: " + a31.verifyPin(4579));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 31");
		a31.deposit(35000);
		System.out.println("Total Balance is: " + a31.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 31");
		a31.withdraw(18000, 4579);
		System.out.println("Total Balance is: " + a31.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 32 Details=================================");
		System.out.println("Object Reference is: " + a32);
		System.out.println("Card Holder Name is: " + a32.getCardHolderName());
		System.out.println("Card Number is: " + a32.getCardNumber());
		System.out.println("Bank Name is: " + a32.getBankName());
		System.out.println("Balance is: " + a32.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 32");
		System.out.println("PIN Verification Result: " + a32.verifyPin(5680));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 32");
		a32.deposit(36000);
		System.out.println("Total Balance is: " + a32.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 32");
		a32.withdraw(18500, 5680);
		System.out.println("Total Balance is: " + a32.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 33 Details=================================");
		System.out.println("Object Reference is: " + a33);
		System.out.println("Card Holder Name is: " + a33.getCardHolderName());
		System.out.println("Card Number is: " + a33.getCardNumber());
		System.out.println("Bank Name is: " + a33.getBankName());
		System.out.println("Balance is: " + a33.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 33");
		System.out.println("PIN Verification Result: " + a33.verifyPin(6791));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 33");
		a33.deposit(37000);
		System.out.println("Total Balance is: " + a33.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 33");
		a33.withdraw(19000, 6791);
		System.out.println("Total Balance is: " + a33.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 34 Details=================================");
		System.out.println("Object Reference is: " + a34);
		System.out.println("Card Holder Name is: " + a34.getCardHolderName());
		System.out.println("Card Number is: " + a34.getCardNumber());
		System.out.println("Bank Name is: " + a34.getBankName());
		System.out.println("Balance is: " + a34.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 34");
		System.out.println("PIN Verification Result: " + a34.verifyPin(7802));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 34");
		a34.deposit(38000);
		System.out.println("Total Balance is: " + a34.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 34");
		a34.withdraw(19500, 7802);
		System.out.println("Total Balance is: " + a34.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 35 Details=================================");
		System.out.println("Object Reference is: " + a35);
		System.out.println("Card Holder Name is: " + a35.getCardHolderName());
		System.out.println("Card Number is: " + a35.getCardNumber());
		System.out.println("Bank Name is: " + a35.getBankName());
		System.out.println("Balance is: " + a35.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 35");
		System.out.println("PIN Verification Result: " + a35.verifyPin(8913));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 35");
		a35.deposit(39000);
		System.out.println("Total Balance is: " + a35.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 35");
		a35.withdraw(20000, 8913);
		System.out.println("Total Balance is: " + a35.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 36 Details=================================");
		System.out.println("Object Reference is: " + a36);
		System.out.println("Card Holder Name is: " + a36.getCardHolderName());
		System.out.println("Card Number is: " + a36.getCardNumber());
		System.out.println("Bank Name is: " + a36.getBankName());
		System.out.println("Balance is: " + a36.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 36");
		System.out.println("PIN Verification Result: " + a36.verifyPin(9024));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 36");
		a36.deposit(40000);
		System.out.println("Total Balance is: " + a36.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 36");
		a36.withdraw(20500, 9024);
		System.out.println("Total Balance is: " + a36.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 37 Details=================================");
		System.out.println("Object Reference is: " + a37);
		System.out.println("Card Holder Name is: " + a37.getCardHolderName());
		System.out.println("Card Number is: " + a37.getCardNumber());
		System.out.println("Bank Name is: " + a37.getBankName());
		System.out.println("Balance is: " + a37.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 37");
		System.out.println("PIN Verification Result: " + a37.verifyPin(1135));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 37");
		a37.deposit(41000);
		System.out.println("Total Balance is: " + a37.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 37");
		a37.withdraw(21000, 1135);
		System.out.println("Total Balance is: " + a37.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 38 Details=================================");
		System.out.println("Object Reference is: " + a38);
		System.out.println("Card Holder Name is: " + a38.getCardHolderName());
		System.out.println("Card Number is: " + a38.getCardNumber());
		System.out.println("Bank Name is: " + a38.getBankName());
		System.out.println("Balance is: " + a38.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 38");
		System.out.println("PIN Verification Result: " + a38.verifyPin(2246));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 38");
		a38.deposit(42000);
		System.out.println("Total Balance is: " + a38.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 38");
		a38.withdraw(21500, 2246);
		System.out.println("Total Balance is: " + a38.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 39 Details=================================");
		System.out.println("Object Reference is: " + a39);
		System.out.println("Card Holder Name is: " + a39.getCardHolderName());
		System.out.println("Card Number is: " + a39.getCardNumber());
		System.out.println("Bank Name is: " + a39.getBankName());
		System.out.println("Balance is: " + a39.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 39");
		System.out.println("PIN Verification Result: " + a39.verifyPin(3357));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 39");
		a39.deposit(43000);
		System.out.println("Total Balance is: " + a39.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 39");
		a39.withdraw(22000, 3357);
		System.out.println("Total Balance is: " + a39.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 40 Details=================================");
		System.out.println("Object Reference is: " + a40);
		System.out.println("Card Holder Name is: " + a40.getCardHolderName());
		System.out.println("Card Number is: " + a40.getCardNumber());
		System.out.println("Bank Name is: " + a40.getBankName());
		System.out.println("Balance is: " + a40.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 40");
		System.out.println("PIN Verification Result: " + a40.verifyPin(4468));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 40");
		a40.deposit(44000);
		System.out.println("Total Balance is: " + a40.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 40");
		a40.withdraw(22500, 4468);
		System.out.println("Total Balance is: " + a40.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 41 Details=================================");
		System.out.println("Object Reference is: " + a41);
		System.out.println("Card Holder Name is: " + a41.getCardHolderName());
		System.out.println("Card Number is: " + a41.getCardNumber());
		System.out.println("Bank Name is: " + a41.getBankName());
		System.out.println("Balance is: " + a41.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 41");
		System.out.println("PIN Verification Result: " + a41.verifyPin(5579));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 41");
		a41.deposit(45000);
		System.out.println("Total Balance is: " + a41.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 41");
		a41.withdraw(23000, 5579);
		System.out.println("Total Balance is: " + a41.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 42 Details=================================");
		System.out.println("Object Reference is: " + a42);
		System.out.println("Card Holder Name is: " + a42.getCardHolderName());
		System.out.println("Card Number is: " + a42.getCardNumber());
		System.out.println("Bank Name is: " + a42.getBankName());
		System.out.println("Balance is: " + a42.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 42");
		System.out.println("PIN Verification Result: " + a42.verifyPin(6680));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 42");
		a42.deposit(46000);
		System.out.println("Total Balance is: " + a42.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 42");
		a42.withdraw(23500, 6680);
		System.out.println("Total Balance is: " + a42.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 43 Details=================================");
		System.out.println("Object Reference is: " + a43);
		System.out.println("Card Holder Name is: " + a43.getCardHolderName());
		System.out.println("Card Number is: " + a43.getCardNumber());
		System.out.println("Bank Name is: " + a43.getBankName());
		System.out.println("Balance is: " + a43.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 43");
		System.out.println("PIN Verification Result: " + a43.verifyPin(7791));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 43");
		a43.deposit(47000);
		System.out.println("Total Balance is: " + a43.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 43");
		a43.withdraw(24000, 7791);
		System.out.println("Total Balance is: " + a43.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 44 Details=================================");
		System.out.println("Object Reference is: " + a44);
		System.out.println("Card Holder Name is: " + a44.getCardHolderName());
		System.out.println("Card Number is: " + a44.getCardNumber());
		System.out.println("Bank Name is: " + a44.getBankName());
		System.out.println("Balance is: " + a44.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 44");
		System.out.println("PIN Verification Result: " + a44.verifyPin(8802));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 44");
		a44.deposit(48000);
		System.out.println("Total Balance is: " + a44.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 44");
		a44.withdraw(24500, 8802);
		System.out.println("Total Balance is: " + a44.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 45 Details=================================");
		System.out.println("Object Reference is: " + a45);
		System.out.println("Card Holder Name is: " + a45.getCardHolderName());
		System.out.println("Card Number is: " + a45.getCardNumber());
		System.out.println("Bank Name is: " + a45.getBankName());
		System.out.println("Balance is: " + a45.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 45");
		System.out.println("PIN Verification Result: " + a45.verifyPin(9913));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 45");
		a45.deposit(49000);
		System.out.println("Total Balance is: " + a45.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 45");
		a45.withdraw(25000, 9913);
		System.out.println("Total Balance is: " + a45.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 46 Details=================================");
		System.out.println("Object Reference is: " + a46);
		System.out.println("Card Holder Name is: " + a46.getCardHolderName());
		System.out.println("Card Number is: " + a46.getCardNumber());
		System.out.println("Bank Name is: " + a46.getBankName());
		System.out.println("Balance is: " + a46.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 46");
		System.out.println("PIN Verification Result: " + a46.verifyPin(1024));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 46");
		a46.deposit(50000);
		System.out.println("Total Balance is: " + a46.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 46");
		a46.withdraw(25500, 1024);
		System.out.println("Total Balance is: " + a46.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 47 Details=================================");
		System.out.println("Object Reference is: " + a47);
		System.out.println("Card Holder Name is: " + a47.getCardHolderName());
		System.out.println("Card Number is: " + a47.getCardNumber());
		System.out.println("Bank Name is: " + a47.getBankName());
		System.out.println("Balance is: " + a47.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 47");
		System.out.println("PIN Verification Result: " + a47.verifyPin(2135));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 47");
		a47.deposit(51000);
		System.out.println("Total Balance is: " + a47.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 47");
		a47.withdraw(26000, 2135);
		System.out.println("Total Balance is: " + a47.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 48 Details=================================");
		System.out.println("Object Reference is: " + a48);
		System.out.println("Card Holder Name is: " + a48.getCardHolderName());
		System.out.println("Card Number is: " + a48.getCardNumber());
		System.out.println("Bank Name is: " + a48.getBankName());
		System.out.println("Balance is: " + a48.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 48");
		System.out.println("PIN Verification Result: " + a48.verifyPin(3246));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 48");
		a48.deposit(52000);
		System.out.println("Total Balance is: " + a48.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 48");
		a48.withdraw(26500, 3246);
		System.out.println("Total Balance is: " + a48.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 49 Details=================================");
		System.out.println("Object Reference is: " + a49);
		System.out.println("Card Holder Name is: " + a49.getCardHolderName());
		System.out.println("Card Number is: " + a49.getCardNumber());
		System.out.println("Bank Name is: " + a49.getBankName());
		System.out.println("Balance is: " + a49.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 49");
		System.out.println("PIN Verification Result: " + a49.verifyPin(4357));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 49");
		a49.deposit(53000);
		System.out.println("Total Balance is: " + a49.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 49");
		a49.withdraw(27000, 4357);
		System.out.println("Total Balance is: " + a49.getBalance());
		System.out.println("=====================================================");

		System.out.println("===========================ATM 50 Details=================================");
		System.out.println("Object Reference is: " + a50);
		System.out.println("Card Holder Name is: " + a50.getCardHolderName());
		System.out.println("Card Number is: " + a50.getCardNumber());
		System.out.println("Bank Name is: " + a50.getBankName());
		System.out.println("Balance is: " + a50.getBalance());
		System.out.println("=====================================================");
		System.out.println("Verifying PIN of Account 50");
		System.out.println("PIN Verification Result: " + a50.verifyPin(5468));
		System.out.println("=====================================================");
		System.out.println("Depositing Amount In Account 50");
		a50.deposit(54000);
		System.out.println("Total Balance is: " + a50.getBalance());
		System.out.println("=====================================================");
		System.out.println("Withdrawing Amount From Account 50");
		a50.withdraw(27500, 5468);
		System.out.println("Total Balance is: " + a50.getBalance());
		System.out.println("=====================================================");
		
		System.out.println("============================Main Method Ends====================================");

	}

}
