package encapsulationsPrograming;

public class BankAccount1Driver {
	
	public static void main(String[] args) {
		
		System.out.println("==================================Main Method Starts===========================================");
		
		BankAccount1 a1 = new BankAccount1("Mohan", "ACC101", "Savings", "Noida", 25000.50);
		BankAccount1 a2 = new BankAccount1("Rohan", "ACC102", "Current", "Lucknow", 50000.00);
		BankAccount1 a3 = new BankAccount1("Sohan", "ACC103", "Savings", "Kanpur", 35000.75);
		BankAccount1 a4 = new BankAccount1("Rahul", "ACC104", "Salary", "Pune", 45000.00);
		BankAccount1 a5 = new BankAccount1("Shyam", "ACC105", "Savings", "Mumbai", 60000.25);
		BankAccount1 a6 = new BankAccount1("Manoj", "ACC106", "Current", "Delhi", 75000.00);
		BankAccount1 a7 = new BankAccount1("Akash", "ACC107", "Savings", "Meerut", 42000.50);
		BankAccount1 a8 = new BankAccount1("Samarth", "ACC108", "Salary", "Noida", 85000.00);
		BankAccount1 a9 = new BankAccount1("Abhishek", "ACC109", "Savings", "Ahmedabad", 55000.75);
		BankAccount1 a10 = new BankAccount1("Karan Singh", "ACC110", "Current", "Gurugram", 95000.00);

		BankAccount1 a11 = new BankAccount1("Amit", "ACC111", "Savings", "Varanasi", 32000.50);
		BankAccount1 a12 = new BankAccount1("Sumit", "ACC112", "Current", "Agra", 48000.00);
		BankAccount1 a13 = new BankAccount1("Ravi", "ACC113", "Salary", "Jaipur", 57000.25);
		BankAccount1 a14 = new BankAccount1("Nitin", "ACC114", "Savings", "Indore", 29000.75);
		BankAccount1 a15 = new BankAccount1("Varun", "ACC115", "Current", "Bhopal", 68000.00);
		BankAccount1 a16 = new BankAccount1("Ankit", "ACC116", "Salary", "Patna", 72000.50);
		BankAccount1 a17 = new BankAccount1("Deepak", "ACC117", "Savings", "Ranchi", 39000.25);
		BankAccount1 a18 = new BankAccount1("Pankaj", "ACC118", "Current", "Chandigarh", 81000.00);
		BankAccount1 a19 = new BankAccount1("Sachin", "ACC119", "Savings", "Amritsar", 44000.75);
		BankAccount1 a20 = new BankAccount1("Rakesh", "ACC120", "Salary", "Faridabad", 92000.50);

		BankAccount1 a21 = new BankAccount1("Vivek", "ACC121", "Savings", "Gurugram", 36000.00);
		BankAccount1 a22 = new BankAccount1("Gaurav", "ACC122", "Current", "Meerut", 53000.25);
		BankAccount1 a23 = new BankAccount1("Harish", "ACC123", "Salary", "Lucknow", 76000.00);
		BankAccount1 a24 = new BankAccount1("Suresh", "ACC124", "Savings", "Kanpur", 41000.50);
		BankAccount1 a25 = new BankAccount1("Mahesh", "ACC125", "Current", "Mumbai", 63000.75);
		BankAccount1 a26 = new BankAccount1("Yash", "ACC126", "Salary", "Delhi", 88000.00);
		BankAccount1 a27 = new BankAccount1("Ayush", "ACC127", "Savings", "Pune", 35000.25);
		BankAccount1 a28 = new BankAccount1("Kunal", "ACC128", "Current", "Noida", 67000.50);
		BankAccount1 a29 = new BankAccount1("Rohit", "ACC129", "Savings", "Jaipur", 46000.00);
		BankAccount1 a30 = new BankAccount1("Mohit", "ACC130", "Salary", "Bhopal", 99000.75);

		BankAccount1 a31 = new BankAccount1("Tarun", "ACC131", "Savings", "Indore", 38000.50);
		BankAccount1 a32 = new BankAccount1("Arjun", "ACC132", "Current", "Patna", 59000.00);
		BankAccount1 a33 = new BankAccount1("Naveen", "ACC133", "Salary", "Ranchi", 78000.25);
		BankAccount1 a34 = new BankAccount1("Prakash", "ACC134", "Savings", "Chandigarh", 43000.75);
		BankAccount1 a35 = new BankAccount1("Shubham", "ACC135", "Current", "Varanasi", 71000.50);
		BankAccount1 a36 = new BankAccount1("Aditya", "ACC136", "Salary", "Agra", 83000.00);
		BankAccount1 a37 = new BankAccount1("Raj", "ACC137", "Savings", "Delhi", 37000.25);
		BankAccount1 a38 = new BankAccount1("Vishal", "ACC138", "Current", "Noida", 65000.75);
		BankAccount1 a39 = new BankAccount1("Dev", "ACC139", "Savings", "Lucknow", 49000.50);
		BankAccount1 a40 = new BankAccount1("Rajat", "ACC140", "Salary", "Kanpur", 105000.00);

		BankAccount1 a41 = new BankAccount1("Mukul", "ACC141", "Savings", "Mumbai", 34000.75);
		BankAccount1 a42 = new BankAccount1("Ashish", "ACC142", "Current", "Pune", 58000.50);
		BankAccount1 a43 = new BankAccount1("Lokesh", "ACC143", "Salary", "Gurugram", 87000.00);
		BankAccount1 a44 = new BankAccount1("Sanjay", "ACC144", "Savings", "Faridabad", 45000.25);
		BankAccount1 a45 = new BankAccount1("Manish", "ACC145", "Current", "Meerut", 73000.75);
		BankAccount1 a46 = new BankAccount1("Rishabh", "ACC146", "Salary", "Noida", 91000.50);
		BankAccount1 a47 = new BankAccount1("Shivam", "ACC147", "Savings", "Delhi", 40000.00);
		BankAccount1 a48 = new BankAccount1("Aman", "ACC148", "Current", "Agra", 69000.25);
		BankAccount1 a49 = new BankAccount1("Neeraj", "ACC149", "Savings", "Lucknow", 52000.75);
		BankAccount1 a50 = new BankAccount1("Varun Singh", "ACC150", "Salary", "Gurugram", 110000.00);
		
				
		System.out.println("==============================BankAccount 1 Details==================================");
		System.out.println("Object Reference is: " +a1);
		System.out.println("Account Holder Name is: " +a1.getAccountHolderName());
		System.out.println("Account Number is: " +a1.getAccountNumber());
		System.out.println("AccountType is: " +a1.getAccountType());
		System.out.println("Branch Name is: " +a1.getBranch());
		System.out.println("Balance is: " +a1.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 1");
		a1.deposit(5000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a1.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 2 Details==================================");
		System.out.println("Object Reference is: " +a2);
		System.out.println("Account Holder Name is: " +a2.getAccountHolderName());
		System.out.println("Account Number is: " +a2.getAccountNumber());
		System.out.println("AccountType is: " +a2.getAccountType());
		System.out.println("Branch Name is: " +a2.getBranch());
		System.out.println("Balance is: " +a2.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 2");
		a2.deposit(6000);
		a1.withdrawl(2000);
		System.out.println("Total Balance is: " +a2.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 3 Details==================================");
		System.out.println("Object Reference is: " +a3);
		System.out.println("Account Holder Name is: " +a3.getAccountHolderName());
		System.out.println("Account Number is: " +a3.getAccountNumber());
		System.out.println("AccountType is: " +a3.getAccountType());
		System.out.println("Branch Name is: " +a3.getBranch());
		System.out.println("Balance is: " +a3.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 3");
		a3.deposit(7000);
		a1.withdrawl(3000);
		System.out.println("Total Balance is: " +a3.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 4 Details==================================");
		System.out.println("Object Reference is: " +a4);
		System.out.println("Account Holder Name is: " +a4.getAccountHolderName());
		System.out.println("Account Number is: " +a4.getAccountNumber());
		System.out.println("AccountType is: " +a4.getAccountType());
		System.out.println("Branch Name is: " +a4.getBranch());
		System.out.println("Balance is: " +a4.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 4");
		a4.deposit(8000);
		a1.withdrawl(4000);
		System.out.println("Total Balance is: " +a4.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 5 Details==================================");
		System.out.println("Object Reference is: " +a5);
		System.out.println("Account Holder Name is: " +a5.getAccountHolderName());
		System.out.println("Account Number is: " +a5.getAccountNumber());
		System.out.println("AccountType is: " +a5.getAccountType());
		System.out.println("Branch Name is: " +a5.getBranch());
		System.out.println("Balance is: " +a5.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 5");
		a5.deposit(9000);
		a1.withdrawl(5000);
		System.out.println("Total Balance is: " +a5.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 6 Details==================================");
		System.out.println("Object Reference is: " +a6);
		System.out.println("Account Holder Name is: " +a6.getAccountHolderName());
		System.out.println("Account Number is: " +a6.getAccountNumber());
		System.out.println("AccountType is: " +a6.getAccountType());
		System.out.println("Branch Name is: " +a6.getBranch());
		System.out.println("Balance is: " +a6.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 6");
		a6.deposit(10000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a6.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 7 Details==================================");
		System.out.println("Object Reference is: " +a7);
		System.out.println("Account Holder Name is: " +a7.getAccountHolderName());
		System.out.println("Account Number is: " +a7.getAccountNumber());
		System.out.println("AccountType is: " +a7.getAccountType());
		System.out.println("Branch Name is: " +a7.getBranch());
		System.out.println("Balance is: " +a7.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 7");
		a7.deposit(11000);
		a1.withdrawl(2000);
		System.out.println("Total Balance is: " +a7.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 8 Details==================================");
		System.out.println("Object Reference is: " +a8);
		System.out.println("Account Holder Name is: " +a8.getAccountHolderName());
		System.out.println("Account Number is: " +a8.getAccountNumber());
		System.out.println("AccountType is: " +a8.getAccountType());
		System.out.println("Branch Name is: " +a8.getBranch());
		System.out.println("Balance is: " +a8.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 8");
		a8.deposit(12000);
		a1.withdrawl(3000);
		System.out.println("Total Balance is: " +a8.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 9 Details==================================");
		System.out.println("Object Reference is: " +a9);
		System.out.println("Account Holder Name is: " +a9.getAccountHolderName());
		System.out.println("Account Number is: " +a9.getAccountNumber());
		System.out.println("AccountType is: " +a9.getAccountType());
		System.out.println("Branch Name is: " +a9.getBranch());
		System.out.println("Balance is: " +a9.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 9");
		a9.deposit(13000);
		a1.withdrawl(4000);
		System.out.println("Total Balance is: " +a9.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 10 Details==================================");
		System.out.println("Object Reference is: " +a10);
		System.out.println("Account Holder Name is: " +a10.getAccountHolderName());
		System.out.println("Account Number is: " +a10.getAccountNumber());
		System.out.println("AccountType is: " +a10.getAccountType());
		System.out.println("Branch Name is: " +a10.getBranch());
		System.out.println("Balance is: " +a10.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 10");
		a10.deposit(14000);
		a1.withdrawl(5000);
		System.out.println("Total Balance is: " +a10.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 11 Details==================================");
		System.out.println("Object Reference is: " +a11);
		System.out.println("Account Holder Name is: " +a11.getAccountHolderName());
		System.out.println("Account Number is: " +a11.getAccountNumber());
		System.out.println("AccountType is: " +a11.getAccountType());
		System.out.println("Branch Name is: " +a11.getBranch());
		System.out.println("Balance is: " +a11.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 11");
		a11.deposit(15000);
		a1.withdrawl(3000);
		System.out.println("Total Balance is: " +a11.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 12 Details==================================");
		System.out.println("Object Reference is: " +a12);
		System.out.println("Account Holder Name is: " +a12.getAccountHolderName());
		System.out.println("Account Number is: " +a12.getAccountNumber());
		System.out.println("AccountType is: " +a12.getAccountType());
		System.out.println("Branch Name is: " +a12.getBranch());
		System.out.println("Balance is: " +a12.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 12");
		a12.deposit(16000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a12.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 13 Details==================================");
		System.out.println("Object Reference is: " +a13);
		System.out.println("Account Holder Name is: " +a13.getAccountHolderName());
		System.out.println("Account Number is: " +a13.getAccountNumber());
		System.out.println("AccountType is: " +a13.getAccountType());
		System.out.println("Branch Name is: " +a13.getBranch());
		System.out.println("Balance is: " +a13.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 13");
		a13.deposit(17000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a13.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 14 Details==================================");
		System.out.println("Object Reference is: " +a14);
		System.out.println("Account Holder Name is: " +a14.getAccountHolderName());
		System.out.println("Account Number is: " +a14.getAccountNumber());
		System.out.println("AccountType is: " +a14.getAccountType());
		System.out.println("Branch Name is: " +a14.getBranch());
		System.out.println("Balance is: " +a14.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 14");
		a14.deposit(18000);
		a1.withdrawl(2000);
		System.out.println("Total Balance is: " +a14.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 15 Details==================================");
		System.out.println("Object Reference is: " +a15);
		System.out.println("Account Holder Name is: " +a15.getAccountHolderName());
		System.out.println("Account Number is: " +a15.getAccountNumber());
		System.out.println("AccountType is: " +a15.getAccountType());
		System.out.println("Branch Name is: " +a15.getBranch());
		System.out.println("Balance is: " +a15.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 15");
		a15.deposit(19000);
		a1.withdrawl(6000);
		System.out.println("Total Balance is: " +a15.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 16 Details==================================");
		System.out.println("Object Reference is: " +a16);
		System.out.println("Account Holder Name is: " +a16.getAccountHolderName());
		System.out.println("Account Number is: " +a16.getAccountNumber());
		System.out.println("AccountType is: " +a16.getAccountType());
		System.out.println("Branch Name is: " +a16.getBranch());
		System.out.println("Balance is: " +a16.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 16");
		a16.deposit(20000);
		a1.withdrawl(5000);
		System.out.println("Total Balance is: " +a16.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 17 Details==================================");
		System.out.println("Object Reference is: " +a17);
		System.out.println("Account Holder Name is: " +a17.getAccountHolderName());
		System.out.println("Account Number is: " +a17.getAccountNumber());
		System.out.println("AccountType is: " +a17.getAccountType());
		System.out.println("Branch Name is: " +a17.getBranch());
		System.out.println("Balance is: " +a17.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 17");
		a17.deposit(21000);
		a1.withdrawl(7000);
		System.out.println("Total Balance is: " +a17.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 18 Details==================================");
		System.out.println("Object Reference is: " +a18);
		System.out.println("Account Holder Name is: " +a18.getAccountHolderName());
		System.out.println("Account Number is: " +a18.getAccountNumber());
		System.out.println("AccountType is: " +a18.getAccountType());
		System.out.println("Branch Name is: " +a18.getBranch());
		System.out.println("Balance is: " +a18.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 18");
		a18.deposit(22000);
		a1.withdrawl(6000);
		System.out.println("Total Balance is: " +a18.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 19 Details==================================");
		System.out.println("Object Reference is: " +a19);
		System.out.println("Account Holder Name is: " +a19.getAccountHolderName());
		System.out.println("Account Number is: " +a19.getAccountNumber());
		System.out.println("AccountType is: " +a19.getAccountType());
		System.out.println("Branch Name is: " +a19.getBranch());
		System.out.println("Balance is: " +a19.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 19");
		a19.deposit(23000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a19.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 20 Details==================================");
		System.out.println("Object Reference is: " +a20);
		System.out.println("Account Holder Name is: " +a20.getAccountHolderName());
		System.out.println("Account Number is: " +a20.getAccountNumber());
		System.out.println("AccountType is: " +a20.getAccountType());
		System.out.println("Branch Name is: " +a20.getBranch());
		System.out.println("Balance is: " +a20.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 20");
		a20.deposit(24000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a20.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 21 Details==================================");
		System.out.println("Object Reference is: " +a21);
		System.out.println("Account Holder Name is: " +a21.getAccountHolderName());
		System.out.println("Account Number is: " +a21.getAccountNumber());
		System.out.println("AccountType is: " +a21.getAccountType());
		System.out.println("Branch Name is: " +a21.getBranch());
		System.out.println("Balance is: " +a21.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 21");
		a21.deposit(25000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a21.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 22 Details==================================");
		System.out.println("Object Reference is: " +a22);
		System.out.println("Account Holder Name is: " +a22.getAccountHolderName());
		System.out.println("Account Number is: " +a22.getAccountNumber());
		System.out.println("AccountType is: " +a22.getAccountType());
		System.out.println("Branch Name is: " +a22.getBranch());
		System.out.println("Balance is: " +a22.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 22");
		a22.deposit(26000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a22.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 23 Details==================================");
		System.out.println("Object Reference is: " +a23);
		System.out.println("Account Holder Name is: " +a23.getAccountHolderName());
		System.out.println("Account Number is: " +a23.getAccountNumber());
		System.out.println("AccountType is: " +a23.getAccountType());
		System.out.println("Branch Name is: " +a23.getBranch());
		System.out.println("Balance is: " +a23.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 23");
		a23.deposit(27000);
		a1.withdrawl(8000);
		System.out.println("Total Balance is: " +a23.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 24 Details==================================");
		System.out.println("Object Reference is: " +a24);
		System.out.println("Account Holder Name is: " +a24.getAccountHolderName());
		System.out.println("Account Number is: " +a24.getAccountNumber());
		System.out.println("AccountType is: " +a24.getAccountType());
		System.out.println("Branch Name is: " +a24.getBranch());
		System.out.println("Balance is: " +a24.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 24");
		a24.deposit(28000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a24.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 25 Details==================================");
		System.out.println("Object Reference is: " +a25);
		System.out.println("Account Holder Name is: " +a25.getAccountHolderName());
		System.out.println("Account Number is: " +a25.getAccountNumber());
		System.out.println("AccountType is: " +a25.getAccountType());
		System.out.println("Branch Name is: " +a25.getBranch());
		System.out.println("Balance is: " +a25.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 25");
		a25.deposit(29000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a25.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 26 Details==================================");
		System.out.println("Object Reference is: " +a26);
		System.out.println("Account Holder Name is: " +a26.getAccountHolderName());
		System.out.println("Account Number is: " +a26.getAccountNumber());
		System.out.println("AccountType is: " +a26.getAccountType());
		System.out.println("Branch Name is: " +a26.getBranch());
		System.out.println("Balance is: " +a26.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 26");
		a26.deposit(30000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a26.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 27 Details==================================");
		System.out.println("Object Reference is: " +a27);
		System.out.println("Account Holder Name is: " +a27.getAccountHolderName());
		System.out.println("Account Number is: " +a27.getAccountNumber());
		System.out.println("AccountType is: " +a27.getAccountType());
		System.out.println("Branch Name is: " +a27.getBranch());
		System.out.println("Balance is: " +a27.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 27");
		a27.deposit(31000);
		a1.withdrawl(2000);
		System.out.println("Total Balance is: " +a27.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 28 Details==================================");
		System.out.println("Object Reference is: " +a28);
		System.out.println("Account Holder Name is: " +a28.getAccountHolderName());
		System.out.println("Account Number is: " +a28.getAccountNumber());
		System.out.println("AccountType is: " +a28.getAccountType());
		System.out.println("Branch Name is: " +a28.getBranch());
		System.out.println("Balance is: " +a28.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 28");
		a28.deposit(32000);
		a1.withdrawl(6000);
		System.out.println("Total Balance is: " +a28.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 29 Details==================================");
		System.out.println("Object Reference is: " +a29);
		System.out.println("Account Holder Name is: " +a29.getAccountHolderName());
		System.out.println("Account Number is: " +a29.getAccountNumber());
		System.out.println("AccountType is: " +a29.getAccountType());
		System.out.println("Branch Name is: " +a29.getBranch());
		System.out.println("Balance is: " +a29.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 29");
		a29.deposit(33000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a29.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 30 Details==================================");
		System.out.println("Object Reference is: " +a30);
		System.out.println("Account Holder Name is: " +a30.getAccountHolderName());
		System.out.println("Account Number is: " +a30.getAccountNumber());
		System.out.println("AccountType is: " +a30.getAccountType());
		System.out.println("Branch Name is: " +a30.getBranch());
		System.out.println("Balance is: " +a30.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 30");
		a30.deposit(34000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a30.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 31 Details==================================");
		System.out.println("Object Reference is: " +a31);
		System.out.println("Account Holder Name is: " +a31.getAccountHolderName());
		System.out.println("Account Number is: " +a31.getAccountNumber());
		System.out.println("AccountType is: " +a31.getAccountType());
		System.out.println("Branch Name is: " +a31.getBranch());
		System.out.println("Balance is: " +a31.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 31");
		a31.deposit(35000);
		a1.withdrawl(9000);
		System.out.println("Total Balance is: " +a31.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 32 Details==================================");
		System.out.println("Object Reference is: " +a32);
		System.out.println("Account Holder Name is: " +a32.getAccountHolderName());
		System.out.println("Account Number is: " +a32.getAccountNumber());
		System.out.println("AccountType is: " +a32.getAccountType());
		System.out.println("Branch Name is: " +a32.getBranch());
		System.out.println("Balance is: " +a32.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 32");
		a32.deposit(36000);
		a1.withdrawl(10000);
		System.out.println("Total Balance is: " +a32.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 33 Details==================================");
		System.out.println("Object Reference is: " +a33);
		System.out.println("Account Holder Name is: " +a33.getAccountHolderName());
		System.out.println("Account Number is: " +a33.getAccountNumber());
		System.out.println("AccountType is: " +a33.getAccountType());
		System.out.println("Branch Name is: " +a33.getBranch());
		System.out.println("Balance is: " +a33.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 33");
		a33.deposit(37000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a33.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 34 Details==================================");
		System.out.println("Object Reference is: " +a34);
		System.out.println("Account Holder Name is: " +a34.getAccountHolderName());
		System.out.println("Account Number is: " +a34.getAccountNumber());
		System.out.println("AccountType is: " +a34.getAccountType());
		System.out.println("Branch Name is: " +a34.getBranch());
		System.out.println("Balance is: " +a34.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 34");
		a34.deposit(38000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a34.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 35 Details==================================");
		System.out.println("Object Reference is: " +a35);
		System.out.println("Account Holder Name is: " +a35.getAccountHolderName());
		System.out.println("Account Number is: " +a35.getAccountNumber());
		System.out.println("AccountType is: " +a35.getAccountType());
		System.out.println("Branch Name is: " +a35.getBranch());
		System.out.println("Balance is: " +a35.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 35");
		a35.deposit(39000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a35.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 36 Details==================================");
		System.out.println("Object Reference is: " +a36);
		System.out.println("Account Holder Name is: " +a36.getAccountHolderName());
		System.out.println("Account Number is: " +a36.getAccountNumber());
		System.out.println("AccountType is: " +a36.getAccountType());
		System.out.println("Branch Name is: " +a36.getBranch());
		System.out.println("Balance is: " +a36.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 36");
		a36.deposit(40000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a36.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 37 Details==================================");
		System.out.println("Object Reference is: " +a37);
		System.out.println("Account Holder Name is: " +a37.getAccountHolderName());
		System.out.println("Account Number is: " +a37.getAccountNumber());
		System.out.println("AccountType is: " +a37.getAccountType());
		System.out.println("Branch Name is: " +a37.getBranch());
		System.out.println("Balance is: " +a37.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 37");
		a37.deposit(41000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a37.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 38 Details==================================");
		System.out.println("Object Reference is: " +a38);
		System.out.println("Account Holder Name is: " +a38.getAccountHolderName());
		System.out.println("Account Number is: " +a38.getAccountNumber());
		System.out.println("AccountType is: " +a38.getAccountType());
		System.out.println("Branch Name is: " +a38.getBranch());
		System.out.println("Balance is: " +a38.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 38");
		a38.deposit(42000);
		a1.withdrawl(7000);
		System.out.println("Total Balance is: " +a38.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 39 Details==================================");
		System.out.println("Object Reference is: " +a39);
		System.out.println("Account Holder Name is: " +a39.getAccountHolderName());
		System.out.println("Account Number is: " +a39.getAccountNumber());
		System.out.println("AccountType is: " +a39.getAccountType());
		System.out.println("Branch Name is: " +a39.getBranch());
		System.out.println("Balance is: " +a39.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 39");
		a39.deposit(43000);
		a1.withdrawl(11000);
		System.out.println("Total Balance is: " +a39.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 40 Details==================================");
		System.out.println("Object Reference is: " +a40);
		System.out.println("Account Holder Name is: " +a40.getAccountHolderName());
		System.out.println("Account Number is: " +a40.getAccountNumber());
		System.out.println("AccountType is: " +a40.getAccountType());
		System.out.println("Branch Name is: " +a40.getBranch());
		System.out.println("Balance is: " +a40.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 40");
		a40.deposit(44000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a40.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 41 Details==================================");
		System.out.println("Object Reference is: " +a41);
		System.out.println("Account Holder Name is: " +a41.getAccountHolderName());
		System.out.println("Account Number is: " +a41.getAccountNumber());
		System.out.println("AccountType is: " +a41.getAccountType());
		System.out.println("Branch Name is: " +a41.getBranch());
		System.out.println("Balance is: " +a41.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 41");
		a41.deposit(45000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a41.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 42 Details==================================");
		System.out.println("Object Reference is: " +a42);
		System.out.println("Account Holder Name is: " +a42.getAccountHolderName());
		System.out.println("Account Number is: " +a42.getAccountNumber());
		System.out.println("AccountType is: " +a42.getAccountType());
		System.out.println("Branch Name is: " +a42.getBranch());
		System.out.println("Balance is: " +a42.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 42");
		a42.deposit(46000);
		a1.withdrawl(12000);
		System.out.println("Total Balance is: " +a42.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 43 Details==================================");
		System.out.println("Object Reference is: " +a43);
		System.out.println("Account Holder Name is: " +a43.getAccountHolderName());
		System.out.println("Account Number is: " +a43.getAccountNumber());
		System.out.println("AccountType is: " +a43.getAccountType());
		System.out.println("Branch Name is: " +a43.getBranch());
		System.out.println("Balance is: " +a43.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 43");
		a43.deposit(47000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a43.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 44 Details==================================");
		System.out.println("Object Reference is: " +a44);
		System.out.println("Account Holder Name is: " +a44.getAccountHolderName());
		System.out.println("Account Number is: " +a44.getAccountNumber());
		System.out.println("AccountType is: " +a44.getAccountType());
		System.out.println("Branch Name is: " +a44.getBranch());
		System.out.println("Balance is: " +a44.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 44");
		a44.deposit(48000);
		a1.withdrawl(6000);
		System.out.println("Total Balance is: " +a44.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 45 Details==================================");
		System.out.println("Object Reference is: " +a45);
		System.out.println("Account Holder Name is: " +a45.getAccountHolderName());
		System.out.println("Account Number is: " +a45.getAccountNumber());
		System.out.println("AccountType is: " +a45.getAccountType());
		System.out.println("Branch Name is: " +a45.getBranch());
		System.out.println("Balance is: " +a45.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 45");
		a45.deposit(49000);
		a1.withdrawl(8000);
		System.out.println("Total Balance is: " +a45.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 46 Details==================================");
		System.out.println("Object Reference is: " +a46);
		System.out.println("Account Holder Name is: " +a46.getAccountHolderName());
		System.out.println("Account Number is: " +a46.getAccountNumber());
		System.out.println("AccountType is: " +a46.getAccountType());
		System.out.println("Branch Name is: " +a46.getBranch());
		System.out.println("Balance is: " +a46.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 46");
		a46.deposit(50000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a46.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 47 Details==================================");
		System.out.println("Object Reference is: " +a47);
		System.out.println("Account Holder Name is: " +a47.getAccountHolderName());
		System.out.println("Account Number is: " +a47.getAccountNumber());
		System.out.println("AccountType is: " +a47.getAccountType());
		System.out.println("Branch Name is: " +a47.getBranch());
		System.out.println("Balance is: " +a47.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 47");
		a47.deposit(51000);
		a1.withdrawl(1000);
		System.out.println("Total Balance is: " +a47.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 48 Details==================================");
		System.out.println("Object Reference is: " +a48);
		System.out.println("Account Holder Name is: " +a48.getAccountHolderName());
		System.out.println("Account Number is: " +a48.getAccountNumber());
		System.out.println("AccountType is: " +a48.getAccountType());
		System.out.println("Branch Name is: " +a48.getBranch());
		System.out.println("Balance is: " +a48.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 48");
		a48.deposit(52000);
		a1.withdrawl(8000);
		System.out.println("Total Balance is: " +a48.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 49 Details==================================");
		System.out.println("Object Reference is: " +a49);
		System.out.println("Account Holder Name is: " +a49.getAccountHolderName());
		System.out.println("Account Number is: " +a49.getAccountNumber());
		System.out.println("AccountType is: " +a49.getAccountType());
		System.out.println("Branch Name is: " +a49.getBranch());
		System.out.println("Balance is: " +a49.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 49");
		a49.deposit(53000);
		a1.withdrawl(21000);
		System.out.println("Total Balance is: " +a49.getBalance());
		System.out.println("=====================================================");

		System.out.println("==============================BankAccount 50 Details==================================");
		System.out.println("Object Reference is: " +a50);
		System.out.println("Account Holder Name is: " +a50.getAccountHolderName());
		System.out.println("Account Number is: " +a50.getAccountNumber());
		System.out.println("AccountType is: " +a50.getAccountType());
		System.out.println("Branch Name is: " +a50.getBranch());
		System.out.println("Balance is: " +a50.getBalance());
		System.out.println("=====================================================");
		System.out.println("Deposited Amount In Account 50");
		a50.deposit(54000);
		a1.withdrawl(30000);
		System.out.println("Total Balance is: " +a50.getBalance());
		System.out.println("=====================================================");
		
		System.out.println("====================================Main Method Ends======================================");
	}

}
