package encapsulationsPrograming;

public class HospitalManagementDrver {

	public static void main(String[] args) {
		
		System.out.println("======================================Main Method Starts==========================================");
		
		HospitalManagement h1 = new HospitalManagement("Mohan Singh", "PAT101", 35, "Fever", "Dr. Sharma", "DOC101", "Cardiologist", 1500.00, "Private Room", true);
		HospitalManagement h2 = new HospitalManagement("Rohan Kumar", "PAT102", 42, "Diabetes", "Dr. Verma", "DOC102", "Endocrinologist", 1800.00, "General Ward", true);
		HospitalManagement h3 = new HospitalManagement("Sohan Sharma", "PAT103", 28, "Migraine", "Dr. Gupta", "DOC103", "Neurologist", 2000.00, "Private Room", false);
		HospitalManagement h4 = new HospitalManagement("Rahul Singh", "PAT104", 50, "Heart Problem", "Dr. Mehta", "DOC104", "Cardiologist", 2500.00, "ICU", true);
		HospitalManagement h5 = new HospitalManagement("Shyam Gupta", "PAT105", 31, "Asthma", "Dr. Kapoor", "DOC105", "Pulmonologist", 1700.00, "General Ward", false);
		HospitalManagement h6 = new HospitalManagement("Manoj Kumar", "PAT106", 45, "Arthritis", "Dr. Singh", "DOC106", "Orthopedic", 1600.00, "Private Room", true);
		HospitalManagement h7 = new HospitalManagement("Akash Verma", "PAT107", 23, "Skin Allergy", "Dr. Rao", "DOC107", "Dermatologist", 1200.00, "General Ward", false);
		HospitalManagement h8 = new HospitalManagement("Samarth Singh", "PAT108", 38, "Kidney Problem", "Dr. Mishra", "DOC108", "Nephrologist", 2200.00, "Private Room", true);
		HospitalManagement h9 = new HospitalManagement("Abhishek Kumar", "PAT109", 29, "Eye Problem", "Dr. Tiwari", "DOC109", "Ophthalmologist", 1300.00, "General Ward", false);
		HospitalManagement h10 = new HospitalManagement("Karan Singh", "PAT110", 55, "Chest Pain", "Dr. Sharma", "DOC110", "Cardiologist", 2500.00, "ICU", true);

		HospitalManagement h11 = new HospitalManagement("Aman Sharma", "PAT111", 34, "Fever", "Dr. Verma", "DOC111", "General Physician", 1000.00, "General Ward", false);
		HospitalManagement h12 = new HospitalManagement("Ravi Kumar", "PAT112", 47, "Hypertension", "Dr. Gupta", "DOC112", "Cardiologist", 1900.00, "Private Room", true);
		HospitalManagement h13 = new HospitalManagement("Pankaj Verma", "PAT113", 26, "Back Pain", "Dr. Mehta", "DOC113", "Orthopedic", 1500.00, "General Ward", false);
		HospitalManagement h14 = new HospitalManagement("Nitin Sharma", "PAT114", 52, "Lung Infection", "Dr. Kapoor", "DOC114", "Pulmonologist", 2100.00, "Private Room", true);
		HospitalManagement h15 = new HospitalManagement("Varun Gupta", "PAT115", 30, "Stomach Pain", "Dr. Singh", "DOC115", "Gastroenterologist", 1800.00, "General Ward", false);
		HospitalManagement h16 = new HospitalManagement("Ankit Kumar", "PAT116", 41, "Kidney Stone", "Dr. Mishra", "DOC116", "Urologist", 2300.00, "Private Room", true);
		HospitalManagement h17 = new HospitalManagement("Deepak Sharma", "PAT117", 36, "Dental Pain", "Dr. Rao", "DOC117", "Dentist", 900.00, "General Ward", false);
		HospitalManagement h18 = new HospitalManagement("Rakesh Verma", "PAT118", 49, "Thyroid", "Dr. Tiwari", "DOC118", "Endocrinologist", 1750.00, "Private Room", true);
		HospitalManagement h19 = new HospitalManagement("Suresh Kumar", "PAT119", 57, "Heart Blockage", "Dr. Sharma", "DOC119", "Cardiologist", 3000.00, "ICU", true);
		HospitalManagement h20 = new HospitalManagement("Rajesh Singh", "PAT120", 33, "Food Allergy", "Dr. Verma", "DOC120", "Allergist", 1250.00, "General Ward", false);

		HospitalManagement h21 = new HospitalManagement("Mohit Sharma", "PAT121", 27, "Anxiety", "Dr. Gupta", "DOC121", "Psychiatrist", 2200.00, "Private Room", false);
		HospitalManagement h22 = new HospitalManagement("Vikas Kumar", "PAT122", 44, "Knee Pain", "Dr. Mehta", "DOC122", "Orthopedic", 1650.00, "General Ward", true);
		HospitalManagement h23 = new HospitalManagement("Amit Verma", "PAT123", 39, "Liver Problem", "Dr. Kapoor", "DOC123", "Hepatologist", 2400.00, "Private Room", true);
		HospitalManagement h24 = new HospitalManagement("Sanjay Sharma", "PAT124", 61, "Blood Pressure", "Dr. Singh", "DOC124", "Cardiologist", 2000.00, "ICU", true);
		HospitalManagement h25 = new HospitalManagement("Ravi Singh", "PAT125", 25, "Cold and Cough", "Dr. Mishra", "DOC125", "General Physician", 850.00, "General Ward", false);
		HospitalManagement h26 = new HospitalManagement("Ashish Kumar", "PAT126", 48, "Skin Infection", "Dr. Rao", "DOC126", "Dermatologist", 1400.00, "Private Room", true);
		HospitalManagement h27 = new HospitalManagement("Neeraj Verma", "PAT127", 32, "Headache", "Dr. Tiwari", "DOC127", "Neurologist", 1950.00, "General Ward", false);
		HospitalManagement h28 = new HospitalManagement("Piyush Sharma", "PAT128", 54, "Diabetes", "Dr. Sharma", "DOC128", "Endocrinologist", 1850.00, "Private Room", true);
		HospitalManagement h29 = new HospitalManagement("Kunal Gupta", "PAT129", 37, "Fracture", "Dr. Verma", "DOC129", "Orthopedic", 1750.00, "General Ward", true);
		HospitalManagement h30 = new HospitalManagement("Manish Singh", "PAT130", 43, "Breathing Problem", "Dr. Gupta", "DOC130", "Pulmonologist", 2100.00, "ICU", true);

		HospitalManagement h31 = new HospitalManagement("Lokesh Kumar", "PAT131", 29, "Gastritis", "Dr. Mehta", "DOC131", "Gastroenterologist", 1550.00, "General Ward", false);
		HospitalManagement h32 = new HospitalManagement("Arjun Verma", "PAT132", 46, "Kidney Disease", "Dr. Kapoor", "DOC132", "Nephrologist", 2250.00, "Private Room", true);
		HospitalManagement h33 = new HospitalManagement("Akhil Sharma", "PAT133", 24, "Dental Infection", "Dr. Singh", "DOC133", "Dentist", 950.00, "General Ward", false);
		HospitalManagement h34 = new HospitalManagement("Sandeep Kumar", "PAT134", 58, "Chest Pain", "Dr. Mishra", "DOC134", "Cardiologist", 2700.00, "ICU", true);
		HospitalManagement h35 = new HospitalManagement("Mukesh Verma", "PAT135", 35, "Migraine", "Dr. Rao", "DOC135", "Neurologist", 1850.00, "Private Room", false);
		HospitalManagement h36 = new HospitalManagement("Yogesh Singh", "PAT136", 40, "High Sugar", "Dr. Tiwari", "DOC136", "Endocrinologist", 1650.00, "General Ward", true);
		HospitalManagement h37 = new HospitalManagement("Nikhil Kumar", "PAT137", 22, "Skin Allergy", "Dr. Sharma", "DOC137", "Dermatologist", 1150.00, "General Ward", false);
		HospitalManagement h38 = new HospitalManagement("Gaurav Sharma", "PAT138", 51, "Liver Infection", "Dr. Verma", "DOC138", "Hepatologist", 2350.00, "Private Room", true);
		HospitalManagement h39 = new HospitalManagement("Rajat Verma", "PAT139", 31, "Back Injury", "Dr. Gupta", "DOC139", "Orthopedic", 1450.00, "General Ward", false);
		HospitalManagement h40 = new HospitalManagement("Chetan Kumar", "PAT140", 63, "Heart Problem", "Dr. Mehta", "DOC140", "Cardiologist", 2900.00, "ICU", true);

		HospitalManagement h41 = new HospitalManagement("Vishal Sharma", "PAT141", 28, "Fever", "Dr. Kapoor", "DOC141", "General Physician", 950.00, "General Ward", false);
		HospitalManagement h42 = new HospitalManagement("Pawan Singh", "PAT142", 45, "Kidney Stone", "Dr. Singh", "DOC142", "Urologist", 2150.00, "Private Room", true);
		HospitalManagement h43 = new HospitalManagement("Suraj Kumar", "PAT143", 52, "Asthma", "Dr. Mishra", "DOC143", "Pulmonologist", 1750.00, "General Ward", false);
		HospitalManagement h44 = new HospitalManagement("Dev Sharma", "PAT144", 33, "Thyroid", "Dr. Rao", "DOC144", "Endocrinologist", 1600.00, "Private Room", true);
		HospitalManagement h45 = new HospitalManagement("Akhilesh Verma", "PAT145", 39, "Arthritis", "Dr. Tiwari", "DOC145", "Orthopedic", 1550.00, "General Ward", false);
		HospitalManagement h46 = new HospitalManagement("Ramesh Kumar", "PAT146", 56, "Hypertension", "Dr. Sharma", "DOC146", "Cardiologist", 2050.00, "Private Room", true);
		HospitalManagement h47 = new HospitalManagement("Shivam Singh", "PAT147", 26, "Eye Problem", "Dr. Verma", "DOC147", "Ophthalmologist", 1350.00, "General Ward", false);
		HospitalManagement h48 = new HospitalManagement("Prakash Kumar", "PAT148", 48, "Diabetes", "Dr. Gupta", "DOC148", "Endocrinologist", 1900.00, "Private Room", true);
		HospitalManagement h49 = new HospitalManagement("Harish Sharma", "PAT149", 42, "Stomach Infection", "Dr. Mehta", "DOC149", "Gastroenterologist", 1700.00, "General Ward", false);
		HospitalManagement h50 = new HospitalManagement("Vijay Verma", "PAT150", 60, "Heart Blockage", "Dr. Kapoor", "DOC150", "Cardiologist", 3100.00, "ICU", true);
		
				
		System.out.println("=========================Hospital Management Details 1===========================");
		System.out.println("Object Reference is: " + h1);
		System.out.println("Patient Name is: " + h1.getPatientName());
		System.out.println("Patient ID is: " + h1.getPatientID());
		System.out.println("Patient Age is: " + h1.getPatientAge());
		System.out.println("Disease is: " + h1.getDisease());
		System.out.println("Doctor Name is: " + h1.getDoctorName());
		System.out.println("Doctor ID is: " + h1.getDoctorID());
		System.out.println("Specialization is: " + h1.getSpecialization());
		System.out.println("Consultation Fee is: " + h1.getConsultationFee());
		System.out.println("Room Type is: " + h1.getRoomType());
		System.out.println("Admitted Status is: " + h1.getAdmitted());
		System.out.println("Patient Status is: " + h1.getPatientStatus());

		System.out.println("=========================Hospital Management Details 2===========================");
		System.out.println("Object Reference is: " + h2);
		System.out.println("Patient Name is: " + h2.getPatientName());
		System.out.println("Patient ID is: " + h2.getPatientID());
		System.out.println("Patient Age is: " + h2.getPatientAge());
		System.out.println("Disease is: " + h2.getDisease());
		System.out.println("Doctor Name is: " + h2.getDoctorName());
		System.out.println("Doctor ID is: " + h2.getDoctorID());
		System.out.println("Specialization is: " + h2.getSpecialization());
		System.out.println("Consultation Fee is: " + h2.getConsultationFee());
		System.out.println("Room Type is: " + h2.getRoomType());
		System.out.println("Admitted Status is: " + h2.getAdmitted());
		System.out.println("Patient Status is: " + h2.getPatientStatus());

		System.out.println("=========================Hospital Management Details 3===========================");
		System.out.println("Object Reference is: " + h3);
		System.out.println("Patient Name is: " + h3.getPatientName());
		System.out.println("Patient ID is: " + h3.getPatientID());
		System.out.println("Patient Age is: " + h3.getPatientAge());
		System.out.println("Disease is: " + h3.getDisease());
		System.out.println("Doctor Name is: " + h3.getDoctorName());
		System.out.println("Doctor ID is: " + h3.getDoctorID());
		System.out.println("Specialization is: " + h3.getSpecialization());
		System.out.println("Consultation Fee is: " + h3.getConsultationFee());
		System.out.println("Room Type is: " + h3.getRoomType());
		System.out.println("Admitted Status is: " + h3.getAdmitted());
		System.out.println("Patient Status is: " + h3.getPatientStatus());

		System.out.println("=========================Hospital Management Details 4===========================");
		System.out.println("Object Reference is: " + h4);
		System.out.println("Patient Name is: " + h4.getPatientName());
		System.out.println("Patient ID is: " + h4.getPatientID());
		System.out.println("Patient Age is: " + h4.getPatientAge());
		System.out.println("Disease is: " + h4.getDisease());
		System.out.println("Doctor Name is: " + h4.getDoctorName());
		System.out.println("Doctor ID is: " + h4.getDoctorID());
		System.out.println("Specialization is: " + h4.getSpecialization());
		System.out.println("Consultation Fee is: " + h4.getConsultationFee());
		System.out.println("Room Type is: " + h4.getRoomType());
		System.out.println("Admitted Status is: " + h4.getAdmitted());
		System.out.println("Patient Status is: " + h4.getPatientStatus());

		System.out.println("=========================Hospital Management Details 5===========================");
		System.out.println("Object Reference is: " + h5);
		System.out.println("Patient Name is: " + h5.getPatientName());
		System.out.println("Patient ID is: " + h5.getPatientID());
		System.out.println("Patient Age is: " + h5.getPatientAge());
		System.out.println("Disease is: " + h5.getDisease());
		System.out.println("Doctor Name is: " + h5.getDoctorName());
		System.out.println("Doctor ID is: " + h5.getDoctorID());
		System.out.println("Specialization is: " + h5.getSpecialization());
		System.out.println("Consultation Fee is: " + h5.getConsultationFee());
		System.out.println("Room Type is: " + h5.getRoomType());
		System.out.println("Admitted Status is: " + h5.getAdmitted());
		System.out.println("Patient Status is: " + h5.getPatientStatus());

		System.out.println("=========================Hospital Management Details 6===========================");
		System.out.println("Object Reference is: " + h6);
		System.out.println("Patient Name is: " + h6.getPatientName());
		System.out.println("Patient ID is: " + h6.getPatientID());
		System.out.println("Patient Age is: " + h6.getPatientAge());
		System.out.println("Disease is: " + h6.getDisease());
		System.out.println("Doctor Name is: " + h6.getDoctorName());
		System.out.println("Doctor ID is: " + h6.getDoctorID());
		System.out.println("Specialization is: " + h6.getSpecialization());
		System.out.println("Consultation Fee is: " + h6.getConsultationFee());
		System.out.println("Room Type is: " + h6.getRoomType());
		System.out.println("Admitted Status is: " + h6.getAdmitted());
		System.out.println("Patient Status is: " + h6.getPatientStatus());

		System.out.println("=========================Hospital Management Details 7===========================");
		System.out.println("Object Reference is: " + h7);
		System.out.println("Patient Name is: " + h7.getPatientName());
		System.out.println("Patient ID is: " + h7.getPatientID());
		System.out.println("Patient Age is: " + h7.getPatientAge());
		System.out.println("Disease is: " + h7.getDisease());
		System.out.println("Doctor Name is: " + h7.getDoctorName());
		System.out.println("Doctor ID is: " + h7.getDoctorID());
		System.out.println("Specialization is: " + h7.getSpecialization());
		System.out.println("Consultation Fee is: " + h7.getConsultationFee());
		System.out.println("Room Type is: " + h7.getRoomType());
		System.out.println("Admitted Status is: " + h7.getAdmitted());
		System.out.println("Patient Status is: " + h7.getPatientStatus());

		System.out.println("=========================Hospital Management Details 8===========================");
		System.out.println("Object Reference is: " + h8);
		System.out.println("Patient Name is: " + h8.getPatientName());
		System.out.println("Patient ID is: " + h8.getPatientID());
		System.out.println("Patient Age is: " + h8.getPatientAge());
		System.out.println("Disease is: " + h8.getDisease());
		System.out.println("Doctor Name is: " + h8.getDoctorName());
		System.out.println("Doctor ID is: " + h8.getDoctorID());
		System.out.println("Specialization is: " + h8.getSpecialization());
		System.out.println("Consultation Fee is: " + h8.getConsultationFee());
		System.out.println("Room Type is: " + h8.getRoomType());
		System.out.println("Admitted Status is: " + h8.getAdmitted());
		System.out.println("Patient Status is: " + h8.getPatientStatus());

		System.out.println("=========================Hospital Management Details 9===========================");
		System.out.println("Object Reference is: " + h9);
		System.out.println("Patient Name is: " + h9.getPatientName());
		System.out.println("Patient ID is: " + h9.getPatientID());
		System.out.println("Patient Age is: " + h9.getPatientAge());
		System.out.println("Disease is: " + h9.getDisease());
		System.out.println("Doctor Name is: " + h9.getDoctorName());
		System.out.println("Doctor ID is: " + h9.getDoctorID());
		System.out.println("Specialization is: " + h9.getSpecialization());
		System.out.println("Consultation Fee is: " + h9.getConsultationFee());
		System.out.println("Room Type is: " + h9.getRoomType());
		System.out.println("Admitted Status is: " + h9.getAdmitted());
		System.out.println("Patient Status is: " + h9.getPatientStatus());

		System.out.println("=========================Hospital Management Details 10===========================");
		System.out.println("Object Reference is: " + h10);
		System.out.println("Patient Name is: " + h10.getPatientName());
		System.out.println("Patient ID is: " + h10.getPatientID());
		System.out.println("Patient Age is: " + h10.getPatientAge());
		System.out.println("Disease is: " + h10.getDisease());
		System.out.println("Doctor Name is: " + h10.getDoctorName());
		System.out.println("Doctor ID is: " + h10.getDoctorID());
		System.out.println("Specialization is: " + h10.getSpecialization());
		System.out.println("Consultation Fee is: " + h10.getConsultationFee());
		System.out.println("Room Type is: " + h10.getRoomType());
		System.out.println("Admitted Status is: " + h10.getAdmitted());
		System.out.println("Patient Status is: " + h10.getPatientStatus());

		System.out.println("=========================Hospital Management Details 11===========================");
		System.out.println("Object Reference is: " + h11);
		System.out.println("Patient Name is: " + h11.getPatientName());
		System.out.println("Patient ID is: " + h11.getPatientID());
		System.out.println("Patient Age is: " + h11.getPatientAge());
		System.out.println("Disease is: " + h11.getDisease());
		System.out.println("Doctor Name is: " + h11.getDoctorName());
		System.out.println("Doctor ID is: " + h11.getDoctorID());
		System.out.println("Specialization is: " + h11.getSpecialization());
		System.out.println("Consultation Fee is: " + h11.getConsultationFee());
		System.out.println("Room Type is: " + h11.getRoomType());
		System.out.println("Admitted Status is: " + h11.getAdmitted());
		System.out.println("Patient Status is: " + h11.getPatientStatus());

		System.out.println("=========================Hospital Management Details 12===========================");
		System.out.println("Object Reference is: " + h12);
		System.out.println("Patient Name is: " + h12.getPatientName());
		System.out.println("Patient ID is: " + h12.getPatientID());
		System.out.println("Patient Age is: " + h12.getPatientAge());
		System.out.println("Disease is: " + h12.getDisease());
		System.out.println("Doctor Name is: " + h12.getDoctorName());
		System.out.println("Doctor ID is: " + h12.getDoctorID());
		System.out.println("Specialization is: " + h12.getSpecialization());
		System.out.println("Consultation Fee is: " + h12.getConsultationFee());
		System.out.println("Room Type is: " + h12.getRoomType());
		System.out.println("Admitted Status is: " + h12.getAdmitted());
		System.out.println("Patient Status is: " + h12.getPatientStatus());

		System.out.println("=========================Hospital Management Details 13===========================");
		System.out.println("Object Reference is: " + h13);
		System.out.println("Patient Name is: " + h13.getPatientName());
		System.out.println("Patient ID is: " + h13.getPatientID());
		System.out.println("Patient Age is: " + h13.getPatientAge());
		System.out.println("Disease is: " + h13.getDisease());
		System.out.println("Doctor Name is: " + h13.getDoctorName());
		System.out.println("Doctor ID is: " + h13.getDoctorID());
		System.out.println("Specialization is: " + h13.getSpecialization());
		System.out.println("Consultation Fee is: " + h13.getConsultationFee());
		System.out.println("Room Type is: " + h13.getRoomType());
		System.out.println("Admitted Status is: " + h13.getAdmitted());
		System.out.println("Patient Status is: " + h13.getPatientStatus());

		System.out.println("=========================Hospital Management Details 14===========================");
		System.out.println("Object Reference is: " + h14);
		System.out.println("Patient Name is: " + h14.getPatientName());
		System.out.println("Patient ID is: " + h14.getPatientID());
		System.out.println("Patient Age is: " + h14.getPatientAge());
		System.out.println("Disease is: " + h14.getDisease());
		System.out.println("Doctor Name is: " + h14.getDoctorName());
		System.out.println("Doctor ID is: " + h14.getDoctorID());
		System.out.println("Specialization is: " + h14.getSpecialization());
		System.out.println("Consultation Fee is: " + h14.getConsultationFee());
		System.out.println("Room Type is: " + h14.getRoomType());
		System.out.println("Admitted Status is: " + h14.getAdmitted());
		System.out.println("Patient Status is: " + h14.getPatientStatus());

		System.out.println("=========================Hospital Management Details 15===========================");
		System.out.println("Object Reference is: " + h15);
		System.out.println("Patient Name is: " + h15.getPatientName());
		System.out.println("Patient ID is: " + h15.getPatientID());
		System.out.println("Patient Age is: " + h15.getPatientAge());
		System.out.println("Disease is: " + h15.getDisease());
		System.out.println("Doctor Name is: " + h15.getDoctorName());
		System.out.println("Doctor ID is: " + h15.getDoctorID());
		System.out.println("Specialization is: " + h15.getSpecialization());
		System.out.println("Consultation Fee is: " + h15.getConsultationFee());
		System.out.println("Room Type is: " + h15.getRoomType());
		System.out.println("Admitted Status is: " + h15.getAdmitted());
		System.out.println("Patient Status is: " + h15.getPatientStatus());

		System.out.println("=========================Hospital Management Details 16===========================");
		System.out.println("Object Reference is: " + h16);
		System.out.println("Patient Name is: " + h16.getPatientName());
		System.out.println("Patient ID is: " + h16.getPatientID());
		System.out.println("Patient Age is: " + h16.getPatientAge());
		System.out.println("Disease is: " + h16.getDisease());
		System.out.println("Doctor Name is: " + h16.getDoctorName());
		System.out.println("Doctor ID is: " + h16.getDoctorID());
		System.out.println("Specialization is: " + h16.getSpecialization());
		System.out.println("Consultation Fee is: " + h16.getConsultationFee());
		System.out.println("Room Type is: " + h16.getRoomType());
		System.out.println("Admitted Status is: " + h16.getAdmitted());
		System.out.println("Patient Status is: " + h16.getPatientStatus());

		System.out.println("=========================Hospital Management Details 17===========================");
		System.out.println("Object Reference is: " + h17);
		System.out.println("Patient Name is: " + h17.getPatientName());
		System.out.println("Patient ID is: " + h17.getPatientID());
		System.out.println("Patient Age is: " + h17.getPatientAge());
		System.out.println("Disease is: " + h17.getDisease());
		System.out.println("Doctor Name is: " + h17.getDoctorName());
		System.out.println("Doctor ID is: " + h17.getDoctorID());
		System.out.println("Specialization is: " + h17.getSpecialization());
		System.out.println("Consultation Fee is: " + h17.getConsultationFee());
		System.out.println("Room Type is: " + h17.getRoomType());
		System.out.println("Admitted Status is: " + h17.getAdmitted());
		System.out.println("Patient Status is: " + h17.getPatientStatus());

		System.out.println("=========================Hospital Management Details 18===========================");
		System.out.println("Object Reference is: " + h18);
		System.out.println("Patient Name is: " + h18.getPatientName());
		System.out.println("Patient ID is: " + h18.getPatientID());
		System.out.println("Patient Age is: " + h18.getPatientAge());
		System.out.println("Disease is: " + h18.getDisease());
		System.out.println("Doctor Name is: " + h18.getDoctorName());
		System.out.println("Doctor ID is: " + h18.getDoctorID());
		System.out.println("Specialization is: " + h18.getSpecialization());
		System.out.println("Consultation Fee is: " + h18.getConsultationFee());
		System.out.println("Room Type is: " + h18.getRoomType());
		System.out.println("Admitted Status is: " + h18.getAdmitted());
		System.out.println("Patient Status is: " + h18.getPatientStatus());

		System.out.println("=========================Hospital Management Details 19===========================");
		System.out.println("Object Reference is: " + h19);
		System.out.println("Patient Name is: " + h19.getPatientName());
		System.out.println("Patient ID is: " + h19.getPatientID());
		System.out.println("Patient Age is: " + h19.getPatientAge());
		System.out.println("Disease is: " + h19.getDisease());
		System.out.println("Doctor Name is: " + h19.getDoctorName());
		System.out.println("Doctor ID is: " + h19.getDoctorID());
		System.out.println("Specialization is: " + h19.getSpecialization());
		System.out.println("Consultation Fee is: " + h19.getConsultationFee());
		System.out.println("Room Type is: " + h19.getRoomType());
		System.out.println("Admitted Status is: " + h19.getAdmitted());
		System.out.println("Patient Status is: " + h19.getPatientStatus());

		System.out.println("=========================Hospital Management Details 20===========================");
		System.out.println("Object Reference is: " + h20);
		System.out.println("Patient Name is: " + h20.getPatientName());
		System.out.println("Patient ID is: " + h20.getPatientID());
		System.out.println("Patient Age is: " + h20.getPatientAge());
		System.out.println("Disease is: " + h20.getDisease());
		System.out.println("Doctor Name is: " + h20.getDoctorName());
		System.out.println("Doctor ID is: " + h20.getDoctorID());
		System.out.println("Specialization is: " + h20.getSpecialization());
		System.out.println("Consultation Fee is: " + h20.getConsultationFee());
		System.out.println("Room Type is: " + h20.getRoomType());
		System.out.println("Admitted Status is: " + h20.getAdmitted());
		System.out.println("Patient Status is: " + h20.getPatientStatus());

		System.out.println("=========================Hospital Management Details 21===========================");
		System.out.println("Object Reference is: " + h21);
		System.out.println("Patient Name is: " + h21.getPatientName());
		System.out.println("Patient ID is: " + h21.getPatientID());
		System.out.println("Patient Age is: " + h21.getPatientAge());
		System.out.println("Disease is: " + h21.getDisease());
		System.out.println("Doctor Name is: " + h21.getDoctorName());
		System.out.println("Doctor ID is: " + h21.getDoctorID());
		System.out.println("Specialization is: " + h21.getSpecialization());
		System.out.println("Consultation Fee is: " + h21.getConsultationFee());
		System.out.println("Room Type is: " + h21.getRoomType());
		System.out.println("Admitted Status is: " + h21.getAdmitted());
		System.out.println("Patient Status is: " + h21.getPatientStatus());

		System.out.println("=========================Hospital Management Details 22===========================");
		System.out.println("Object Reference is: " + h22);
		System.out.println("Patient Name is: " + h22.getPatientName());
		System.out.println("Patient ID is: " + h22.getPatientID());
		System.out.println("Patient Age is: " + h22.getPatientAge());
		System.out.println("Disease is: " + h22.getDisease());
		System.out.println("Doctor Name is: " + h22.getDoctorName());
		System.out.println("Doctor ID is: " + h22.getDoctorID());
		System.out.println("Specialization is: " + h22.getSpecialization());
		System.out.println("Consultation Fee is: " + h22.getConsultationFee());
		System.out.println("Room Type is: " + h22.getRoomType());
		System.out.println("Admitted Status is: " + h22.getAdmitted());
		System.out.println("Patient Status is: " + h22.getPatientStatus());

		System.out.println("=========================Hospital Management Details 23===========================");
		System.out.println("Object Reference is: " + h23);
		System.out.println("Patient Name is: " + h23.getPatientName());
		System.out.println("Patient ID is: " + h23.getPatientID());
		System.out.println("Patient Age is: " + h23.getPatientAge());
		System.out.println("Disease is: " + h23.getDisease());
		System.out.println("Doctor Name is: " + h23.getDoctorName());
		System.out.println("Doctor ID is: " + h23.getDoctorID());
		System.out.println("Specialization is: " + h23.getSpecialization());
		System.out.println("Consultation Fee is: " + h23.getConsultationFee());
		System.out.println("Room Type is: " + h23.getRoomType());
		System.out.println("Admitted Status is: " + h23.getAdmitted());
		System.out.println("Patient Status is: " + h23.getPatientStatus());

		System.out.println("=========================Hospital Management Details 24===========================");
		System.out.println("Object Reference is: " + h24);
		System.out.println("Patient Name is: " + h24.getPatientName());
		System.out.println("Patient ID is: " + h24.getPatientID());
		System.out.println("Patient Age is: " + h24.getPatientAge());
		System.out.println("Disease is: " + h24.getDisease());
		System.out.println("Doctor Name is: " + h24.getDoctorName());
		System.out.println("Doctor ID is: " + h24.getDoctorID());
		System.out.println("Specialization is: " + h24.getSpecialization());
		System.out.println("Consultation Fee is: " + h24.getConsultationFee());
		System.out.println("Room Type is: " + h24.getRoomType());
		System.out.println("Admitted Status is: " + h24.getAdmitted());
		System.out.println("Patient Status is: " + h24.getPatientStatus());

		System.out.println("=========================Hospital Management Details 25===========================");
		System.out.println("Object Reference is: " + h25);
		System.out.println("Patient Name is: " + h25.getPatientName());
		System.out.println("Patient ID is: " + h25.getPatientID());
		System.out.println("Patient Age is: " + h25.getPatientAge());
		System.out.println("Disease is: " + h25.getDisease());
		System.out.println("Doctor Name is: " + h25.getDoctorName());
		System.out.println("Doctor ID is: " + h25.getDoctorID());
		System.out.println("Specialization is: " + h25.getSpecialization());
		System.out.println("Consultation Fee is: " + h25.getConsultationFee());
		System.out.println("Room Type is: " + h25.getRoomType());
		System.out.println("Admitted Status is: " + h25.getAdmitted());
		System.out.println("Patient Status is: " + h25.getPatientStatus());

		System.out.println("=========================Hospital Management Details 26===========================");
		System.out.println("Object Reference is: " + h26);
		System.out.println("Patient Name is: " + h26.getPatientName());
		System.out.println("Patient ID is: " + h26.getPatientID());
		System.out.println("Patient Age is: " + h26.getPatientAge());
		System.out.println("Disease is: " + h26.getDisease());
		System.out.println("Doctor Name is: " + h26.getDoctorName());
		System.out.println("Doctor ID is: " + h26.getDoctorID());
		System.out.println("Specialization is: " + h26.getSpecialization());
		System.out.println("Consultation Fee is: " + h26.getConsultationFee());
		System.out.println("Room Type is: " + h26.getRoomType());
		System.out.println("Admitted Status is: " + h26.getAdmitted());
		System.out.println("Patient Status is: " + h26.getPatientStatus());

		System.out.println("=========================Hospital Management Details 27===========================");
		System.out.println("Object Reference is: " + h27);
		System.out.println("Patient Name is: " + h27.getPatientName());
		System.out.println("Patient ID is: " + h27.getPatientID());
		System.out.println("Patient Age is: " + h27.getPatientAge());
		System.out.println("Disease is: " + h27.getDisease());
		System.out.println("Doctor Name is: " + h27.getDoctorName());
		System.out.println("Doctor ID is: " + h27.getDoctorID());
		System.out.println("Specialization is: " + h27.getSpecialization());
		System.out.println("Consultation Fee is: " + h27.getConsultationFee());
		System.out.println("Room Type is: " + h27.getRoomType());
		System.out.println("Admitted Status is: " + h27.getAdmitted());
		System.out.println("Patient Status is: " + h27.getPatientStatus());

		System.out.println("=========================Hospital Management Details 28===========================");
		System.out.println("Object Reference is: " + h28);
		System.out.println("Patient Name is: " + h28.getPatientName());
		System.out.println("Patient ID is: " + h28.getPatientID());
		System.out.println("Patient Age is: " + h28.getPatientAge());
		System.out.println("Disease is: " + h28.getDisease());
		System.out.println("Doctor Name is: " + h28.getDoctorName());
		System.out.println("Doctor ID is: " + h28.getDoctorID());
		System.out.println("Specialization is: " + h28.getSpecialization());
		System.out.println("Consultation Fee is: " + h28.getConsultationFee());
		System.out.println("Room Type is: " + h28.getRoomType());
		System.out.println("Admitted Status is: " + h28.getAdmitted());
		System.out.println("Patient Status is: " + h28.getPatientStatus());

		System.out.println("=========================Hospital Management Details 29===========================");
		System.out.println("Object Reference is: " + h29);
		System.out.println("Patient Name is: " + h29.getPatientName());
		System.out.println("Patient ID is: " + h29.getPatientID());
		System.out.println("Patient Age is: " + h29.getPatientAge());
		System.out.println("Disease is: " + h29.getDisease());
		System.out.println("Doctor Name is: " + h29.getDoctorName());
		System.out.println("Doctor ID is: " + h29.getDoctorID());
		System.out.println("Specialization is: " + h29.getSpecialization());
		System.out.println("Consultation Fee is: " + h29.getConsultationFee());
		System.out.println("Room Type is: " + h29.getRoomType());
		System.out.println("Admitted Status is: " + h29.getAdmitted());
		System.out.println("Patient Status is: " + h29.getPatientStatus());

		System.out.println("=========================Hospital Management Details 30===========================");
		System.out.println("Object Reference is: " + h30);
		System.out.println("Patient Name is: " + h30.getPatientName());
		System.out.println("Patient ID is: " + h30.getPatientID());
		System.out.println("Patient Age is: " + h30.getPatientAge());
		System.out.println("Disease is: " + h30.getDisease());
		System.out.println("Doctor Name is: " + h30.getDoctorName());
		System.out.println("Doctor ID is: " + h30.getDoctorID());
		System.out.println("Specialization is: " + h30.getSpecialization());
		System.out.println("Consultation Fee is: " + h30.getConsultationFee());
		System.out.println("Room Type is: " + h30.getRoomType());
		System.out.println("Admitted Status is: " + h30.getAdmitted());
		System.out.println("Patient Status is: " + h30.getPatientStatus());

		System.out.println("=========================Hospital Management Details 31===========================");
		System.out.println("Object Reference is: " + h31);
		System.out.println("Patient Name is: " + h31.getPatientName());
		System.out.println("Patient ID is: " + h31.getPatientID());
		System.out.println("Patient Age is: " + h31.getPatientAge());
		System.out.println("Disease is: " + h31.getDisease());
		System.out.println("Doctor Name is: " + h31.getDoctorName());
		System.out.println("Doctor ID is: " + h31.getDoctorID());
		System.out.println("Specialization is: " + h31.getSpecialization());
		System.out.println("Consultation Fee is: " + h31.getConsultationFee());
		System.out.println("Room Type is: " + h31.getRoomType());
		System.out.println("Admitted Status is: " + h31.getAdmitted());
		System.out.println("Patient Status is: " + h31.getPatientStatus());

		System.out.println("=========================Hospital Management Details 32===========================");
		System.out.println("Object Reference is: " + h32);
		System.out.println("Patient Name is: " + h32.getPatientName());
		System.out.println("Patient ID is: " + h32.getPatientID());
		System.out.println("Patient Age is: " + h32.getPatientAge());
		System.out.println("Disease is: " + h32.getDisease());
		System.out.println("Doctor Name is: " + h32.getDoctorName());
		System.out.println("Doctor ID is: " + h32.getDoctorID());
		System.out.println("Specialization is: " + h32.getSpecialization());
		System.out.println("Consultation Fee is: " + h32.getConsultationFee());
		System.out.println("Room Type is: " + h32.getRoomType());
		System.out.println("Admitted Status is: " + h32.getAdmitted());
		System.out.println("Patient Status is: " + h32.getPatientStatus());

		System.out.println("=========================Hospital Management Details 33===========================");
		System.out.println("Object Reference is: " + h33);
		System.out.println("Patient Name is: " + h33.getPatientName());
		System.out.println("Patient ID is: " + h33.getPatientID());
		System.out.println("Patient Age is: " + h33.getPatientAge());
		System.out.println("Disease is: " + h33.getDisease());
		System.out.println("Doctor Name is: " + h33.getDoctorName());
		System.out.println("Doctor ID is: " + h33.getDoctorID());
		System.out.println("Specialization is: " + h33.getSpecialization());
		System.out.println("Consultation Fee is: " + h33.getConsultationFee());
		System.out.println("Room Type is: " + h33.getRoomType());
		System.out.println("Admitted Status is: " + h33.getAdmitted());
		System.out.println("Patient Status is: " + h33.getPatientStatus());

		System.out.println("=========================Hospital Management Details 34===========================");
		System.out.println("Object Reference is: " + h34);
		System.out.println("Patient Name is: " + h34.getPatientName());
		System.out.println("Patient ID is: " + h34.getPatientID());
		System.out.println("Patient Age is: " + h34.getPatientAge());
		System.out.println("Disease is: " + h34.getDisease());
		System.out.println("Doctor Name is: " + h34.getDoctorName());
		System.out.println("Doctor ID is: " + h34.getDoctorID());
		System.out.println("Specialization is: " + h34.getSpecialization());
		System.out.println("Consultation Fee is: " + h34.getConsultationFee());
		System.out.println("Room Type is: " + h34.getRoomType());
		System.out.println("Admitted Status is: " + h34.getAdmitted());
		System.out.println("Patient Status is: " + h34.getPatientStatus());

		System.out.println("=========================Hospital Management Details 35===========================");
		System.out.println("Object Reference is: " + h35);
		System.out.println("Patient Name is: " + h35.getPatientName());
		System.out.println("Patient ID is: " + h35.getPatientID());
		System.out.println("Patient Age is: " + h35.getPatientAge());
		System.out.println("Disease is: " + h35.getDisease());
		System.out.println("Doctor Name is: " + h35.getDoctorName());
		System.out.println("Doctor ID is: " + h35.getDoctorID());
		System.out.println("Specialization is: " + h35.getSpecialization());
		System.out.println("Consultation Fee is: " + h35.getConsultationFee());
		System.out.println("Room Type is: " + h35.getRoomType());
		System.out.println("Admitted Status is: " + h35.getAdmitted());
		System.out.println("Patient Status is: " + h35.getPatientStatus());

		System.out.println("=========================Hospital Management Details 36===========================");
		System.out.println("Object Reference is: " + h36);
		System.out.println("Patient Name is: " + h36.getPatientName());
		System.out.println("Patient ID is: " + h36.getPatientID());
		System.out.println("Patient Age is: " + h36.getPatientAge());
		System.out.println("Disease is: " + h36.getDisease());
		System.out.println("Doctor Name is: " + h36.getDoctorName());
		System.out.println("Doctor ID is: " + h36.getDoctorID());
		System.out.println("Specialization is: " + h36.getSpecialization());
		System.out.println("Consultation Fee is: " + h36.getConsultationFee());
		System.out.println("Room Type is: " + h36.getRoomType());
		System.out.println("Admitted Status is: " + h36.getAdmitted());
		System.out.println("Patient Status is: " + h36.getPatientStatus());

		System.out.println("=========================Hospital Management Details 37===========================");
		System.out.println("Object Reference is: " + h37);
		System.out.println("Patient Name is: " + h37.getPatientName());
		System.out.println("Patient ID is: " + h37.getPatientID());
		System.out.println("Patient Age is: " + h37.getPatientAge());
		System.out.println("Disease is: " + h37.getDisease());
		System.out.println("Doctor Name is: " + h37.getDoctorName());
		System.out.println("Doctor ID is: " + h37.getDoctorID());
		System.out.println("Specialization is: " + h37.getSpecialization());
		System.out.println("Consultation Fee is: " + h37.getConsultationFee());
		System.out.println("Room Type is: " + h37.getRoomType());
		System.out.println("Admitted Status is: " + h37.getAdmitted());
		System.out.println("Patient Status is: " + h37.getPatientStatus());

		System.out.println("=========================Hospital Management Details 38===========================");
		System.out.println("Object Reference is: " + h38);
		System.out.println("Patient Name is: " + h38.getPatientName());
		System.out.println("Patient ID is: " + h38.getPatientID());
		System.out.println("Patient Age is: " + h38.getPatientAge());
		System.out.println("Disease is: " + h38.getDisease());
		System.out.println("Doctor Name is: " + h38.getDoctorName());
		System.out.println("Doctor ID is: " + h38.getDoctorID());
		System.out.println("Specialization is: " + h38.getSpecialization());
		System.out.println("Consultation Fee is: " + h38.getConsultationFee());
		System.out.println("Room Type is: " + h38.getRoomType());
		System.out.println("Admitted Status is: " + h38.getAdmitted());
		System.out.println("Patient Status is: " + h38.getPatientStatus());

		System.out.println("=========================Hospital Management Details 39===========================");
		System.out.println("Object Reference is: " + h39);
		System.out.println("Patient Name is: " + h39.getPatientName());
		System.out.println("Patient ID is: " + h39.getPatientID());
		System.out.println("Patient Age is: " + h39.getPatientAge());
		System.out.println("Disease is: " + h39.getDisease());
		System.out.println("Doctor Name is: " + h39.getDoctorName());
		System.out.println("Doctor ID is: " + h39.getDoctorID());
		System.out.println("Specialization is: " + h39.getSpecialization());
		System.out.println("Consultation Fee is: " + h39.getConsultationFee());
		System.out.println("Room Type is: " + h39.getRoomType());
		System.out.println("Admitted Status is: " + h39.getAdmitted());
		System.out.println("Patient Status is: " + h39.getPatientStatus());

		System.out.println("=========================Hospital Management Details 40===========================");
		System.out.println("Object Reference is: " + h40);
		System.out.println("Patient Name is: " + h40.getPatientName());
		System.out.println("Patient ID is: " + h40.getPatientID());
		System.out.println("Patient Age is: " + h40.getPatientAge());
		System.out.println("Disease is: " + h40.getDisease());
		System.out.println("Doctor Name is: " + h40.getDoctorName());
		System.out.println("Doctor ID is: " + h40.getDoctorID());
		System.out.println("Specialization is: " + h40.getSpecialization());
		System.out.println("Consultation Fee is: " + h40.getConsultationFee());
		System.out.println("Room Type is: " + h40.getRoomType());
		System.out.println("Admitted Status is: " + h40.getAdmitted());
		System.out.println("Patient Status is: " + h40.getPatientStatus());

		System.out.println("=========================Hospital Management Details 41===========================");
		System.out.println("Object Reference is: " + h41);
		System.out.println("Patient Name is: " + h41.getPatientName());
		System.out.println("Patient ID is: " + h41.getPatientID());
		System.out.println("Patient Age is: " + h41.getPatientAge());
		System.out.println("Disease is: " + h41.getDisease());
		System.out.println("Doctor Name is: " + h41.getDoctorName());
		System.out.println("Doctor ID is: " + h41.getDoctorID());
		System.out.println("Specialization is: " + h41.getSpecialization());
		System.out.println("Consultation Fee is: " + h41.getConsultationFee());
		System.out.println("Room Type is: " + h41.getRoomType());
		System.out.println("Admitted Status is: " + h41.getAdmitted());
		System.out.println("Patient Status is: " + h41.getPatientStatus());

		System.out.println("=========================Hospital Management Details 42===========================");
		System.out.println("Object Reference is: " + h42);
		System.out.println("Patient Name is: " + h42.getPatientName());
		System.out.println("Patient ID is: " + h42.getPatientID());
		System.out.println("Patient Age is: " + h42.getPatientAge());
		System.out.println("Disease is: " + h42.getDisease());
		System.out.println("Doctor Name is: " + h42.getDoctorName());
		System.out.println("Doctor ID is: " + h42.getDoctorID());
		System.out.println("Specialization is: " + h42.getSpecialization());
		System.out.println("Consultation Fee is: " + h42.getConsultationFee());
		System.out.println("Room Type is: " + h42.getRoomType());
		System.out.println("Admitted Status is: " + h42.getAdmitted());
		System.out.println("Patient Status is: " + h42.getPatientStatus());

		System.out.println("=========================Hospital Management Details 43===========================");
		System.out.println("Object Reference is: " + h43);
		System.out.println("Patient Name is: " + h43.getPatientName());
		System.out.println("Patient ID is: " + h43.getPatientID());
		System.out.println("Patient Age is: " + h43.getPatientAge());
		System.out.println("Disease is: " + h43.getDisease());
		System.out.println("Doctor Name is: " + h43.getDoctorName());
		System.out.println("Doctor ID is: " + h43.getDoctorID());
		System.out.println("Specialization is: " + h43.getSpecialization());
		System.out.println("Consultation Fee is: " + h43.getConsultationFee());
		System.out.println("Room Type is: " + h43.getRoomType());
		System.out.println("Admitted Status is: " + h43.getAdmitted());
		System.out.println("Patient Status is: " + h43.getPatientStatus());

		System.out.println("=========================Hospital Management Details 44===========================");
		System.out.println("Object Reference is: " + h44);
		System.out.println("Patient Name is: " + h44.getPatientName());
		System.out.println("Patient ID is: " + h44.getPatientID());
		System.out.println("Patient Age is: " + h44.getPatientAge());
		System.out.println("Disease is: " + h44.getDisease());
		System.out.println("Doctor Name is: " + h44.getDoctorName());
		System.out.println("Doctor ID is: " + h44.getDoctorID());
		System.out.println("Specialization is: " + h44.getSpecialization());
		System.out.println("Consultation Fee is: " + h44.getConsultationFee());
		System.out.println("Room Type is: " + h44.getRoomType());
		System.out.println("Admitted Status is: " + h44.getAdmitted());
		System.out.println("Patient Status is: " + h44.getPatientStatus());

		System.out.println("=========================Hospital Management Details 45===========================");
		System.out.println("Object Reference is: " + h45);
		System.out.println("Patient Name is: " + h45.getPatientName());
		System.out.println("Patient ID is: " + h45.getPatientID());
		System.out.println("Patient Age is: " + h45.getPatientAge());
		System.out.println("Disease is: " + h45.getDisease());
		System.out.println("Doctor Name is: " + h45.getDoctorName());
		System.out.println("Doctor ID is: " + h45.getDoctorID());
		System.out.println("Specialization is: " + h45.getSpecialization());
		System.out.println("Consultation Fee is: " + h45.getConsultationFee());
		System.out.println("Room Type is: " + h45.getRoomType());
		System.out.println("Admitted Status is: " + h45.getAdmitted());
		System.out.println("Patient Status is: " + h45.getPatientStatus());

		System.out.println("=========================Hospital Management Details 46===========================");
		System.out.println("Object Reference is: " + h46);
		System.out.println("Patient Name is: " + h46.getPatientName());
		System.out.println("Patient ID is: " + h46.getPatientID());
		System.out.println("Patient Age is: " + h46.getPatientAge());
		System.out.println("Disease is: " + h46.getDisease());
		System.out.println("Doctor Name is: " + h46.getDoctorName());
		System.out.println("Doctor ID is: " + h46.getDoctorID());
		System.out.println("Specialization is: " + h46.getSpecialization());
		System.out.println("Consultation Fee is: " + h46.getConsultationFee());
		System.out.println("Room Type is: " + h46.getRoomType());
		System.out.println("Admitted Status is: " + h46.getAdmitted());
		System.out.println("Patient Status is: " + h46.getPatientStatus());

		System.out.println("=========================Hospital Management Details 47===========================");
		System.out.println("Object Reference is: " + h47);
		System.out.println("Patient Name is: " + h47.getPatientName());
		System.out.println("Patient ID is: " + h47.getPatientID());
		System.out.println("Patient Age is: " + h47.getPatientAge());
		System.out.println("Disease is: " + h47.getDisease());
		System.out.println("Doctor Name is: " + h47.getDoctorName());
		System.out.println("Doctor ID is: " + h47.getDoctorID());
		System.out.println("Specialization is: " + h47.getSpecialization());
		System.out.println("Consultation Fee is: " + h47.getConsultationFee());
		System.out.println("Room Type is: " + h47.getRoomType());
		System.out.println("Admitted Status is: " + h47.getAdmitted());
		System.out.println("Patient Status is: " + h47.getPatientStatus());

		System.out.println("=========================Hospital Management Details 48===========================");
		System.out.println("Object Reference is: " + h48);
		System.out.println("Patient Name is: " + h48.getPatientName());
		System.out.println("Patient ID is: " + h48.getPatientID());
		System.out.println("Patient Age is: " + h48.getPatientAge());
		System.out.println("Disease is: " + h48.getDisease());
		System.out.println("Doctor Name is: " + h48.getDoctorName());
		System.out.println("Doctor ID is: " + h48.getDoctorID());
		System.out.println("Specialization is: " + h48.getSpecialization());
		System.out.println("Consultation Fee is: " + h48.getConsultationFee());
		System.out.println("Room Type is: " + h48.getRoomType());
		System.out.println("Admitted Status is: " + h48.getAdmitted());
		System.out.println("Patient Status is: " + h48.getPatientStatus());

		System.out.println("=========================Hospital Management Details 49===========================");
		System.out.println("Object Reference is: " + h49);
		System.out.println("Patient Name is: " + h49.getPatientName());
		System.out.println("Patient ID is: " + h49.getPatientID());
		System.out.println("Patient Age is: " + h49.getPatientAge());
		System.out.println("Disease is: " + h49.getDisease());
		System.out.println("Doctor Name is: " + h49.getDoctorName());
		System.out.println("Doctor ID is: " + h49.getDoctorID());
		System.out.println("Specialization is: " + h49.getSpecialization());
		System.out.println("Consultation Fee is: " + h49.getConsultationFee());
		System.out.println("Room Type is: " + h49.getRoomType());
		System.out.println("Admitted Status is: " + h49.getAdmitted());
		System.out.println("Patient Status is: " + h49.getPatientStatus());

		System.out.println("=========================Hospital Management Details 50===========================");
		System.out.println("Object Reference is: " + h50);
		System.out.println("Patient Name is: " + h50.getPatientName());
		System.out.println("Patient ID is: " + h50.getPatientID());
		System.out.println("Patient Age is: " + h50.getPatientAge());
		System.out.println("Disease is: " + h50.getDisease());
		System.out.println("Doctor Name is: " + h50.getDoctorName());
		System.out.println("Doctor ID is: " + h50.getDoctorID());
		System.out.println("Specialization is: " + h50.getSpecialization());
		System.out.println("Consultation Fee is: " + h50.getConsultationFee());
		System.out.println("Room Type is: " + h50.getRoomType());
		System.out.println("Admitted Status is: " + h50.getAdmitted());
		System.out.println("Patient Status is: " + h50.getPatientStatus());
		
		System.out.println("===================================Main Method Ends======================================");
	}

}
