package encapsulationsPrograming;

public class LibraryBookDriver {

	public static void main(String[] args) {
		
		System.out.println("============================Main Method Starts=================================");
		
		LibraryBook b1 = new LibraryBook("Java Programming", "James Gosling", "BOOK101", "Programming", true);
		LibraryBook b2 = new LibraryBook("Selenium WebDriver", "Rahul Sharma", "BOOK102", "Testing", true);
		LibraryBook b3 = new LibraryBook("Python Basics", "Ravi Kumar", "BOOK103", "Programming", false);
		LibraryBook b4 = new LibraryBook("Database Management", "Robert Martin", "BOOK104", "Database", true);
		LibraryBook b5 = new LibraryBook("Manual Testing", "Suresh Verma", "BOOK105", "Testing", false);
		LibraryBook b6 = new LibraryBook("JavaScript Guide", "Amit Sharma", "BOOK106", "Web Development", true);
		LibraryBook b7 = new LibraryBook("Data Structures", "Mark Allen", "BOOK107", "Computer Science", true);
		LibraryBook b8 = new LibraryBook("Machine Learning", "Andrew Ng", "BOOK108", "Artificial Intelligence", false);
		LibraryBook b9 = new LibraryBook("Operating Systems", "Abraham Silberschatz", "BOOK109", "Computer Science", true);
		LibraryBook b10 = new LibraryBook("Software Engineering", "Roger Pressman", "BOOK110", "Engineering", false);

		LibraryBook b11 = new LibraryBook("Core Java", "Herbert Schildt", "BOOK111", "Programming", true);
		LibraryBook b12 = new LibraryBook("Effective Java", "Joshua Bloch", "BOOK112", "Programming", true);
		LibraryBook b13 = new LibraryBook("Head First Java", "Kathy Sierra", "BOOK113", "Programming", false);
		LibraryBook b14 = new LibraryBook("Spring Boot", "Craig Walls", "BOOK114", "Framework", true);
		LibraryBook b15 = new LibraryBook("Hibernate Guide", "Gavin King", "BOOK115", "Framework", false);
		LibraryBook b16 = new LibraryBook("C Programming", "Dennis Ritchie", "BOOK116", "Programming", true);
		LibraryBook b17 = new LibraryBook("C++ Programming", "Bjarne Stroustrup", "BOOK117", "Programming", true);
		LibraryBook b18 = new LibraryBook("Python Crash Course", "Eric Matthes", "BOOK118", "Programming", false);
		LibraryBook b19 = new LibraryBook("Clean Code", "Robert Martin", "BOOK119", "Software Engineering", true);
		LibraryBook b20 = new LibraryBook("Design Patterns", "Erich Gamma", "BOOK120", "Software Engineering", false);

		LibraryBook b21 = new LibraryBook("Computer Networks", "Andrew Tanenbaum", "BOOK121", "Networking", true);
		LibraryBook b22 = new LibraryBook("Computer Architecture", "David Patterson", "BOOK122", "Computer Science", true);
		LibraryBook b23 = new LibraryBook("Operating System Concepts", "Silberschatz", "BOOK123", "Operating Systems", false);
		LibraryBook b24 = new LibraryBook("Artificial Intelligence", "Stuart Russell", "BOOK124", "Artificial Intelligence", true);
		LibraryBook b25 = new LibraryBook("Deep Learning", "Ian Goodfellow", "BOOK125", "Artificial Intelligence", false);
		LibraryBook b26 = new LibraryBook("Data Science Handbook", "Jake VanderPlas", "BOOK126", "Data Science", true);
		LibraryBook b27 = new LibraryBook("Statistics Basics", "David Freedman", "BOOK127", "Mathematics", true);
		LibraryBook b28 = new LibraryBook("Discrete Mathematics", "Kenneth Rosen", "BOOK128", "Mathematics", false);
		LibraryBook b29 = new LibraryBook("Software Testing", "Ron Patton", "BOOK129", "Testing", true);
		LibraryBook b30 = new LibraryBook("TestNG Framework", "Ankit Sharma", "BOOK130", "Testing", false);

		LibraryBook b31 = new LibraryBook("Maven Complete Guide", "Brett Porter", "BOOK131", "Build Tools", true);
		LibraryBook b32 = new LibraryBook("Jenkins Handbook", "John Ferguson", "BOOK132", "DevOps", true);
		LibraryBook b33 = new LibraryBook("Git and GitHub", "Jon Loeliger", "BOOK133", "DevOps", false);
		LibraryBook b34 = new LibraryBook("Docker Essentials", "Adrian Mouat", "BOOK134", "DevOps", true);
		LibraryBook b35 = new LibraryBook("Kubernetes Guide", "Kelsey Hightower", "BOOK135", "Cloud Computing", false);
		LibraryBook b36 = new LibraryBook("Cloud Computing", "Thomas Erl", "BOOK136", "Cloud Computing", true);
		LibraryBook b37 = new LibraryBook("Cyber Security", "William Stallings", "BOOK137", "Security", true);
		LibraryBook b38 = new LibraryBook("Ethical Hacking", "Michael Sikorski", "BOOK138", "Security", false);
		LibraryBook b39 = new LibraryBook("HTML and CSS", "Jon Duckett", "BOOK139", "Web Development", true);
		LibraryBook b40 = new LibraryBook("JavaScript and JQuery", "Jon Duckett", "BOOK140", "Web Development", false);

		LibraryBook b41 = new LibraryBook("React Programming", "Robin Wieruch", "BOOK141", "Web Development", true);
		LibraryBook b42 = new LibraryBook("Angular Guide", "Adam Freeman", "BOOK142", "Web Development", true);
		LibraryBook b43 = new LibraryBook("SQL Complete Reference", "James Groff", "BOOK143", "Database", false);
		LibraryBook b44 = new LibraryBook("MySQL Cookbook", "Paul DuBois", "BOOK144", "Database", true);
		LibraryBook b45 = new LibraryBook("Oracle Database", "Kevin Loney", "BOOK145", "Database", false);
		LibraryBook b46 = new LibraryBook("Agile Software Development", "Robert Martin", "BOOK146", "Software Engineering", true);
		LibraryBook b47 = new LibraryBook("Scrum Guide", "Jeff Sutherland", "BOOK147", "Project Management", true);
		LibraryBook b48 = new LibraryBook("Project Management", "Harold Kerzner", "BOOK148", "Management", false);
		LibraryBook b49 = new LibraryBook("Computer Fundamentals", "Anita Goel", "BOOK149", "Computer Science", true);
		LibraryBook b50 = new LibraryBook("Programming Fundamentals", "Peter Norton", "BOOK150", "Programming", false);
		
		System.out.println("===========================LibraryBook 1 Details=================================");
		System.out.println("Object Reference is: " + b1);
		System.out.println("Title is: " + b1.getTitle());
		System.out.println("Author is: " + b1.getAuthor());
		System.out.println("Book ID is: " + b1.getBookID());
		System.out.println("Category is: " + b1.getCategory());
		System.out.println("Availability is: " + b1.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 1");
		b1.issueBook();
		System.out.println("Availability After Issue is: " + b1.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 1");
		b1.returnBook();
		System.out.println("Availability After Return is: " + b1.getAvailability());
		
		System.out.println("===========================LibraryBook 2 Details=================================");
		System.out.println("Object Reference is: " + b2);
		System.out.println("Title is: " + b2.getTitle());
		System.out.println("Author is: " + b2.getAuthor());
		System.out.println("Book ID is: " + b2.getBookID());
		System.out.println("Category is: " + b2.getCategory());
		System.out.println("Availability is: " + b2.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 2");
		b2.issueBook();
		System.out.println("Availability After Issue is: " + b2.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 2");
		b2.returnBook();
		System.out.println("Availability After Return is: " + b2.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 3 Details=================================");
		System.out.println("Object Reference is: " + b3);
		System.out.println("Title is: " + b3.getTitle());
		System.out.println("Author is: " + b3.getAuthor());
		System.out.println("Book ID is: " + b3.getBookID());
		System.out.println("Category is: " + b3.getCategory());
		System.out.println("Availability is: " + b3.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 3");
		b3.issueBook();
		System.out.println("Availability After Issue is: " + b3.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 3");
		b3.returnBook();
		System.out.println("Availability After Return is: " + b3.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 4 Details=================================");
		System.out.println("Object Reference is: " + b4);
		System.out.println("Title is: " + b4.getTitle());
		System.out.println("Author is: " + b4.getAuthor());
		System.out.println("Book ID is: " + b4.getBookID());
		System.out.println("Category is: " + b4.getCategory());
		System.out.println("Availability is: " + b4.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 4");
		b4.issueBook();
		System.out.println("Availability After Issue is: " + b4.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 4");
		b4.returnBook();
		System.out.println("Availability After Return is: " + b4.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 5 Details=================================");
		System.out.println("Object Reference is: " + b5);
		System.out.println("Title is: " + b5.getTitle());
		System.out.println("Author is: " + b5.getAuthor());
		System.out.println("Book ID is: " + b5.getBookID());
		System.out.println("Category is: " + b5.getCategory());
		System.out.println("Availability is: " + b5.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 5");
		b5.issueBook();
		System.out.println("Availability After Issue is: " + b5.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 5");
		b5.returnBook();
		System.out.println("Availability After Return is: " + b5.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 6 Details=================================");
		System.out.println("Object Reference is: " + b6);
		System.out.println("Title is: " + b6.getTitle());
		System.out.println("Author is: " + b6.getAuthor());
		System.out.println("Book ID is: " + b6.getBookID());
		System.out.println("Category is: " + b6.getCategory());
		System.out.println("Availability is: " + b6.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 6");
		b6.issueBook();
		System.out.println("Availability After Issue is: " + b6.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 6");
		b6.returnBook();
		System.out.println("Availability After Return is: " + b6.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 7 Details=================================");
		System.out.println("Object Reference is: " + b7);
		System.out.println("Title is: " + b7.getTitle());
		System.out.println("Author is: " + b7.getAuthor());
		System.out.println("Book ID is: " + b7.getBookID());
		System.out.println("Category is: " + b7.getCategory());
		System.out.println("Availability is: " + b7.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 7");
		b7.issueBook();
		System.out.println("Availability After Issue is: " + b7.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 7");
		b7.returnBook();
		System.out.println("Availability After Return is: " + b7.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 8 Details=================================");
		System.out.println("Object Reference is: " + b8);
		System.out.println("Title is: " + b8.getTitle());
		System.out.println("Author is: " + b8.getAuthor());
		System.out.println("Book ID is: " + b8.getBookID());
		System.out.println("Category is: " + b8.getCategory());
		System.out.println("Availability is: " + b8.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 8");
		b8.issueBook();
		System.out.println("Availability After Issue is: " + b8.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 8");
		b8.returnBook();
		System.out.println("Availability After Return is: " + b8.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 9 Details=================================");
		System.out.println("Object Reference is: " + b9);
		System.out.println("Title is: " + b9.getTitle());
		System.out.println("Author is: " + b9.getAuthor());
		System.out.println("Book ID is: " + b9.getBookID());
		System.out.println("Category is: " + b9.getCategory());
		System.out.println("Availability is: " + b9.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 9");
		b9.issueBook();
		System.out.println("Availability After Issue is: " + b9.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 9");
		b9.returnBook();
		System.out.println("Availability After Return is: " + b9.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 10 Details=================================");
		System.out.println("Object Reference is: " + b10);
		System.out.println("Title is: " + b10.getTitle());
		System.out.println("Author is: " + b10.getAuthor());
		System.out.println("Book ID is: " + b10.getBookID());
		System.out.println("Category is: " + b10.getCategory());
		System.out.println("Availability is: " + b10.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 10");
		b10.issueBook();
		System.out.println("Availability After Issue is: " + b10.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 10");
		b10.returnBook();
		System.out.println("Availability After Return is: " + b10.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 11 Details=================================");
		System.out.println("Object Reference is: " + b11);
		System.out.println("Title is: " + b11.getTitle());
		System.out.println("Author is: " + b11.getAuthor());
		System.out.println("Book ID is: " + b11.getBookID());
		System.out.println("Category is: " + b11.getCategory());
		System.out.println("Availability is: " + b11.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 11");
		b11.issueBook();
		System.out.println("Availability After Issue is: " + b11.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 11");
		b11.returnBook();
		System.out.println("Availability After Return is: " + b11.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 12 Details=================================");
		System.out.println("Object Reference is: " + b12);
		System.out.println("Title is: " + b12.getTitle());
		System.out.println("Author is: " + b12.getAuthor());
		System.out.println("Book ID is: " + b12.getBookID());
		System.out.println("Category is: " + b12.getCategory());
		System.out.println("Availability is: " + b12.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 12");
		b12.issueBook();
		System.out.println("Availability After Issue is: " + b12.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 12");
		b12.returnBook();
		System.out.println("Availability After Return is: " + b12.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 13 Details=================================");
		System.out.println("Object Reference is: " + b13);
		System.out.println("Title is: " + b13.getTitle());
		System.out.println("Author is: " + b13.getAuthor());
		System.out.println("Book ID is: " + b13.getBookID());
		System.out.println("Category is: " + b13.getCategory());
		System.out.println("Availability is: " + b13.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 13");
		b13.issueBook();
		System.out.println("Availability After Issue is: " + b13.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 13");
		b13.returnBook();
		System.out.println("Availability After Return is: " + b13.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 14 Details=================================");
		System.out.println("Object Reference is: " + b14);
		System.out.println("Title is: " + b14.getTitle());
		System.out.println("Author is: " + b14.getAuthor());
		System.out.println("Book ID is: " + b14.getBookID());
		System.out.println("Category is: " + b14.getCategory());
		System.out.println("Availability is: " + b14.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 14");
		b14.issueBook();
		System.out.println("Availability After Issue is: " + b14.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 14");
		b14.returnBook();
		System.out.println("Availability After Return is: " + b14.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 15 Details=================================");
		System.out.println("Object Reference is: " + b15);
		System.out.println("Title is: " + b15.getTitle());
		System.out.println("Author is: " + b15.getAuthor());
		System.out.println("Book ID is: " + b15.getBookID());
		System.out.println("Category is: " + b15.getCategory());
		System.out.println("Availability is: " + b15.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 15");
		b15.issueBook();
		System.out.println("Availability After Issue is: " + b15.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 15");
		b15.returnBook();
		System.out.println("Availability After Return is: " + b15.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 16 Details=================================");
		System.out.println("Object Reference is: " + b16);
		System.out.println("Title is: " + b16.getTitle());
		System.out.println("Author is: " + b16.getAuthor());
		System.out.println("Book ID is: " + b16.getBookID());
		System.out.println("Category is: " + b16.getCategory());
		System.out.println("Availability is: " + b16.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 16");
		b16.issueBook();
		System.out.println("Availability After Issue is: " + b16.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 16");
		b16.returnBook();
		System.out.println("Availability After Return is: " + b16.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 17 Details=================================");
		System.out.println("Object Reference is: " + b17);
		System.out.println("Title is: " + b17.getTitle());
		System.out.println("Author is: " + b17.getAuthor());
		System.out.println("Book ID is: " + b17.getBookID());
		System.out.println("Category is: " + b17.getCategory());
		System.out.println("Availability is: " + b17.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 17");
		b17.issueBook();
		System.out.println("Availability After Issue is: " + b17.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 17");
		b17.returnBook();
		System.out.println("Availability After Return is: " + b17.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 18 Details=================================");
		System.out.println("Object Reference is: " + b18);
		System.out.println("Title is: " + b18.getTitle());
		System.out.println("Author is: " + b18.getAuthor());
		System.out.println("Book ID is: " + b18.getBookID());
		System.out.println("Category is: " + b18.getCategory());
		System.out.println("Availability is: " + b18.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 18");
		b18.issueBook();
		System.out.println("Availability After Issue is: " + b18.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 18");
		b18.returnBook();
		System.out.println("Availability After Return is: " + b18.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 19 Details=================================");
		System.out.println("Object Reference is: " + b19);
		System.out.println("Title is: " + b19.getTitle());
		System.out.println("Author is: " + b19.getAuthor());
		System.out.println("Book ID is: " + b19.getBookID());
		System.out.println("Category is: " + b19.getCategory());
		System.out.println("Availability is: " + b19.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 19");
		b19.issueBook();
		System.out.println("Availability After Issue is: " + b19.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 19");
		b19.returnBook();
		System.out.println("Availability After Return is: " + b19.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 20 Details=================================");
		System.out.println("Object Reference is: " + b20);
		System.out.println("Title is: " + b20.getTitle());
		System.out.println("Author is: " + b20.getAuthor());
		System.out.println("Book ID is: " + b20.getBookID());
		System.out.println("Category is: " + b20.getCategory());
		System.out.println("Availability is: " + b20.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 20");
		b20.issueBook();
		System.out.println("Availability After Issue is: " + b20.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 20");
		b20.returnBook();
		System.out.println("Availability After Return is: " + b20.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 21 Details=================================");
		System.out.println("Object Reference is: " + b21);
		System.out.println("Title is: " + b21.getTitle());
		System.out.println("Author is: " + b21.getAuthor());
		System.out.println("Book ID is: " + b21.getBookID());
		System.out.println("Category is: " + b21.getCategory());
		System.out.println("Availability is: " + b21.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 21");
		b21.issueBook();
		System.out.println("Availability After Issue is: " + b21.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 21");
		b21.returnBook();
		System.out.println("Availability After Return is: " + b21.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 22 Details=================================");
		System.out.println("Object Reference is: " + b22);
		System.out.println("Title is: " + b22.getTitle());
		System.out.println("Author is: " + b22.getAuthor());
		System.out.println("Book ID is: " + b22.getBookID());
		System.out.println("Category is: " + b22.getCategory());
		System.out.println("Availability is: " + b22.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 22");
		b22.issueBook();
		System.out.println("Availability After Issue is: " + b22.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 22");
		b22.returnBook();
		System.out.println("Availability After Return is: " + b22.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 23 Details=================================");
		System.out.println("Object Reference is: " + b23);
		System.out.println("Title is: " + b23.getTitle());
		System.out.println("Author is: " + b23.getAuthor());
		System.out.println("Book ID is: " + b23.getBookID());
		System.out.println("Category is: " + b23.getCategory());
		System.out.println("Availability is: " + b23.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 23");
		b23.issueBook();
		System.out.println("Availability After Issue is: " + b23.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 23");
		b23.returnBook();
		System.out.println("Availability After Return is: " + b23.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 24 Details=================================");
		System.out.println("Object Reference is: " + b24);
		System.out.println("Title is: " + b24.getTitle());
		System.out.println("Author is: " + b24.getAuthor());
		System.out.println("Book ID is: " + b24.getBookID());
		System.out.println("Category is: " + b24.getCategory());
		System.out.println("Availability is: " + b24.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 24");
		b24.issueBook();
		System.out.println("Availability After Issue is: " + b24.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 24");
		b24.returnBook();
		System.out.println("Availability After Return is: " + b24.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 25 Details=================================");
		System.out.println("Object Reference is: " + b25);
		System.out.println("Title is: " + b25.getTitle());
		System.out.println("Author is: " + b25.getAuthor());
		System.out.println("Book ID is: " + b25.getBookID());
		System.out.println("Category is: " + b25.getCategory());
		System.out.println("Availability is: " + b25.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 25");
		b25.issueBook();
		System.out.println("Availability After Issue is: " + b25.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 25");
		b25.returnBook();
		System.out.println("Availability After Return is: " + b25.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 26 Details=================================");
		System.out.println("Object Reference is: " + b26);
		System.out.println("Title is: " + b26.getTitle());
		System.out.println("Author is: " + b26.getAuthor());
		System.out.println("Book ID is: " + b26.getBookID());
		System.out.println("Category is: " + b26.getCategory());
		System.out.println("Availability is: " + b26.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 26");
		b26.issueBook();
		System.out.println("Availability After Issue is: " + b26.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 26");
		b26.returnBook();
		System.out.println("Availability After Return is: " + b26.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 27 Details=================================");
		System.out.println("Object Reference is: " + b27);
		System.out.println("Title is: " + b27.getTitle());
		System.out.println("Author is: " + b27.getAuthor());
		System.out.println("Book ID is: " + b27.getBookID());
		System.out.println("Category is: " + b27.getCategory());
		System.out.println("Availability is: " + b27.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 27");
		b27.issueBook();
		System.out.println("Availability After Issue is: " + b27.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 27");
		b27.returnBook();
		System.out.println("Availability After Return is: " + b27.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 28 Details=================================");
		System.out.println("Object Reference is: " + b28);
		System.out.println("Title is: " + b28.getTitle());
		System.out.println("Author is: " + b28.getAuthor());
		System.out.println("Book ID is: " + b28.getBookID());
		System.out.println("Category is: " + b28.getCategory());
		System.out.println("Availability is: " + b28.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 28");
		b28.issueBook();
		System.out.println("Availability After Issue is: " + b28.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 28");
		b28.returnBook();
		System.out.println("Availability After Return is: " + b28.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 29 Details=================================");
		System.out.println("Object Reference is: " + b29);
		System.out.println("Title is: " + b29.getTitle());
		System.out.println("Author is: " + b29.getAuthor());
		System.out.println("Book ID is: " + b29.getBookID());
		System.out.println("Category is: " + b29.getCategory());
		System.out.println("Availability is: " + b29.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 29");
		b29.issueBook();
		System.out.println("Availability After Issue is: " + b29.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 29");
		b29.returnBook();
		System.out.println("Availability After Return is: " + b29.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 30 Details=================================");
		System.out.println("Object Reference is: " + b30);
		System.out.println("Title is: " + b30.getTitle());
		System.out.println("Author is: " + b30.getAuthor());
		System.out.println("Book ID is: " + b30.getBookID());
		System.out.println("Category is: " + b30.getCategory());
		System.out.println("Availability is: " + b30.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 30");
		b30.issueBook();
		System.out.println("Availability After Issue is: " + b30.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 30");
		b30.returnBook();
		System.out.println("Availability After Return is: " + b30.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 31 Details=================================");
		System.out.println("Object Reference is: " + b31);
		System.out.println("Title is: " + b31.getTitle());
		System.out.println("Author is: " + b31.getAuthor());
		System.out.println("Book ID is: " + b31.getBookID());
		System.out.println("Category is: " + b31.getCategory());
		System.out.println("Availability is: " + b31.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 31");
		b31.issueBook();
		System.out.println("Availability After Issue is: " + b31.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 31");
		b31.returnBook();
		System.out.println("Availability After Return is: " + b31.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 32 Details=================================");
		System.out.println("Object Reference is: " + b32);
		System.out.println("Title is: " + b32.getTitle());
		System.out.println("Author is: " + b32.getAuthor());
		System.out.println("Book ID is: " + b32.getBookID());
		System.out.println("Category is: " + b32.getCategory());
		System.out.println("Availability is: " + b32.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 32");
		b32.issueBook();
		System.out.println("Availability After Issue is: " + b32.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 32");
		b32.returnBook();
		System.out.println("Availability After Return is: " + b32.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 33 Details=================================");
		System.out.println("Object Reference is: " + b33);
		System.out.println("Title is: " + b33.getTitle());
		System.out.println("Author is: " + b33.getAuthor());
		System.out.println("Book ID is: " + b33.getBookID());
		System.out.println("Category is: " + b33.getCategory());
		System.out.println("Availability is: " + b33.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 33");
		b33.issueBook();
		System.out.println("Availability After Issue is: " + b33.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 33");
		b33.returnBook();
		System.out.println("Availability After Return is: " + b33.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 34 Details=================================");
		System.out.println("Object Reference is: " + b34);
		System.out.println("Title is: " + b34.getTitle());
		System.out.println("Author is: " + b34.getAuthor());
		System.out.println("Book ID is: " + b34.getBookID());
		System.out.println("Category is: " + b34.getCategory());
		System.out.println("Availability is: " + b34.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 34");
		b34.issueBook();
		System.out.println("Availability After Issue is: " + b34.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 34");
		b34.returnBook();
		System.out.println("Availability After Return is: " + b34.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 35 Details=================================");
		System.out.println("Object Reference is: " + b35);
		System.out.println("Title is: " + b35.getTitle());
		System.out.println("Author is: " + b35.getAuthor());
		System.out.println("Book ID is: " + b35.getBookID());
		System.out.println("Category is: " + b35.getCategory());
		System.out.println("Availability is: " + b35.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 35");
		b35.issueBook();
		System.out.println("Availability After Issue is: " + b35.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 35");
		b35.returnBook();
		System.out.println("Availability After Return is: " + b35.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 36 Details=================================");
		System.out.println("Object Reference is: " + b36);
		System.out.println("Title is: " + b36.getTitle());
		System.out.println("Author is: " + b36.getAuthor());
		System.out.println("Book ID is: " + b36.getBookID());
		System.out.println("Category is: " + b36.getCategory());
		System.out.println("Availability is: " + b36.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 36");
		b36.issueBook();
		System.out.println("Availability After Issue is: " + b36.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 36");
		b36.returnBook();
		System.out.println("Availability After Return is: " + b36.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 37 Details=================================");
		System.out.println("Object Reference is: " + b37);
		System.out.println("Title is: " + b37.getTitle());
		System.out.println("Author is: " + b37.getAuthor());
		System.out.println("Book ID is: " + b37.getBookID());
		System.out.println("Category is: " + b37.getCategory());
		System.out.println("Availability is: " + b37.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 37");
		b37.issueBook();
		System.out.println("Availability After Issue is: " + b37.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 37");
		b37.returnBook();
		System.out.println("Availability After Return is: " + b37.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 38 Details=================================");
		System.out.println("Object Reference is: " + b38);
		System.out.println("Title is: " + b38.getTitle());
		System.out.println("Author is: " + b38.getAuthor());
		System.out.println("Book ID is: " + b38.getBookID());
		System.out.println("Category is: " + b38.getCategory());
		System.out.println("Availability is: " + b38.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 38");
		b38.issueBook();
		System.out.println("Availability After Issue is: " + b38.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 38");
		b38.returnBook();
		System.out.println("Availability After Return is: " + b38.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 39 Details=================================");
		System.out.println("Object Reference is: " + b39);
		System.out.println("Title is: " + b39.getTitle());
		System.out.println("Author is: " + b39.getAuthor());
		System.out.println("Book ID is: " + b39.getBookID());
		System.out.println("Category is: " + b39.getCategory());
		System.out.println("Availability is: " + b39.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 39");
		b39.issueBook();
		System.out.println("Availability After Issue is: " + b39.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 39");
		b39.returnBook();
		System.out.println("Availability After Return is: " + b39.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 40 Details=================================");
		System.out.println("Object Reference is: " + b40);
		System.out.println("Title is: " + b40.getTitle());
		System.out.println("Author is: " + b40.getAuthor());
		System.out.println("Book ID is: " + b40.getBookID());
		System.out.println("Category is: " + b40.getCategory());
		System.out.println("Availability is: " + b40.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 40");
		b40.issueBook();
		System.out.println("Availability After Issue is: " + b40.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 40");
		b40.returnBook();
		System.out.println("Availability After Return is: " + b40.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 41 Details=================================");
		System.out.println("Object Reference is: " + b41);
		System.out.println("Title is: " + b41.getTitle());
		System.out.println("Author is: " + b41.getAuthor());
		System.out.println("Book ID is: " + b41.getBookID());
		System.out.println("Category is: " + b41.getCategory());
		System.out.println("Availability is: " + b41.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 41");
		b41.issueBook();
		System.out.println("Availability After Issue is: " + b41.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 41");
		b41.returnBook();
		System.out.println("Availability After Return is: " + b41.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 42 Details=================================");
		System.out.println("Object Reference is: " + b42);
		System.out.println("Title is: " + b42.getTitle());
		System.out.println("Author is: " + b42.getAuthor());
		System.out.println("Book ID is: " + b42.getBookID());
		System.out.println("Category is: " + b42.getCategory());
		System.out.println("Availability is: " + b42.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 42");
		b42.issueBook();
		System.out.println("Availability After Issue is: " + b42.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 42");
		b42.returnBook();
		System.out.println("Availability After Return is: " + b42.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 43 Details=================================");
		System.out.println("Object Reference is: " + b43);
		System.out.println("Title is: " + b43.getTitle());
		System.out.println("Author is: " + b43.getAuthor());
		System.out.println("Book ID is: " + b43.getBookID());
		System.out.println("Category is: " + b43.getCategory());
		System.out.println("Availability is: " + b43.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 43");
		b43.issueBook();
		System.out.println("Availability After Issue is: " + b43.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 43");
		b43.returnBook();
		System.out.println("Availability After Return is: " + b43.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 44 Details=================================");
		System.out.println("Object Reference is: " + b44);
		System.out.println("Title is: " + b44.getTitle());
		System.out.println("Author is: " + b44.getAuthor());
		System.out.println("Book ID is: " + b44.getBookID());
		System.out.println("Category is: " + b44.getCategory());
		System.out.println("Availability is: " + b44.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 44");
		b44.issueBook();
		System.out.println("Availability After Issue is: " + b44.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 44");
		b44.returnBook();
		System.out.println("Availability After Return is: " + b44.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 45 Details=================================");
		System.out.println("Object Reference is: " + b45);
		System.out.println("Title is: " + b45.getTitle());
		System.out.println("Author is: " + b45.getAuthor());
		System.out.println("Book ID is: " + b45.getBookID());
		System.out.println("Category is: " + b45.getCategory());
		System.out.println("Availability is: " + b45.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 45");
		b45.issueBook();
		System.out.println("Availability After Issue is: " + b45.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 45");
		b45.returnBook();
		System.out.println("Availability After Return is: " + b45.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 46 Details=================================");
		System.out.println("Object Reference is: " + b46);
		System.out.println("Title is: " + b46.getTitle());
		System.out.println("Author is: " + b46.getAuthor());
		System.out.println("Book ID is: " + b46.getBookID());
		System.out.println("Category is: " + b46.getCategory());
		System.out.println("Availability is: " + b46.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 46");
		b46.issueBook();
		System.out.println("Availability After Issue is: " + b46.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 46");
		b46.returnBook();
		System.out.println("Availability After Return is: " + b46.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 47 Details=================================");
		System.out.println("Object Reference is: " + b47);
		System.out.println("Title is: " + b47.getTitle());
		System.out.println("Author is: " + b47.getAuthor());
		System.out.println("Book ID is: " + b47.getBookID());
		System.out.println("Category is: " + b47.getCategory());
		System.out.println("Availability is: " + b47.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 47");
		b47.issueBook();
		System.out.println("Availability After Issue is: " + b47.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 47");
		b47.returnBook();
		System.out.println("Availability After Return is: " + b47.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 48 Details=================================");
		System.out.println("Object Reference is: " + b48);
		System.out.println("Title is: " + b48.getTitle());
		System.out.println("Author is: " + b48.getAuthor());
		System.out.println("Book ID is: " + b48.getBookID());
		System.out.println("Category is: " + b48.getCategory());
		System.out.println("Availability is: " + b48.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 48");
		b48.issueBook();
		System.out.println("Availability After Issue is: " + b48.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 48");
		b48.returnBook();
		System.out.println("Availability After Return is: " + b48.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 49 Details=================================");
		System.out.println("Object Reference is: " + b49);
		System.out.println("Title is: " + b49.getTitle());
		System.out.println("Author is: " + b49.getAuthor());
		System.out.println("Book ID is: " + b49.getBookID());
		System.out.println("Category is: " + b49.getCategory());
		System.out.println("Availability is: " + b49.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 49");
		b49.issueBook();
		System.out.println("Availability After Issue is: " + b49.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 49");
		b49.returnBook();
		System.out.println("Availability After Return is: " + b49.getAvailability());
		System.out.println("=====================================================");

		System.out.println("===========================LibraryBook 50 Details=================================");
		System.out.println("Object Reference is: " + b50);
		System.out.println("Title is: " + b50.getTitle());
		System.out.println("Author is: " + b50.getAuthor());
		System.out.println("Book ID is: " + b50.getBookID());
		System.out.println("Category is: " + b50.getCategory());
		System.out.println("Availability is: " + b50.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Issuing Book 50");
		b50.issueBook();
		System.out.println("Availability After Issue is: " + b50.getAvailability());
		System.out.println("=====================================================");
		System.out.println("Returning Book 50");
		b50.returnBook();
		System.out.println("Availability After Return is: " + b50.getAvailability());
		System.out.println("=====================================================");
		
		System.out.println("==================================Main Method Ends====================================");

	}

}
