package encapsulationsPrograming;

public class OnlineShoppingSystemDriver {

	public static void main(String[] args) {
		
		System.out.println("========================================Main Method Ends===========================================");

		OnlineShoppingSystem s1 = new OnlineShoppingSystem("Mohan Singh", "CUS101", "Noida", 9876543210L, "Laptop", "PROD101", "Electronics", 75000.00, 1, "ORD101", "Placed");
		OnlineShoppingSystem s2 = new OnlineShoppingSystem("Rohan Kumar", "CUS102", "Lucknow", 9876543211L, "Smartphone", "PROD102", "Electronics", 45000.00, 2, "ORD102", "Packed");
		OnlineShoppingSystem s3 = new OnlineShoppingSystem("Sohan Sharma", "CUS103", "Delhi", 9876543212L, "Headphones", "PROD103", "Accessories", 3500.00, 3, "ORD103", "Shipped");
		OnlineShoppingSystem s4 = new OnlineShoppingSystem("Rahul Verma", "CUS104", "Mumbai", 9876543213L, "Smart Watch", "PROD104", "Electronics", 6500.00, 1, "ORD104", "Delivered");
		OnlineShoppingSystem s5 = new OnlineShoppingSystem("Shyam Gupta", "CUS105", "Pune", 9876543214L, "Office Chair", "PROD105", "Furniture", 8500.00, 2, "ORD105", "Placed");
		OnlineShoppingSystem s6 = new OnlineShoppingSystem("Manoj Singh", "CUS106", "Kanpur", 9876543215L, "Running Shoes", "PROD106", "Footwear", 4200.00, 2, "ORD106", "Packed");
		OnlineShoppingSystem s7 = new OnlineShoppingSystem("Akash Kumar", "CUS107", "Meerut", 9876543216L, "Backpack", "PROD107", "Fashion", 2200.00, 1, "ORD107", "Shipped");
		OnlineShoppingSystem s8 = new OnlineShoppingSystem("Samarth Singh", "CUS108", "Jaipur", 9876543217L, "Television", "PROD108", "Electronics", 55000.00, 1, "ORD108", "Delivered");
		OnlineShoppingSystem s9 = new OnlineShoppingSystem("Abhishek Kumar", "CUS109", "Ahmedabad", 9876543218L, "Dining Table", "PROD109", "Furniture", 18000.00, 1, "ORD109", "Placed");
		OnlineShoppingSystem s10 = new OnlineShoppingSystem("Karan Singh", "CUS110", "Gurugram", 9876543219L, "Bluetooth Speaker", "PROD110", "Accessories", 5500.00, 2, "ORD110", "Cancelled");

		OnlineShoppingSystem s11 = new OnlineShoppingSystem("Aman Sharma", "CUS111", "Noida", 9876543220L, "Tablet", "PROD111", "Electronics", 28000.00, 1, "ORD111", "Placed");
		OnlineShoppingSystem s12 = new OnlineShoppingSystem("Ravi Kumar", "CUS112", "Lucknow", 9876543221L, "Keyboard", "PROD112", "Accessories", 2500.00, 2, "ORD112", "Packed");
		OnlineShoppingSystem s13 = new OnlineShoppingSystem("Pankaj Verma", "CUS113", "Delhi", 9876543222L, "Mouse", "PROD113", "Accessories", 1200.00, 3, "ORD113", "Shipped");
		OnlineShoppingSystem s14 = new OnlineShoppingSystem("Nitin Sharma", "CUS114", "Mumbai", 9876543223L, "Refrigerator", "PROD114", "Home Appliances", 62000.00, 1, "ORD114", "Delivered");
		OnlineShoppingSystem s15 = new OnlineShoppingSystem("Varun Gupta", "CUS115", "Pune", 9876543224L, "Microwave Oven", "PROD115", "Home Appliances", 15000.00, 1, "ORD115", "Placed");
		OnlineShoppingSystem s16 = new OnlineShoppingSystem("Ankit Kumar", "CUS116", "Kanpur", 9876543225L, "Washing Machine", "PROD116", "Home Appliances", 38000.00, 1, "ORD116", "Packed");
		OnlineShoppingSystem s17 = new OnlineShoppingSystem("Deepak Sharma", "CUS117", "Meerut", 9876543226L, "Jeans", "PROD117", "Fashion", 2200.00, 2, "ORD117", "Shipped");
		OnlineShoppingSystem s18 = new OnlineShoppingSystem("Rakesh Verma", "CUS118", "Jaipur", 9876543227L, "T-Shirt", "PROD118", "Fashion", 999.00, 3, "ORD118", "Delivered");
		OnlineShoppingSystem s19 = new OnlineShoppingSystem("Suresh Kumar", "CUS119", "Ahmedabad", 9876543228L, "Sofa Set", "PROD119", "Furniture", 45000.00, 1, "ORD119", "Placed");
		OnlineShoppingSystem s20 = new OnlineShoppingSystem("Rajesh Singh", "CUS120", "Gurugram", 9876543229L, "Study Table", "PROD120", "Furniture", 12500.00, 1, "ORD120", "Cancelled");

		OnlineShoppingSystem s21 = new OnlineShoppingSystem("Mohit Sharma", "CUS121", "Noida", 9876543230L, "Camera", "PROD121", "Electronics", 52000.00, 1, "ORD121", "Placed");
		OnlineShoppingSystem s22 = new OnlineShoppingSystem("Vikas Kumar", "CUS122", "Lucknow", 9876543231L, "Tripod", "PROD122", "Accessories", 3500.00, 2, "ORD122", "Packed");
		OnlineShoppingSystem s23 = new OnlineShoppingSystem("Amit Verma", "CUS123", "Delhi", 9876543232L, "Power Bank", "PROD123", "Accessories", 1800.00, 3, "ORD123", "Shipped");
		OnlineShoppingSystem s24 = new OnlineShoppingSystem("Sanjay Sharma", "CUS124", "Mumbai", 9876543233L, "Air Conditioner", "PROD124", "Home Appliances", 48000.00, 1, "ORD124", "Delivered");
		OnlineShoppingSystem s25 = new OnlineShoppingSystem("Ravi Singh", "CUS125", "Pune", 9876543234L, "Ceiling Fan", "PROD125", "Home Appliances", 3200.00, 2, "ORD125", "Placed");
		OnlineShoppingSystem s26 = new OnlineShoppingSystem("Ashish Kumar", "CUS126", "Kanpur", 9876543235L, "Mixer Grinder", "PROD126", "Kitchen Appliances", 6500.00, 1, "ORD126", "Packed");
		OnlineShoppingSystem s27 = new OnlineShoppingSystem("Neeraj Verma", "CUS127", "Meerut", 9876543236L, "Coffee Maker", "PROD127", "Kitchen Appliances", 4800.00, 1, "ORD127", "Shipped");
		OnlineShoppingSystem s28 = new OnlineShoppingSystem("Piyush Sharma", "CUS128", "Jaipur", 9876543237L, "Air Fryer", "PROD128", "Kitchen Appliances", 7200.00, 2, "ORD128", "Delivered");
		OnlineShoppingSystem s29 = new OnlineShoppingSystem("Kunal Gupta", "CUS129", "Ahmedabad", 9876543238L, "Formal Shirt", "PROD129", "Fashion", 1800.00, 2, "ORD129", "Placed");
		OnlineShoppingSystem s30 = new OnlineShoppingSystem("Manish Singh", "CUS130", "Gurugram", 9876543239L, "Leather Shoes", "PROD130", "Footwear", 5500.00, 1, "ORD130", "Cancelled");

		OnlineShoppingSystem s31 = new OnlineShoppingSystem("Lokesh Kumar", "CUS131", "Noida", 9876543240L, "Sports Watch", "PROD131", "Sports", 6800.00, 1, "ORD131", "Placed");
		OnlineShoppingSystem s32 = new OnlineShoppingSystem("Arjun Verma", "CUS132", "Lucknow", 9876543241L, "Cricket Bat", "PROD132", "Sports", 4200.00, 2, "ORD132", "Packed");
		OnlineShoppingSystem s33 = new OnlineShoppingSystem("Akhil Sharma", "CUS133", "Delhi", 9876543242L, "Football", "PROD133", "Sports", 1600.00, 3, "ORD133", "Shipped");
		OnlineShoppingSystem s34 = new OnlineShoppingSystem("Sandeep Kumar", "CUS134", "Mumbai", 9876543243L, "Treadmill", "PROD134", "Fitness", 55000.00, 1, "ORD134", "Delivered");
		OnlineShoppingSystem s35 = new OnlineShoppingSystem("Mukesh Verma", "CUS135", "Pune", 9876543244L, "Yoga Mat", "PROD135", "Fitness", 1400.00, 2, "ORD135", "Placed");
		OnlineShoppingSystem s36 = new OnlineShoppingSystem("Yogesh Singh", "CUS136", "Kanpur", 9876543245L, "Dumbbells", "PROD136", "Fitness", 2600.00, 2, "ORD136", "Packed");
		OnlineShoppingSystem s37 = new OnlineShoppingSystem("Nikhil Kumar", "CUS137", "Meerut", 9876543246L, "School Bag", "PROD137", "Bags", 1800.00, 1, "ORD137", "Shipped");
		OnlineShoppingSystem s38 = new OnlineShoppingSystem("Gaurav Sharma", "CUS138", "Jaipur", 9876543247L, "Travel Bag", "PROD138", "Bags", 3200.00, 2, "ORD138", "Delivered");
		OnlineShoppingSystem s39 = new OnlineShoppingSystem("Rajat Verma", "CUS139", "Ahmedabad", 9876543248L, "Sunglasses", "PROD139", "Fashion", 2800.00, 1, "ORD139", "Placed");
		OnlineShoppingSystem s40 = new OnlineShoppingSystem("Chetan Kumar", "CUS140", "Gurugram", 9876543249L, "Smart TV", "PROD140", "Electronics", 68000.00, 1, "ORD140", "Cancelled");

		OnlineShoppingSystem s41 = new OnlineShoppingSystem("Vishal Sharma", "CUS141", "Noida", 9876543250L, "Laptop Bag", "PROD141", "Accessories", 2400.00, 2, "ORD141", "Placed");
		OnlineShoppingSystem s42 = new OnlineShoppingSystem("Pawan Singh", "CUS142", "Lucknow", 9876543251L, "Wireless Earbuds", "PROD142", "Accessories", 4200.00, 2, "ORD142", "Packed");
		OnlineShoppingSystem s43 = new OnlineShoppingSystem("Suraj Kumar", "CUS143", "Delhi", 9876543252L, "Gaming Monitor", "PROD143", "Electronics", 27000.00, 1, "ORD143", "Shipped");
		OnlineShoppingSystem s44 = new OnlineShoppingSystem("Dev Sharma", "CUS144", "Mumbai", 9876543253L, "Gaming Keyboard", "PROD144", "Electronics", 6500.00, 1, "ORD144", "Delivered");
		OnlineShoppingSystem s45 = new OnlineShoppingSystem("Akhilesh Verma", "CUS145", "Pune", 9876543254L, "Gaming Mouse", "PROD145", "Accessories", 3200.00, 2, "ORD145", "Placed");
		OnlineShoppingSystem s46 = new OnlineShoppingSystem("Ramesh Kumar", "CUS146", "Kanpur", 9876543255L, "Printer", "PROD146", "Electronics", 15000.00, 1, "ORD146", "Packed");
		OnlineShoppingSystem s47 = new OnlineShoppingSystem("Shivam Singh", "CUS147", "Meerut", 9876543256L, "Bookshelf", "PROD147", "Furniture", 8500.00, 1, "ORD147", "Shipped");
		OnlineShoppingSystem s48 = new OnlineShoppingSystem("Prakash Kumar", "CUS148", "Jaipur", 9876543257L, "Bedside Table", "PROD148", "Furniture", 5600.00, 2, "ORD148", "Delivered");
		OnlineShoppingSystem s49 = new OnlineShoppingSystem("Harish Sharma", "CUS149", "Ahmedabad", 9876543258L, "Wall Clock", "PROD149", "Home Decor", 1800.00, 1, "ORD149", "Placed");
		OnlineShoppingSystem s50 = new OnlineShoppingSystem("Vijay Verma", "CUS150", "Gurugram", 9876543259L, "Table Lamp", "PROD150", "Home Decor", 2200.00, 3, "ORD150", "Cancelled");
		
		System.out.println("=========================Online Shopping Details 1===========================");
		System.out.println("Object Reference is: " + s1);
		System.out.println("Customer Name is: " + s1.getCustomerName());
		System.out.println("Customer ID is: " + s1.getCustomerID());
		System.out.println("Customer Address is: " + s1.getCustomerAddress());
		System.out.println("Contact is: " + s1.getContact());
		System.out.println("Product Name is: " + s1.getProductName());
		System.out.println("Product ID is: " + s1.getProductID());
		System.out.println("Category is: " + s1.getCategory());
		System.out.println("Price is: " + s1.getPrice());
		System.out.println("Quantity is: " + s1.getQuantity());
		System.out.println("Order ID is: " + s1.getOrderID());
		System.out.println("Order Status is: " + s1.getOrderStatus());
		System.out.println("Total Amount is: " + s1.getTotalAmount());
		
		System.out.println("=========================Online Shopping Details 1===========================");
		System.out.println("Object Reference is: " + s1);
		System.out.println("Customer Name is: " + s1.getCustomerName());
		System.out.println("Customer ID is: " + s1.getCustomerID());
		System.out.println("Customer Address is: " + s1.getCustomerAddress());
		System.out.println("Contact is: " + s1.getContact());
		System.out.println("Product Name is: " + s1.getProductName());
		System.out.println("Product ID is: " + s1.getProductID());
		System.out.println("Category is: " + s1.getCategory());
		System.out.println("Price is: " + s1.getPrice());
		System.out.println("Quantity is: " + s1.getQuantity());
		System.out.println("Order ID is: " + s1.getOrderID());
		System.out.println("Order Status is: " + s1.getOrderStatus());
		System.out.println("Total Amount is: " + s1.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 2===========================");
		System.out.println("Object Reference is: " + s2);
		System.out.println("Customer Name is: " + s2.getCustomerName());
		System.out.println("Customer ID is: " + s2.getCustomerID());
		System.out.println("Customer Address is: " + s2.getCustomerAddress());
		System.out.println("Contact is: " + s2.getContact());
		System.out.println("Product Name is: " + s2.getProductName());
		System.out.println("Product ID is: " + s2.getProductID());
		System.out.println("Category is: " + s2.getCategory());
		System.out.println("Price is: " + s2.getPrice());
		System.out.println("Quantity is: " + s2.getQuantity());
		System.out.println("Order ID is: " + s2.getOrderID());
		System.out.println("Order Status is: " + s2.getOrderStatus());
		System.out.println("Total Amount is: " + s2.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 3===========================");
		System.out.println("Object Reference is: " + s3);
		System.out.println("Customer Name is: " + s3.getCustomerName());
		System.out.println("Customer ID is: " + s3.getCustomerID());
		System.out.println("Customer Address is: " + s3.getCustomerAddress());
		System.out.println("Contact is: " + s3.getContact());
		System.out.println("Product Name is: " + s3.getProductName());
		System.out.println("Product ID is: " + s3.getProductID());
		System.out.println("Category is: " + s3.getCategory());
		System.out.println("Price is: " + s3.getPrice());
		System.out.println("Quantity is: " + s3.getQuantity());
		System.out.println("Order ID is: " + s3.getOrderID());
		System.out.println("Order Status is: " + s3.getOrderStatus());
		System.out.println("Total Amount is: " + s3.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 4===========================");
		System.out.println("Object Reference is: " + s4);
		System.out.println("Customer Name is: " + s4.getCustomerName());
		System.out.println("Customer ID is: " + s4.getCustomerID());
		System.out.println("Customer Address is: " + s4.getCustomerAddress());
		System.out.println("Contact is: " + s4.getContact());
		System.out.println("Product Name is: " + s4.getProductName());
		System.out.println("Product ID is: " + s4.getProductID());
		System.out.println("Category is: " + s4.getCategory());
		System.out.println("Price is: " + s4.getPrice());
		System.out.println("Quantity is: " + s4.getQuantity());
		System.out.println("Order ID is: " + s4.getOrderID());
		System.out.println("Order Status is: " + s4.getOrderStatus());
		System.out.println("Total Amount is: " + s4.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 5===========================");
		System.out.println("Object Reference is: " + s5);
		System.out.println("Customer Name is: " + s5.getCustomerName());
		System.out.println("Customer ID is: " + s5.getCustomerID());
		System.out.println("Customer Address is: " + s5.getCustomerAddress());
		System.out.println("Contact is: " + s5.getContact());
		System.out.println("Product Name is: " + s5.getProductName());
		System.out.println("Product ID is: " + s5.getProductID());
		System.out.println("Category is: " + s5.getCategory());
		System.out.println("Price is: " + s5.getPrice());
		System.out.println("Quantity is: " + s5.getQuantity());
		System.out.println("Order ID is: " + s5.getOrderID());
		System.out.println("Order Status is: " + s5.getOrderStatus());
		System.out.println("Total Amount is: " + s5.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 6===========================");
		System.out.println("Object Reference is: " + s6);
		System.out.println("Customer Name is: " + s6.getCustomerName());
		System.out.println("Customer ID is: " + s6.getCustomerID());
		System.out.println("Customer Address is: " + s6.getCustomerAddress());
		System.out.println("Contact is: " + s6.getContact());
		System.out.println("Product Name is: " + s6.getProductName());
		System.out.println("Product ID is: " + s6.getProductID());
		System.out.println("Category is: " + s6.getCategory());
		System.out.println("Price is: " + s6.getPrice());
		System.out.println("Quantity is: " + s6.getQuantity());
		System.out.println("Order ID is: " + s6.getOrderID());
		System.out.println("Order Status is: " + s6.getOrderStatus());
		System.out.println("Total Amount is: " + s6.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 7===========================");
		System.out.println("Object Reference is: " + s7);
		System.out.println("Customer Name is: " + s7.getCustomerName());
		System.out.println("Customer ID is: " + s7.getCustomerID());
		System.out.println("Customer Address is: " + s7.getCustomerAddress());
		System.out.println("Contact is: " + s7.getContact());
		System.out.println("Product Name is: " + s7.getProductName());
		System.out.println("Product ID is: " + s7.getProductID());
		System.out.println("Category is: " + s7.getCategory());
		System.out.println("Price is: " + s7.getPrice());
		System.out.println("Quantity is: " + s7.getQuantity());
		System.out.println("Order ID is: " + s7.getOrderID());
		System.out.println("Order Status is: " + s7.getOrderStatus());
		System.out.println("Total Amount is: " + s7.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 8===========================");
		System.out.println("Object Reference is: " + s8);
		System.out.println("Customer Name is: " + s8.getCustomerName());
		System.out.println("Customer ID is: " + s8.getCustomerID());
		System.out.println("Customer Address is: " + s8.getCustomerAddress());
		System.out.println("Contact is: " + s8.getContact());
		System.out.println("Product Name is: " + s8.getProductName());
		System.out.println("Product ID is: " + s8.getProductID());
		System.out.println("Category is: " + s8.getCategory());
		System.out.println("Price is: " + s8.getPrice());
		System.out.println("Quantity is: " + s8.getQuantity());
		System.out.println("Order ID is: " + s8.getOrderID());
		System.out.println("Order Status is: " + s8.getOrderStatus());
		System.out.println("Total Amount is: " + s8.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 9===========================");
		System.out.println("Object Reference is: " + s9);
		System.out.println("Customer Name is: " + s9.getCustomerName());
		System.out.println("Customer ID is: " + s9.getCustomerID());
		System.out.println("Customer Address is: " + s9.getCustomerAddress());
		System.out.println("Contact is: " + s9.getContact());
		System.out.println("Product Name is: " + s9.getProductName());
		System.out.println("Product ID is: " + s9.getProductID());
		System.out.println("Category is: " + s9.getCategory());
		System.out.println("Price is: " + s9.getPrice());
		System.out.println("Quantity is: " + s9.getQuantity());
		System.out.println("Order ID is: " + s9.getOrderID());
		System.out.println("Order Status is: " + s9.getOrderStatus());
		System.out.println("Total Amount is: " + s9.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 10===========================");
		System.out.println("Object Reference is: " + s10);
		System.out.println("Customer Name is: " + s10.getCustomerName());
		System.out.println("Customer ID is: " + s10.getCustomerID());
		System.out.println("Customer Address is: " + s10.getCustomerAddress());
		System.out.println("Contact is: " + s10.getContact());
		System.out.println("Product Name is: " + s10.getProductName());
		System.out.println("Product ID is: " + s10.getProductID());
		System.out.println("Category is: " + s10.getCategory());
		System.out.println("Price is: " + s10.getPrice());
		System.out.println("Quantity is: " + s10.getQuantity());
		System.out.println("Order ID is: " + s10.getOrderID());
		System.out.println("Order Status is: " + s10.getOrderStatus());
		System.out.println("Total Amount is: " + s10.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 11===========================");
		System.out.println("Object Reference is: " + s11);
		System.out.println("Customer Name is: " + s11.getCustomerName());
		System.out.println("Customer ID is: " + s11.getCustomerID());
		System.out.println("Customer Address is: " + s11.getCustomerAddress());
		System.out.println("Contact is: " + s11.getContact());
		System.out.println("Product Name is: " + s11.getProductName());
		System.out.println("Product ID is: " + s11.getProductID());
		System.out.println("Category is: " + s11.getCategory());
		System.out.println("Price is: " + s11.getPrice());
		System.out.println("Quantity is: " + s11.getQuantity());
		System.out.println("Order ID is: " + s11.getOrderID());
		System.out.println("Order Status is: " + s11.getOrderStatus());
		System.out.println("Total Amount is: " + s11.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 12===========================");
		System.out.println("Object Reference is: " + s12);
		System.out.println("Customer Name is: " + s12.getCustomerName());
		System.out.println("Customer ID is: " + s12.getCustomerID());
		System.out.println("Customer Address is: " + s12.getCustomerAddress());
		System.out.println("Contact is: " + s12.getContact());
		System.out.println("Product Name is: " + s12.getProductName());
		System.out.println("Product ID is: " + s12.getProductID());
		System.out.println("Category is: " + s12.getCategory());
		System.out.println("Price is: " + s12.getPrice());
		System.out.println("Quantity is: " + s12.getQuantity());
		System.out.println("Order ID is: " + s12.getOrderID());
		System.out.println("Order Status is: " + s12.getOrderStatus());
		System.out.println("Total Amount is: " + s12.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 13===========================");
		System.out.println("Object Reference is: " + s13);
		System.out.println("Customer Name is: " + s13.getCustomerName());
		System.out.println("Customer ID is: " + s13.getCustomerID());
		System.out.println("Customer Address is: " + s13.getCustomerAddress());
		System.out.println("Contact is: " + s13.getContact());
		System.out.println("Product Name is: " + s13.getProductName());
		System.out.println("Product ID is: " + s13.getProductID());
		System.out.println("Category is: " + s13.getCategory());
		System.out.println("Price is: " + s13.getPrice());
		System.out.println("Quantity is: " + s13.getQuantity());
		System.out.println("Order ID is: " + s13.getOrderID());
		System.out.println("Order Status is: " + s13.getOrderStatus());
		System.out.println("Total Amount is: " + s13.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 14===========================");
		System.out.println("Object Reference is: " + s14);
		System.out.println("Customer Name is: " + s14.getCustomerName());
		System.out.println("Customer ID is: " + s14.getCustomerID());
		System.out.println("Customer Address is: " + s14.getCustomerAddress());
		System.out.println("Contact is: " + s14.getContact());
		System.out.println("Product Name is: " + s14.getProductName());
		System.out.println("Product ID is: " + s14.getProductID());
		System.out.println("Category is: " + s14.getCategory());
		System.out.println("Price is: " + s14.getPrice());
		System.out.println("Quantity is: " + s14.getQuantity());
		System.out.println("Order ID is: " + s14.getOrderID());
		System.out.println("Order Status is: " + s14.getOrderStatus());
		System.out.println("Total Amount is: " + s14.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 15===========================");
		System.out.println("Object Reference is: " + s15);
		System.out.println("Customer Name is: " + s15.getCustomerName());
		System.out.println("Customer ID is: " + s15.getCustomerID());
		System.out.println("Customer Address is: " + s15.getCustomerAddress());
		System.out.println("Contact is: " + s15.getContact());
		System.out.println("Product Name is: " + s15.getProductName());
		System.out.println("Product ID is: " + s15.getProductID());
		System.out.println("Category is: " + s15.getCategory());
		System.out.println("Price is: " + s15.getPrice());
		System.out.println("Quantity is: " + s15.getQuantity());
		System.out.println("Order ID is: " + s15.getOrderID());
		System.out.println("Order Status is: " + s15.getOrderStatus());
		System.out.println("Total Amount is: " + s15.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 16===========================");
		System.out.println("Object Reference is: " + s16);
		System.out.println("Customer Name is: " + s16.getCustomerName());
		System.out.println("Customer ID is: " + s16.getCustomerID());
		System.out.println("Customer Address is: " + s16.getCustomerAddress());
		System.out.println("Contact is: " + s16.getContact());
		System.out.println("Product Name is: " + s16.getProductName());
		System.out.println("Product ID is: " + s16.getProductID());
		System.out.println("Category is: " + s16.getCategory());
		System.out.println("Price is: " + s16.getPrice());
		System.out.println("Quantity is: " + s16.getQuantity());
		System.out.println("Order ID is: " + s16.getOrderID());
		System.out.println("Order Status is: " + s16.getOrderStatus());
		System.out.println("Total Amount is: " + s16.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 17===========================");
		System.out.println("Object Reference is: " + s17);
		System.out.println("Customer Name is: " + s17.getCustomerName());
		System.out.println("Customer ID is: " + s17.getCustomerID());
		System.out.println("Customer Address is: " + s17.getCustomerAddress());
		System.out.println("Contact is: " + s17.getContact());
		System.out.println("Product Name is: " + s17.getProductName());
		System.out.println("Product ID is: " + s17.getProductID());
		System.out.println("Category is: " + s17.getCategory());
		System.out.println("Price is: " + s17.getPrice());
		System.out.println("Quantity is: " + s17.getQuantity());
		System.out.println("Order ID is: " + s17.getOrderID());
		System.out.println("Order Status is: " + s17.getOrderStatus());
		System.out.println("Total Amount is: " + s17.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 18===========================");
		System.out.println("Object Reference is: " + s18);
		System.out.println("Customer Name is: " + s18.getCustomerName());
		System.out.println("Customer ID is: " + s18.getCustomerID());
		System.out.println("Customer Address is: " + s18.getCustomerAddress());
		System.out.println("Contact is: " + s18.getContact());
		System.out.println("Product Name is: " + s18.getProductName());
		System.out.println("Product ID is: " + s18.getProductID());
		System.out.println("Category is: " + s18.getCategory());
		System.out.println("Price is: " + s18.getPrice());
		System.out.println("Quantity is: " + s18.getQuantity());
		System.out.println("Order ID is: " + s18.getOrderID());
		System.out.println("Order Status is: " + s18.getOrderStatus());
		System.out.println("Total Amount is: " + s18.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 19===========================");
		System.out.println("Object Reference is: " + s19);
		System.out.println("Customer Name is: " + s19.getCustomerName());
		System.out.println("Customer ID is: " + s19.getCustomerID());
		System.out.println("Customer Address is: " + s19.getCustomerAddress());
		System.out.println("Contact is: " + s19.getContact());
		System.out.println("Product Name is: " + s19.getProductName());
		System.out.println("Product ID is: " + s19.getProductID());
		System.out.println("Category is: " + s19.getCategory());
		System.out.println("Price is: " + s19.getPrice());
		System.out.println("Quantity is: " + s19.getQuantity());
		System.out.println("Order ID is: " + s19.getOrderID());
		System.out.println("Order Status is: " + s19.getOrderStatus());
		System.out.println("Total Amount is: " + s19.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 20===========================");
		System.out.println("Object Reference is: " + s20);
		System.out.println("Customer Name is: " + s20.getCustomerName());
		System.out.println("Customer ID is: " + s20.getCustomerID());
		System.out.println("Customer Address is: " + s20.getCustomerAddress());
		System.out.println("Contact is: " + s20.getContact());
		System.out.println("Product Name is: " + s20.getProductName());
		System.out.println("Product ID is: " + s20.getProductID());
		System.out.println("Category is: " + s20.getCategory());
		System.out.println("Price is: " + s20.getPrice());
		System.out.println("Quantity is: " + s20.getQuantity());
		System.out.println("Order ID is: " + s20.getOrderID());
		System.out.println("Order Status is: " + s20.getOrderStatus());
		System.out.println("Total Amount is: " + s20.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 21===========================");
		System.out.println("Object Reference is: " + s21);
		System.out.println("Customer Name is: " + s21.getCustomerName());
		System.out.println("Customer ID is: " + s21.getCustomerID());
		System.out.println("Customer Address is: " + s21.getCustomerAddress());
		System.out.println("Contact is: " + s21.getContact());
		System.out.println("Product Name is: " + s21.getProductName());
		System.out.println("Product ID is: " + s21.getProductID());
		System.out.println("Category is: " + s21.getCategory());
		System.out.println("Price is: " + s21.getPrice());
		System.out.println("Quantity is: " + s21.getQuantity());
		System.out.println("Order ID is: " + s21.getOrderID());
		System.out.println("Order Status is: " + s21.getOrderStatus());
		System.out.println("Total Amount is: " + s21.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 22===========================");
		System.out.println("Object Reference is: " + s22);
		System.out.println("Customer Name is: " + s22.getCustomerName());
		System.out.println("Customer ID is: " + s22.getCustomerID());
		System.out.println("Customer Address is: " + s22.getCustomerAddress());
		System.out.println("Contact is: " + s22.getContact());
		System.out.println("Product Name is: " + s22.getProductName());
		System.out.println("Product ID is: " + s22.getProductID());
		System.out.println("Category is: " + s22.getCategory());
		System.out.println("Price is: " + s22.getPrice());
		System.out.println("Quantity is: " + s22.getQuantity());
		System.out.println("Order ID is: " + s22.getOrderID());
		System.out.println("Order Status is: " + s22.getOrderStatus());
		System.out.println("Total Amount is: " + s22.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 23===========================");
		System.out.println("Object Reference is: " + s23);
		System.out.println("Customer Name is: " + s23.getCustomerName());
		System.out.println("Customer ID is: " + s23.getCustomerID());
		System.out.println("Customer Address is: " + s23.getCustomerAddress());
		System.out.println("Contact is: " + s23.getContact());
		System.out.println("Product Name is: " + s23.getProductName());
		System.out.println("Product ID is: " + s23.getProductID());
		System.out.println("Category is: " + s23.getCategory());
		System.out.println("Price is: " + s23.getPrice());
		System.out.println("Quantity is: " + s23.getQuantity());
		System.out.println("Order ID is: " + s23.getOrderID());
		System.out.println("Order Status is: " + s23.getOrderStatus());
		System.out.println("Total Amount is: " + s23.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 24===========================");
		System.out.println("Object Reference is: " + s24);
		System.out.println("Customer Name is: " + s24.getCustomerName());
		System.out.println("Customer ID is: " + s24.getCustomerID());
		System.out.println("Customer Address is: " + s24.getCustomerAddress());
		System.out.println("Contact is: " + s24.getContact());
		System.out.println("Product Name is: " + s24.getProductName());
		System.out.println("Product ID is: " + s24.getProductID());
		System.out.println("Category is: " + s24.getCategory());
		System.out.println("Price is: " + s24.getPrice());
		System.out.println("Quantity is: " + s24.getQuantity());
		System.out.println("Order ID is: " + s24.getOrderID());
		System.out.println("Order Status is: " + s24.getOrderStatus());
		System.out.println("Total Amount is: " + s24.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 25===========================");
		System.out.println("Object Reference is: " + s25);
		System.out.println("Customer Name is: " + s25.getCustomerName());
		System.out.println("Customer ID is: " + s25.getCustomerID());
		System.out.println("Customer Address is: " + s25.getCustomerAddress());
		System.out.println("Contact is: " + s25.getContact());
		System.out.println("Product Name is: " + s25.getProductName());
		System.out.println("Product ID is: " + s25.getProductID());
		System.out.println("Category is: " + s25.getCategory());
		System.out.println("Price is: " + s25.getPrice());
		System.out.println("Quantity is: " + s25.getQuantity());
		System.out.println("Order ID is: " + s25.getOrderID());
		System.out.println("Order Status is: " + s25.getOrderStatus());
		System.out.println("Total Amount is: " + s25.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 26===========================");
		System.out.println("Object Reference is: " + s26);
		System.out.println("Customer Name is: " + s26.getCustomerName());
		System.out.println("Customer ID is: " + s26.getCustomerID());
		System.out.println("Customer Address is: " + s26.getCustomerAddress());
		System.out.println("Contact is: " + s26.getContact());
		System.out.println("Product Name is: " + s26.getProductName());
		System.out.println("Product ID is: " + s26.getProductID());
		System.out.println("Category is: " + s26.getCategory());
		System.out.println("Price is: " + s26.getPrice());
		System.out.println("Quantity is: " + s26.getQuantity());
		System.out.println("Order ID is: " + s26.getOrderID());
		System.out.println("Order Status is: " + s26.getOrderStatus());
		System.out.println("Total Amount is: " + s26.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 27===========================");
		System.out.println("Object Reference is: " + s27);
		System.out.println("Customer Name is: " + s27.getCustomerName());
		System.out.println("Customer ID is: " + s27.getCustomerID());
		System.out.println("Customer Address is: " + s27.getCustomerAddress());
		System.out.println("Contact is: " + s27.getContact());
		System.out.println("Product Name is: " + s27.getProductName());
		System.out.println("Product ID is: " + s27.getProductID());
		System.out.println("Category is: " + s27.getCategory());
		System.out.println("Price is: " + s27.getPrice());
		System.out.println("Quantity is: " + s27.getQuantity());
		System.out.println("Order ID is: " + s27.getOrderID());
		System.out.println("Order Status is: " + s27.getOrderStatus());
		System.out.println("Total Amount is: " + s27.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 28===========================");
		System.out.println("Object Reference is: " + s28);
		System.out.println("Customer Name is: " + s28.getCustomerName());
		System.out.println("Customer ID is: " + s28.getCustomerID());
		System.out.println("Customer Address is: " + s28.getCustomerAddress());
		System.out.println("Contact is: " + s28.getContact());
		System.out.println("Product Name is: " + s28.getProductName());
		System.out.println("Product ID is: " + s28.getProductID());
		System.out.println("Category is: " + s28.getCategory());
		System.out.println("Price is: " + s28.getPrice());
		System.out.println("Quantity is: " + s28.getQuantity());
		System.out.println("Order ID is: " + s28.getOrderID());
		System.out.println("Order Status is: " + s28.getOrderStatus());
		System.out.println("Total Amount is: " + s28.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 29===========================");
		System.out.println("Object Reference is: " + s29);
		System.out.println("Customer Name is: " + s29.getCustomerName());
		System.out.println("Customer ID is: " + s29.getCustomerID());
		System.out.println("Customer Address is: " + s29.getCustomerAddress());
		System.out.println("Contact is: " + s29.getContact());
		System.out.println("Product Name is: " + s29.getProductName());
		System.out.println("Product ID is: " + s29.getProductID());
		System.out.println("Category is: " + s29.getCategory());
		System.out.println("Price is: " + s29.getPrice());
		System.out.println("Quantity is: " + s29.getQuantity());
		System.out.println("Order ID is: " + s29.getOrderID());
		System.out.println("Order Status is: " + s29.getOrderStatus());
		System.out.println("Total Amount is: " + s29.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 30===========================");
		System.out.println("Object Reference is: " + s30);
		System.out.println("Customer Name is: " + s30.getCustomerName());
		System.out.println("Customer ID is: " + s30.getCustomerID());
		System.out.println("Customer Address is: " + s30.getCustomerAddress());
		System.out.println("Contact is: " + s30.getContact());
		System.out.println("Product Name is: " + s30.getProductName());
		System.out.println("Product ID is: " + s30.getProductID());
		System.out.println("Category is: " + s30.getCategory());
		System.out.println("Price is: " + s30.getPrice());
		System.out.println("Quantity is: " + s30.getQuantity());
		System.out.println("Order ID is: " + s30.getOrderID());
		System.out.println("Order Status is: " + s30.getOrderStatus());
		System.out.println("Total Amount is: " + s30.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 31===========================");
		System.out.println("Object Reference is: " + s31);
		System.out.println("Customer Name is: " + s31.getCustomerName());
		System.out.println("Customer ID is: " + s31.getCustomerID());
		System.out.println("Customer Address is: " + s31.getCustomerAddress());
		System.out.println("Contact is: " + s31.getContact());
		System.out.println("Product Name is: " + s31.getProductName());
		System.out.println("Product ID is: " + s31.getProductID());
		System.out.println("Category is: " + s31.getCategory());
		System.out.println("Price is: " + s31.getPrice());
		System.out.println("Quantity is: " + s31.getQuantity());
		System.out.println("Order ID is: " + s31.getOrderID());
		System.out.println("Order Status is: " + s31.getOrderStatus());
		System.out.println("Total Amount is: " + s31.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 32===========================");
		System.out.println("Object Reference is: " + s32);
		System.out.println("Customer Name is: " + s32.getCustomerName());
		System.out.println("Customer ID is: " + s32.getCustomerID());
		System.out.println("Customer Address is: " + s32.getCustomerAddress());
		System.out.println("Contact is: " + s32.getContact());
		System.out.println("Product Name is: " + s32.getProductName());
		System.out.println("Product ID is: " + s32.getProductID());
		System.out.println("Category is: " + s32.getCategory());
		System.out.println("Price is: " + s32.getPrice());
		System.out.println("Quantity is: " + s32.getQuantity());
		System.out.println("Order ID is: " + s32.getOrderID());
		System.out.println("Order Status is: " + s32.getOrderStatus());
		System.out.println("Total Amount is: " + s32.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 33===========================");
		System.out.println("Object Reference is: " + s33);
		System.out.println("Customer Name is: " + s33.getCustomerName());
		System.out.println("Customer ID is: " + s33.getCustomerID());
		System.out.println("Customer Address is: " + s33.getCustomerAddress());
		System.out.println("Contact is: " + s33.getContact());
		System.out.println("Product Name is: " + s33.getProductName());
		System.out.println("Product ID is: " + s33.getProductID());
		System.out.println("Category is: " + s33.getCategory());
		System.out.println("Price is: " + s33.getPrice());
		System.out.println("Quantity is: " + s33.getQuantity());
		System.out.println("Order ID is: " + s33.getOrderID());
		System.out.println("Order Status is: " + s33.getOrderStatus());
		System.out.println("Total Amount is: " + s33.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 34===========================");
		System.out.println("Object Reference is: " + s34);
		System.out.println("Customer Name is: " + s34.getCustomerName());
		System.out.println("Customer ID is: " + s34.getCustomerID());
		System.out.println("Customer Address is: " + s34.getCustomerAddress());
		System.out.println("Contact is: " + s34.getContact());
		System.out.println("Product Name is: " + s34.getProductName());
		System.out.println("Product ID is: " + s34.getProductID());
		System.out.println("Category is: " + s34.getCategory());
		System.out.println("Price is: " + s34.getPrice());
		System.out.println("Quantity is: " + s34.getQuantity());
		System.out.println("Order ID is: " + s34.getOrderID());
		System.out.println("Order Status is: " + s34.getOrderStatus());
		System.out.println("Total Amount is: " + s34.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 35===========================");
		System.out.println("Object Reference is: " + s35);
		System.out.println("Customer Name is: " + s35.getCustomerName());
		System.out.println("Customer ID is: " + s35.getCustomerID());
		System.out.println("Customer Address is: " + s35.getCustomerAddress());
		System.out.println("Contact is: " + s35.getContact());
		System.out.println("Product Name is: " + s35.getProductName());
		System.out.println("Product ID is: " + s35.getProductID());
		System.out.println("Category is: " + s35.getCategory());
		System.out.println("Price is: " + s35.getPrice());
		System.out.println("Quantity is: " + s35.getQuantity());
		System.out.println("Order ID is: " + s35.getOrderID());
		System.out.println("Order Status is: " + s35.getOrderStatus());
		System.out.println("Total Amount is: " + s35.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 36===========================");
		System.out.println("Object Reference is: " + s36);
		System.out.println("Customer Name is: " + s36.getCustomerName());
		System.out.println("Customer ID is: " + s36.getCustomerID());
		System.out.println("Customer Address is: " + s36.getCustomerAddress());
		System.out.println("Contact is: " + s36.getContact());
		System.out.println("Product Name is: " + s36.getProductName());
		System.out.println("Product ID is: " + s36.getProductID());
		System.out.println("Category is: " + s36.getCategory());
		System.out.println("Price is: " + s36.getPrice());
		System.out.println("Quantity is: " + s36.getQuantity());
		System.out.println("Order ID is: " + s36.getOrderID());
		System.out.println("Order Status is: " + s36.getOrderStatus());
		System.out.println("Total Amount is: " + s36.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 37===========================");
		System.out.println("Object Reference is: " + s37);
		System.out.println("Customer Name is: " + s37.getCustomerName());
		System.out.println("Customer ID is: " + s37.getCustomerID());
		System.out.println("Customer Address is: " + s37.getCustomerAddress());
		System.out.println("Contact is: " + s37.getContact());
		System.out.println("Product Name is: " + s37.getProductName());
		System.out.println("Product ID is: " + s37.getProductID());
		System.out.println("Category is: " + s37.getCategory());
		System.out.println("Price is: " + s37.getPrice());
		System.out.println("Quantity is: " + s37.getQuantity());
		System.out.println("Order ID is: " + s37.getOrderID());
		System.out.println("Order Status is: " + s37.getOrderStatus());
		System.out.println("Total Amount is: " + s37.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 38===========================");
		System.out.println("Object Reference is: " + s38);
		System.out.println("Customer Name is: " + s38.getCustomerName());
		System.out.println("Customer ID is: " + s38.getCustomerID());
		System.out.println("Customer Address is: " + s38.getCustomerAddress());
		System.out.println("Contact is: " + s38.getContact());
		System.out.println("Product Name is: " + s38.getProductName());
		System.out.println("Product ID is: " + s38.getProductID());
		System.out.println("Category is: " + s38.getCategory());
		System.out.println("Price is: " + s38.getPrice());
		System.out.println("Quantity is: " + s38.getQuantity());
		System.out.println("Order ID is: " + s38.getOrderID());
		System.out.println("Order Status is: " + s38.getOrderStatus());
		System.out.println("Total Amount is: " + s38.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 39===========================");
		System.out.println("Object Reference is: " + s39);
		System.out.println("Customer Name is: " + s39.getCustomerName());
		System.out.println("Customer ID is: " + s39.getCustomerID());
		System.out.println("Customer Address is: " + s39.getCustomerAddress());
		System.out.println("Contact is: " + s39.getContact());
		System.out.println("Product Name is: " + s39.getProductName());
		System.out.println("Product ID is: " + s39.getProductID());
		System.out.println("Category is: " + s39.getCategory());
		System.out.println("Price is: " + s39.getPrice());
		System.out.println("Quantity is: " + s39.getQuantity());
		System.out.println("Order ID is: " + s39.getOrderID());
		System.out.println("Order Status is: " + s39.getOrderStatus());
		System.out.println("Total Amount is: " + s39.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 40===========================");
		System.out.println("Object Reference is: " + s40);
		System.out.println("Customer Name is: " + s40.getCustomerName());
		System.out.println("Customer ID is: " + s40.getCustomerID());
		System.out.println("Customer Address is: " + s40.getCustomerAddress());
		System.out.println("Contact is: " + s40.getContact());
		System.out.println("Product Name is: " + s40.getProductName());
		System.out.println("Product ID is: " + s40.getProductID());
		System.out.println("Category is: " + s40.getCategory());
		System.out.println("Price is: " + s40.getPrice());
		System.out.println("Quantity is: " + s40.getQuantity());
		System.out.println("Order ID is: " + s40.getOrderID());
		System.out.println("Order Status is: " + s40.getOrderStatus());
		System.out.println("Total Amount is: " + s40.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 41===========================");
		System.out.println("Object Reference is: " + s41);
		System.out.println("Customer Name is: " + s41.getCustomerName());
		System.out.println("Customer ID is: " + s41.getCustomerID());
		System.out.println("Customer Address is: " + s41.getCustomerAddress());
		System.out.println("Contact is: " + s41.getContact());
		System.out.println("Product Name is: " + s41.getProductName());
		System.out.println("Product ID is: " + s41.getProductID());
		System.out.println("Category is: " + s41.getCategory());
		System.out.println("Price is: " + s41.getPrice());
		System.out.println("Quantity is: " + s41.getQuantity());
		System.out.println("Order ID is: " + s41.getOrderID());
		System.out.println("Order Status is: " + s41.getOrderStatus());
		System.out.println("Total Amount is: " + s41.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 42===========================");
		System.out.println("Object Reference is: " + s42);
		System.out.println("Customer Name is: " + s42.getCustomerName());
		System.out.println("Customer ID is: " + s42.getCustomerID());
		System.out.println("Customer Address is: " + s42.getCustomerAddress());
		System.out.println("Contact is: " + s42.getContact());
		System.out.println("Product Name is: " + s42.getProductName());
		System.out.println("Product ID is: " + s42.getProductID());
		System.out.println("Category is: " + s42.getCategory());
		System.out.println("Price is: " + s42.getPrice());
		System.out.println("Quantity is: " + s42.getQuantity());
		System.out.println("Order ID is: " + s42.getOrderID());
		System.out.println("Order Status is: " + s42.getOrderStatus());
		System.out.println("Total Amount is: " + s42.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 43===========================");
		System.out.println("Object Reference is: " + s43);
		System.out.println("Customer Name is: " + s43.getCustomerName());
		System.out.println("Customer ID is: " + s43.getCustomerID());
		System.out.println("Customer Address is: " + s43.getCustomerAddress());
		System.out.println("Contact is: " + s43.getContact());
		System.out.println("Product Name is: " + s43.getProductName());
		System.out.println("Product ID is: " + s43.getProductID());
		System.out.println("Category is: " + s43.getCategory());
		System.out.println("Price is: " + s43.getPrice());
		System.out.println("Quantity is: " + s43.getQuantity());
		System.out.println("Order ID is: " + s43.getOrderID());
		System.out.println("Order Status is: " + s43.getOrderStatus());
		System.out.println("Total Amount is: " + s43.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 44===========================");
		System.out.println("Object Reference is: " + s44);
		System.out.println("Customer Name is: " + s44.getCustomerName());
		System.out.println("Customer ID is: " + s44.getCustomerID());
		System.out.println("Customer Address is: " + s44.getCustomerAddress());
		System.out.println("Contact is: " + s44.getContact());
		System.out.println("Product Name is: " + s44.getProductName());
		System.out.println("Product ID is: " + s44.getProductID());
		System.out.println("Category is: " + s44.getCategory());
		System.out.println("Price is: " + s44.getPrice());
		System.out.println("Quantity is: " + s44.getQuantity());
		System.out.println("Order ID is: " + s44.getOrderID());
		System.out.println("Order Status is: " + s44.getOrderStatus());
		System.out.println("Total Amount is: " + s44.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 45===========================");
		System.out.println("Object Reference is: " + s45);
		System.out.println("Customer Name is: " + s45.getCustomerName());
		System.out.println("Customer ID is: " + s45.getCustomerID());
		System.out.println("Customer Address is: " + s45.getCustomerAddress());
		System.out.println("Contact is: " + s45.getContact());
		System.out.println("Product Name is: " + s45.getProductName());
		System.out.println("Product ID is: " + s45.getProductID());
		System.out.println("Category is: " + s45.getCategory());
		System.out.println("Price is: " + s45.getPrice());
		System.out.println("Quantity is: " + s45.getQuantity());
		System.out.println("Order ID is: " + s45.getOrderID());
		System.out.println("Order Status is: " + s45.getOrderStatus());
		System.out.println("Total Amount is: " + s45.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 46===========================");
		System.out.println("Object Reference is: " + s46);
		System.out.println("Customer Name is: " + s46.getCustomerName());
		System.out.println("Customer ID is: " + s46.getCustomerID());
		System.out.println("Customer Address is: " + s46.getCustomerAddress());
		System.out.println("Contact is: " + s46.getContact());
		System.out.println("Product Name is: " + s46.getProductName());
		System.out.println("Product ID is: " + s46.getProductID());
		System.out.println("Category is: " + s46.getCategory());
		System.out.println("Price is: " + s46.getPrice());
		System.out.println("Quantity is: " + s46.getQuantity());
		System.out.println("Order ID is: " + s46.getOrderID());
		System.out.println("Order Status is: " + s46.getOrderStatus());
		System.out.println("Total Amount is: " + s46.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 47===========================");
		System.out.println("Object Reference is: " + s47);
		System.out.println("Customer Name is: " + s47.getCustomerName());
		System.out.println("Customer ID is: " + s47.getCustomerID());
		System.out.println("Customer Address is: " + s47.getCustomerAddress());
		System.out.println("Contact is: " + s47.getContact());
		System.out.println("Product Name is: " + s47.getProductName());
		System.out.println("Product ID is: " + s47.getProductID());
		System.out.println("Category is: " + s47.getCategory());
		System.out.println("Price is: " + s47.getPrice());
		System.out.println("Quantity is: " + s47.getQuantity());
		System.out.println("Order ID is: " + s47.getOrderID());
		System.out.println("Order Status is: " + s47.getOrderStatus());
		System.out.println("Total Amount is: " + s47.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 48===========================");
		System.out.println("Object Reference is: " + s48);
		System.out.println("Customer Name is: " + s48.getCustomerName());
		System.out.println("Customer ID is: " + s48.getCustomerID());
		System.out.println("Customer Address is: " + s48.getCustomerAddress());
		System.out.println("Contact is: " + s48.getContact());
		System.out.println("Product Name is: " + s48.getProductName());
		System.out.println("Product ID is: " + s48.getProductID());
		System.out.println("Category is: " + s48.getCategory());
		System.out.println("Price is: " + s48.getPrice());
		System.out.println("Quantity is: " + s48.getQuantity());
		System.out.println("Order ID is: " + s48.getOrderID());
		System.out.println("Order Status is: " + s48.getOrderStatus());
		System.out.println("Total Amount is: " + s48.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 49===========================");
		System.out.println("Object Reference is: " + s49);
		System.out.println("Customer Name is: " + s49.getCustomerName());
		System.out.println("Customer ID is: " + s49.getCustomerID());
		System.out.println("Customer Address is: " + s49.getCustomerAddress());
		System.out.println("Contact is: " + s49.getContact());
		System.out.println("Product Name is: " + s49.getProductName());
		System.out.println("Product ID is: " + s49.getProductID());
		System.out.println("Category is: " + s49.getCategory());
		System.out.println("Price is: " + s49.getPrice());
		System.out.println("Quantity is: " + s49.getQuantity());
		System.out.println("Order ID is: " + s49.getOrderID());
		System.out.println("Order Status is: " + s49.getOrderStatus());
		System.out.println("Total Amount is: " + s49.getTotalAmount());
		System.out.println("============================================");

		System.out.println("=========================Online Shopping Details 50===========================");
		System.out.println("Object Reference is: " + s50);
		System.out.println("Customer Name is: " + s50.getCustomerName());
		System.out.println("Customer ID is: " + s50.getCustomerID());
		System.out.println("Customer Address is: " + s50.getCustomerAddress());
		System.out.println("Contact is: " + s50.getContact());
		System.out.println("Product Name is: " + s50.getProductName());
		System.out.println("Product ID is: " + s50.getProductID());
		System.out.println("Category is: " + s50.getCategory());
		System.out.println("Price is: " + s50.getPrice());
		System.out.println("Quantity is: " + s50.getQuantity());
		System.out.println("Order ID is: " + s50.getOrderID());
		System.out.println("Order Status is: " + s50.getOrderStatus());
		System.out.println("Total Amount is: " + s50.getTotalAmount());
		System.out.println("============================================");
		
		System.out.println("=====================================Main Method Ends=============================================");
	}

}
