package encapsulationsPrograming;

public class OnlineFoodOrderDriver {

	public static void main(String[] args) {
		
		System.out.println("=====================================Main Method Starts=======================================");
		
		OnlineFoodOrder o1 = new OnlineFoodOrder("Mohan Singh", "ORD101", "Paneer Butter Masala", "Food Palace", 2, 250.00, "Placed", "2 Paneer Butter Masala with Butter Naan");
		OnlineFoodOrder o2 = new OnlineFoodOrder("Rohan Kumar", "ORD102", "Chicken Biryani", "Biryani House", 1, 320.00, "Preparing", "1 Chicken Biryani with Raita");
		OnlineFoodOrder o3 = new OnlineFoodOrder("Sohan Sharma", "ORD103", "Veg Pizza", "Pizza Corner", 2, 450.00, "Out for Delivery", "2 Large Veg Pizzas");
		OnlineFoodOrder o4 = new OnlineFoodOrder("Rahul Verma", "ORD104", "Masala Dosa", "South Indian Kitchen", 3, 180.00, "Delivered", "3 Masala Dosa with Sambar");
		OnlineFoodOrder o5 = new OnlineFoodOrder("Shyam Gupta", "ORD105", "Chole Bhature", "Delhi Food Hub", 2, 160.00, "Placed", "2 Chole Bhature with Pickle");
		OnlineFoodOrder o6 = new OnlineFoodOrder("Manoj Singh", "ORD106", "Cheese Burger", "Burger Point", 3, 220.00, "Preparing", "3 Cheese Burgers with French Fries");
		OnlineFoodOrder o7 = new OnlineFoodOrder("Akash Kumar", "ORD107", "Veg Thali", "Indian Taste", 1, 280.00, "Delivered", "1 Special Veg Thali");
		OnlineFoodOrder o8 = new OnlineFoodOrder("Samarth Singh", "ORD108", "White Sauce Pasta", "Pasta World", 2, 350.00, "Out for Delivery", "2 White Sauce Pasta");
		OnlineFoodOrder o9 = new OnlineFoodOrder("Abhishek Kumar", "ORD109", "Margherita Pizza", "Pizza Corner", 1, 399.00, "Placed", "1 Medium Margherita Pizza");
		OnlineFoodOrder o10 = new OnlineFoodOrder("Karan Singh", "ORD110", "Fried Rice", "Chinese Wok", 2, 240.00, "Cancelled", "2 Schezwan Fried Rice");

		OnlineFoodOrder o11 = new OnlineFoodOrder("Aman Sharma", "ORD111", "Butter Chicken", "Punjabi Kitchen", 2, 520.00, "Placed", "2 Butter Chicken with Butter Naan");
		OnlineFoodOrder o12 = new OnlineFoodOrder("Rohit Kumar", "ORD112", "Veg Biryani", "Biryani House", 1, 280.00, "Preparing", "1 Veg Biryani with Raita");
		OnlineFoodOrder o13 = new OnlineFoodOrder("Vivek Singh", "ORD113", "Aloo Paratha", "Breakfast Point", 4, 120.00, "Delivered", "4 Aloo Paratha with Curd");
		OnlineFoodOrder o14 = new OnlineFoodOrder("Pankaj Verma", "ORD114", "Paneer Tikka", "Food Palace", 2, 360.00, "Out for Delivery", "2 Plates Paneer Tikka");
		OnlineFoodOrder o15 = new OnlineFoodOrder("Nitin Gupta", "ORD115", "Momos", "Momo Junction", 3, 150.00, "Placed", "3 Plates Steamed Momos");
		OnlineFoodOrder o16 = new OnlineFoodOrder("Varun Singh", "ORD116", "Dal Makhani", "Indian Taste", 2, 260.00, "Preparing", "2 Dal Makhani with Tandoori Roti");
		OnlineFoodOrder o17 = new OnlineFoodOrder("Ankit Kumar", "ORD117", "Tandoori Chicken", "Punjabi Kitchen", 1, 480.00, "Delivered", "1 Full Tandoori Chicken");
		OnlineFoodOrder o18 = new OnlineFoodOrder("Deepak Sharma", "ORD118", "Veg Sandwich", "Cafe Delight", 2, 180.00, "Placed", "2 Grilled Veg Sandwiches");
		OnlineFoodOrder o19 = new OnlineFoodOrder("Rakesh Verma", "ORD119", "Pav Bhaji", "Mumbai Food Hub", 3, 210.00, "Out for Delivery", "3 Pav Bhaji");
		OnlineFoodOrder o20 = new OnlineFoodOrder("Suresh Kumar", "ORD120", "Dosa", "South Indian Kitchen", 2, 140.00, "Delivered", "2 Plain Dosa with Chutney");

		OnlineFoodOrder o21 = new OnlineFoodOrder("Rajesh Singh", "ORD121", "Rajma Chawal", "Delhi Food Hub", 2, 300.00, "Placed", "2 Rajma Chawal");
		OnlineFoodOrder o22 = new OnlineFoodOrder("Mohit Sharma", "ORD122", "Chowmein", "Chinese Wok", 2, 260.00, "Preparing", "2 Veg Chowmein");
		OnlineFoodOrder o23 = new OnlineFoodOrder("Sunil Kumar", "ORD123", "Spring Rolls", "Chinese Wok", 3, 180.00, "Delivered", "3 Plates Spring Rolls");
		OnlineFoodOrder o24 = new OnlineFoodOrder("Arjun Verma", "ORD124", "Chicken Roll", "Roll House", 2, 240.00, "Out for Delivery", "2 Chicken Rolls");
		OnlineFoodOrder o25 = new OnlineFoodOrder("Kunal Gupta", "ORD125", "Paneer Roll", "Roll House", 2, 220.00, "Placed", "2 Paneer Rolls");
		OnlineFoodOrder o26 = new OnlineFoodOrder("Manish Singh", "ORD126", "Fish Curry", "Coastal Kitchen", 1, 580.00, "Preparing", "1 Fish Curry with Rice");
		OnlineFoodOrder o27 = new OnlineFoodOrder("Lokesh Kumar", "ORD127", "Chicken Kebab", "Grill House", 2, 460.00, "Delivered", "2 Plates Chicken Kebab");
		OnlineFoodOrder o28 = new OnlineFoodOrder("Neeraj Sharma", "ORD128", "Veg Fried Rice", "Chinese Wok", 3, 270.00, "Placed", "3 Veg Fried Rice");
		OnlineFoodOrder o29 = new OnlineFoodOrder("Piyush Verma", "ORD129", "Hakka Noodles", "Noodle House", 2, 290.00, "Out for Delivery", "2 Hakka Noodles");
		OnlineFoodOrder o30 = new OnlineFoodOrder("Ashish Kumar", "ORD130", "Mushroom Pizza", "Pizza Corner", 1, 480.00, "Delivered", "1 Large Mushroom Pizza");

		OnlineFoodOrder o31 = new OnlineFoodOrder("Amit Singh", "ORD131", "Farmhouse Pizza", "Pizza Corner", 2, 550.00, "Placed", "2 Medium Farmhouse Pizzas");
		OnlineFoodOrder o32 = new OnlineFoodOrder("Sanjay Sharma", "ORD132", "Chicken Burger", "Burger Point", 2, 320.00, "Preparing", "2 Chicken Burgers with Fries");
		OnlineFoodOrder o33 = new OnlineFoodOrder("Ravi Kumar", "ORD133", "Veg Burger", "Burger Point", 3, 270.00, "Delivered", "3 Veg Burgers with Fries");
		OnlineFoodOrder o34 = new OnlineFoodOrder("Vikas Verma", "ORD134", "Garlic Naan", "Indian Taste", 4, 160.00, "Out for Delivery", "4 Garlic Naan with Paneer Curry");
		OnlineFoodOrder o35 = new OnlineFoodOrder("Tarun Singh", "ORD135", "Malai Kofta", "Indian Taste", 2, 340.00, "Placed", "2 Malai Kofta with Naan");
		OnlineFoodOrder o36 = new OnlineFoodOrder("Ajay Kumar", "ORD136", "Shahi Paneer", "Food Palace", 2, 380.00, "Preparing", "2 Shahi Paneer with Roti");
		OnlineFoodOrder o37 = new OnlineFoodOrder("Akhil Sharma", "ORD137", "Kadhai Paneer", "Food Palace", 1, 240.00, "Delivered", "1 Kadhai Paneer with Butter Naan");
		OnlineFoodOrder o38 = new OnlineFoodOrder("Sandeep Verma", "ORD138", "Mutton Biryani", "Biryani House", 2, 650.00, "Out for Delivery", "2 Mutton Biryani with Raita");
		OnlineFoodOrder o39 = new OnlineFoodOrder("Mukesh Kumar", "ORD139", "Chicken Tikka", "Grill House", 2, 420.00, "Placed", "2 Plates Chicken Tikka");
		OnlineFoodOrder o40 = new OnlineFoodOrder("Yogesh Singh", "ORD140", "Veg Manchurian", "Chinese Wok", 3, 330.00, "Delivered", "3 Veg Manchurian");

		OnlineFoodOrder o41 = new OnlineFoodOrder("Nikhil Kumar", "ORD141", "Chilli Paneer", "Chinese Wok", 2, 360.00, "Placed", "2 Chilli Paneer");
		OnlineFoodOrder o42 = new OnlineFoodOrder("Gaurav Sharma", "ORD142", "Pasta Alfredo", "Pasta World", 1, 320.00, "Preparing", "1 Creamy Alfredo Pasta");
		OnlineFoodOrder o43 = new OnlineFoodOrder("Manish Verma", "ORD143", "Arrabbiata Pasta", "Pasta World", 2, 340.00, "Delivered", "2 Arrabbiata Pasta");
		OnlineFoodOrder o44 = new OnlineFoodOrder("Ramesh Kumar", "ORD144", "Mango Shake", "Juice Corner", 3, 270.00, "Out for Delivery", "3 Mango Shakes");
		OnlineFoodOrder o45 = new OnlineFoodOrder("Akhilesh Singh", "ORD145", "Cold Coffee", "Cafe Delight", 2, 220.00, "Placed", "2 Cold Coffees");
		OnlineFoodOrder o46 = new OnlineFoodOrder("Rajat Verma", "ORD146", "Chocolate Cake", "Sweet Treats", 1, 550.00, "Preparing", "1 Chocolate Truffle Cake");
		OnlineFoodOrder o47 = new OnlineFoodOrder("Chetan Kumar", "ORD147", "Gulab Jamun", "Sweet Treats", 4, 180.00, "Delivered", "4 Gulab Jamun");
		OnlineFoodOrder o48 = new OnlineFoodOrder("Vishal Sharma", "ORD148", "Rasmalai", "Sweet Treats", 3, 210.00, "Out for Delivery", "3 Plates Rasmalai");
		OnlineFoodOrder o49 = new OnlineFoodOrder("Pawan Singh", "ORD149", "Ice Cream", "Dessert House", 2, 190.00, "Placed", "2 Scoops Chocolate Ice Cream");
		OnlineFoodOrder o50 = new OnlineFoodOrder("Suraj Kumar", "ORD150", "Veg Combo Meal", "Food Palace", 2, 450.00, "Delivered", "2 Complete Veg Combo Meals");
		
				
		System.out.println("=========================Online Food Order Details 1===========================");
		System.out.println("Object Reference is: " + o1);
		System.out.println("Customer Name is: " + o1.getCustomerName());
		System.out.println("Order ID is: " + o1.getOrderID());
		System.out.println("Food Name is: " + o1.getFoodName());
		System.out.println("Restaurant Name is: " + o1.getRestaurantName());
		System.out.println("Quantity is: " + o1.getQuantity());
		System.out.println("Price is: " + o1.getPrice());
		System.out.println("Order Status is: " + o1.getOrderStatus());
		System.out.println("Order Details are: " + o1.getOrderDetails());
		System.out.println("Total Amount is: " + o1.getTotalAmount());

		System.out.println("=========================Online Food Order Details 2===========================");
		System.out.println("Object Reference is: " + o2);
		System.out.println("Customer Name is: " + o2.getCustomerName());
		System.out.println("Order ID is: " + o2.getOrderID());
		System.out.println("Food Name is: " + o2.getFoodName());
		System.out.println("Restaurant Name is: " + o2.getRestaurantName());
		System.out.println("Quantity is: " + o2.getQuantity());
		System.out.println("Price is: " + o2.getPrice());
		System.out.println("Order Status is: " + o2.getOrderStatus());
		System.out.println("Order Details are: " + o2.getOrderDetails());
		System.out.println("Total Amount is: " + o2.getTotalAmount());

		System.out.println("=========================Online Food Order Details 3===========================");
		System.out.println("Object Reference is: " + o3);
		System.out.println("Customer Name is: " + o3.getCustomerName());
		System.out.println("Order ID is: " + o3.getOrderID());
		System.out.println("Food Name is: " + o3.getFoodName());
		System.out.println("Restaurant Name is: " + o3.getRestaurantName());
		System.out.println("Quantity is: " + o3.getQuantity());
		System.out.println("Price is: " + o3.getPrice());
		System.out.println("Order Status is: " + o3.getOrderStatus());
		System.out.println("Order Details are: " + o3.getOrderDetails());
		System.out.println("Total Amount is: " + o3.getTotalAmount());

		System.out.println("=========================Online Food Order Details 4===========================");
		System.out.println("Object Reference is: " + o4);
		System.out.println("Customer Name is: " + o4.getCustomerName());
		System.out.println("Order ID is: " + o4.getOrderID());
		System.out.println("Food Name is: " + o4.getFoodName());
		System.out.println("Restaurant Name is: " + o4.getRestaurantName());
		System.out.println("Quantity is: " + o4.getQuantity());
		System.out.println("Price is: " + o4.getPrice());
		System.out.println("Order Status is: " + o4.getOrderStatus());
		System.out.println("Order Details are: " + o4.getOrderDetails());
		System.out.println("Total Amount is: " + o4.getTotalAmount());

		System.out.println("=========================Online Food Order Details 5===========================");
		System.out.println("Object Reference is: " + o5);
		System.out.println("Customer Name is: " + o5.getCustomerName());
		System.out.println("Order ID is: " + o5.getOrderID());
		System.out.println("Food Name is: " + o5.getFoodName());
		System.out.println("Restaurant Name is: " + o5.getRestaurantName());
		System.out.println("Quantity is: " + o5.getQuantity());
		System.out.println("Price is: " + o5.getPrice());
		System.out.println("Order Status is: " + o5.getOrderStatus());
		System.out.println("Order Details are: " + o5.getOrderDetails());
		System.out.println("Total Amount is: " + o5.getTotalAmount());

		System.out.println("=========================Online Food Order Details 6===========================");
		System.out.println("Object Reference is: " + o6);
		System.out.println("Customer Name is: " + o6.getCustomerName());
		System.out.println("Order ID is: " + o6.getOrderID());
		System.out.println("Food Name is: " + o6.getFoodName());
		System.out.println("Restaurant Name is: " + o6.getRestaurantName());
		System.out.println("Quantity is: " + o6.getQuantity());
		System.out.println("Price is: " + o6.getPrice());
		System.out.println("Order Status is: " + o6.getOrderStatus());
		System.out.println("Order Details are: " + o6.getOrderDetails());
		System.out.println("Total Amount is: " + o6.getTotalAmount());

		System.out.println("=========================Online Food Order Details 7===========================");
		System.out.println("Object Reference is: " + o7);
		System.out.println("Customer Name is: " + o7.getCustomerName());
		System.out.println("Order ID is: " + o7.getOrderID());
		System.out.println("Food Name is: " + o7.getFoodName());
		System.out.println("Restaurant Name is: " + o7.getRestaurantName());
		System.out.println("Quantity is: " + o7.getQuantity());
		System.out.println("Price is: " + o7.getPrice());
		System.out.println("Order Status is: " + o7.getOrderStatus());
		System.out.println("Order Details are: " + o7.getOrderDetails());
		System.out.println("Total Amount is: " + o7.getTotalAmount());

		System.out.println("=========================Online Food Order Details 8===========================");
		System.out.println("Object Reference is: " + o8);
		System.out.println("Customer Name is: " + o8.getCustomerName());
		System.out.println("Order ID is: " + o8.getOrderID());
		System.out.println("Food Name is: " + o8.getFoodName());
		System.out.println("Restaurant Name is: " + o8.getRestaurantName());
		System.out.println("Quantity is: " + o8.getQuantity());
		System.out.println("Price is: " + o8.getPrice());
		System.out.println("Order Status is: " + o8.getOrderStatus());
		System.out.println("Order Details are: " + o8.getOrderDetails());
		System.out.println("Total Amount is: " + o8.getTotalAmount());

		System.out.println("=========================Online Food Order Details 9===========================");
		System.out.println("Object Reference is: " + o9);
		System.out.println("Customer Name is: " + o9.getCustomerName());
		System.out.println("Order ID is: " + o9.getOrderID());
		System.out.println("Food Name is: " + o9.getFoodName());
		System.out.println("Restaurant Name is: " + o9.getRestaurantName());
		System.out.println("Quantity is: " + o9.getQuantity());
		System.out.println("Price is: " + o9.getPrice());
		System.out.println("Order Status is: " + o9.getOrderStatus());
		System.out.println("Order Details are: " + o9.getOrderDetails());
		System.out.println("Total Amount is: " + o9.getTotalAmount());

		System.out.println("=========================Online Food Order Details 10===========================");
		System.out.println("Object Reference is: " + o10);
		System.out.println("Customer Name is: " + o10.getCustomerName());
		System.out.println("Order ID is: " + o10.getOrderID());
		System.out.println("Food Name is: " + o10.getFoodName());
		System.out.println("Restaurant Name is: " + o10.getRestaurantName());
		System.out.println("Quantity is: " + o10.getQuantity());
		System.out.println("Price is: " + o10.getPrice());
		System.out.println("Order Status is: " + o10.getOrderStatus());
		System.out.println("Order Details are: " + o10.getOrderDetails());
		System.out.println("Total Amount is: " + o10.getTotalAmount());

		System.out.println("=========================Online Food Order Details 11===========================");
		System.out.println("Object Reference is: " + o11);
		System.out.println("Customer Name is: " + o11.getCustomerName());
		System.out.println("Order ID is: " + o11.getOrderID());
		System.out.println("Food Name is: " + o11.getFoodName());
		System.out.println("Restaurant Name is: " + o11.getRestaurantName());
		System.out.println("Quantity is: " + o11.getQuantity());
		System.out.println("Price is: " + o11.getPrice());
		System.out.println("Order Status is: " + o11.getOrderStatus());
		System.out.println("Order Details are: " + o11.getOrderDetails());
		System.out.println("Total Amount is: " + o11.getTotalAmount());

		System.out.println("=========================Online Food Order Details 12===========================");
		System.out.println("Object Reference is: " + o12);
		System.out.println("Customer Name is: " + o12.getCustomerName());
		System.out.println("Order ID is: " + o12.getOrderID());
		System.out.println("Food Name is: " + o12.getFoodName());
		System.out.println("Restaurant Name is: " + o12.getRestaurantName());
		System.out.println("Quantity is: " + o12.getQuantity());
		System.out.println("Price is: " + o12.getPrice());
		System.out.println("Order Status is: " + o12.getOrderStatus());
		System.out.println("Order Details are: " + o12.getOrderDetails());
		System.out.println("Total Amount is: " + o12.getTotalAmount());

		System.out.println("=========================Online Food Order Details 13===========================");
		System.out.println("Object Reference is: " + o13);
		System.out.println("Customer Name is: " + o13.getCustomerName());
		System.out.println("Order ID is: " + o13.getOrderID());
		System.out.println("Food Name is: " + o13.getFoodName());
		System.out.println("Restaurant Name is: " + o13.getRestaurantName());
		System.out.println("Quantity is: " + o13.getQuantity());
		System.out.println("Price is: " + o13.getPrice());
		System.out.println("Order Status is: " + o13.getOrderStatus());
		System.out.println("Order Details are: " + o13.getOrderDetails());
		System.out.println("Total Amount is: " + o13.getTotalAmount());

		System.out.println("=========================Online Food Order Details 14===========================");
		System.out.println("Object Reference is: " + o14);
		System.out.println("Customer Name is: " + o14.getCustomerName());
		System.out.println("Order ID is: " + o14.getOrderID());
		System.out.println("Food Name is: " + o14.getFoodName());
		System.out.println("Restaurant Name is: " + o14.getRestaurantName());
		System.out.println("Quantity is: " + o14.getQuantity());
		System.out.println("Price is: " + o14.getPrice());
		System.out.println("Order Status is: " + o14.getOrderStatus());
		System.out.println("Order Details are: " + o14.getOrderDetails());
		System.out.println("Total Amount is: " + o14.getTotalAmount());

		System.out.println("=========================Online Food Order Details 15===========================");
		System.out.println("Object Reference is: " + o15);
		System.out.println("Customer Name is: " + o15.getCustomerName());
		System.out.println("Order ID is: " + o15.getOrderID());
		System.out.println("Food Name is: " + o15.getFoodName());
		System.out.println("Restaurant Name is: " + o15.getRestaurantName());
		System.out.println("Quantity is: " + o15.getQuantity());
		System.out.println("Price is: " + o15.getPrice());
		System.out.println("Order Status is: " + o15.getOrderStatus());
		System.out.println("Order Details are: " + o15.getOrderDetails());
		System.out.println("Total Amount is: " + o15.getTotalAmount());

		System.out.println("=========================Online Food Order Details 16===========================");
		System.out.println("Object Reference is: " + o16);
		System.out.println("Customer Name is: " + o16.getCustomerName());
		System.out.println("Order ID is: " + o16.getOrderID());
		System.out.println("Food Name is: " + o16.getFoodName());
		System.out.println("Restaurant Name is: " + o16.getRestaurantName());
		System.out.println("Quantity is: " + o16.getQuantity());
		System.out.println("Price is: " + o16.getPrice());
		System.out.println("Order Status is: " + o16.getOrderStatus());
		System.out.println("Order Details are: " + o16.getOrderDetails());
		System.out.println("Total Amount is: " + o16.getTotalAmount());

		System.out.println("=========================Online Food Order Details 17===========================");
		System.out.println("Object Reference is: " + o17);
		System.out.println("Customer Name is: " + o17.getCustomerName());
		System.out.println("Order ID is: " + o17.getOrderID());
		System.out.println("Food Name is: " + o17.getFoodName());
		System.out.println("Restaurant Name is: " + o17.getRestaurantName());
		System.out.println("Quantity is: " + o17.getQuantity());
		System.out.println("Price is: " + o17.getPrice());
		System.out.println("Order Status is: " + o17.getOrderStatus());
		System.out.println("Order Details are: " + o17.getOrderDetails());
		System.out.println("Total Amount is: " + o17.getTotalAmount());

		System.out.println("=========================Online Food Order Details 18===========================");
		System.out.println("Object Reference is: " + o18);
		System.out.println("Customer Name is: " + o18.getCustomerName());
		System.out.println("Order ID is: " + o18.getOrderID());
		System.out.println("Food Name is: " + o18.getFoodName());
		System.out.println("Restaurant Name is: " + o18.getRestaurantName());
		System.out.println("Quantity is: " + o18.getQuantity());
		System.out.println("Price is: " + o18.getPrice());
		System.out.println("Order Status is: " + o18.getOrderStatus());
		System.out.println("Order Details are: " + o18.getOrderDetails());
		System.out.println("Total Amount is: " + o18.getTotalAmount());

		System.out.println("=========================Online Food Order Details 19===========================");
		System.out.println("Object Reference is: " + o19);
		System.out.println("Customer Name is: " + o19.getCustomerName());
		System.out.println("Order ID is: " + o19.getOrderID());
		System.out.println("Food Name is: " + o19.getFoodName());
		System.out.println("Restaurant Name is: " + o19.getRestaurantName());
		System.out.println("Quantity is: " + o19.getQuantity());
		System.out.println("Price is: " + o19.getPrice());
		System.out.println("Order Status is: " + o19.getOrderStatus());
		System.out.println("Order Details are: " + o19.getOrderDetails());
		System.out.println("Total Amount is: " + o19.getTotalAmount());

		System.out.println("=========================Online Food Order Details 20===========================");
		System.out.println("Object Reference is: " + o20);
		System.out.println("Customer Name is: " + o20.getCustomerName());
		System.out.println("Order ID is: " + o20.getOrderID());
		System.out.println("Food Name is: " + o20.getFoodName());
		System.out.println("Restaurant Name is: " + o20.getRestaurantName());
		System.out.println("Quantity is: " + o20.getQuantity());
		System.out.println("Price is: " + o20.getPrice());
		System.out.println("Order Status is: " + o20.getOrderStatus());
		System.out.println("Order Details are: " + o20.getOrderDetails());
		System.out.println("Total Amount is: " + o20.getTotalAmount());

		System.out.println("=========================Online Food Order Details 21===========================");
		System.out.println("Object Reference is: " + o21);
		System.out.println("Customer Name is: " + o21.getCustomerName());
		System.out.println("Order ID is: " + o21.getOrderID());
		System.out.println("Food Name is: " + o21.getFoodName());
		System.out.println("Restaurant Name is: " + o21.getRestaurantName());
		System.out.println("Quantity is: " + o21.getQuantity());
		System.out.println("Price is: " + o21.getPrice());
		System.out.println("Order Status is: " + o21.getOrderStatus());
		System.out.println("Order Details are: " + o21.getOrderDetails());
		System.out.println("Total Amount is: " + o21.getTotalAmount());

		System.out.println("=========================Online Food Order Details 22===========================");
		System.out.println("Object Reference is: " + o22);
		System.out.println("Customer Name is: " + o22.getCustomerName());
		System.out.println("Order ID is: " + o22.getOrderID());
		System.out.println("Food Name is: " + o22.getFoodName());
		System.out.println("Restaurant Name is: " + o22.getRestaurantName());
		System.out.println("Quantity is: " + o22.getQuantity());
		System.out.println("Price is: " + o22.getPrice());
		System.out.println("Order Status is: " + o22.getOrderStatus());
		System.out.println("Order Details are: " + o22.getOrderDetails());
		System.out.println("Total Amount is: " + o22.getTotalAmount());

		System.out.println("=========================Online Food Order Details 23===========================");
		System.out.println("Object Reference is: " + o23);
		System.out.println("Customer Name is: " + o23.getCustomerName());
		System.out.println("Order ID is: " + o23.getOrderID());
		System.out.println("Food Name is: " + o23.getFoodName());
		System.out.println("Restaurant Name is: " + o23.getRestaurantName());
		System.out.println("Quantity is: " + o23.getQuantity());
		System.out.println("Price is: " + o23.getPrice());
		System.out.println("Order Status is: " + o23.getOrderStatus());
		System.out.println("Order Details are: " + o23.getOrderDetails());
		System.out.println("Total Amount is: " + o23.getTotalAmount());

		System.out.println("=========================Online Food Order Details 24===========================");
		System.out.println("Object Reference is: " + o24);
		System.out.println("Customer Name is: " + o24.getCustomerName());
		System.out.println("Order ID is: " + o24.getOrderID());
		System.out.println("Food Name is: " + o24.getFoodName());
		System.out.println("Restaurant Name is: " + o24.getRestaurantName());
		System.out.println("Quantity is: " + o24.getQuantity());
		System.out.println("Price is: " + o24.getPrice());
		System.out.println("Order Status is: " + o24.getOrderStatus());
		System.out.println("Order Details are: " + o24.getOrderDetails());
		System.out.println("Total Amount is: " + o24.getTotalAmount());

		System.out.println("=========================Online Food Order Details 25===========================");
		System.out.println("Object Reference is: " + o25);
		System.out.println("Customer Name is: " + o25.getCustomerName());
		System.out.println("Order ID is: " + o25.getOrderID());
		System.out.println("Food Name is: " + o25.getFoodName());
		System.out.println("Restaurant Name is: " + o25.getRestaurantName());
		System.out.println("Quantity is: " + o25.getQuantity());
		System.out.println("Price is: " + o25.getPrice());
		System.out.println("Order Status is: " + o25.getOrderStatus());
		System.out.println("Order Details are: " + o25.getOrderDetails());
		System.out.println("Total Amount is: " + o25.getTotalAmount());

		System.out.println("=========================Online Food Order Details 26===========================");
		System.out.println("Object Reference is: " + o26);
		System.out.println("Customer Name is: " + o26.getCustomerName());
		System.out.println("Order ID is: " + o26.getOrderID());
		System.out.println("Food Name is: " + o26.getFoodName());
		System.out.println("Restaurant Name is: " + o26.getRestaurantName());
		System.out.println("Quantity is: " + o26.getQuantity());
		System.out.println("Price is: " + o26.getPrice());
		System.out.println("Order Status is: " + o26.getOrderStatus());
		System.out.println("Order Details are: " + o26.getOrderDetails());
		System.out.println("Total Amount is: " + o26.getTotalAmount());

		System.out.println("=========================Online Food Order Details 27===========================");
		System.out.println("Object Reference is: " + o27);
		System.out.println("Customer Name is: " + o27.getCustomerName());
		System.out.println("Order ID is: " + o27.getOrderID());
		System.out.println("Food Name is: " + o27.getFoodName());
		System.out.println("Restaurant Name is: " + o27.getRestaurantName());
		System.out.println("Quantity is: " + o27.getQuantity());
		System.out.println("Price is: " + o27.getPrice());
		System.out.println("Order Status is: " + o27.getOrderStatus());
		System.out.println("Order Details are: " + o27.getOrderDetails());
		System.out.println("Total Amount is: " + o27.getTotalAmount());

		System.out.println("=========================Online Food Order Details 28===========================");
		System.out.println("Object Reference is: " + o28);
		System.out.println("Customer Name is: " + o28.getCustomerName());
		System.out.println("Order ID is: " + o28.getOrderID());
		System.out.println("Food Name is: " + o28.getFoodName());
		System.out.println("Restaurant Name is: " + o28.getRestaurantName());
		System.out.println("Quantity is: " + o28.getQuantity());
		System.out.println("Price is: " + o28.getPrice());
		System.out.println("Order Status is: " + o28.getOrderStatus());
		System.out.println("Order Details are: " + o28.getOrderDetails());
		System.out.println("Total Amount is: " + o28.getTotalAmount());

		System.out.println("=========================Online Food Order Details 29===========================");
		System.out.println("Object Reference is: " + o29);
		System.out.println("Customer Name is: " + o29.getCustomerName());
		System.out.println("Order ID is: " + o29.getOrderID());
		System.out.println("Food Name is: " + o29.getFoodName());
		System.out.println("Restaurant Name is: " + o29.getRestaurantName());
		System.out.println("Quantity is: " + o29.getQuantity());
		System.out.println("Price is: " + o29.getPrice());
		System.out.println("Order Status is: " + o29.getOrderStatus());
		System.out.println("Order Details are: " + o29.getOrderDetails());
		System.out.println("Total Amount is: " + o29.getTotalAmount());

		System.out.println("=========================Online Food Order Details 30===========================");
		System.out.println("Object Reference is: " + o30);
		System.out.println("Customer Name is: " + o30.getCustomerName());
		System.out.println("Order ID is: " + o30.getOrderID());
		System.out.println("Food Name is: " + o30.getFoodName());
		System.out.println("Restaurant Name is: " + o30.getRestaurantName());
		System.out.println("Quantity is: " + o30.getQuantity());
		System.out.println("Price is: " + o30.getPrice());
		System.out.println("Order Status is: " + o30.getOrderStatus());
		System.out.println("Order Details are: " + o30.getOrderDetails());
		System.out.println("Total Amount is: " + o30.getTotalAmount());

		System.out.println("=========================Online Food Order Details 31===========================");
		System.out.println("Object Reference is: " + o31);
		System.out.println("Customer Name is: " + o31.getCustomerName());
		System.out.println("Order ID is: " + o31.getOrderID());
		System.out.println("Food Name is: " + o31.getFoodName());
		System.out.println("Restaurant Name is: " + o31.getRestaurantName());
		System.out.println("Quantity is: " + o31.getQuantity());
		System.out.println("Price is: " + o31.getPrice());
		System.out.println("Order Status is: " + o31.getOrderStatus());
		System.out.println("Order Details are: " + o31.getOrderDetails());
		System.out.println("Total Amount is: " + o31.getTotalAmount());

		System.out.println("=========================Online Food Order Details 32===========================");
		System.out.println("Object Reference is: " + o32);
		System.out.println("Customer Name is: " + o32.getCustomerName());
		System.out.println("Order ID is: " + o32.getOrderID());
		System.out.println("Food Name is: " + o32.getFoodName());
		System.out.println("Restaurant Name is: " + o32.getRestaurantName());
		System.out.println("Quantity is: " + o32.getQuantity());
		System.out.println("Price is: " + o32.getPrice());
		System.out.println("Order Status is: " + o32.getOrderStatus());
		System.out.println("Order Details are: " + o32.getOrderDetails());
		System.out.println("Total Amount is: " + o32.getTotalAmount());

		System.out.println("=========================Online Food Order Details 33===========================");
		System.out.println("Object Reference is: " + o33);
		System.out.println("Customer Name is: " + o33.getCustomerName());
		System.out.println("Order ID is: " + o33.getOrderID());
		System.out.println("Food Name is: " + o33.getFoodName());
		System.out.println("Restaurant Name is: " + o33.getRestaurantName());
		System.out.println("Quantity is: " + o33.getQuantity());
		System.out.println("Price is: " + o33.getPrice());
		System.out.println("Order Status is: " + o33.getOrderStatus());
		System.out.println("Order Details are: " + o33.getOrderDetails());
		System.out.println("Total Amount is: " + o33.getTotalAmount());

		System.out.println("=========================Online Food Order Details 34===========================");
		System.out.println("Object Reference is: " + o34);
		System.out.println("Customer Name is: " + o34.getCustomerName());
		System.out.println("Order ID is: " + o34.getOrderID());
		System.out.println("Food Name is: " + o34.getFoodName());
		System.out.println("Restaurant Name is: " + o34.getRestaurantName());
		System.out.println("Quantity is: " + o34.getQuantity());
		System.out.println("Price is: " + o34.getPrice());
		System.out.println("Order Status is: " + o34.getOrderStatus());
		System.out.println("Order Details are: " + o34.getOrderDetails());
		System.out.println("Total Amount is: " + o34.getTotalAmount());

		System.out.println("=========================Online Food Order Details 35===========================");
		System.out.println("Object Reference is: " + o35);
		System.out.println("Customer Name is: " + o35.getCustomerName());
		System.out.println("Order ID is: " + o35.getOrderID());
		System.out.println("Food Name is: " + o35.getFoodName());
		System.out.println("Restaurant Name is: " + o35.getRestaurantName());
		System.out.println("Quantity is: " + o35.getQuantity());
		System.out.println("Price is: " + o35.getPrice());
		System.out.println("Order Status is: " + o35.getOrderStatus());
		System.out.println("Order Details are: " + o35.getOrderDetails());
		System.out.println("Total Amount is: " + o35.getTotalAmount());

		System.out.println("=========================Online Food Order Details 36===========================");
		System.out.println("Object Reference is: " + o36);
		System.out.println("Customer Name is: " + o36.getCustomerName());
		System.out.println("Order ID is: " + o36.getOrderID());
		System.out.println("Food Name is: " + o36.getFoodName());
		System.out.println("Restaurant Name is: " + o36.getRestaurantName());
		System.out.println("Quantity is: " + o36.getQuantity());
		System.out.println("Price is: " + o36.getPrice());
		System.out.println("Order Status is: " + o36.getOrderStatus());
		System.out.println("Order Details are: " + o36.getOrderDetails());
		System.out.println("Total Amount is: " + o36.getTotalAmount());

		System.out.println("=========================Online Food Order Details 37===========================");
		System.out.println("Object Reference is: " + o37);
		System.out.println("Customer Name is: " + o37.getCustomerName());
		System.out.println("Order ID is: " + o37.getOrderID());
		System.out.println("Food Name is: " + o37.getFoodName());
		System.out.println("Restaurant Name is: " + o37.getRestaurantName());
		System.out.println("Quantity is: " + o37.getQuantity());
		System.out.println("Price is: " + o37.getPrice());
		System.out.println("Order Status is: " + o37.getOrderStatus());
		System.out.println("Order Details are: " + o37.getOrderDetails());
		System.out.println("Total Amount is: " + o37.getTotalAmount());

		System.out.println("=========================Online Food Order Details 38===========================");
		System.out.println("Object Reference is: " + o38);
		System.out.println("Customer Name is: " + o38.getCustomerName());
		System.out.println("Order ID is: " + o38.getOrderID());
		System.out.println("Food Name is: " + o38.getFoodName());
		System.out.println("Restaurant Name is: " + o38.getRestaurantName());
		System.out.println("Quantity is: " + o38.getQuantity());
		System.out.println("Price is: " + o38.getPrice());
		System.out.println("Order Status is: " + o38.getOrderStatus());
		System.out.println("Order Details are: " + o38.getOrderDetails());
		System.out.println("Total Amount is: " + o38.getTotalAmount());

		System.out.println("=========================Online Food Order Details 39===========================");
		System.out.println("Object Reference is: " + o39);
		System.out.println("Customer Name is: " + o39.getCustomerName());
		System.out.println("Order ID is: " + o39.getOrderID());
		System.out.println("Food Name is: " + o39.getFoodName());
		System.out.println("Restaurant Name is: " + o39.getRestaurantName());
		System.out.println("Quantity is: " + o39.getQuantity());
		System.out.println("Price is: " + o39.getPrice());
		System.out.println("Order Status is: " + o39.getOrderStatus());
		System.out.println("Order Details are: " + o39.getOrderDetails());
		System.out.println("Total Amount is: " + o39.getTotalAmount());

		System.out.println("=========================Online Food Order Details 40===========================");
		System.out.println("Object Reference is: " + o40);
		System.out.println("Customer Name is: " + o40.getCustomerName());
		System.out.println("Order ID is: " + o40.getOrderID());
		System.out.println("Food Name is: " + o40.getFoodName());
		System.out.println("Restaurant Name is: " + o40.getRestaurantName());
		System.out.println("Quantity is: " + o40.getQuantity());
		System.out.println("Price is: " + o40.getPrice());
		System.out.println("Order Status is: " + o40.getOrderStatus());
		System.out.println("Order Details are: " + o40.getOrderDetails());
		System.out.println("Total Amount is: " + o40.getTotalAmount());

		System.out.println("=========================Online Food Order Details 41===========================");
		System.out.println("Object Reference is: " + o41);
		System.out.println("Customer Name is: " + o41.getCustomerName());
		System.out.println("Order ID is: " + o41.getOrderID());
		System.out.println("Food Name is: " + o41.getFoodName());
		System.out.println("Restaurant Name is: " + o41.getRestaurantName());
		System.out.println("Quantity is: " + o41.getQuantity());
		System.out.println("Price is: " + o41.getPrice());
		System.out.println("Order Status is: " + o41.getOrderStatus());
		System.out.println("Order Details are: " + o41.getOrderDetails());
		System.out.println("Total Amount is: " + o41.getTotalAmount());

		System.out.println("=========================Online Food Order Details 42===========================");
		System.out.println("Object Reference is: " + o42);
		System.out.println("Customer Name is: " + o42.getCustomerName());
		System.out.println("Order ID is: " + o42.getOrderID());
		System.out.println("Food Name is: " + o42.getFoodName());
		System.out.println("Restaurant Name is: " + o42.getRestaurantName());
		System.out.println("Quantity is: " + o42.getQuantity());
		System.out.println("Price is: " + o42.getPrice());
		System.out.println("Order Status is: " + o42.getOrderStatus());
		System.out.println("Order Details are: " + o42.getOrderDetails());
		System.out.println("Total Amount is: " + o42.getTotalAmount());

		System.out.println("=========================Online Food Order Details 43===========================");
		System.out.println("Object Reference is: " + o43);
		System.out.println("Customer Name is: " + o43.getCustomerName());
		System.out.println("Order ID is: " + o43.getOrderID());
		System.out.println("Food Name is: " + o43.getFoodName());
		System.out.println("Restaurant Name is: " + o43.getRestaurantName());
		System.out.println("Quantity is: " + o43.getQuantity());
		System.out.println("Price is: " + o43.getPrice());
		System.out.println("Order Status is: " + o43.getOrderStatus());
		System.out.println("Order Details are: " + o43.getOrderDetails());
		System.out.println("Total Amount is: " + o43.getTotalAmount());

		System.out.println("=========================Online Food Order Details 44===========================");
		System.out.println("Object Reference is: " + o44);
		System.out.println("Customer Name is: " + o44.getCustomerName());
		System.out.println("Order ID is: " + o44.getOrderID());
		System.out.println("Food Name is: " + o44.getFoodName());
		System.out.println("Restaurant Name is: " + o44.getRestaurantName());
		System.out.println("Quantity is: " + o44.getQuantity());
		System.out.println("Price is: " + o44.getPrice());
		System.out.println("Order Status is: " + o44.getOrderStatus());
		System.out.println("Order Details are: " + o44.getOrderDetails());
		System.out.println("Total Amount is: " + o44.getTotalAmount());

		System.out.println("=========================Online Food Order Details 45===========================");
		System.out.println("Object Reference is: " + o45);
		System.out.println("Customer Name is: " + o45.getCustomerName());
		System.out.println("Order ID is: " + o45.getOrderID());
		System.out.println("Food Name is: " + o45.getFoodName());
		System.out.println("Restaurant Name is: " + o45.getRestaurantName());
		System.out.println("Quantity is: " + o45.getQuantity());
		System.out.println("Price is: " + o45.getPrice());
		System.out.println("Order Status is: " + o45.getOrderStatus());
		System.out.println("Order Details are: " + o45.getOrderDetails());
		System.out.println("Total Amount is: " + o45.getTotalAmount());

		System.out.println("=========================Online Food Order Details 46===========================");
		System.out.println("Object Reference is: " + o46);
		System.out.println("Customer Name is: " + o46.getCustomerName());
		System.out.println("Order ID is: " + o46.getOrderID());
		System.out.println("Food Name is: " + o46.getFoodName());
		System.out.println("Restaurant Name is: " + o46.getRestaurantName());
		System.out.println("Quantity is: " + o46.getQuantity());
		System.out.println("Price is: " + o46.getPrice());
		System.out.println("Order Status is: " + o46.getOrderStatus());
		System.out.println("Order Details are: " + o46.getOrderDetails());
		System.out.println("Total Amount is: " + o46.getTotalAmount());

		System.out.println("=========================Online Food Order Details 47===========================");
		System.out.println("Object Reference is: " + o47);
		System.out.println("Customer Name is: " + o47.getCustomerName());
		System.out.println("Order ID is: " + o47.getOrderID());
		System.out.println("Food Name is: " + o47.getFoodName());
		System.out.println("Restaurant Name is: " + o47.getRestaurantName());
		System.out.println("Quantity is: " + o47.getQuantity());
		System.out.println("Price is: " + o47.getPrice());
		System.out.println("Order Status is: " + o47.getOrderStatus());
		System.out.println("Order Details are: " + o47.getOrderDetails());
		System.out.println("Total Amount is: " + o47.getTotalAmount());

		System.out.println("=========================Online Food Order Details 48===========================");
		System.out.println("Object Reference is: " + o48);
		System.out.println("Customer Name is: " + o48.getCustomerName());
		System.out.println("Order ID is: " + o48.getOrderID());
		System.out.println("Food Name is: " + o48.getFoodName());
		System.out.println("Restaurant Name is: " + o48.getRestaurantName());
		System.out.println("Quantity is: " + o48.getQuantity());
		System.out.println("Price is: " + o48.getPrice());
		System.out.println("Order Status is: " + o48.getOrderStatus());
		System.out.println("Order Details are: " + o48.getOrderDetails());
		System.out.println("Total Amount is: " + o48.getTotalAmount());

		System.out.println("=========================Online Food Order Details 49===========================");
		System.out.println("Object Reference is: " + o49);
		System.out.println("Customer Name is: " + o49.getCustomerName());
		System.out.println("Order ID is: " + o49.getOrderID());
		System.out.println("Food Name is: " + o49.getFoodName());
		System.out.println("Restaurant Name is: " + o49.getRestaurantName());
		System.out.println("Quantity is: " + o49.getQuantity());
		System.out.println("Price is: " + o49.getPrice());
		System.out.println("Order Status is: " + o49.getOrderStatus());
		System.out.println("Order Details are: " + o49.getOrderDetails());
		System.out.println("Total Amount is: " + o49.getTotalAmount());

		System.out.println("=========================Online Food Order Details 50===========================");
		System.out.println("Object Reference is: " + o50);
		System.out.println("Customer Name is: " + o50.getCustomerName());
		System.out.println("Order ID is: " + o50.getOrderID());
		System.out.println("Food Name is: " + o50.getFoodName());
		System.out.println("Restaurant Name is: " + o50.getRestaurantName());
		System.out.println("Quantity is: " + o50.getQuantity());
		System.out.println("Price is: " + o50.getPrice());
		System.out.println("Order Status is: " + o50.getOrderStatus());
		System.out.println("Order Details are: " + o50.getOrderDetails());
		System.out.println("Total Amount is: " + o50.getTotalAmount());
		
		System.out.println("======================================Main Method Ends============================================");
	}

}
