package encapsulationsPrograming;

public class RailwayReservationDriver {

	public static void main(String[] args) {
		
		System.out.println("==================================Main Method Starts=====================================");
		
		RailwayReservation r1 = new RailwayReservation( "RR100001", "12001", "Shatabdi Express", "Delhi", "Lucknow", "15-09-2026", "AC 2 Tier", 25, 1850.50, true, "Mohan Singh, 28, Male, PS100001, 9876543210");
		RailwayReservation r2 = new RailwayReservation("RR100002", "12002", "Gomti Express", "Lucknow", "Delhi", "16-09-2026", "AC 3 Tier", 18, 1450.75, true, "Rohan Kumar, 32, Male, PS100002, 9876543211");
		RailwayReservation r3 = new RailwayReservation("RR100003", "12003", "Rajdhani Express", "Delhi", "Mumbai", "17-09-2026", "AC 2 Tier", 30, 2450.00, true, "Sohan Sharma, 35, Male, PS100003, 9876543212");
		RailwayReservation r4 = new RailwayReservation("RR100004", "12004", "Tejas Express", "Mumbai", "Pune", "18-09-2026", "AC Chair Car", 22, 980.50, true, "Rahul Verma, 29, Male, PS100004, 9876543213");
		RailwayReservation r5 = new RailwayReservation("RR100005", "12005", "Duronto Express", "Pune", "Delhi", "19-09-2026", "AC 3 Tier", 27, 1650.00, true, "Shyam Gupta, 41, Male, PS100005, 9876543214");
		RailwayReservation r6 = new RailwayReservation("RR100006", "12006", "Garib Rath", "Lucknow", "Delhi", "20-09-2026", "AC 3 Tier", 40, 1050.25, true, "Manoj Singh, 38, Male, PS100006, 9876543215");
		RailwayReservation r7 = new RailwayReservation("RR100007", "12007", "Kashi Vishwanath Express", "Delhi", "Varanasi", "21-09-2026", "Sleeper", 55, 750.00, true, "Akash Kumar, 26, Male, PS100007, 9876543216");
		RailwayReservation r8 = new RailwayReservation("RR100008", "12008", "Intercity Express", "Kanpur", "Lucknow", "22-09-2026", "AC Chair Car", 20, 650.50, true, "Samarth Singh, 30, Male, PS100008, 9876543217");
		RailwayReservation r9 = new RailwayReservation("RR100009", "12009", "Golden Temple Mail", "Delhi", "Amritsar", "23-09-2026", "AC 2 Tier", 33, 1950.75, true, "Abhishek Kumar, 34, Male, PS100009, 9876543218");
		RailwayReservation r10 = new RailwayReservation("RR100010", "12010", "Punjab Mail", "Mumbai", "Delhi", "24-09-2026", "Sleeper", 48, 920.00, true, "Karan Singh, 31, Male, PS100010, 9876543219");

		RailwayReservation r11 = new RailwayReservation("RR100011", "12011", "Shatabdi Express", "Delhi", "Chandigarh", "25-09-2026", "AC Chair Car", 24, 1180.50, true, "Aman Sharma, 27, Male, PS100011, 9876543220");
		RailwayReservation r12 = new RailwayReservation("RR100012", "12012", "Karnataka Express", "Delhi", "Bangalore", "26-09-2026", "AC 2 Tier", 36, 2850.00, true, "Vivek Kumar, 39, Male, PS100012, 9876543221");
		RailwayReservation r13 = new RailwayReservation("RR100013", "12013", "Avadh Express", "Lucknow", "Mumbai", "27-09-2026", "Sleeper", 60, 1100.75, true, "Pankaj Verma, 36, Male, PS100013, 9876543222");
		RailwayReservation r14 = new RailwayReservation("RR100014", "12014", "LKO Intercity", "Lucknow", "Kanpur", "28-09-2026", "AC Chair Car", 19, 580.25, true, "Nitin Gupta, 25, Male, PS100014, 9876543223");
		RailwayReservation r15 = new RailwayReservation("RR100015", "12015", "Rajdhani Express", "Delhi", "Kolkata", "29-09-2026", "AC 1st Class", 12, 3900.50, true, "Varun Singh, 43, Male, PS100015, 9876543224");
		RailwayReservation r16 = new RailwayReservation("RR100016", "12016", "Sealdah Rajdhani", "Delhi", "Kolkata", "30-09-2026", "AC 2 Tier", 29, 2750.00, true, "Ankit Kumar, 33, Male, PS100016, 9876543225");
		RailwayReservation r17 = new RailwayReservation("RR100017", "12017", "Chennai Express", "Delhi", "Chennai", "01-10-2026", "AC 3 Tier", 31, 2650.75, true, "Deepak Sharma, 40, Male, PS100017, 9876543226");
		RailwayReservation r18 = new RailwayReservation("RR100018", "12018", "Tamil Nadu Express", "Delhi", "Chennai", "02-10-2026", "Sleeper", 58, 1350.50, true, "Rakesh Verma, 37, Male, PS100018, 9876543227");
		RailwayReservation r19 = new RailwayReservation("RR100019", "12019", "Goa Express", "Delhi", "Goa", "03-10-2026", "AC 2 Tier", 26, 2300.00, true, "Suresh Kumar, 45, Male, PS100019, 9876543228");
		RailwayReservation r20 = new RailwayReservation("RR100020", "12020", "Mangaluru Express", "Mumbai", "Mangalore", "04-10-2026", "AC 3 Tier", 34, 1750.25, true, "Rajesh Singh, 42, Male, PS100020, 9876543229");

		RailwayReservation r21 = new RailwayReservation("RR100021", "12021", "Himalayan Queen", "Delhi", "Kalka", "05-10-2026", "AC Chair Car", 17, 920.50, true, "Mohit Sharma, 28, Male, PS100021, 9876543230");
		RailwayReservation r22 = new RailwayReservation("RR100022", "12022", "Ala Hazrat Express", "Delhi", "Bareilly", "06-10-2026", "Sleeper", 52, 620.00, true, "Sunil Kumar, 46, Male, PS100022, 9876543231");
		RailwayReservation r23 = new RailwayReservation("RR100023", "12023", "Brahmaputra Mail", "Delhi", "Guwahati", "07-10-2026", "AC 2 Tier", 28, 2500.75, true, "Rohit Verma, 30, Male, PS100023, 9876543232");
		RailwayReservation r24 = new RailwayReservation("RR100024", "12024", "Bihar Sampark Kranti", "Delhi", "Patna", "08-10-2026", "AC 3 Tier", 32, 1600.50, true, "Ashish Gupta, 35, Male, PS100024, 9876543233");
		RailwayReservation r25 = new RailwayReservation("RR100025", "12025", "Magadh Express", "Delhi", "Patna", "09-10-2026", "Sleeper", 63, 850.25, true, "Vikas Singh, 29, Male, PS100025, 9876543234");
		RailwayReservation r26 = new RailwayReservation("RR100026", "12026", "Poorva Express", "Delhi", "Howrah", "10-10-2026", "AC 2 Tier", 27, 2200.00, true, "Arun Kumar, 44, Male, PS100026, 9876543235");
		RailwayReservation r27 = new RailwayReservation("RR100027", "12027", "Chauri Chaura Express", "Gorakhpur", "Kanpur", "11-10-2026", "Sleeper", 57, 780.00, true, "Dev Sharma, 31, Male, PS100027, 9876543236");
		RailwayReservation r28 = new RailwayReservation("RR100028", "12028", "Saryu Yamuna Express", "Delhi", "Ayodhya", "12-10-2026", "AC 3 Tier", 25, 1320.50, true, "Naveen Verma, 36, Male, PS100028, 9876543237");
		RailwayReservation r29 = new RailwayReservation("RR100029", "12029", "Ayodhya Dham Express", "Lucknow", "Ayodhya", "13-10-2026", "AC Chair Car", 21, 540.00, true, "Shivam Kumar, 24, Male, PS100029, 9876543238");
		RailwayReservation r30 = new RailwayReservation("RR100030", "12030", "Varanasi Vande Bharat", "Delhi", "Varanasi", "14-10-2026", "Executive Chair Car", 15, 2850.75, true, "Amit Singh, 33, Male, PS100030, 9876543239");

		RailwayReservation r31 = new RailwayReservation("RR100031", "12031", "Lucknow Mail", "Lucknow", "Delhi", "15-10-2026", "AC 2 Tier", 28, 1750.00, true, "Ravi Sharma, 39, Male, PS100031, 9876543240");
		RailwayReservation r32 = new RailwayReservation("RR100032", "12032", "Delhi Mail", "Delhi", "Lucknow", "16-10-2026", "AC 3 Tier", 35, 1420.50, true, "Sanjay Kumar, 41, Male, PS100032, 9876543241");
		RailwayReservation r33 = new RailwayReservation("RR100033", "12033", "Lifeline Express", "Mumbai", "Delhi", "17-10-2026", "Sleeper", 50, 980.75, true, "Vijay Verma, 47, Male, PS100033, 9876543242");
		RailwayReservation r34 = new RailwayReservation("RR100034", "12034", "Maharashtra Express", "Mumbai", "Nagpur", "18-10-2026", "AC 3 Tier", 30, 1480.25, true, "Harish Gupta, 34, Male, PS100034, 9876543243");
		RailwayReservation r35 = new RailwayReservation("RR100035", "12035", "Vidarbha Express", "Nagpur", "Mumbai", "19-10-2026", "AC 2 Tier", 26, 1650.75, true, "Prakash Singh, 42, Male, PS100035, 9876543244");
		RailwayReservation r36 = new RailwayReservation("RR100036", "12036", "Pune Duronto", "Pune", "Mumbai", "20-10-2026", "AC Chair Car", 18, 820.00, true, "Kishore Kumar, 38, Male, PS100036, 9876543245");
		RailwayReservation r37 = new RailwayReservation("RR100037", "12037", "Deccan Queen", "Mumbai", "Pune", "21-10-2026", "AC Chair Car", 20, 950.50, true, "Rajeev Sharma, 29, Male, PS100037, 9876543246");
		RailwayReservation r38 = new RailwayReservation("RR100038", "12038", "Nizamuddin Express", "Delhi", "Hyderabad", "22-10-2026", "AC 2 Tier", 29, 2480.00, true, "Sandeep Kumar, 37, Male, PS100038, 9876543247");
		RailwayReservation r39 = new RailwayReservation("RR100039", "12039", "Telangana Express", "Delhi", "Hyderabad", "23-10-2026", "Sleeper", 61, 1250.75, true, "Mukesh Verma, 45, Male, PS100039, 9876543248");
		RailwayReservation r40 = new RailwayReservation("RR100040", "12040", "Kacheguda Express", "Hyderabad", "Bangalore", "24-10-2026", "AC 3 Tier", 24, 1380.50, true, "Yogesh Singh, 32, Male, PS100040, 9876543249");

		RailwayReservation r41 = new RailwayReservation("RR100041", "12041", "Bangalore Express", "Bangalore", "Chennai", "25-10-2026", "AC Chair Car", 16, 760.25, true, "Nikhil Kumar, 27, Male, PS100041, 9876543250");
		RailwayReservation r42 = new RailwayReservation("RR100042", "12042", "Shatabdi Express", "Chennai", "Bangalore", "26-10-2026", "Executive Chair Car", 14, 1250.00, true, "Gaurav Sharma, 35, Male, PS100042, 9876543251");
		RailwayReservation r43 = new RailwayReservation("RR100043", "12043", "Kerala Express", "Delhi", "Kochi", "27-10-2026", "AC 2 Tier", 33, 3200.50, true, "Manish Verma, 40, Male, PS100043, 9876543252");
		RailwayReservation r44 = new RailwayReservation("RR100044", "12044", "Malabar Express", "Kochi", "Thiruvananthapuram", "28-10-2026", "AC 3 Tier", 22, 1180.75, true, "Ramesh Kumar, 43, Male, PS100044, 9876543253");
		RailwayReservation r45 = new RailwayReservation("RR100045", "12045", "Mysuru Express", "Bangalore", "Mysore", "29-10-2026", "AC Chair Car", 18, 690.50, true, "Akhilesh Singh, 31, Male, PS100045, 9876543254");
		RailwayReservation r46 = new RailwayReservation("RR100046", "12046", "Konkan Kanya Express", "Mumbai", "Madgaon", "30-10-2026", "AC 2 Tier", 27, 1850.00, true, "Rajat Verma, 36, Male, PS100046, 9876543255");
		RailwayReservation r47 = new RailwayReservation("RR100047", "12047", "Mandovi Express", "Mumbai", "Goa", "31-10-2026", "AC Chair Car", 19, 1120.25, true, "Chetan Kumar, 28, Male, PS100047, 9876543256");
		RailwayReservation r48 = new RailwayReservation("RR100048", "12048", "Jhelum Express", "Pune", "Jammu", "01-11-2026", "Sleeper", 64, 1450.75, true, "Vishal Sharma, 39, Male, PS100048, 9876543257");
		RailwayReservation r49 = new RailwayReservation("RR100049", "12049", "Himgiri Express", "Jammu", "Delhi", "02-11-2026", "AC 3 Tier", 31, 1725.50, true, "Pawan Singh, 44, Male, PS100049, 9876543258");
		RailwayReservation r50 = new RailwayReservation("RR100050", "12050", "Amarkantak Express", "Jabalpur", "Bhopal", "03-11-2026", "AC 2 Tier", 23, 1350.00, true, "Suraj Kumar, 30, Male, PS100050, 9876543259");
		
				
		System.out.println("=========================Railway Reservation Details 1===========================");
		System.out.println("Object Reference is: " + r1);
		System.out.println("Reservation ID is: " + r1.getReservationId());
		System.out.println("Train Number is: " + r1.getTrainNumber());
		System.out.println("Train Name is: " + r1.getTrainName());
		System.out.println("Source Station is: " + r1.getSourceStation());
		System.out.println("Destination Station is: " + r1.getDestinationStation());
		System.out.println("Journey Date is: " + r1.getJourneyDate());
		System.out.println("Coach Type is: " + r1.getCoachType());
		System.out.println("Seat Number is: " + r1.getSeatNumber());
		System.out.println("Ticket Price is: " + r1.getTicketPrice());
		System.out.println("Booking Status is: " + r1.getBookingStatus());
		System.out.println("Passenger Details are: " + r1.getPassengerDetails());
		System.out.println("Passenger Name is: " + r1.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 2===========================");
		System.out.println("Object Reference is: " + r2);
		System.out.println("Reservation ID is: " + r2.getReservationId());
		System.out.println("Train Number is: " + r2.getTrainNumber());
		System.out.println("Train Name is: " + r2.getTrainName());
		System.out.println("Source Station is: " + r2.getSourceStation());
		System.out.println("Destination Station is: " + r2.getDestinationStation());
		System.out.println("Journey Date is: " + r2.getJourneyDate());
		System.out.println("Coach Type is: " + r2.getCoachType());
		System.out.println("Seat Number is: " + r2.getSeatNumber());
		System.out.println("Ticket Price is: " + r2.getTicketPrice());
		System.out.println("Booking Status is: " + r2.getBookingStatus());
		System.out.println("Passenger Details are: " + r2.getPassengerDetails());
		System.out.println("Passenger Name is: " + r2.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 3===========================");
		System.out.println("Object Reference is: " + r3);
		System.out.println("Reservation ID is: " + r3.getReservationId());
		System.out.println("Train Number is: " + r3.getTrainNumber());
		System.out.println("Train Name is: " + r3.getTrainName());
		System.out.println("Source Station is: " + r3.getSourceStation());
		System.out.println("Destination Station is: " + r3.getDestinationStation());
		System.out.println("Journey Date is: " + r3.getJourneyDate());
		System.out.println("Coach Type is: " + r3.getCoachType());
		System.out.println("Seat Number is: " + r3.getSeatNumber());
		System.out.println("Ticket Price is: " + r3.getTicketPrice());
		System.out.println("Booking Status is: " + r3.getBookingStatus());
		System.out.println("Passenger Details are: " + r3.getPassengerDetails());
		System.out.println("Passenger Name is: " + r3.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 4===========================");
		System.out.println("Object Reference is: " + r4);
		System.out.println("Reservation ID is: " + r4.getReservationId());
		System.out.println("Train Number is: " + r4.getTrainNumber());
		System.out.println("Train Name is: " + r4.getTrainName());
		System.out.println("Source Station is: " + r4.getSourceStation());
		System.out.println("Destination Station is: " + r4.getDestinationStation());
		System.out.println("Journey Date is: " + r4.getJourneyDate());
		System.out.println("Coach Type is: " + r4.getCoachType());
		System.out.println("Seat Number is: " + r4.getSeatNumber());
		System.out.println("Ticket Price is: " + r4.getTicketPrice());
		System.out.println("Booking Status is: " + r4.getBookingStatus());
		System.out.println("Passenger Details are: " + r4.getPassengerDetails());
		System.out.println("Passenger Name is: " + r4.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 5===========================");
		System.out.println("Object Reference is: " + r5);
		System.out.println("Reservation ID is: " + r5.getReservationId());
		System.out.println("Train Number is: " + r5.getTrainNumber());
		System.out.println("Train Name is: " + r5.getTrainName());
		System.out.println("Source Station is: " + r5.getSourceStation());
		System.out.println("Destination Station is: " + r5.getDestinationStation());
		System.out.println("Journey Date is: " + r5.getJourneyDate());
		System.out.println("Coach Type is: " + r5.getCoachType());
		System.out.println("Seat Number is: " + r5.getSeatNumber());
		System.out.println("Ticket Price is: " + r5.getTicketPrice());
		System.out.println("Booking Status is: " + r5.getBookingStatus());
		System.out.println("Passenger Details are: " + r5.getPassengerDetails());
		System.out.println("Passenger Name is: " + r5.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 6===========================");
		System.out.println("Object Reference is: " + r6);
		System.out.println("Reservation ID is: " + r6.getReservationId());
		System.out.println("Train Number is: " + r6.getTrainNumber());
		System.out.println("Train Name is: " + r6.getTrainName());
		System.out.println("Source Station is: " + r6.getSourceStation());
		System.out.println("Destination Station is: " + r6.getDestinationStation());
		System.out.println("Journey Date is: " + r6.getJourneyDate());
		System.out.println("Coach Type is: " + r6.getCoachType());
		System.out.println("Seat Number is: " + r6.getSeatNumber());
		System.out.println("Ticket Price is: " + r6.getTicketPrice());
		System.out.println("Booking Status is: " + r6.getBookingStatus());
		System.out.println("Passenger Details are: " + r6.getPassengerDetails());
		System.out.println("Passenger Name is: " + r6.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 7===========================");
		System.out.println("Object Reference is: " + r7);
		System.out.println("Reservation ID is: " + r7.getReservationId());
		System.out.println("Train Number is: " + r7.getTrainNumber());
		System.out.println("Train Name is: " + r7.getTrainName());
		System.out.println("Source Station is: " + r7.getSourceStation());
		System.out.println("Destination Station is: " + r7.getDestinationStation());
		System.out.println("Journey Date is: " + r7.getJourneyDate());
		System.out.println("Coach Type is: " + r7.getCoachType());
		System.out.println("Seat Number is: " + r7.getSeatNumber());
		System.out.println("Ticket Price is: " + r7.getTicketPrice());
		System.out.println("Booking Status is: " + r7.getBookingStatus());
		System.out.println("Passenger Details are: " + r7.getPassengerDetails());
		System.out.println("Passenger Name is: " + r7.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 8===========================");
		System.out.println("Object Reference is: " + r8);
		System.out.println("Reservation ID is: " + r8.getReservationId());
		System.out.println("Train Number is: " + r8.getTrainNumber());
		System.out.println("Train Name is: " + r8.getTrainName());
		System.out.println("Source Station is: " + r8.getSourceStation());
		System.out.println("Destination Station is: " + r8.getDestinationStation());
		System.out.println("Journey Date is: " + r8.getJourneyDate());
		System.out.println("Coach Type is: " + r8.getCoachType());
		System.out.println("Seat Number is: " + r8.getSeatNumber());
		System.out.println("Ticket Price is: " + r8.getTicketPrice());
		System.out.println("Booking Status is: " + r8.getBookingStatus());
		System.out.println("Passenger Details are: " + r8.getPassengerDetails());
		System.out.println("Passenger Name is: " + r8.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 9===========================");
		System.out.println("Object Reference is: " + r9);
		System.out.println("Reservation ID is: " + r9.getReservationId());
		System.out.println("Train Number is: " + r9.getTrainNumber());
		System.out.println("Train Name is: " + r9.getTrainName());
		System.out.println("Source Station is: " + r9.getSourceStation());
		System.out.println("Destination Station is: " + r9.getDestinationStation());
		System.out.println("Journey Date is: " + r9.getJourneyDate());
		System.out.println("Coach Type is: " + r9.getCoachType());
		System.out.println("Seat Number is: " + r9.getSeatNumber());
		System.out.println("Ticket Price is: " + r9.getTicketPrice());
		System.out.println("Booking Status is: " + r9.getBookingStatus());
		System.out.println("Passenger Details are: " + r9.getPassengerDetails());
		System.out.println("Passenger Name is: " + r9.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 10===========================");
		System.out.println("Object Reference is: " + r10);
		System.out.println("Reservation ID is: " + r10.getReservationId());
		System.out.println("Train Number is: " + r10.getTrainNumber());
		System.out.println("Train Name is: " + r10.getTrainName());
		System.out.println("Source Station is: " + r10.getSourceStation());
		System.out.println("Destination Station is: " + r10.getDestinationStation());
		System.out.println("Journey Date is: " + r10.getJourneyDate());
		System.out.println("Coach Type is: " + r10.getCoachType());
		System.out.println("Seat Number is: " + r10.getSeatNumber());
		System.out.println("Ticket Price is: " + r10.getTicketPrice());
		System.out.println("Booking Status is: " + r10.getBookingStatus());
		System.out.println("Passenger Details are: " + r10.getPassengerDetails());
		System.out.println("Passenger Name is: " + r10.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 11===========================");
		System.out.println("Object Reference is: " + r11);
		System.out.println("Reservation ID is: " + r11.getReservationId());
		System.out.println("Train Number is: " + r11.getTrainNumber());
		System.out.println("Train Name is: " + r11.getTrainName());
		System.out.println("Source Station is: " + r11.getSourceStation());
		System.out.println("Destination Station is: " + r11.getDestinationStation());
		System.out.println("Journey Date is: " + r11.getJourneyDate());
		System.out.println("Coach Type is: " + r11.getCoachType());
		System.out.println("Seat Number is: " + r11.getSeatNumber());
		System.out.println("Ticket Price is: " + r11.getTicketPrice());
		System.out.println("Booking Status is: " + r11.getBookingStatus());
		System.out.println("Passenger Details are: " + r11.getPassengerDetails());
		System.out.println("Passenger Name is: " + r11.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 12===========================");
		System.out.println("Object Reference is: " + r12);
		System.out.println("Reservation ID is: " + r12.getReservationId());
		System.out.println("Train Number is: " + r12.getTrainNumber());
		System.out.println("Train Name is: " + r12.getTrainName());
		System.out.println("Source Station is: " + r12.getSourceStation());
		System.out.println("Destination Station is: " + r12.getDestinationStation());
		System.out.println("Journey Date is: " + r12.getJourneyDate());
		System.out.println("Coach Type is: " + r12.getCoachType());
		System.out.println("Seat Number is: " + r12.getSeatNumber());
		System.out.println("Ticket Price is: " + r12.getTicketPrice());
		System.out.println("Booking Status is: " + r12.getBookingStatus());
		System.out.println("Passenger Details are: " + r12.getPassengerDetails());
		System.out.println("Passenger Name is: " + r12.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 13===========================");
		System.out.println("Object Reference is: " + r13);
		System.out.println("Reservation ID is: " + r13.getReservationId());
		System.out.println("Train Number is: " + r13.getTrainNumber());
		System.out.println("Train Name is: " + r13.getTrainName());
		System.out.println("Source Station is: " + r13.getSourceStation());
		System.out.println("Destination Station is: " + r13.getDestinationStation());
		System.out.println("Journey Date is: " + r13.getJourneyDate());
		System.out.println("Coach Type is: " + r13.getCoachType());
		System.out.println("Seat Number is: " + r13.getSeatNumber());
		System.out.println("Ticket Price is: " + r13.getTicketPrice());
		System.out.println("Booking Status is: " + r13.getBookingStatus());
		System.out.println("Passenger Details are: " + r13.getPassengerDetails());
		System.out.println("Passenger Name is: " + r13.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 14===========================");
		System.out.println("Object Reference is: " + r14);
		System.out.println("Reservation ID is: " + r14.getReservationId());
		System.out.println("Train Number is: " + r14.getTrainNumber());
		System.out.println("Train Name is: " + r14.getTrainName());
		System.out.println("Source Station is: " + r14.getSourceStation());
		System.out.println("Destination Station is: " + r14.getDestinationStation());
		System.out.println("Journey Date is: " + r14.getJourneyDate());
		System.out.println("Coach Type is: " + r14.getCoachType());
		System.out.println("Seat Number is: " + r14.getSeatNumber());
		System.out.println("Ticket Price is: " + r14.getTicketPrice());
		System.out.println("Booking Status is: " + r14.getBookingStatus());
		System.out.println("Passenger Details are: " + r14.getPassengerDetails());
		System.out.println("Passenger Name is: " + r14.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 15===========================");
		System.out.println("Object Reference is: " + r15);
		System.out.println("Reservation ID is: " + r15.getReservationId());
		System.out.println("Train Number is: " + r15.getTrainNumber());
		System.out.println("Train Name is: " + r15.getTrainName());
		System.out.println("Source Station is: " + r15.getSourceStation());
		System.out.println("Destination Station is: " + r15.getDestinationStation());
		System.out.println("Journey Date is: " + r15.getJourneyDate());
		System.out.println("Coach Type is: " + r15.getCoachType());
		System.out.println("Seat Number is: " + r15.getSeatNumber());
		System.out.println("Ticket Price is: " + r15.getTicketPrice());
		System.out.println("Booking Status is: " + r15.getBookingStatus());
		System.out.println("Passenger Details are: " + r15.getPassengerDetails());
		System.out.println("Passenger Name is: " + r15.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 16===========================");
		System.out.println("Object Reference is: " + r16);
		System.out.println("Reservation ID is: " + r16.getReservationId());
		System.out.println("Train Number is: " + r16.getTrainNumber());
		System.out.println("Train Name is: " + r16.getTrainName());
		System.out.println("Source Station is: " + r16.getSourceStation());
		System.out.println("Destination Station is: " + r16.getDestinationStation());
		System.out.println("Journey Date is: " + r16.getJourneyDate());
		System.out.println("Coach Type is: " + r16.getCoachType());
		System.out.println("Seat Number is: " + r16.getSeatNumber());
		System.out.println("Ticket Price is: " + r16.getTicketPrice());
		System.out.println("Booking Status is: " + r16.getBookingStatus());
		System.out.println("Passenger Details are: " + r16.getPassengerDetails());
		System.out.println("Passenger Name is: " + r16.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 17===========================");
		System.out.println("Object Reference is: " + r17);
		System.out.println("Reservation ID is: " + r17.getReservationId());
		System.out.println("Train Number is: " + r17.getTrainNumber());
		System.out.println("Train Name is: " + r17.getTrainName());
		System.out.println("Source Station is: " + r17.getSourceStation());
		System.out.println("Destination Station is: " + r17.getDestinationStation());
		System.out.println("Journey Date is: " + r17.getJourneyDate());
		System.out.println("Coach Type is: " + r17.getCoachType());
		System.out.println("Seat Number is: " + r17.getSeatNumber());
		System.out.println("Ticket Price is: " + r17.getTicketPrice());
		System.out.println("Booking Status is: " + r17.getBookingStatus());
		System.out.println("Passenger Details are: " + r17.getPassengerDetails());
		System.out.println("Passenger Name is: " + r17.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 18===========================");
		System.out.println("Object Reference is: " + r18);
		System.out.println("Reservation ID is: " + r18.getReservationId());
		System.out.println("Train Number is: " + r18.getTrainNumber());
		System.out.println("Train Name is: " + r18.getTrainName());
		System.out.println("Source Station is: " + r18.getSourceStation());
		System.out.println("Destination Station is: " + r18.getDestinationStation());
		System.out.println("Journey Date is: " + r18.getJourneyDate());
		System.out.println("Coach Type is: " + r18.getCoachType());
		System.out.println("Seat Number is: " + r18.getSeatNumber());
		System.out.println("Ticket Price is: " + r18.getTicketPrice());
		System.out.println("Booking Status is: " + r18.getBookingStatus());
		System.out.println("Passenger Details are: " + r18.getPassengerDetails());
		System.out.println("Passenger Name is: " + r18.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 19===========================");
		System.out.println("Object Reference is: " + r19);
		System.out.println("Reservation ID is: " + r19.getReservationId());
		System.out.println("Train Number is: " + r19.getTrainNumber());
		System.out.println("Train Name is: " + r19.getTrainName());
		System.out.println("Source Station is: " + r19.getSourceStation());
		System.out.println("Destination Station is: " + r19.getDestinationStation());
		System.out.println("Journey Date is: " + r19.getJourneyDate());
		System.out.println("Coach Type is: " + r19.getCoachType());
		System.out.println("Seat Number is: " + r19.getSeatNumber());
		System.out.println("Ticket Price is: " + r19.getTicketPrice());
		System.out.println("Booking Status is: " + r19.getBookingStatus());
		System.out.println("Passenger Details are: " + r19.getPassengerDetails());
		System.out.println("Passenger Name is: " + r19.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 20===========================");
		System.out.println("Object Reference is: " + r20);
		System.out.println("Reservation ID is: " + r20.getReservationId());
		System.out.println("Train Number is: " + r20.getTrainNumber());
		System.out.println("Train Name is: " + r20.getTrainName());
		System.out.println("Source Station is: " + r20.getSourceStation());
		System.out.println("Destination Station is: " + r20.getDestinationStation());
		System.out.println("Journey Date is: " + r20.getJourneyDate());
		System.out.println("Coach Type is: " + r20.getCoachType());
		System.out.println("Seat Number is: " + r20.getSeatNumber());
		System.out.println("Ticket Price is: " + r20.getTicketPrice());
		System.out.println("Booking Status is: " + r20.getBookingStatus());
		System.out.println("Passenger Details are: " + r20.getPassengerDetails());
		System.out.println("Passenger Name is: " + r20.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 21===========================");
		System.out.println("Object Reference is: " + r21);
		System.out.println("Reservation ID is: " + r21.getReservationId());
		System.out.println("Train Number is: " + r21.getTrainNumber());
		System.out.println("Train Name is: " + r21.getTrainName());
		System.out.println("Source Station is: " + r21.getSourceStation());
		System.out.println("Destination Station is: " + r21.getDestinationStation());
		System.out.println("Journey Date is: " + r21.getJourneyDate());
		System.out.println("Coach Type is: " + r21.getCoachType());
		System.out.println("Seat Number is: " + r21.getSeatNumber());
		System.out.println("Ticket Price is: " + r21.getTicketPrice());
		System.out.println("Booking Status is: " + r21.getBookingStatus());
		System.out.println("Passenger Details are: " + r21.getPassengerDetails());
		System.out.println("Passenger Name is: " + r21.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 22===========================");
		System.out.println("Object Reference is: " + r22);
		System.out.println("Reservation ID is: " + r22.getReservationId());
		System.out.println("Train Number is: " + r22.getTrainNumber());
		System.out.println("Train Name is: " + r22.getTrainName());
		System.out.println("Source Station is: " + r22.getSourceStation());
		System.out.println("Destination Station is: " + r22.getDestinationStation());
		System.out.println("Journey Date is: " + r22.getJourneyDate());
		System.out.println("Coach Type is: " + r22.getCoachType());
		System.out.println("Seat Number is: " + r22.getSeatNumber());
		System.out.println("Ticket Price is: " + r22.getTicketPrice());
		System.out.println("Booking Status is: " + r22.getBookingStatus());
		System.out.println("Passenger Details are: " + r22.getPassengerDetails());
		System.out.println("Passenger Name is: " + r22.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 23===========================");
		System.out.println("Object Reference is: " + r23);
		System.out.println("Reservation ID is: " + r23.getReservationId());
		System.out.println("Train Number is: " + r23.getTrainNumber());
		System.out.println("Train Name is: " + r23.getTrainName());
		System.out.println("Source Station is: " + r23.getSourceStation());
		System.out.println("Destination Station is: " + r23.getDestinationStation());
		System.out.println("Journey Date is: " + r23.getJourneyDate());
		System.out.println("Coach Type is: " + r23.getCoachType());
		System.out.println("Seat Number is: " + r23.getSeatNumber());
		System.out.println("Ticket Price is: " + r23.getTicketPrice());
		System.out.println("Booking Status is: " + r23.getBookingStatus());
		System.out.println("Passenger Details are: " + r23.getPassengerDetails());
		System.out.println("Passenger Name is: " + r23.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 24===========================");
		System.out.println("Object Reference is: " + r24);
		System.out.println("Reservation ID is: " + r24.getReservationId());
		System.out.println("Train Number is: " + r24.getTrainNumber());
		System.out.println("Train Name is: " + r24.getTrainName());
		System.out.println("Source Station is: " + r24.getSourceStation());
		System.out.println("Destination Station is: " + r24.getDestinationStation());
		System.out.println("Journey Date is: " + r24.getJourneyDate());
		System.out.println("Coach Type is: " + r24.getCoachType());
		System.out.println("Seat Number is: " + r24.getSeatNumber());
		System.out.println("Ticket Price is: " + r24.getTicketPrice());
		System.out.println("Booking Status is: " + r24.getBookingStatus());
		System.out.println("Passenger Details are: " + r24.getPassengerDetails());
		System.out.println("Passenger Name is: " + r24.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 25===========================");
		System.out.println("Object Reference is: " + r25);
		System.out.println("Reservation ID is: " + r25.getReservationId());
		System.out.println("Train Number is: " + r25.getTrainNumber());
		System.out.println("Train Name is: " + r25.getTrainName());
		System.out.println("Source Station is: " + r25.getSourceStation());
		System.out.println("Destination Station is: " + r25.getDestinationStation());
		System.out.println("Journey Date is: " + r25.getJourneyDate());
		System.out.println("Coach Type is: " + r25.getCoachType());
		System.out.println("Seat Number is: " + r25.getSeatNumber());
		System.out.println("Ticket Price is: " + r25.getTicketPrice());
		System.out.println("Booking Status is: " + r25.getBookingStatus());
		System.out.println("Passenger Details are: " + r25.getPassengerDetails());
		System.out.println("Passenger Name is: " + r25.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 26===========================");
		System.out.println("Object Reference is: " + r26);
		System.out.println("Reservation ID is: " + r26.getReservationId());
		System.out.println("Train Number is: " + r26.getTrainNumber());
		System.out.println("Train Name is: " + r26.getTrainName());
		System.out.println("Source Station is: " + r26.getSourceStation());
		System.out.println("Destination Station is: " + r26.getDestinationStation());
		System.out.println("Journey Date is: " + r26.getJourneyDate());
		System.out.println("Coach Type is: " + r26.getCoachType());
		System.out.println("Seat Number is: " + r26.getSeatNumber());
		System.out.println("Ticket Price is: " + r26.getTicketPrice());
		System.out.println("Booking Status is: " + r26.getBookingStatus());
		System.out.println("Passenger Details are: " + r26.getPassengerDetails());
		System.out.println("Passenger Name is: " + r26.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 27===========================");
		System.out.println("Object Reference is: " + r27);
		System.out.println("Reservation ID is: " + r27.getReservationId());
		System.out.println("Train Number is: " + r27.getTrainNumber());
		System.out.println("Train Name is: " + r27.getTrainName());
		System.out.println("Source Station is: " + r27.getSourceStation());
		System.out.println("Destination Station is: " + r27.getDestinationStation());
		System.out.println("Journey Date is: " + r27.getJourneyDate());
		System.out.println("Coach Type is: " + r27.getCoachType());
		System.out.println("Seat Number is: " + r27.getSeatNumber());
		System.out.println("Ticket Price is: " + r27.getTicketPrice());
		System.out.println("Booking Status is: " + r27.getBookingStatus());
		System.out.println("Passenger Details are: " + r27.getPassengerDetails());
		System.out.println("Passenger Name is: " + r27.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 28===========================");
		System.out.println("Object Reference is: " + r28);
		System.out.println("Reservation ID is: " + r28.getReservationId());
		System.out.println("Train Number is: " + r28.getTrainNumber());
		System.out.println("Train Name is: " + r28.getTrainName());
		System.out.println("Source Station is: " + r28.getSourceStation());
		System.out.println("Destination Station is: " + r28.getDestinationStation());
		System.out.println("Journey Date is: " + r28.getJourneyDate());
		System.out.println("Coach Type is: " + r28.getCoachType());
		System.out.println("Seat Number is: " + r28.getSeatNumber());
		System.out.println("Ticket Price is: " + r28.getTicketPrice());
		System.out.println("Booking Status is: " + r28.getBookingStatus());
		System.out.println("Passenger Details are: " + r28.getPassengerDetails());
		System.out.println("Passenger Name is: " + r28.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 29===========================");
		System.out.println("Object Reference is: " + r29);
		System.out.println("Reservation ID is: " + r29.getReservationId());
		System.out.println("Train Number is: " + r29.getTrainNumber());
		System.out.println("Train Name is: " + r29.getTrainName());
		System.out.println("Source Station is: " + r29.getSourceStation());
		System.out.println("Destination Station is: " + r29.getDestinationStation());
		System.out.println("Journey Date is: " + r29.getJourneyDate());
		System.out.println("Coach Type is: " + r29.getCoachType());
		System.out.println("Seat Number is: " + r29.getSeatNumber());
		System.out.println("Ticket Price is: " + r29.getTicketPrice());
		System.out.println("Booking Status is: " + r29.getBookingStatus());
		System.out.println("Passenger Details are: " + r29.getPassengerDetails());
		System.out.println("Passenger Name is: " + r29.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 30===========================");
		System.out.println("Object Reference is: " + r30);
		System.out.println("Reservation ID is: " + r30.getReservationId());
		System.out.println("Train Number is: " + r30.getTrainNumber());
		System.out.println("Train Name is: " + r30.getTrainName());
		System.out.println("Source Station is: " + r30.getSourceStation());
		System.out.println("Destination Station is: " + r30.getDestinationStation());
		System.out.println("Journey Date is: " + r30.getJourneyDate());
		System.out.println("Coach Type is: " + r30.getCoachType());
		System.out.println("Seat Number is: " + r30.getSeatNumber());
		System.out.println("Ticket Price is: " + r30.getTicketPrice());
		System.out.println("Booking Status is: " + r30.getBookingStatus());
		System.out.println("Passenger Details are: " + r30.getPassengerDetails());
		System.out.println("Passenger Name is: " + r30.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 31===========================");
		System.out.println("Object Reference is: " + r31);
		System.out.println("Reservation ID is: " + r31.getReservationId());
		System.out.println("Train Number is: " + r31.getTrainNumber());
		System.out.println("Train Name is: " + r31.getTrainName());
		System.out.println("Source Station is: " + r31.getSourceStation());
		System.out.println("Destination Station is: " + r31.getDestinationStation());
		System.out.println("Journey Date is: " + r31.getJourneyDate());
		System.out.println("Coach Type is: " + r31.getCoachType());
		System.out.println("Seat Number is: " + r31.getSeatNumber());
		System.out.println("Ticket Price is: " + r31.getTicketPrice());
		System.out.println("Booking Status is: " + r31.getBookingStatus());
		System.out.println("Passenger Details are: " + r31.getPassengerDetails());
		System.out.println("Passenger Name is: " + r31.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 32===========================");
		System.out.println("Object Reference is: " + r32);
		System.out.println("Reservation ID is: " + r32.getReservationId());
		System.out.println("Train Number is: " + r32.getTrainNumber());
		System.out.println("Train Name is: " + r32.getTrainName());
		System.out.println("Source Station is: " + r32.getSourceStation());
		System.out.println("Destination Station is: " + r32.getDestinationStation());
		System.out.println("Journey Date is: " + r32.getJourneyDate());
		System.out.println("Coach Type is: " + r32.getCoachType());
		System.out.println("Seat Number is: " + r32.getSeatNumber());
		System.out.println("Ticket Price is: " + r32.getTicketPrice());
		System.out.println("Booking Status is: " + r32.getBookingStatus());
		System.out.println("Passenger Details are: " + r32.getPassengerDetails());
		System.out.println("Passenger Name is: " + r32.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 33===========================");
		System.out.println("Object Reference is: " + r33);
		System.out.println("Reservation ID is: " + r33.getReservationId());
		System.out.println("Train Number is: " + r33.getTrainNumber());
		System.out.println("Train Name is: " + r33.getTrainName());
		System.out.println("Source Station is: " + r33.getSourceStation());
		System.out.println("Destination Station is: " + r33.getDestinationStation());
		System.out.println("Journey Date is: " + r33.getJourneyDate());
		System.out.println("Coach Type is: " + r33.getCoachType());
		System.out.println("Seat Number is: " + r33.getSeatNumber());
		System.out.println("Ticket Price is: " + r33.getTicketPrice());
		System.out.println("Booking Status is: " + r33.getBookingStatus());
		System.out.println("Passenger Details are: " + r33.getPassengerDetails());
		System.out.println("Passenger Name is: " + r33.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 34===========================");
		System.out.println("Object Reference is: " + r34);
		System.out.println("Reservation ID is: " + r34.getReservationId());
		System.out.println("Train Number is: " + r34.getTrainNumber());
		System.out.println("Train Name is: " + r34.getTrainName());
		System.out.println("Source Station is: " + r34.getSourceStation());
		System.out.println("Destination Station is: " + r34.getDestinationStation());
		System.out.println("Journey Date is: " + r34.getJourneyDate());
		System.out.println("Coach Type is: " + r34.getCoachType());
		System.out.println("Seat Number is: " + r34.getSeatNumber());
		System.out.println("Ticket Price is: " + r34.getTicketPrice());
		System.out.println("Booking Status is: " + r34.getBookingStatus());
		System.out.println("Passenger Details are: " + r34.getPassengerDetails());
		System.out.println("Passenger Name is: " + r34.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 35===========================");
		System.out.println("Object Reference is: " + r35);
		System.out.println("Reservation ID is: " + r35.getReservationId());
		System.out.println("Train Number is: " + r35.getTrainNumber());
		System.out.println("Train Name is: " + r35.getTrainName());
		System.out.println("Source Station is: " + r35.getSourceStation());
		System.out.println("Destination Station is: " + r35.getDestinationStation());
		System.out.println("Journey Date is: " + r35.getJourneyDate());
		System.out.println("Coach Type is: " + r35.getCoachType());
		System.out.println("Seat Number is: " + r35.getSeatNumber());
		System.out.println("Ticket Price is: " + r35.getTicketPrice());
		System.out.println("Booking Status is: " + r35.getBookingStatus());
		System.out.println("Passenger Details are: " + r35.getPassengerDetails());
		System.out.println("Passenger Name is: " + r35.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 36===========================");
		System.out.println("Object Reference is: " + r36);
		System.out.println("Reservation ID is: " + r36.getReservationId());
		System.out.println("Train Number is: " + r36.getTrainNumber());
		System.out.println("Train Name is: " + r36.getTrainName());
		System.out.println("Source Station is: " + r36.getSourceStation());
		System.out.println("Destination Station is: " + r36.getDestinationStation());
		System.out.println("Journey Date is: " + r36.getJourneyDate());
		System.out.println("Coach Type is: " + r36.getCoachType());
		System.out.println("Seat Number is: " + r36.getSeatNumber());
		System.out.println("Ticket Price is: " + r36.getTicketPrice());
		System.out.println("Booking Status is: " + r36.getBookingStatus());
		System.out.println("Passenger Details are: " + r36.getPassengerDetails());
		System.out.println("Passenger Name is: " + r36.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 37===========================");
		System.out.println("Object Reference is: " + r37);
		System.out.println("Reservation ID is: " + r37.getReservationId());
		System.out.println("Train Number is: " + r37.getTrainNumber());
		System.out.println("Train Name is: " + r37.getTrainName());
		System.out.println("Source Station is: " + r37.getSourceStation());
		System.out.println("Destination Station is: " + r37.getDestinationStation());
		System.out.println("Journey Date is: " + r37.getJourneyDate());
		System.out.println("Coach Type is: " + r37.getCoachType());
		System.out.println("Seat Number is: " + r37.getSeatNumber());
		System.out.println("Ticket Price is: " + r37.getTicketPrice());
		System.out.println("Booking Status is: " + r37.getBookingStatus());
		System.out.println("Passenger Details are: " + r37.getPassengerDetails());
		System.out.println("Passenger Name is: " + r37.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 38===========================");
		System.out.println("Object Reference is: " + r38);
		System.out.println("Reservation ID is: " + r38.getReservationId());
		System.out.println("Train Number is: " + r38.getTrainNumber());
		System.out.println("Train Name is: " + r38.getTrainName());
		System.out.println("Source Station is: " + r38.getSourceStation());
		System.out.println("Destination Station is: " + r38.getDestinationStation());
		System.out.println("Journey Date is: " + r38.getJourneyDate());
		System.out.println("Coach Type is: " + r38.getCoachType());
		System.out.println("Seat Number is: " + r38.getSeatNumber());
		System.out.println("Ticket Price is: " + r38.getTicketPrice());
		System.out.println("Booking Status is: " + r38.getBookingStatus());
		System.out.println("Passenger Details are: " + r38.getPassengerDetails());
		System.out.println("Passenger Name is: " + r38.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 39===========================");
		System.out.println("Object Reference is: " + r39);
		System.out.println("Reservation ID is: " + r39.getReservationId());
		System.out.println("Train Number is: " + r39.getTrainNumber());
		System.out.println("Train Name is: " + r39.getTrainName());
		System.out.println("Source Station is: " + r39.getSourceStation());
		System.out.println("Destination Station is: " + r39.getDestinationStation());
		System.out.println("Journey Date is: " + r39.getJourneyDate());
		System.out.println("Coach Type is: " + r39.getCoachType());
		System.out.println("Seat Number is: " + r39.getSeatNumber());
		System.out.println("Ticket Price is: " + r39.getTicketPrice());
		System.out.println("Booking Status is: " + r39.getBookingStatus());
		System.out.println("Passenger Details are: " + r39.getPassengerDetails());
		System.out.println("Passenger Name is: " + r39.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 40===========================");
		System.out.println("Object Reference is: " + r40);
		System.out.println("Reservation ID is: " + r40.getReservationId());
		System.out.println("Train Number is: " + r40.getTrainNumber());
		System.out.println("Train Name is: " + r40.getTrainName());
		System.out.println("Source Station is: " + r40.getSourceStation());
		System.out.println("Destination Station is: " + r40.getDestinationStation());
		System.out.println("Journey Date is: " + r40.getJourneyDate());
		System.out.println("Coach Type is: " + r40.getCoachType());
		System.out.println("Seat Number is: " + r40.getSeatNumber());
		System.out.println("Ticket Price is: " + r40.getTicketPrice());
		System.out.println("Booking Status is: " + r40.getBookingStatus());
		System.out.println("Passenger Details are: " + r40.getPassengerDetails());
		System.out.println("Passenger Name is: " + r40.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 41===========================");
		System.out.println("Object Reference is: " + r41);
		System.out.println("Reservation ID is: " + r41.getReservationId());
		System.out.println("Train Number is: " + r41.getTrainNumber());
		System.out.println("Train Name is: " + r41.getTrainName());
		System.out.println("Source Station is: " + r41.getSourceStation());
		System.out.println("Destination Station is: " + r41.getDestinationStation());
		System.out.println("Journey Date is: " + r41.getJourneyDate());
		System.out.println("Coach Type is: " + r41.getCoachType());
		System.out.println("Seat Number is: " + r41.getSeatNumber());
		System.out.println("Ticket Price is: " + r41.getTicketPrice());
		System.out.println("Booking Status is: " + r41.getBookingStatus());
		System.out.println("Passenger Details are: " + r41.getPassengerDetails());
		System.out.println("Passenger Name is: " + r41.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 42===========================");
		System.out.println("Object Reference is: " + r42);
		System.out.println("Reservation ID is: " + r42.getReservationId());
		System.out.println("Train Number is: " + r42.getTrainNumber());
		System.out.println("Train Name is: " + r42.getTrainName());
		System.out.println("Source Station is: " + r42.getSourceStation());
		System.out.println("Destination Station is: " + r42.getDestinationStation());
		System.out.println("Journey Date is: " + r42.getJourneyDate());
		System.out.println("Coach Type is: " + r42.getCoachType());
		System.out.println("Seat Number is: " + r42.getSeatNumber());
		System.out.println("Ticket Price is: " + r42.getTicketPrice());
		System.out.println("Booking Status is: " + r42.getBookingStatus());
		System.out.println("Passenger Details are: " + r42.getPassengerDetails());
		System.out.println("Passenger Name is: " + r42.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 43===========================");
		System.out.println("Object Reference is: " + r43);
		System.out.println("Reservation ID is: " + r43.getReservationId());
		System.out.println("Train Number is: " + r43.getTrainNumber());
		System.out.println("Train Name is: " + r43.getTrainName());
		System.out.println("Source Station is: " + r43.getSourceStation());
		System.out.println("Destination Station is: " + r43.getDestinationStation());
		System.out.println("Journey Date is: " + r43.getJourneyDate());
		System.out.println("Coach Type is: " + r43.getCoachType());
		System.out.println("Seat Number is: " + r43.getSeatNumber());
		System.out.println("Ticket Price is: " + r43.getTicketPrice());
		System.out.println("Booking Status is: " + r43.getBookingStatus());
		System.out.println("Passenger Details are: " + r43.getPassengerDetails());
		System.out.println("Passenger Name is: " + r43.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 44===========================");
		System.out.println("Object Reference is: " + r44);
		System.out.println("Reservation ID is: " + r44.getReservationId());
		System.out.println("Train Number is: " + r44.getTrainNumber());
		System.out.println("Train Name is: " + r44.getTrainName());
		System.out.println("Source Station is: " + r44.getSourceStation());
		System.out.println("Destination Station is: " + r44.getDestinationStation());
		System.out.println("Journey Date is: " + r44.getJourneyDate());
		System.out.println("Coach Type is: " + r44.getCoachType());
		System.out.println("Seat Number is: " + r44.getSeatNumber());
		System.out.println("Ticket Price is: " + r44.getTicketPrice());
		System.out.println("Booking Status is: " + r44.getBookingStatus());
		System.out.println("Passenger Details are: " + r44.getPassengerDetails());
		System.out.println("Passenger Name is: " + r44.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 45===========================");
		System.out.println("Object Reference is: " + r45);
		System.out.println("Reservation ID is: " + r45.getReservationId());
		System.out.println("Train Number is: " + r45.getTrainNumber());
		System.out.println("Train Name is: " + r45.getTrainName());
		System.out.println("Source Station is: " + r45.getSourceStation());
		System.out.println("Destination Station is: " + r45.getDestinationStation());
		System.out.println("Journey Date is: " + r45.getJourneyDate());
		System.out.println("Coach Type is: " + r45.getCoachType());
		System.out.println("Seat Number is: " + r45.getSeatNumber());
		System.out.println("Ticket Price is: " + r45.getTicketPrice());
		System.out.println("Booking Status is: " + r45.getBookingStatus());
		System.out.println("Passenger Details are: " + r45.getPassengerDetails());
		System.out.println("Passenger Name is: " + r45.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 46===========================");
		System.out.println("Object Reference is: " + r46);
		System.out.println("Reservation ID is: " + r46.getReservationId());
		System.out.println("Train Number is: " + r46.getTrainNumber());
		System.out.println("Train Name is: " + r46.getTrainName());
		System.out.println("Source Station is: " + r46.getSourceStation());
		System.out.println("Destination Station is: " + r46.getDestinationStation());
		System.out.println("Journey Date is: " + r46.getJourneyDate());
		System.out.println("Coach Type is: " + r46.getCoachType());
		System.out.println("Seat Number is: " + r46.getSeatNumber());
		System.out.println("Ticket Price is: " + r46.getTicketPrice());
		System.out.println("Booking Status is: " + r46.getBookingStatus());
		System.out.println("Passenger Details are: " + r46.getPassengerDetails());
		System.out.println("Passenger Name is: " + r46.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 47===========================");
		System.out.println("Object Reference is: " + r47);
		System.out.println("Reservation ID is: " + r47.getReservationId());
		System.out.println("Train Number is: " + r47.getTrainNumber());
		System.out.println("Train Name is: " + r47.getTrainName());
		System.out.println("Source Station is: " + r47.getSourceStation());
		System.out.println("Destination Station is: " + r47.getDestinationStation());
		System.out.println("Journey Date is: " + r47.getJourneyDate());
		System.out.println("Coach Type is: " + r47.getCoachType());
		System.out.println("Seat Number is: " + r47.getSeatNumber());
		System.out.println("Ticket Price is: " + r47.getTicketPrice());
		System.out.println("Booking Status is: " + r47.getBookingStatus());
		System.out.println("Passenger Details are: " + r47.getPassengerDetails());
		System.out.println("Passenger Name is: " + r47.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 48===========================");
		System.out.println("Object Reference is: " + r48);
		System.out.println("Reservation ID is: " + r48.getReservationId());
		System.out.println("Train Number is: " + r48.getTrainNumber());
		System.out.println("Train Name is: " + r48.getTrainName());
		System.out.println("Source Station is: " + r48.getSourceStation());
		System.out.println("Destination Station is: " + r48.getDestinationStation());
		System.out.println("Journey Date is: " + r48.getJourneyDate());
		System.out.println("Coach Type is: " + r48.getCoachType());
		System.out.println("Seat Number is: " + r48.getSeatNumber());
		System.out.println("Ticket Price is: " + r48.getTicketPrice());
		System.out.println("Booking Status is: " + r48.getBookingStatus());
		System.out.println("Passenger Details are: " + r48.getPassengerDetails());
		System.out.println("Passenger Name is: " + r48.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 49===========================");
		System.out.println("Object Reference is: " + r49);
		System.out.println("Reservation ID is: " + r49.getReservationId());
		System.out.println("Train Number is: " + r49.getTrainNumber());
		System.out.println("Train Name is: " + r49.getTrainName());
		System.out.println("Source Station is: " + r49.getSourceStation());
		System.out.println("Destination Station is: " + r49.getDestinationStation());
		System.out.println("Journey Date is: " + r49.getJourneyDate());
		System.out.println("Coach Type is: " + r49.getCoachType());
		System.out.println("Seat Number is: " + r49.getSeatNumber());
		System.out.println("Ticket Price is: " + r49.getTicketPrice());
		System.out.println("Booking Status is: " + r49.getBookingStatus());
		System.out.println("Passenger Details are: " + r49.getPassengerDetails());
		System.out.println("Passenger Name is: " + r49.getPassengerDetails());

		System.out.println("=========================Railway Reservation Details 50===========================");
		System.out.println("Object Reference is: " + r50);
		System.out.println("Reservation ID is: " + r50.getReservationId());
		System.out.println("Train Number is: " + r50.getTrainNumber());
		System.out.println("Train Name is: " + r50.getTrainName());
		System.out.println("Source Station is: " + r50.getSourceStation());
		System.out.println("Destination Station is: " + r50.getDestinationStation());
		System.out.println("Journey Date is: " + r50.getJourneyDate());
		System.out.println("Coach Type is: " + r50.getCoachType());
		System.out.println("Seat Number is: " + r50.getSeatNumber());
		System.out.println("Ticket Price is: " + r50.getTicketPrice());
		System.out.println("Booking Status is: " + r50.getBookingStatus());
		System.out.println("Passenger Details are: " + r50.getPassengerDetails());
		System.out.println("Passenger Name is: " + r50.getPassengerDetails());
		
		System.out.println("=========================================Main Method Ends========================================");
	}

}
