package task2Assignment;

public class CubNumber {
	
	public static int getCube(int num) {
		
		return num*num*num;
	}

	public static void main(String[] args) {
		 
		int result = getCube(11);
		int result1 = getCube(12);
		int result2 = getCube(13);
		int result3 = getCube(14);
		int result4 = getCube(15);
		int result5 = getCube(16);
		int result6 = getCube(17);
		int result7 = getCube(18);
		int result8 = getCube(19);
		int result9 = getCube(20);
		int result10 = getCube(21);
		int result11 = getCube(22);
		int result12 = getCube(23);
		int result13 = getCube(24);
		int result14 = getCube(25);
		int result15 = getCube(26);
		int result16 = getCube(27);
		int result17 = getCube(28);
		int result18 = getCube(29);
		int result19 = getCube(30);
		int result20 = getCube(31);
		int result21 = getCube(32);
		int result22 = getCube(33);
		int result23 = getCube(34);
		int result24 = getCube(35);
		int result25 = getCube(36);
		int result26 = getCube(37);
		int result27 = getCube(38);
		int result28 = getCube(39);
		int result29 = getCube(40);
		int result30 = getCube(41);
		int result31 = getCube(42);
		int result32 = getCube(43);
		int result33 = getCube(44);
		int result34 = getCube(45);
		int result35 = getCube(46);
		int result36 = getCube(47);
		int result37 = getCube(48);
		int result38 = getCube(49);
		int result39 = getCube(50);
		int result40 = getCube(51);
		int result41 = getCube(52);
		int result42 = getCube(53);
		int result43 = getCube(54);
		int result44 = getCube(55);
		int result45 = getCube(56);
		int result46 = getCube(57);
		int result47 = getCube(58);
		int result48 = getCube(59);
		int result49 = getCube(60);
		int result50 = getCube(61);
		int result51 = getCube(62);
		int result52 = getCube(63);
		int result53 = getCube(64);
		int result54 = getCube(65);
		int result55 = getCube(66);
		int result56 = getCube(67);
		int result57 = getCube(68);
		int result58 = getCube(69);
		int result59 = getCube(70);
		int result60 = getCube(71);
		int result61 = getCube(72);
		int result62 = getCube(73);
		int result63 = getCube(74);
		int result64 = getCube(75);
		int result65 = getCube(76);
		int result66 = getCube(77);
		int result67 = getCube(78);
		int result68 = getCube(79);
		int result69 = getCube(80);
		int result70 = getCube(81);
		int result71 = getCube(82);
		int result72 = getCube(83);
		int result73 = getCube(84);
		int result74 = getCube(85);
		int result75 = getCube(86);
		int result76 = getCube(87);
		int result77 = getCube(88);
		int result78 = getCube(89);
		int result79 = getCube(90);
		int result80 = getCube(91);
		int result81 = getCube(92);
		int result82 = getCube(93);
		int result83 = getCube(94);
		int result84 = getCube(95);
		int result85 = getCube(96);
		int result86 = getCube(97);
		int result87 = getCube(98);
		int result88 = getCube(99);
		int result89 = getCube(100);
		int result90 = getCube(100);
		
		System.out.println(result);
		System.out.println(result1);
		System.out.println(result2);
		System.out.println(result3);
		System.out.println(result4);
		System.out.println(result5);
		System.out.println(result6);
		System.out.println(result7);
		System.out.println(result8);
		System.out.println(result9);
		System.out.println(result10);
		System.out.println(result11);
		System.out.println(result12);
		System.out.println(result13);
		System.out.println(result14);
		System.out.println(result15);
		System.out.println(result16);
		System.out.println(result17);
		System.out.println(result18);
		System.out.println(result19);
		System.out.println(result20);
		System.out.println(result21);
		System.out.println(result22);
		System.out.println(result23);
		System.out.println(result24);
		System.out.println(result25);
		System.out.println(result26);
		System.out.println(result27);
		System.out.println(result28);
		System.out.println(result29);
		System.out.println(result30);
		System.out.println(result31);
		System.out.println(result32);
		System.out.println(result33);
		System.out.println(result34);
		System.out.println(result35);
		System.out.println(result36);
		System.out.println(result37);
		System.out.println(result38);
		System.out.println(result39);
		System.out.println(result40);
		System.out.println(result41);
		System.out.println(result42);
		System.out.println(result43);
		System.out.println(result44);
		System.out.println(result45);
		System.out.println(result46);
		System.out.println(result47);
		System.out.println(result48);
		System.out.println(result49);
		System.out.println(result50);
		System.out.println(result51);
		System.out.println(result52);
		System.out.println(result53);
		System.out.println(result54);
		System.out.println(result55);
		System.out.println(result56);
		System.out.println(result57);
		System.out.println(result58);
		System.out.println(result59);
		System.out.println(result60);
		System.out.println(result61);
		System.out.println(result62);
		System.out.println(result63);
		System.out.println(result64);
		System.out.println(result65);
		System.out.println(result66);
		System.out.println(result67);
		System.out.println(result68);
		System.out.println(result69);
		System.out.println(result70);
		System.out.println(result71);
		System.out.println(result72);
		System.out.println(result73);
		System.out.println(result74);
		System.out.println(result75);
		System.out.println(result76);
		System.out.println(result77);
		System.out.println(result78);
		System.out.println(result79);
		System.out.println(result80);
		System.out.println(result81);
		System.out.println(result82);
		System.out.println(result83);
		System.out.println(result84);
		System.out.println(result85);
		System.out.println(result86);
		System.out.println(result87);
		System.out.println(result88);
		System.out.println(result89);
		System.out.println(result90);

	}

}
