package pojoPrograming;

public class StudentManagementDriver {

	public static void main(String[] args) {
		
		StudentManagement s1 = new StudentManagement(101, "Mohan Singh", 21, 87.50, "Java", "Lucknow University", "mohan@gmail.com", 9876543210L, "Lucknow", "Male", 5, "A");
		StudentManagement s2 = new StudentManagement(102, "Rohan Kumar", 22, 91.75, "Python", "Delhi University", "rohan@gmail.com", 9876543211L, "Delhi", "Male", 6, "A+");
		StudentManagement s3 = new StudentManagement(103, "Sohan Sharma", 20, 82.40, "Java", "Allahabad University", "sohan@gmail.com", 9876543212L, "Prayagraj", "Male", 4, "B+");
		StudentManagement s4 = new StudentManagement(104, "Rahul Verma", 23, 88.90, "C++", "Banaras Hindu University", "rahul@gmail.com", 9876543213L, "Varanasi", "Male", 7, "A");
		StudentManagement s5 = new StudentManagement(105, "Shyam Gupta", 21, 79.65, "JavaScript", "Lucknow University", "shyam@gmail.com", 9876543214L, "Lucknow", "Male", 5, "B+");
		StudentManagement s6 = new StudentManagement(106, "Manoj Singh", 24, 93.20, "Software Testing", "Noida International University", "manoj@gmail.com", 9876543215L, "Noida", "Male", 8, "A+");
		StudentManagement s7 = new StudentManagement(107, "Akash Verma", 20, 85.50, "Data Science", "Amity University", "akash@gmail.com", 9876543216L, "Noida", "Male", 4, "A");
		StudentManagement s8 = new StudentManagement(108, "Samarth Singh", 22, 90.25, "Artificial Intelligence", "Sharda University", "samarth@gmail.com", 9876543217L, "Greater Noida", "Male", 6, "A+");
		StudentManagement s9 = new StudentManagement(109, "Abhishek Kumar", 21, 76.80, "Computer Science", "Galgotias University", "abhishek@gmail.com", 9876543218L, "Greater Noida", "Male", 5, "B");
		StudentManagement s10 = new StudentManagement(110, "Karan Singh", 23, 89.45, "Information Technology", "Amity University", "karan@gmail.com", 9876543219L, "Noida", "Male", 7, "A");
		StudentManagement s11 = new StudentManagement(111, "Aman Sharma", 20, 81.35, "Java", "Lucknow University", "aman@gmail.com", 9876543220L, "Lucknow", "Male", 4, "B+");
		StudentManagement s12 = new StudentManagement(112, "Ravi Kumar", 22, 94.60, "Python", "Delhi University", "ravi@gmail.com", 9876543221L, "Delhi", "Male", 6, "A+");
		StudentManagement s13 = new StudentManagement(113, "Pankaj Verma", 21, 87.15, "C#", "Panjab University", "pankaj@gmail.com", 9876543222L, "Chandigarh", "Male", 5, "A");
		StudentManagement s14 = new StudentManagement(114, "Nitin Sharma", 24, 78.55, "PHP", "University of Mumbai", "nitin@gmail.com", 9876543223L, "Mumbai", "Male", 8, "B");
		StudentManagement s15 = new StudentManagement(115, "Varun Gupta", 20, 92.30, "Java", "Banaras Hindu University", "varun@gmail.com", 9876543224L, "Varanasi", "Male", 4, "A+");
		StudentManagement s16 = new StudentManagement(116, "Ankit Kumar", 23, 84.75, "Automation Testing", "Amity University", "ankit@gmail.com", 9876543225L, "Lucknow", "Male", 7, "A");
		StudentManagement s17 = new StudentManagement(117, "Deepak Sharma", 21, 80.40, "Manual Testing", "Lucknow University", "deepak@gmail.com", 9876543226L, "Lucknow", "Male", 5, "B+");
		StudentManagement s18 = new StudentManagement(118, "Rakesh Verma", 22, 96.10, "Data Analytics", "Delhi University", "rakesh@gmail.com", 9876543227L, "Delhi", "Male", 6, "A+");
		StudentManagement s19 = new StudentManagement(119, "Suresh Kumar", 24, 77.95, "Cloud Computing", "Galgotias University", "suresh@gmail.com", 9876543228L, "Greater Noida", "Male", 8, "B");
		StudentManagement s20 = new StudentManagement(120, "Rajesh Singh", 20, 86.25, "Cyber Security", "Sharda University", "rajesh@gmail.com", 9876543229L, "Greater Noida", "Male", 4, "A");
		StudentManagement s21 = new StudentManagement(121, "Mohit Sharma", 22, 90.85, "Machine Learning", "Amity University", "mohit@gmail.com", 9876543230L, "Noida", "Male", 6, "A+");
		StudentManagement s22 = new StudentManagement(122, "Vikas Kumar", 23, 83.60, "Java", "Lucknow University", "vikas@gmail.com", 9876543231L, "Lucknow", "Male", 7, "B+");
		StudentManagement s23 = new StudentManagement(123, "Amit Verma", 21, 88.35, "Python", "Allahabad University", "amit@gmail.com", 9876543232L, "Prayagraj", "Male", 5, "A");
		StudentManagement s24 = new StudentManagement(124, "Sanjay Sharma", 24, 75.50, "Networking", "Delhi University", "sanjay@gmail.com", 9876543233L, "Delhi", "Male", 8, "B");
		StudentManagement s25 = new StudentManagement(125, "Ravi Singh", 20, 91.40, "Software Engineering", "Banaras Hindu University", "ravisingh@gmail.com", 9876543234L, "Varanasi", "Male", 4, "A+");
		StudentManagement s26 = new StudentManagement(126, "Ashish Kumar", 22, 89.15, "Database Management", "Amity University", "ashish@gmail.com", 9876543235L, "Noida", "Male", 6, "A");
		StudentManagement s27 = new StudentManagement(127, "Neeraj Verma", 23, 82.75, "Web Development", "Sharda University", "neeraj@gmail.com", 9876543236L, "Greater Noida", "Male", 7, "B+");
		StudentManagement s28 = new StudentManagement(128, "Piyush Sharma", 21, 95.25, "Artificial Intelligence", "Galgotias University", "piyush@gmail.com", 9876543237L, "Greater Noida", "Male", 5, "A+");
		StudentManagement s29 = new StudentManagement(129, "Kunal Gupta", 20, 87.60, "Java", "Lucknow University", "kunal@gmail.com", 9876543238L, "Lucknow", "Male", 4, "A");
		StudentManagement s30 = new StudentManagement(130, "Manish Singh", 24, 79.85, "Python", "University of Mumbai", "manish@gmail.com", 9876543239L, "Mumbai", "Male", 8, "B");
		StudentManagement s31 = new StudentManagement(131, "Lokesh Kumar", 22, 93.75, "Data Science", "Delhi University", "lokesh@gmail.com", 9876543240L, "Delhi", "Male", 6, "A+");
		StudentManagement s32 = new StudentManagement(132, "Arjun Verma", 21, 84.20, "Cyber Security", "Amity University", "arjun@gmail.com", 9876543241L, "Noida", "Male", 5, "B+");
		StudentManagement s33 = new StudentManagement(133, "Akhil Sharma", 23, 90.50, "Automation Testing", "Lucknow University", "akhil@gmail.com", 9876543242L, "Lucknow", "Male", 7, "A+");
		StudentManagement s34 = new StudentManagement(134, "Sandeep Kumar", 24, 76.35, "Computer Networks", "Panjab University", "sandeep@gmail.com", 9876543243L, "Chandigarh", "Male", 8, "B");
		StudentManagement s35 = new StudentManagement(135, "Mukesh Verma", 20, 88.75, "Java", "Banaras Hindu University", "mukesh@gmail.com", 9876543244L, "Varanasi", "Male", 4, "A");
		StudentManagement s36 = new StudentManagement(136, "Yogesh Singh", 22, 92.15, "Cloud Computing", "Sharda University", "yogesh@gmail.com", 9876543245L, "Greater Noida", "Male", 6, "A+");
		StudentManagement s37 = new StudentManagement(137, "Nikhil Kumar", 21, 80.65, "Software Testing", "Amity University", "nikhil@gmail.com", 9876543246L, "Noida", "Male", 5, "B+");
		StudentManagement s38 = new StudentManagement(138, "Gaurav Sharma", 23, 86.95, "Machine Learning", "Delhi University", "gaurav@gmail.com", 9876543247L, "Delhi", "Male", 7, "A");
		StudentManagement s39 = new StudentManagement(139, "Rajat Verma", 20, 94.35, "Artificial Intelligence", "Galgotias University", "rajat@gmail.com", 9876543248L, "Greater Noida", "Male", 4, "A+");
		StudentManagement s40 = new StudentManagement(140, "Chetan Kumar", 24, 78.25, "Database Management", "Lucknow University", "chetan@gmail.com", 9876543249L, "Lucknow", "Male", 8, "B");
		StudentManagement s41 = new StudentManagement(141, "Vishal Sharma", 22, 89.80, "Web Development", "Amity University", "vishal@gmail.com", 9876543250L, "Noida", "Male", 6, "A");
		StudentManagement s42 = new StudentManagement(142, "Pawan Singh", 21, 83.45, "JavaScript", "Delhi University", "pawan@gmail.com", 9876543251L, "Delhi", "Male", 5, "B+");
		StudentManagement s43 = new StudentManagement(143, "Suraj Kumar", 23, 91.60, "C++", "Allahabad University", "suraj@gmail.com", 9876543252L, "Prayagraj", "Male", 7, "A+");
		StudentManagement s44 = new StudentManagement(144, "Dev Sharma", 20, 85.25, "Python", "Banaras Hindu University", "dev@gmail.com", 9876543253L, "Varanasi", "Male", 4, "A");
		StudentManagement s45 = new StudentManagement(145, "Akhilesh Verma", 24, 97.10, "Data Science", "Amity University", "akhilesh@gmail.com", 9876543254L, "Noida", "Male", 8, "A+");
		StudentManagement s46 = new StudentManagement(146, "Ramesh Kumar", 22, 81.90, "Java", "Lucknow University", "ramesh@gmail.com", 9876543255L, "Lucknow", "Male", 6, "B+");
		StudentManagement s47 = new StudentManagement(147, "Shivam Singh", 21, 88.05, "Cyber Security", "Sharda University", "shivam@gmail.com", 9876543256L, "Greater Noida", "Male", 5, "A");
		StudentManagement s48 = new StudentManagement(148, "Prakash Kumar", 23, 90.95, "Software Engineering", "Galgotias University", "prakash@gmail.com", 9876543257L, "Greater Noida", "Male", 7, "A+");
		StudentManagement s49 = new StudentManagement(149, "Harish Sharma", 20, 79.30, "Networking", "Delhi University", "harish@gmail.com", 9876543258L, "Delhi", "Male", 4, "B");
		StudentManagement s50 = new StudentManagement(150, "Vijay Verma", 24, 93.85, "Automation Testing", "Amity University", "vijay@gmail.com", 9876543259L, "Noida", "Male", 8, "A+");
		
				
		System.out.println("=========================Student Management Details 1=========================");

		System.out.println("Object Reference is: " + s1);
		System.out.println("Student ID is: " + s1.getStudentID());
		System.out.println("Student Name is: " + s1.getStudentName());
		System.out.println("Age is: " + s1.getAge());
		System.out.println("Marks are: " + s1.getMarks());
		System.out.println("Course is: " + s1.getCourse());
		System.out.println("College is: " + s1.getCollege());
		System.out.println("Email is: " + s1.getEmail());
		System.out.println("Contact is: " + s1.getContact());
		System.out.println("Address is: " + s1.getAddress());
		System.out.println("Gender is: " + s1.getGender());
		System.out.println("Semester is: " + s1.getSemester());
		System.out.println("Grade is: " + s1.getGrade());
		System.out.println("===============================================================");

		s1.setStudentName("Rohan Kumar");
		s1.setAge(22);
		s1.setMarks(92.75);
		s1.setCourse("Automation Testing");
		s1.setEmail("rohan@gmail.com");
		s1.setContact(9876543211L);
		s1.setAddress("Noida");
		s1.setSemester(6);
		s1.setGrade("A+");

		System.out.println("After Updating Student 1 Details");
		System.out.println("Student ID is: " + s1.getStudentID());
		System.out.println("Student Name is: " + s1.getStudentName());
		System.out.println("Age is: " + s1.getAge());
		System.out.println("Marks are: " + s1.getMarks());
		System.out.println("Course is: " + s1.getCourse());
		System.out.println("College is: " + s1.getCollege());
		System.out.println("Email is: " + s1.getEmail());
		System.out.println("Contact is: " + s1.getContact());
		System.out.println("Address is: " + s1.getAddress());
		System.out.println("Gender is: " + s1.getGender());
		System.out.println("Semester is: " + s1.getSemester());
		System.out.println("Grade is: " + s1.getGrade());


		System.out.println("=========================Student Management Details 2=========================");

		System.out.println("Object Reference is: " + s2);
		System.out.println("Student ID is: " + s2.getStudentID());
		System.out.println("Student Name is: " + s2.getStudentName());
		System.out.println("Age is: " + s2.getAge());
		System.out.println("Marks are: " + s2.getMarks());
		System.out.println("Course is: " + s2.getCourse());
		System.out.println("College is: " + s2.getCollege());
		System.out.println("Email is: " + s2.getEmail());
		System.out.println("Contact is: " + s2.getContact());
		System.out.println("Address is: " + s2.getAddress());
		System.out.println("Gender is: " + s2.getGender());
		System.out.println("Semester is: " + s2.getSemester());
		System.out.println("Grade is: " + s2.getGrade());
		System.out.println("===============================================================");

		s2.setStudentName("Amit Sharma");
		s2.setAge(23);
		s2.setMarks(94.50);
		s2.setCourse("Java");
		s2.setEmail("amit@gmail.com");
		s2.setContact(9876543212L);
		s2.setAddress("Delhi");
		s2.setSemester(7);
		s2.setGrade("A+");

		System.out.println("After Updating Student 2 Details");
		System.out.println("Student ID is: " + s2.getStudentID());
		System.out.println("Student Name is: " + s2.getStudentName());
		System.out.println("Age is: " + s2.getAge());
		System.out.println("Marks are: " + s2.getMarks());
		System.out.println("Course is: " + s2.getCourse());
		System.out.println("College is: " + s2.getCollege());
		System.out.println("Email is: " + s2.getEmail());
		System.out.println("Contact is: " + s2.getContact());
		System.out.println("Address is: " + s2.getAddress());
		System.out.println("Gender is: " + s2.getGender());
		System.out.println("Semester is: " + s2.getSemester());
		System.out.println("Grade is: " + s2.getGrade());


		System.out.println("=========================Student Management Details 3=========================");

		System.out.println("Object Reference is: " + s3);
		System.out.println("Student ID is: " + s3.getStudentID());
		System.out.println("Student Name is: " + s3.getStudentName());
		System.out.println("Age is: " + s3.getAge());
		System.out.println("Marks are: " + s3.getMarks());
		System.out.println("Course is: " + s3.getCourse());
		System.out.println("College is: " + s3.getCollege());
		System.out.println("Email is: " + s3.getEmail());
		System.out.println("Contact is: " + s3.getContact());
		System.out.println("Address is: " + s3.getAddress());
		System.out.println("Gender is: " + s3.getGender());
		System.out.println("Semester is: " + s3.getSemester());
		System.out.println("Grade is: " + s3.getGrade());
		System.out.println("===============================================================");

		s3.setStudentName("Vikas Verma");
		s3.setAge(21);
		s3.setMarks(88.75);
		s3.setCourse("Python");
		s3.setEmail("vikas@gmail.com");
		s3.setContact(9876543213L);
		s3.setAddress("Lucknow");
		s3.setSemester(5);
		s3.setGrade("A");

		System.out.println("After Updating Student 3 Details");
		System.out.println("Student ID is: " + s3.getStudentID());
		System.out.println("Student Name is: " + s3.getStudentName());
		System.out.println("Age is: " + s3.getAge());
		System.out.println("Marks are: " + s3.getMarks());
		System.out.println("Course is: " + s3.getCourse());
		System.out.println("College is: " + s3.getCollege());
		System.out.println("Email is: " + s3.getEmail());
		System.out.println("Contact is: " + s3.getContact());
		System.out.println("Address is: " + s3.getAddress());
		System.out.println("Gender is: " + s3.getGender());
		System.out.println("Semester is: " + s3.getSemester());
		System.out.println("Grade is: " + s3.getGrade());


		System.out.println("=========================Student Management Details 4=========================");

		System.out.println("Object Reference is: " + s4);
		System.out.println("Student ID is: " + s4.getStudentID());
		System.out.println("Student Name is: " + s4.getStudentName());
		System.out.println("Age is: " + s4.getAge());
		System.out.println("Marks are: " + s4.getMarks());
		System.out.println("Course is: " + s4.getCourse());
		System.out.println("College is: " + s4.getCollege());
		System.out.println("Email is: " + s4.getEmail());
		System.out.println("Contact is: " + s4.getContact());
		System.out.println("Address is: " + s4.getAddress());
		System.out.println("Gender is: " + s4.getGender());
		System.out.println("Semester is: " + s4.getSemester());
		System.out.println("Grade is: " + s4.getGrade());
		System.out.println("===============================================================");

		s4.setStudentName("Rahul Singh");
		s4.setAge(24);
		s4.setMarks(90.20);
		s4.setCourse("C++");
		s4.setEmail("rahul@gmail.com");
		s4.setContact(9876543214L);
		s4.setAddress("Kanpur");
		s4.setSemester(8);
		s4.setGrade("A+");

		System.out.println("After Updating Student 4 Details");
		System.out.println("Student ID is: " + s4.getStudentID());
		System.out.println("Student Name is: " + s4.getStudentName());
		System.out.println("Age is: " + s4.getAge());
		System.out.println("Marks are: " + s4.getMarks());
		System.out.println("Course is: " + s4.getCourse());
		System.out.println("College is: " + s4.getCollege());
		System.out.println("Email is: " + s4.getEmail());
		System.out.println("Contact is: " + s4.getContact());
		System.out.println("Address is: " + s4.getAddress());
		System.out.println("Gender is: " + s4.getGender());
		System.out.println("Semester is: " + s4.getSemester());
		System.out.println("Grade is: " + s4.getGrade());


		System.out.println("=========================Student Management Details 5=========================");

		System.out.println("Object Reference is: " + s5);
		System.out.println("Student ID is: " + s5.getStudentID());
		System.out.println("Student Name is: " + s5.getStudentName());
		System.out.println("Age is: " + s5.getAge());
		System.out.println("Marks are: " + s5.getMarks());
		System.out.println("Course is: " + s5.getCourse());
		System.out.println("College is: " + s5.getCollege());
		System.out.println("Email is: " + s5.getEmail());
		System.out.println("Contact is: " + s5.getContact());
		System.out.println("Address is: " + s5.getAddress());
		System.out.println("Gender is: " + s5.getGender());
		System.out.println("Semester is: " + s5.getSemester());
		System.out.println("Grade is: " + s5.getGrade());
		System.out.println("===============================================================");

		s5.setStudentName("Shyam Gupta");
		s5.setAge(22);
		s5.setMarks(86.40);
		s5.setCourse("JavaScript");
		s5.setEmail("shyam@gmail.com");
		s5.setContact(9876543215L);
		s5.setAddress("Pune");
		s5.setSemester(6);
		s5.setGrade("A");

		System.out.println("After Updating Student 5 Details");
		System.out.println("Student ID is: " + s5.getStudentID());
		System.out.println("Student Name is: " + s5.getStudentName());
		System.out.println("Age is: " + s5.getAge());
		System.out.println("Marks are: " + s5.getMarks());
		System.out.println("Course is: " + s5.getCourse());
		System.out.println("College is: " + s5.getCollege());
		System.out.println("Email is: " + s5.getEmail());
		System.out.println("Contact is: " + s5.getContact());
		System.out.println("Address is: " + s5.getAddress());
		System.out.println("Gender is: " + s5.getGender());
		System.out.println("Semester is: " + s5.getSemester());
		System.out.println("Grade is: " + s5.getGrade());


		System.out.println("=========================Student Management Details 6=========================");

		System.out.println("Object Reference is: " + s6);
		System.out.println("Student ID is: " + s6.getStudentID());
		System.out.println("Student Name is: " + s6.getStudentName());
		System.out.println("Age is: " + s6.getAge());
		System.out.println("Marks are: " + s6.getMarks());
		System.out.println("Course is: " + s6.getCourse());
		System.out.println("College is: " + s6.getCollege());
		System.out.println("Email is: " + s6.getEmail());
		System.out.println("Contact is: " + s6.getContact());
		System.out.println("Address is: " + s6.getAddress());
		System.out.println("Gender is: " + s6.getGender());
		System.out.println("Semester is: " + s6.getSemester());
		System.out.println("Grade is: " + s6.getGrade());
		System.out.println("===============================================================");

		s6.setStudentName("Manoj Kumar");
		s6.setAge(25);
		s6.setMarks(95.10);
		s6.setCourse("Software Testing");
		s6.setEmail("manoj@gmail.com");
		s6.setContact(9876543216L);
		s6.setAddress("Gurugram");
		s6.setSemester(8);
		s6.setGrade("A+");

		System.out.println("After Updating Student 6 Details");
		System.out.println("Student ID is: " + s6.getStudentID());
		System.out.println("Student Name is: " + s6.getStudentName());
		System.out.println("Age is: " + s6.getAge());
		System.out.println("Marks are: " + s6.getMarks());
		System.out.println("Course is: " + s6.getCourse());
		System.out.println("College is: " + s6.getCollege());
		System.out.println("Email is: " + s6.getEmail());
		System.out.println("Contact is: " + s6.getContact());
		System.out.println("Address is: " + s6.getAddress());
		System.out.println("Gender is: " + s6.getGender());
		System.out.println("Semester is: " + s6.getSemester());
		System.out.println("Grade is: " + s6.getGrade());


		System.out.println("=========================Student Management Details 7=========================");

		System.out.println("Object Reference is: " + s7);
		System.out.println("Student ID is: " + s7.getStudentID());
		System.out.println("Student Name is: " + s7.getStudentName());
		System.out.println("Age is: " + s7.getAge());
		System.out.println("Marks are: " + s7.getMarks());
		System.out.println("Course is: " + s7.getCourse());
		System.out.println("College is: " + s7.getCollege());
		System.out.println("Email is: " + s7.getEmail());
		System.out.println("Contact is: " + s7.getContact());
		System.out.println("Address is: " + s7.getAddress());
		System.out.println("Gender is: " + s7.getGender());
		System.out.println("Semester is: " + s7.getSemester());
		System.out.println("Grade is: " + s7.getGrade());
		System.out.println("===============================================================");

		s7.setStudentName("Akash Verma");
		s7.setAge(21);
		s7.setMarks(89.90);
		s7.setCourse("Data Science");
		s7.setEmail("akash@gmail.com");
		s7.setContact(9876543217L);
		s7.setAddress("Meerut");
		s7.setSemester(5);
		s7.setGrade("A");

		System.out.println("After Updating Student 7 Details");
		System.out.println("Student ID is: " + s7.getStudentID());
		System.out.println("Student Name is: " + s7.getStudentName());
		System.out.println("Age is: " + s7.getAge());
		System.out.println("Marks are: " + s7.getMarks());
		System.out.println("Course is: " + s7.getCourse());
		System.out.println("College is: " + s7.getCollege());
		System.out.println("Email is: " + s7.getEmail());
		System.out.println("Contact is: " + s7.getContact());
		System.out.println("Address is: " + s7.getAddress());
		System.out.println("Gender is: " + s7.getGender());
		System.out.println("Semester is: " + s7.getSemester());
		System.out.println("Grade is: " + s7.getGrade());


		System.out.println("=========================Student Management Details 8=========================");

		System.out.println("Object Reference is: " + s8);
		System.out.println("Student ID is: " + s8.getStudentID());
		System.out.println("Student Name is: " + s8.getStudentName());
		System.out.println("Age is: " + s8.getAge());
		System.out.println("Marks are: " + s8.getMarks());
		System.out.println("Course is: " + s8.getCourse());
		System.out.println("College is: " + s8.getCollege());
		System.out.println("Email is: " + s8.getEmail());
		System.out.println("Contact is: " + s8.getContact());
		System.out.println("Address is: " + s8.getAddress());
		System.out.println("Gender is: " + s8.getGender());
		System.out.println("Semester is: " + s8.getSemester());
		System.out.println("Grade is: " + s8.getGrade());
		System.out.println("===============================================================");

		s8.setStudentName("Samarth Singh");
		s8.setAge(23);
		s8.setMarks(91.35);
		s8.setCourse("Artificial Intelligence");
		s8.setEmail("samarth@gmail.com");
		s8.setContact(9876543218L);
		s8.setAddress("Jaipur");
		s8.setSemester(7);
		s8.setGrade("A+");

		System.out.println("After Updating Student 8 Details");
		System.out.println("Student ID is: " + s8.getStudentID());
		System.out.println("Student Name is: " + s8.getStudentName());
		System.out.println("Age is: " + s8.getAge());
		System.out.println("Marks are: " + s8.getMarks());
		System.out.println("Course is: " + s8.getCourse());
		System.out.println("College is: " + s8.getCollege());
		System.out.println("Email is: " + s8.getEmail());
		System.out.println("Contact is: " + s8.getContact());
		System.out.println("Address is: " + s8.getAddress());
		System.out.println("Gender is: " + s8.getGender());
		System.out.println("Semester is: " + s8.getSemester());
		System.out.println("Grade is: " + s8.getGrade());


		System.out.println("=========================Student Management Details 9=========================");

		System.out.println("Object Reference is: " + s9);
		System.out.println("Student ID is: " + s9.getStudentID());
		System.out.println("Student Name is: " + s9.getStudentName());
		System.out.println("Age is: " + s9.getAge());
		System.out.println("Marks are: " + s9.getMarks());
		System.out.println("Course is: " + s9.getCourse());
		System.out.println("College is: " + s9.getCollege());
		System.out.println("Email is: " + s9.getEmail());
		System.out.println("Contact is: " + s9.getContact());
		System.out.println("Address is: " + s9.getAddress());
		System.out.println("Gender is: " + s9.getGender());
		System.out.println("Semester is: " + s9.getSemester());
		System.out.println("Grade is: " + s9.getGrade());
		System.out.println("===============================================================");

		s9.setStudentName("Abhishek Kumar");
		s9.setAge(22);
		s9.setMarks(84.65);
		s9.setCourse("Computer Science");
		s9.setEmail("abhishek@gmail.com");
		s9.setContact(9876543219L);
		s9.setAddress("Ahmedabad");
		s9.setSemester(6);
		s9.setGrade("B+");

		System.out.println("After Updating Student 9 Details");
		System.out.println("Student ID is: " + s9.getStudentID());
		System.out.println("Student Name is: " + s9.getStudentName());
		System.out.println("Age is: " + s9.getAge());
		System.out.println("Marks are: " + s9.getMarks());
		System.out.println("Course is: " + s9.getCourse());
		System.out.println("College is: " + s9.getCollege());
		System.out.println("Email is: " + s9.getEmail());
		System.out.println("Contact is: " + s9.getContact());
		System.out.println("Address is: " + s9.getAddress());
		System.out.println("Gender is: " + s9.getGender());
		System.out.println("Semester is: " + s9.getSemester());
		System.out.println("Grade is: " + s9.getGrade());


		System.out.println("=========================Student Management Details 10=========================");

		System.out.println("Object Reference is: " + s10);
		System.out.println("Student ID is: " + s10.getStudentID());
		System.out.println("Student Name is: " + s10.getStudentName());
		System.out.println("Age is: " + s10.getAge());
		System.out.println("Marks are: " + s10.getMarks());
		System.out.println("Course is: " + s10.getCourse());
		System.out.println("College is: " + s10.getCollege());
		System.out.println("Email is: " + s10.getEmail());
		System.out.println("Contact is: " + s10.getContact());
		System.out.println("Address is: " + s10.getAddress());
		System.out.println("Gender is: " + s10.getGender());
		System.out.println("Semester is: " + s10.getSemester());
		System.out.println("Grade is: " + s10.getGrade());
		System.out.println("===============================================================");

		s10.setStudentName("Karan Singh");
		s10.setAge(24);
		s10.setMarks(93.45);
		s10.setCourse("Information Technology");
		s10.setEmail("karan@gmail.com");
		s10.setContact(9876543220L);
		s10.setAddress("Gurugram");
		s10.setSemester(8);
		s10.setGrade("A+");

		System.out.println("After Updating Student 10 Details");
		System.out.println("Student ID is: " + s10.getStudentID());
		System.out.println("Student Name is: " + s10.getStudentName());
		System.out.println("Age is: " + s10.getAge());
		System.out.println("Marks are: " + s10.getMarks());
		System.out.println("Course is: " + s10.getCourse());
		System.out.println("College is: " + s10.getCollege());
		System.out.println("Email is: " + s10.getEmail());
		System.out.println("Contact is: " + s10.getContact());
		System.out.println("Address is: " + s10.getAddress());
		System.out.println("Gender is: " + s10.getGender());
		System.out.println("Semester is: " + s10.getSemester());
		System.out.println("Grade is: " + s10.getGrade());
		
		System.out.println("=========================Student Management Details 1=========================");
		System.out.println("Object Reference is: " + s1);
		System.out.println("Student ID is: " + s1.getStudentID());
		System.out.println("Student Name is: " + s1.getStudentName());
		System.out.println("Age is: " + s1.getAge());
		System.out.println("Marks are: " + s1.getMarks());
		System.out.println("Course is: " + s1.getCourse());
		System.out.println("College is: " + s1.getCollege());
		System.out.println("Email is: " + s1.getEmail());
		System.out.println("Contact is: " + s1.getContact());
		System.out.println("Address is: " + s1.getAddress());
		System.out.println("Gender is: " + s1.getGender());
		System.out.println("Semester is: " + s1.getSemester());
		System.out.println("Grade is: " + s1.getGrade());

		System.out.println("=========================Student Management Details 2=========================");
		System.out.println("Object Reference is: " + s2);
		System.out.println("Student ID is: " + s2.getStudentID());
		System.out.println("Student Name is: " + s2.getStudentName());
		System.out.println("Age is: " + s2.getAge());
		System.out.println("Marks are: " + s2.getMarks());
		System.out.println("Course is: " + s2.getCourse());
		System.out.println("College is: " + s2.getCollege());
		System.out.println("Email is: " + s2.getEmail());
		System.out.println("Contact is: " + s2.getContact());
		System.out.println("Address is: " + s2.getAddress());
		System.out.println("Gender is: " + s2.getGender());
		System.out.println("Semester is: " + s2.getSemester());
		System.out.println("Grade is: " + s2.getGrade());

		System.out.println("=========================Student Management Details 3=========================");
		System.out.println("Object Reference is: " + s3);
		System.out.println("Student ID is: " + s3.getStudentID());
		System.out.println("Student Name is: " + s3.getStudentName());
		System.out.println("Age is: " + s3.getAge());
		System.out.println("Marks are: " + s3.getMarks());
		System.out.println("Course is: " + s3.getCourse());
		System.out.println("College is: " + s3.getCollege());
		System.out.println("Email is: " + s3.getEmail());
		System.out.println("Contact is: " + s3.getContact());
		System.out.println("Address is: " + s3.getAddress());
		System.out.println("Gender is: " + s3.getGender());
		System.out.println("Semester is: " + s3.getSemester());
		System.out.println("Grade is: " + s3.getGrade());

		System.out.println("=========================Student Management Details 4=========================");
		System.out.println("Object Reference is: " + s4);
		System.out.println("Student ID is: " + s4.getStudentID());
		System.out.println("Student Name is: " + s4.getStudentName());
		System.out.println("Age is: " + s4.getAge());
		System.out.println("Marks are: " + s4.getMarks());
		System.out.println("Course is: " + s4.getCourse());
		System.out.println("College is: " + s4.getCollege());
		System.out.println("Email is: " + s4.getEmail());
		System.out.println("Contact is: " + s4.getContact());
		System.out.println("Address is: " + s4.getAddress());
		System.out.println("Gender is: " + s4.getGender());
		System.out.println("Semester is: " + s4.getSemester());
		System.out.println("Grade is: " + s4.getGrade());

		System.out.println("=========================Student Management Details 5=========================");
		System.out.println("Object Reference is: " + s5);
		System.out.println("Student ID is: " + s5.getStudentID());
		System.out.println("Student Name is: " + s5.getStudentName());
		System.out.println("Age is: " + s5.getAge());
		System.out.println("Marks are: " + s5.getMarks());
		System.out.println("Course is: " + s5.getCourse());
		System.out.println("College is: " + s5.getCollege());
		System.out.println("Email is: " + s5.getEmail());
		System.out.println("Contact is: " + s5.getContact());
		System.out.println("Address is: " + s5.getAddress());
		System.out.println("Gender is: " + s5.getGender());
		System.out.println("Semester is: " + s5.getSemester());
		System.out.println("Grade is: " + s5.getGrade());

		System.out.println("=========================Student Management Details 6=========================");
		System.out.println("Object Reference is: " + s6);
		System.out.println("Student ID is: " + s6.getStudentID());
		System.out.println("Student Name is: " + s6.getStudentName());
		System.out.println("Age is: " + s6.getAge());
		System.out.println("Marks are: " + s6.getMarks());
		System.out.println("Course is: " + s6.getCourse());
		System.out.println("College is: " + s6.getCollege());
		System.out.println("Email is: " + s6.getEmail());
		System.out.println("Contact is: " + s6.getContact());
		System.out.println("Address is: " + s6.getAddress());
		System.out.println("Gender is: " + s6.getGender());
		System.out.println("Semester is: " + s6.getSemester());
		System.out.println("Grade is: " + s6.getGrade());

		System.out.println("=========================Student Management Details 7=========================");
		System.out.println("Object Reference is: " + s7);
		System.out.println("Student ID is: " + s7.getStudentID());
		System.out.println("Student Name is: " + s7.getStudentName());
		System.out.println("Age is: " + s7.getAge());
		System.out.println("Marks are: " + s7.getMarks());
		System.out.println("Course is: " + s7.getCourse());
		System.out.println("College is: " + s7.getCollege());
		System.out.println("Email is: " + s7.getEmail());
		System.out.println("Contact is: " + s7.getContact());
		System.out.println("Address is: " + s7.getAddress());
		System.out.println("Gender is: " + s7.getGender());
		System.out.println("Semester is: " + s7.getSemester());
		System.out.println("Grade is: " + s7.getGrade());

		System.out.println("=========================Student Management Details 8=========================");
		System.out.println("Object Reference is: " + s8);
		System.out.println("Student ID is: " + s8.getStudentID());
		System.out.println("Student Name is: " + s8.getStudentName());
		System.out.println("Age is: " + s8.getAge());
		System.out.println("Marks are: " + s8.getMarks());
		System.out.println("Course is: " + s8.getCourse());
		System.out.println("College is: " + s8.getCollege());
		System.out.println("Email is: " + s8.getEmail());
		System.out.println("Contact is: " + s8.getContact());
		System.out.println("Address is: " + s8.getAddress());
		System.out.println("Gender is: " + s8.getGender());
		System.out.println("Semester is: " + s8.getSemester());
		System.out.println("Grade is: " + s8.getGrade());

		System.out.println("=========================Student Management Details 9=========================");
		System.out.println("Object Reference is: " + s9);
		System.out.println("Student ID is: " + s9.getStudentID());
		System.out.println("Student Name is: " + s9.getStudentName());
		System.out.println("Age is: " + s9.getAge());
		System.out.println("Marks are: " + s9.getMarks());
		System.out.println("Course is: " + s9.getCourse());
		System.out.println("College is: " + s9.getCollege());
		System.out.println("Email is: " + s9.getEmail());
		System.out.println("Contact is: " + s9.getContact());
		System.out.println("Address is: " + s9.getAddress());
		System.out.println("Gender is: " + s9.getGender());
		System.out.println("Semester is: " + s9.getSemester());
		System.out.println("Grade is: " + s9.getGrade());

		System.out.println("=========================Student Management Details 10=========================");
		System.out.println("Object Reference is: " + s10);
		System.out.println("Student ID is: " + s10.getStudentID());
		System.out.println("Student Name is: " + s10.getStudentName());
		System.out.println("Age is: " + s10.getAge());
		System.out.println("Marks are: " + s10.getMarks());
		System.out.println("Course is: " + s10.getCourse());
		System.out.println("College is: " + s10.getCollege());
		System.out.println("Email is: " + s10.getEmail());
		System.out.println("Contact is: " + s10.getContact());
		System.out.println("Address is: " + s10.getAddress());
		System.out.println("Gender is: " + s10.getGender());
		System.out.println("Semester is: " + s10.getSemester());
		System.out.println("Grade is: " + s10.getGrade());

		System.out.println("=========================Student Management Details 11=========================");
		System.out.println("Object Reference is: " + s11);
		System.out.println("Student ID is: " + s11.getStudentID());
		System.out.println("Student Name is: " + s11.getStudentName());
		System.out.println("Age is: " + s11.getAge());
		System.out.println("Marks are: " + s11.getMarks());
		System.out.println("Course is: " + s11.getCourse());
		System.out.println("College is: " + s11.getCollege());
		System.out.println("Email is: " + s11.getEmail());
		System.out.println("Contact is: " + s11.getContact());
		System.out.println("Address is: " + s11.getAddress());
		System.out.println("Gender is: " + s11.getGender());
		System.out.println("Semester is: " + s11.getSemester());
		System.out.println("Grade is: " + s11.getGrade());

		System.out.println("=========================Student Management Details 12=========================");
		System.out.println("Object Reference is: " + s12);
		System.out.println("Student ID is: " + s12.getStudentID());
		System.out.println("Student Name is: " + s12.getStudentName());
		System.out.println("Age is: " + s12.getAge());
		System.out.println("Marks are: " + s12.getMarks());
		System.out.println("Course is: " + s12.getCourse());
		System.out.println("College is: " + s12.getCollege());
		System.out.println("Email is: " + s12.getEmail());
		System.out.println("Contact is: " + s12.getContact());
		System.out.println("Address is: " + s12.getAddress());
		System.out.println("Gender is: " + s12.getGender());
		System.out.println("Semester is: " + s12.getSemester());
		System.out.println("Grade is: " + s12.getGrade());

		System.out.println("=========================Student Management Details 13=========================");
		System.out.println("Object Reference is: " + s13);
		System.out.println("Student ID is: " + s13.getStudentID());
		System.out.println("Student Name is: " + s13.getStudentName());
		System.out.println("Age is: " + s13.getAge());
		System.out.println("Marks are: " + s13.getMarks());
		System.out.println("Course is: " + s13.getCourse());
		System.out.println("College is: " + s13.getCollege());
		System.out.println("Email is: " + s13.getEmail());
		System.out.println("Contact is: " + s13.getContact());
		System.out.println("Address is: " + s13.getAddress());
		System.out.println("Gender is: " + s13.getGender());
		System.out.println("Semester is: " + s13.getSemester());
		System.out.println("Grade is: " + s13.getGrade());

		System.out.println("=========================Student Management Details 14=========================");
		System.out.println("Object Reference is: " + s14);
		System.out.println("Student ID is: " + s14.getStudentID());
		System.out.println("Student Name is: " + s14.getStudentName());
		System.out.println("Age is: " + s14.getAge());
		System.out.println("Marks are: " + s14.getMarks());
		System.out.println("Course is: " + s14.getCourse());
		System.out.println("College is: " + s14.getCollege());
		System.out.println("Email is: " + s14.getEmail());
		System.out.println("Contact is: " + s14.getContact());
		System.out.println("Address is: " + s14.getAddress());
		System.out.println("Gender is: " + s14.getGender());
		System.out.println("Semester is: " + s14.getSemester());
		System.out.println("Grade is: " + s14.getGrade());

		System.out.println("=========================Student Management Details 15=========================");
		System.out.println("Object Reference is: " + s15);
		System.out.println("Student ID is: " + s15.getStudentID());
		System.out.println("Student Name is: " + s15.getStudentName());
		System.out.println("Age is: " + s15.getAge());
		System.out.println("Marks are: " + s15.getMarks());
		System.out.println("Course is: " + s15.getCourse());
		System.out.println("College is: " + s15.getCollege());
		System.out.println("Email is: " + s15.getEmail());
		System.out.println("Contact is: " + s15.getContact());
		System.out.println("Address is: " + s15.getAddress());
		System.out.println("Gender is: " + s15.getGender());
		System.out.println("Semester is: " + s15.getSemester());
		System.out.println("Grade is: " + s15.getGrade());

		System.out.println("=========================Student Management Details 16=========================");
		System.out.println("Object Reference is: " + s16);
		System.out.println("Student ID is: " + s16.getStudentID());
		System.out.println("Student Name is: " + s16.getStudentName());
		System.out.println("Age is: " + s16.getAge());
		System.out.println("Marks are: " + s16.getMarks());
		System.out.println("Course is: " + s16.getCourse());
		System.out.println("College is: " + s16.getCollege());
		System.out.println("Email is: " + s16.getEmail());
		System.out.println("Contact is: " + s16.getContact());
		System.out.println("Address is: " + s16.getAddress());
		System.out.println("Gender is: " + s16.getGender());
		System.out.println("Semester is: " + s16.getSemester());
		System.out.println("Grade is: " + s16.getGrade());

		System.out.println("=========================Student Management Details 17=========================");
		System.out.println("Object Reference is: " + s17);
		System.out.println("Student ID is: " + s17.getStudentID());
		System.out.println("Student Name is: " + s17.getStudentName());
		System.out.println("Age is: " + s17.getAge());
		System.out.println("Marks are: " + s17.getMarks());
		System.out.println("Course is: " + s17.getCourse());
		System.out.println("College is: " + s17.getCollege());
		System.out.println("Email is: " + s17.getEmail());
		System.out.println("Contact is: " + s17.getContact());
		System.out.println("Address is: " + s17.getAddress());
		System.out.println("Gender is: " + s17.getGender());
		System.out.println("Semester is: " + s17.getSemester());
		System.out.println("Grade is: " + s17.getGrade());

		System.out.println("=========================Student Management Details 18=========================");
		System.out.println("Object Reference is: " + s18);
		System.out.println("Student ID is: " + s18.getStudentID());
		System.out.println("Student Name is: " + s18.getStudentName());
		System.out.println("Age is: " + s18.getAge());
		System.out.println("Marks are: " + s18.getMarks());
		System.out.println("Course is: " + s18.getCourse());
		System.out.println("College is: " + s18.getCollege());
		System.out.println("Email is: " + s18.getEmail());
		System.out.println("Contact is: " + s18.getContact());
		System.out.println("Address is: " + s18.getAddress());
		System.out.println("Gender is: " + s18.getGender());
		System.out.println("Semester is: " + s18.getSemester());
		System.out.println("Grade is: " + s18.getGrade());

		System.out.println("=========================Student Management Details 19=========================");
		System.out.println("Object Reference is: " + s19);
		System.out.println("Student ID is: " + s19.getStudentID());
		System.out.println("Student Name is: " + s19.getStudentName());
		System.out.println("Age is: " + s19.getAge());
		System.out.println("Marks are: " + s19.getMarks());
		System.out.println("Course is: " + s19.getCourse());
		System.out.println("College is: " + s19.getCollege());
		System.out.println("Email is: " + s19.getEmail());
		System.out.println("Contact is: " + s19.getContact());
		System.out.println("Address is: " + s19.getAddress());
		System.out.println("Gender is: " + s19.getGender());
		System.out.println("Semester is: " + s19.getSemester());
		System.out.println("Grade is: " + s19.getGrade());

		System.out.println("=========================Student Management Details 20=========================");
		System.out.println("Object Reference is: " + s20);
		System.out.println("Student ID is: " + s20.getStudentID());
		System.out.println("Student Name is: " + s20.getStudentName());
		System.out.println("Age is: " + s20.getAge());
		System.out.println("Marks are: " + s20.getMarks());
		System.out.println("Course is: " + s20.getCourse());
		System.out.println("College is: " + s20.getCollege());
		System.out.println("Email is: " + s20.getEmail());
		System.out.println("Contact is: " + s20.getContact());
		System.out.println("Address is: " + s20.getAddress());
		System.out.println("Gender is: " + s20.getGender());
		System.out.println("Semester is: " + s20.getSemester());
		System.out.println("Grade is: " + s20.getGrade());

		System.out.println("=========================Student Management Details 21=========================");
		System.out.println("Object Reference is: " + s21);
		System.out.println("Student ID is: " + s21.getStudentID());
		System.out.println("Student Name is: " + s21.getStudentName());
		System.out.println("Age is: " + s21.getAge());
		System.out.println("Marks are: " + s21.getMarks());
		System.out.println("Course is: " + s21.getCourse());
		System.out.println("College is: " + s21.getCollege());
		System.out.println("Email is: " + s21.getEmail());
		System.out.println("Contact is: " + s21.getContact());
		System.out.println("Address is: " + s21.getAddress());
		System.out.println("Gender is: " + s21.getGender());
		System.out.println("Semester is: " + s21.getSemester());
		System.out.println("Grade is: " + s21.getGrade());

		System.out.println("=========================Student Management Details 22=========================");
		System.out.println("Object Reference is: " + s22);
		System.out.println("Student ID is: " + s22.getStudentID());
		System.out.println("Student Name is: " + s22.getStudentName());
		System.out.println("Age is: " + s22.getAge());
		System.out.println("Marks are: " + s22.getMarks());
		System.out.println("Course is: " + s22.getCourse());
		System.out.println("College is: " + s22.getCollege());
		System.out.println("Email is: " + s22.getEmail());
		System.out.println("Contact is: " + s22.getContact());
		System.out.println("Address is: " + s22.getAddress());
		System.out.println("Gender is: " + s22.getGender());
		System.out.println("Semester is: " + s22.getSemester());
		System.out.println("Grade is: " + s22.getGrade());

		System.out.println("=========================Student Management Details 23=========================");
		System.out.println("Object Reference is: " + s23);
		System.out.println("Student ID is: " + s23.getStudentID());
		System.out.println("Student Name is: " + s23.getStudentName());
		System.out.println("Age is: " + s23.getAge());
		System.out.println("Marks are: " + s23.getMarks());
		System.out.println("Course is: " + s23.getCourse());
		System.out.println("College is: " + s23.getCollege());
		System.out.println("Email is: " + s23.getEmail());
		System.out.println("Contact is: " + s23.getContact());
		System.out.println("Address is: " + s23.getAddress());
		System.out.println("Gender is: " + s23.getGender());
		System.out.println("Semester is: " + s23.getSemester());
		System.out.println("Grade is: " + s23.getGrade());

		System.out.println("=========================Student Management Details 24=========================");
		System.out.println("Object Reference is: " + s24);
		System.out.println("Student ID is: " + s24.getStudentID());
		System.out.println("Student Name is: " + s24.getStudentName());
		System.out.println("Age is: " + s24.getAge());
		System.out.println("Marks are: " + s24.getMarks());
		System.out.println("Course is: " + s24.getCourse());
		System.out.println("College is: " + s24.getCollege());
		System.out.println("Email is: " + s24.getEmail());
		System.out.println("Contact is: " + s24.getContact());
		System.out.println("Address is: " + s24.getAddress());
		System.out.println("Gender is: " + s24.getGender());
		System.out.println("Semester is: " + s24.getSemester());
		System.out.println("Grade is: " + s24.getGrade());

		System.out.println("=========================Student Management Details 25=========================");
		System.out.println("Object Reference is: " + s25);
		System.out.println("Student ID is: " + s25.getStudentID());
		System.out.println("Student Name is: " + s25.getStudentName());
		System.out.println("Age is: " + s25.getAge());
		System.out.println("Marks are: " + s25.getMarks());
		System.out.println("Course is: " + s25.getCourse());
		System.out.println("College is: " + s25.getCollege());
		System.out.println("Email is: " + s25.getEmail());
		System.out.println("Contact is: " + s25.getContact());
		System.out.println("Address is: " + s25.getAddress());
		System.out.println("Gender is: " + s25.getGender());
		System.out.println("Semester is: " + s25.getSemester());
		System.out.println("Grade is: " + s25.getGrade());

		System.out.println("=========================Student Management Details 26=========================");
		System.out.println("Object Reference is: " + s26);
		System.out.println("Student ID is: " + s26.getStudentID());
		System.out.println("Student Name is: " + s26.getStudentName());
		System.out.println("Age is: " + s26.getAge());
		System.out.println("Marks are: " + s26.getMarks());
		System.out.println("Course is: " + s26.getCourse());
		System.out.println("College is: " + s26.getCollege());
		System.out.println("Email is: " + s26.getEmail());
		System.out.println("Contact is: " + s26.getContact());
		System.out.println("Address is: " + s26.getAddress());
		System.out.println("Gender is: " + s26.getGender());
		System.out.println("Semester is: " + s26.getSemester());
		System.out.println("Grade is: " + s26.getGrade());

		System.out.println("=========================Student Management Details 27=========================");
		System.out.println("Object Reference is: " + s27);
		System.out.println("Student ID is: " + s27.getStudentID());
		System.out.println("Student Name is: " + s27.getStudentName());
		System.out.println("Age is: " + s27.getAge());
		System.out.println("Marks are: " + s27.getMarks());
		System.out.println("Course is: " + s27.getCourse());
		System.out.println("College is: " + s27.getCollege());
		System.out.println("Email is: " + s27.getEmail());
		System.out.println("Contact is: " + s27.getContact());
		System.out.println("Address is: " + s27.getAddress());
		System.out.println("Gender is: " + s27.getGender());
		System.out.println("Semester is: " + s27.getSemester());
		System.out.println("Grade is: " + s27.getGrade());

		System.out.println("=========================Student Management Details 28=========================");
		System.out.println("Object Reference is: " + s28);
		System.out.println("Student ID is: " + s28.getStudentID());
		System.out.println("Student Name is: " + s28.getStudentName());
		System.out.println("Age is: " + s28.getAge());
		System.out.println("Marks are: " + s28.getMarks());
		System.out.println("Course is: " + s28.getCourse());
		System.out.println("College is: " + s28.getCollege());
		System.out.println("Email is: " + s28.getEmail());
		System.out.println("Contact is: " + s28.getContact());
		System.out.println("Address is: " + s28.getAddress());
		System.out.println("Gender is: " + s28.getGender());
		System.out.println("Semester is: " + s28.getSemester());
		System.out.println("Grade is: " + s28.getGrade());

		System.out.println("=========================Student Management Details 29=========================");
		System.out.println("Object Reference is: " + s29);
		System.out.println("Student ID is: " + s29.getStudentID());
		System.out.println("Student Name is: " + s29.getStudentName());
		System.out.println("Age is: " + s29.getAge());
		System.out.println("Marks are: " + s29.getMarks());
		System.out.println("Course is: " + s29.getCourse());
		System.out.println("College is: " + s29.getCollege());
		System.out.println("Email is: " + s29.getEmail());
		System.out.println("Contact is: " + s29.getContact());
		System.out.println("Address is: " + s29.getAddress());
		System.out.println("Gender is: " + s29.getGender());
		System.out.println("Semester is: " + s29.getSemester());
		System.out.println("Grade is: " + s29.getGrade());

		System.out.println("=========================Student Management Details 30=========================");
		System.out.println("Object Reference is: " + s30);
		System.out.println("Student ID is: " + s30.getStudentID());
		System.out.println("Student Name is: " + s30.getStudentName());
		System.out.println("Age is: " + s30.getAge());
		System.out.println("Marks are: " + s30.getMarks());
		System.out.println("Course is: " + s30.getCourse());
		System.out.println("College is: " + s30.getCollege());
		System.out.println("Email is: " + s30.getEmail());
		System.out.println("Contact is: " + s30.getContact());
		System.out.println("Address is: " + s30.getAddress());
		System.out.println("Gender is: " + s30.getGender());
		System.out.println("Semester is: " + s30.getSemester());
		System.out.println("Grade is: " + s30.getGrade());

		System.out.println("=========================Student Management Details 31=========================");
		System.out.println("Object Reference is: " + s31);
		System.out.println("Student ID is: " + s31.getStudentID());
		System.out.println("Student Name is: " + s31.getStudentName());
		System.out.println("Age is: " + s31.getAge());
		System.out.println("Marks are: " + s31.getMarks());
		System.out.println("Course is: " + s31.getCourse());
		System.out.println("College is: " + s31.getCollege());
		System.out.println("Email is: " + s31.getEmail());
		System.out.println("Contact is: " + s31.getContact());
		System.out.println("Address is: " + s31.getAddress());
		System.out.println("Gender is: " + s31.getGender());
		System.out.println("Semester is: " + s31.getSemester());
		System.out.println("Grade is: " + s31.getGrade());

		System.out.println("=========================Student Management Details 32=========================");
		System.out.println("Object Reference is: " + s32);
		System.out.println("Student ID is: " + s32.getStudentID());
		System.out.println("Student Name is: " + s32.getStudentName());
		System.out.println("Age is: " + s32.getAge());
		System.out.println("Marks are: " + s32.getMarks());
		System.out.println("Course is: " + s32.getCourse());
		System.out.println("College is: " + s32.getCollege());
		System.out.println("Email is: " + s32.getEmail());
		System.out.println("Contact is: " + s32.getContact());
		System.out.println("Address is: " + s32.getAddress());
		System.out.println("Gender is: " + s32.getGender());
		System.out.println("Semester is: " + s32.getSemester());
		System.out.println("Grade is: " + s32.getGrade());

		System.out.println("=========================Student Management Details 33=========================");
		System.out.println("Object Reference is: " + s33);
		System.out.println("Student ID is: " + s33.getStudentID());
		System.out.println("Student Name is: " + s33.getStudentName());
		System.out.println("Age is: " + s33.getAge());
		System.out.println("Marks are: " + s33.getMarks());
		System.out.println("Course is: " + s33.getCourse());
		System.out.println("College is: " + s33.getCollege());
		System.out.println("Email is: " + s33.getEmail());
		System.out.println("Contact is: " + s33.getContact());
		System.out.println("Address is: " + s33.getAddress());
		System.out.println("Gender is: " + s33.getGender());
		System.out.println("Semester is: " + s33.getSemester());
		System.out.println("Grade is: " + s33.getGrade());

		System.out.println("=========================Student Management Details 34=========================");
		System.out.println("Object Reference is: " + s34);
		System.out.println("Student ID is: " + s34.getStudentID());
		System.out.println("Student Name is: " + s34.getStudentName());
		System.out.println("Age is: " + s34.getAge());
		System.out.println("Marks are: " + s34.getMarks());
		System.out.println("Course is: " + s34.getCourse());
		System.out.println("College is: " + s34.getCollege());
		System.out.println("Email is: " + s34.getEmail());
		System.out.println("Contact is: " + s34.getContact());
		System.out.println("Address is: " + s34.getAddress());
		System.out.println("Gender is: " + s34.getGender());
		System.out.println("Semester is: " + s34.getSemester());
		System.out.println("Grade is: " + s34.getGrade());

		System.out.println("=========================Student Management Details 35=========================");
		System.out.println("Object Reference is: " + s35);
		System.out.println("Student ID is: " + s35.getStudentID());
		System.out.println("Student Name is: " + s35.getStudentName());
		System.out.println("Age is: " + s35.getAge());
		System.out.println("Marks are: " + s35.getMarks());
		System.out.println("Course is: " + s35.getCourse());
		System.out.println("College is: " + s35.getCollege());
		System.out.println("Email is: " + s35.getEmail());
		System.out.println("Contact is: " + s35.getContact());
		System.out.println("Address is: " + s35.getAddress());
		System.out.println("Gender is: " + s35.getGender());
		System.out.println("Semester is: " + s35.getSemester());
		System.out.println("Grade is: " + s35.getGrade());

		System.out.println("=========================Student Management Details 36=========================");
		System.out.println("Object Reference is: " + s36);
		System.out.println("Student ID is: " + s36.getStudentID());
		System.out.println("Student Name is: " + s36.getStudentName());
		System.out.println("Age is: " + s36.getAge());
		System.out.println("Marks are: " + s36.getMarks());
		System.out.println("Course is: " + s36.getCourse());
		System.out.println("College is: " + s36.getCollege());
		System.out.println("Email is: " + s36.getEmail());
		System.out.println("Contact is: " + s36.getContact());
		System.out.println("Address is: " + s36.getAddress());
		System.out.println("Gender is: " + s36.getGender());
		System.out.println("Semester is: " + s36.getSemester());
		System.out.println("Grade is: " + s36.getGrade());

		System.out.println("=========================Student Management Details 37=========================");
		System.out.println("Object Reference is: " + s37);
		System.out.println("Student ID is: " + s37.getStudentID());
		System.out.println("Student Name is: " + s37.getStudentName());
		System.out.println("Age is: " + s37.getAge());
		System.out.println("Marks are: " + s37.getMarks());
		System.out.println("Course is: " + s37.getCourse());
		System.out.println("College is: " + s37.getCollege());
		System.out.println("Email is: " + s37.getEmail());
		System.out.println("Contact is: " + s37.getContact());
		System.out.println("Address is: " + s37.getAddress());
		System.out.println("Gender is: " + s37.getGender());
		System.out.println("Semester is: " + s37.getSemester());
		System.out.println("Grade is: " + s37.getGrade());

		System.out.println("=========================Student Management Details 38=========================");
		System.out.println("Object Reference is: " + s38);
		System.out.println("Student ID is: " + s38.getStudentID());
		System.out.println("Student Name is: " + s38.getStudentName());
		System.out.println("Age is: " + s38.getAge());
		System.out.println("Marks are: " + s38.getMarks());
		System.out.println("Course is: " + s38.getCourse());
		System.out.println("College is: " + s38.getCollege());
		System.out.println("Email is: " + s38.getEmail());
		System.out.println("Contact is: " + s38.getContact());
		System.out.println("Address is: " + s38.getAddress());
		System.out.println("Gender is: " + s38.getGender());
		System.out.println("Semester is: " + s38.getSemester());
		System.out.println("Grade is: " + s38.getGrade());

		System.out.println("=========================Student Management Details 39=========================");
		System.out.println("Object Reference is: " + s39);
		System.out.println("Student ID is: " + s39.getStudentID());
		System.out.println("Student Name is: " + s39.getStudentName());
		System.out.println("Age is: " + s39.getAge());
		System.out.println("Marks are: " + s39.getMarks());
		System.out.println("Course is: " + s39.getCourse());
		System.out.println("College is: " + s39.getCollege());
		System.out.println("Email is: " + s39.getEmail());
		System.out.println("Contact is: " + s39.getContact());
		System.out.println("Address is: " + s39.getAddress());
		System.out.println("Gender is: " + s39.getGender());
		System.out.println("Semester is: " + s39.getSemester());
		System.out.println("Grade is: " + s39.getGrade());

		System.out.println("=========================Student Management Details 40=========================");
		System.out.println("Object Reference is: " + s40);
		System.out.println("Student ID is: " + s40.getStudentID());
		System.out.println("Student Name is: " + s40.getStudentName());
		System.out.println("Age is: " + s40.getAge());
		System.out.println("Marks are: " + s40.getMarks());
		System.out.println("Course is: " + s40.getCourse());
		System.out.println("College is: " + s40.getCollege());
		System.out.println("Email is: " + s40.getEmail());
		System.out.println("Contact is: " + s40.getContact());
		System.out.println("Address is: " + s40.getAddress());
		System.out.println("Gender is: " + s40.getGender());
		System.out.println("Semester is: " + s40.getSemester());
		System.out.println("Grade is: " + s40.getGrade());
		
	}

}
