package constructor.deepCopy.Game;

public class GameDriver {
	
	public static void main(String[] args) {
		
		System.out.println("==================================Main Method Starts======================================");
		
		Game p1 = new Game("Cricket 24", "Sports", 4999, "PlayStation", new Player(101, "Virat", 35, "India", 1.5, "Royal Challengers"));
		Game p2 = new Game("FIFA 24", "Football", 5999, "PC", new Player(102, "Lionel", 36, "Argentina", 2.1, "Inter Miami"));
		Game p3 = new Game("WWE 2K24", "Wrestling", 5499, "Xbox", new Player(103, "John Cena", 47, "USA", 3.2, "WWE"));
		Game p4 = new Game("NBA 2K24", "Basketball", 5799, "PlayStation", new Player(104, "LeBron James", 39, "USA", 1.8, "Lakers"));
		Game p5 = new Game("Tennis World", "Tennis", 3999, "PC", new Player(105, "Novak Djokovic", 37, "Serbia", 1.2, "Serbia"));
		Game p6 = new Game("Hockey Pro", "Hockey", 4299, "Xbox", new Player(106, "Manpreet Singh", 32, "India", 4.5, "India"));
		Game p7 = new Game("Rugby Challenge", "Rugby", 4599, "PlayStation", new Player(107, "Antoine Dupont", 28, "France", 2.4, "France"));
		Game p8 = new Game("Formula Racing", "Racing", 6499, "PC", new Player(108, "Lewis Hamilton", 41, "UK", 1.7, "Ferrari"));
		Game p9 = new Game("Moto GP 24", "Racing", 6299, "Xbox", new Player(109, "Marc Marquez", 33, "Spain", 2.6, "Ducati"));
		Game p10 = new Game("Boxing Champion", "Boxing", 4799, "PlayStation", new Player(110, "Mike Tyson", 59, "USA", 5.1, "USA"));
		Game p11 = new Game("Cricket World", "Cricket", 5199, "PC", new Player(111, "Rohit Sharma", 39, "India", 2.3, "Mumbai Indians"));
		Game p12 = new Game("Football Stars", "Football", 6099, "PlayStation", new Player(112, "Cristiano Ronaldo", 41, "Portugal", 1.1, "Al Nassr"));
		Game p13 = new Game("Basketball League", "Basketball", 5899, "Xbox", new Player(113, "Stephen Curry", 38, "USA", 2.0, "Warriors"));
		Game p14 = new Game("Tennis Masters", "Tennis", 4199, "PC", new Player(114, "Carlos Alcaraz", 23, "Spain", 1.4, "Spain"));
		Game p15 = new Game("Hockey Stars", "Hockey", 4399, "PlayStation", new Player(115, "Harmanpreet Singh", 30, "India", 3.7, "India"));
		Game p16 = new Game("Golf Pro", "Golf", 3699, "Xbox", new Player(116, "Tiger Woods", 50, "USA", 4.2, "USA"));
		Game p17 = new Game("Baseball Pro", "Baseball", 4499, "PC", new Player(117, "Shohei Ohtani", 32, "Japan", 1.6, "Dodgers"));
		Game p18 = new Game("Volleyball Stars", "Volleyball", 3899, "PlayStation", new Player(118, "Yuji Nishida", 30, "Japan", 3.9, "Japan"));
		Game p19 = new Game("Badminton World", "Badminton", 3599, "PC", new Player(119, "Lakshya Sen", 24, "India", 6.3, "India"));
		Game p20 = new Game("Chess Master", "Chess", 2999, "Xbox", new Player(120, "Magnus Carlsen", 35, "Norway", 1.0, "Norway"));
		Game p21 = new Game("Kabaddi Pro", "Kabaddi", 3299, "PlayStation", new Player(121, "Pardeep Narwal", 29, "India", 5.4, "Patna Pirates"));
		Game p22 = new Game("Swimming Challenge", "Swimming", 3799, "PC", new Player(122, "Caeleb Dressel", 29, "USA", 3.5, "USA"));
		Game p23 = new Game("Athletics Pro", "Athletics", 4099, "Xbox", new Player(123, "Neeraj Chopra", 28, "India", 1.3, "India"));
		Game p24 = new Game("Wrestling Arena", "Wrestling", 4899, "PlayStation", new Player(124, "Bajrang Punia", 32, "India", 4.8, "India"));
		Game p25 = new Game("Archery Master", "Archery", 3199, "PC", new Player(125, "Deepika Kumari", 32, "India", 3.6, "India"));
		Game p26 = new Game("Table Tennis Pro", "Table Tennis", 3499, "Xbox", new Player(126, "Manika Batra", 31, "India", 7.2, "India"));
		Game p27 = new Game("Boxing World", "Boxing", 4699, "PlayStation", new Player(127, "Muhammad Ali", 74, "USA", 2.9, "USA"));
		Game p28 = new Game("Cricket Legends", "Cricket", 5599, "PC", new Player(128, "MS Dhoni", 45, "India", 1.9, "Chennai Super Kings"));
		Game p29 = new Game("Football Legends", "Football", 5799, "Xbox", new Player(129, "Kylian Mbappe", 27, "France", 1.5, "Real Madrid"));
		Game p30 = new Game("NBA Legends", "Basketball", 6199, "PlayStation", new Player(130, "Michael Jordan", 63, "USA", 1.0, "Bulls"));
		Game p31 = new Game("Tennis Legends", "Tennis", 4299, "PC", new Player(131, "Roger Federer", 45, "Switzerland", 1.7, "Switzerland"));
		Game p32 = new Game("Racing Legends", "Racing", 6599, "Xbox", new Player(132, "Michael Schumacher", 57, "Germany", 1.4, "Ferrari"));
		Game p33 = new Game("Hockey Champions", "Hockey", 4499, "PlayStation", new Player(133, "Dhanraj Pillay", 57, "India", 4.1, "India"));
		Game p34 = new Game("Golf Masters", "Golf", 3999, "PC", new Player(134, "Rory McIlroy", 37, "Ireland", 2.5, "Ireland"));
		Game p35 = new Game("Baseball Legends", "Baseball", 4599, "Xbox", new Player(135, "Babe Ruth", 53, "USA", 1.9, "Yankees"));
		Game p36 = new Game("Volleyball Pro", "Volleyball", 3699, "PlayStation", new Player(136, "Karch Kiraly", 65, "USA", 3.8, "USA"));
		Game p37 = new Game("Badminton Champions", "Badminton", 3799, "PC", new Player(137, "PV Sindhu", 31, "India", 2.8, "India"));
		Game p38 = new Game("Chess Grandmaster", "Chess", 3099, "Xbox", new Player(138, "Viswanathan Anand", 57, "India", 1.3, "India"));
		Game p39 = new Game("Kabaddi Champions", "Kabaddi", 3399, "PlayStation", new Player(139, "Rahul Chaudhari", 32, "India", 4.6, "Telugu Titans"));
		Game p40 = new Game("Swimming Pro", "Swimming", 3899, "PC", new Player(140, "Michael Phelps", 41, "USA", 1.2, "USA"));
		Game p41 = new Game("Athletics Champions", "Athletics", 4199, "Xbox", new Player(141, "Usain Bolt", 40, "Jamaica", 1.0, "Jamaica"));
		Game p42 = new Game("Wrestling Champions", "Wrestling", 4999, "PlayStation", new Player(142, "Sushil Kumar", 43, "India", 3.4, "India"));
		Game p43 = new Game("Archery Pro", "Archery", 3299, "PC", new Player(143, "Atanu Das", 34, "India", 5.2, "India"));
		Game p44 = new Game("Table Tennis Masters", "Table Tennis", 3599, "Xbox", new Player(144, "Sharath Kamal", 44, "India", 6.1, "India"));
		Game p45 = new Game("Boxing Legends", "Boxing", 4799, "PlayStation", new Player(145, "Floyd Mayweather", 49, "USA", 1.1, "USA"));
		Game p46 = new Game("Cricket Champions", "Cricket", 5299, "PC", new Player(146, "Jasprit Bumrah", 32, "India", 1.6, "Mumbai Indians"));
		Game p47 = new Game("Football Champions", "Football", 5899, "Xbox", new Player(147, "Neymar", 34, "Brazil", 2.2, "Santos"));
		Game p48 = new Game("Basketball Champions", "Basketball", 5999, "PlayStation", new Player(148, "Kevin Durant", 38, "USA", 2.7, "Suns"));
		Game p49 = new Game("Tennis Champions", "Tennis", 4399, "PC", new Player(149, "Rafael Nadal", 40, "Spain", 1.8, "Spain"));
		Game p50 = new Game("Racing Champions", "Racing", 6699, "Xbox", new Player(150, "Max Verstappen", 29, "Netherlands", 1.2, "Red Bull"));
		Game p51 = new Game(p1);
		Game p52 = new Game(p2);
		Game p53 = new Game(p3);
		Game p54 = new Game(p4);
		Game p55 = new Game(p5);
		Game p56 = new Game(p6);
		Game p57 = new Game(p7);
		Game p58 = new Game(p8);
		Game p59 = new Game(p9);
		Game p60 = new Game(p10);
		Game p61 = new Game(p11);
		Game p62 = new Game(p12);
		Game p63 = new Game(p13);
		Game p64 = new Game(p14);
		Game p65 = new Game(p15);
		Game p66 = new Game(p16);
		Game p67 = new Game(p17);
		Game p68 = new Game(p18);
		Game p69 = new Game(p19);
		Game p70 = new Game(p20);
		Game p71 = new Game(p21);
		Game p72 = new Game(p22);
		Game p73 = new Game(p23);
		Game p74 = new Game(p24);
		Game p75 = new Game(p25);
		Game p76 = new Game(p26);
		Game p77 = new Game(p27);
		Game p78 = new Game(p28);
		Game p79 = new Game(p29);
		Game p80 = new Game(p30);
		Game p81 = new Game(p31);
		Game p82 = new Game(p32);
		Game p83 = new Game(p33);
		Game p84 = new Game(p34);
		Game p85 = new Game(p35);
		Game p86 = new Game(p36);
		Game p87 = new Game(p37);
		Game p88 = new Game(p38);
		Game p89 = new Game(p39);
		Game p90 = new Game(p40);
		
		System.out.println(p1);
		System.out.println(p2);
		System.out.println(p3);
		System.out.println(p4);
		System.out.println(p5);
		System.out.println(p6);
		System.out.println(p7);
		System.out.println(p8);
		System.out.println(p9);
		System.out.println(p10);
		System.out.println(p11);
		System.out.println(p12);
		System.out.println(p13);
		System.out.println(p14);
		System.out.println(p15);
		System.out.println(p16);
		System.out.println(p17);
		System.out.println(p18);
		System.out.println(p19);
		System.out.println(p20);
		System.out.println(p21);
		System.out.println(p22);
		System.out.println(p23);
		System.out.println(p24);
		System.out.println(p25);
		System.out.println(p26);
		System.out.println(p27);
		System.out.println(p28);
		System.out.println(p29);
		System.out.println(p30);
		System.out.println(p31);
		System.out.println(p32);
		System.out.println(p33);
		System.out.println(p34);
		System.out.println(p35);
		System.out.println(p36);
		System.out.println(p37);
		System.out.println(p38);
		System.out.println(p39);
		System.out.println(p40);
		System.out.println(p41);
		System.out.println(p42);
		System.out.println(p43);
		System.out.println(p44);
		System.out.println(p45);
		System.out.println(p46);
		System.out.println(p47);
		System.out.println(p48);
		System.out.println(p49);
		System.out.println(p50);
		System.out.println(p51);
		System.out.println(p52);
		System.out.println(p53);
		System.out.println(p54);
		System.out.println(p55);
		System.out.println(p56);
		System.out.println(p57);
		System.out.println(p58);
		System.out.println(p59);
		System.out.println(p60);
		System.out.println(p61);
		System.out.println(p62);
		System.out.println(p63);
		System.out.println(p64);
		System.out.println(p65);
		System.out.println(p66);
		System.out.println(p67);
		System.out.println(p68);
		System.out.println(p69);
		System.out.println(p70);
		System.out.println(p71);
		System.out.println(p72);
		System.out.println(p73);
		System.out.println(p74);
		System.out.println(p75);
		System.out.println(p76);
		System.out.println(p77);
		System.out.println(p78);
		System.out.println(p79);
		System.out.println(p80);
		System.out.println(p81);
		System.out.println(p82);
		System.out.println(p83);
		System.out.println(p84);
		System.out.println(p85);
		System.out.println(p86);
		System.out.println(p87);
		System.out.println(p88);
		System.out.println(p89);
		System.out.println(p90);
		
		System.out.println("========================================Main Method Ends========================================");
	}

}
