package constructor.deepCopy.Book;

public class BookDriver {

	public static void main(String[] args) {
		
		System.out.println("===============================Main Method Starts=================================");
		
		Book b1 = new Book("Java Programming", "Mc Graw Hill", 850, "English", new Author(101, "Mohan Singh", 35, "Male", "Indian", "Java Programming"));
		Book b2 = new Book("Python Programming", "Pearson", 750, "English", new Author(102, "Rahul Sharma", 32, "Male", "Indian", "Python Programming"));
		Book b3 = new Book("Web Development", "O'Reilly", 950, "English", new Author(103, "Anita Verma", 30, "Female", "Indian", "Web Development"));
		Book b4 = new Book("JavaScript Basics", "Wiley", 650, "English", new Author(104, "Amit Kumar", 38, "Male", "Indian", "JavaScript"));
		Book b5 = new Book("Data Structures", "Pearson", 900, "English", new Author(105, "Priya Singh", 34, "Female", "Indian", "Data Structures"));
		Book b6 = new Book("Database Management", "Mc Graw Hill", 800, "English", new Author(106, "Ravi Gupta", 40, "Male", "Indian", "Database Management"));
		Book b7 = new Book("Operating System", "Oxford", 700, "English", new Author(107, "Neha Sharma", 29, "Female", "Indian", "Operating System"));
		Book b8 = new Book("Computer Networks", "Pearson", 880, "English", new Author(108, "Vikas Yadav", 36, "Male", "Indian", "Computer Networks"));
		Book b9 = new Book("Software Testing", "Wiley", 780, "English", new Author(109, "Pooja Mishra", 31, "Female", "Indian", "Software Testing"));
		Book b10 = new Book("Selenium Automation", "Packt", 990, "English", new Author(110, "Arun Singh", 37, "Male", "Indian", "Selenium Automation"));

		Book b11 = new Book("Java Advanced", "Mc Graw Hill", 1050, "English", new Author(111, "Suresh Kumar", 42, "Male", "Indian", "Advanced Java"));
		Book b12 = new Book("Spring Framework", "Apress", 1150, "English", new Author(112, "Kavita Rao", 39, "Female", "Indian", "Spring Framework"));
		Book b13 = new Book("Hibernate", "Manning", 1200, "English", new Author(113, "Rajesh Verma", 44, "Male", "Indian", "Hibernate"));
		Book b14 = new Book("C Programming", "Pearson", 600, "English", new Author(114, "Sunita Sharma", 33, "Female", "Indian", "C Programming"));
		Book b15 = new Book("C++ Programming", "Wiley", 850, "English", new Author(115, "Manoj Singh", 41, "Male", "Indian", "C++ Programming"));
		Book b16 = new Book("HTML and CSS", "O'Reilly", 550, "English", new Author(116, "Ritu Gupta", 28, "Female", "Indian", "HTML and CSS"));
		Book b17 = new Book("React Development", "Packt", 1100, "English", new Author(117, "Deepak Kumar", 35, "Male", "Indian", "React Development"));
		Book b18 = new Book("Angular Development", "Apress", 1000, "English", new Author(118, "Shweta Singh", 32, "Female", "Indian", "Angular Development"));
		Book b19 = new Book("Node.js Guide", "Wiley", 950, "English", new Author(119, "Nitin Sharma", 34, "Male", "Indian", "Node.js"));
		Book b20 = new Book("SQL Programming", "Pearson", 720, "English", new Author(120, "Meena Verma", 37, "Female", "Indian", "SQL Programming"));

		Book b21 = new Book("Artificial Intelligence", "Mc Graw Hill", 1300, "English", new Author(121, "Vivek Singh", 45, "Male", "Indian", "Artificial Intelligence"));
		Book b22 = new Book("Machine Learning", "Springer", 1450, "English", new Author(122, "Anjali Sharma", 36, "Female", "Indian", "Machine Learning"));
		Book b23 = new Book("Deep Learning", "MIT Press", 1550, "English", new Author(123, "Rohan Gupta", 39, "Male", "Indian", "Deep Learning"));
		Book b24 = new Book("Cloud Computing", "Pearson", 1250, "English", new Author(124, "Nisha Kumar", 31, "Female", "Indian", "Cloud Computing"));
		Book b25 = new Book("DevOps Handbook", "O'Reilly", 1350, "English", new Author(125, "Abhishek Verma", 40, "Male", "Indian", "DevOps"));
		Book b26 = new Book("Git and GitHub", "Packt", 650, "English", new Author(126, "Sakshi Singh", 27, "Female", "Indian", "Git and GitHub"));
		Book b27 = new Book("Jenkins Automation", "Apress", 900, "English", new Author(127, "Gaurav Sharma", 38, "Male", "Indian", "Jenkins"));
		Book b28 = new Book("Maven Guide", "Wiley", 750, "English", new Author(128, "Komal Gupta", 29, "Female", "Indian", "Maven"));
		Book b29 = new Book("TestNG Framework", "Packt", 850, "English", new Author(129, "Rakesh Kumar", 35, "Male", "Indian", "TestNG"));
		Book b30 = new Book("Automation Testing", "Pearson", 1000, "English", new Author(130, "Priyanka Verma", 33, "Female", "Indian", "Automation Testing"));

		Book b31 = new Book("Manual Testing", "Mc Graw Hill", 700, "English", new Author(131, "Ajay Singh", 43, "Male", "Indian", "Manual Testing"));
		Book b32 = new Book("Software Engineering", "Oxford", 900, "English", new Author(132, "Pallavi Sharma", 37, "Female", "Indian", "Software Engineering"));
		Book b33 = new Book("OOP in Java", "Pearson", 850, "English", new Author(133, "Karan Gupta", 30, "Male", "Indian", "Object Oriented Programming"));
		Book b34 = new Book("Java Constructors", "Wiley", 600, "English", new Author(134, "Neelam Singh", 35, "Female", "Indian", "Java Constructors"));
		Book b35 = new Book("Java Inheritance", "Packt", 680, "English", new Author(135, "Harish Kumar", 42, "Male", "Indian", "Java Inheritance"));
		Book b36 = new Book("Java Polymorphism", "Apress", 720, "English", new Author(136, "Reena Sharma", 34, "Female", "Indian", "Java Polymorphism"));
		Book b37 = new Book("Java Abstraction", "Pearson", 690, "English", new Author(137, "Mohit Verma", 31, "Male", "Indian", "Java Abstraction"));
		Book b38 = new Book("Java Encapsulation", "Wiley", 640, "English", new Author(138, "Rashmi Gupta", 28, "Female", "Indian", "Java Encapsulation"));
		Book b39 = new Book("Java Collections", "Mc Graw Hill", 980, "English", new Author(139, "Sanjay Singh", 40, "Male", "Indian", "Java Collections"));
		Book b40 = new Book("Java Multithreading", "Pearson", 920, "English", new Author(140, "Nandini Rao", 36, "Female", "Indian", "Java Multithreading"));

		Book b41 = new Book("Java Exception Handling", "Wiley", 650, "English", new Author(141, "Vijay Kumar", 39, "Male", "Indian", "Exception Handling"));
		Book b42 = new Book("Java File Handling", "Packt", 700, "English", new Author(142, "Swati Sharma", 32, "Female", "Indian", "File Handling"));
		Book b43 = new Book("Java JDBC", "Apress", 800, "English", new Author(143, "Rohit Gupta", 35, "Male", "Indian", "JDBC"));
		Book b44 = new Book("Java Servlets", "Pearson", 880, "English", new Author(144, "Preeti Singh", 30, "Female", "Indian", "Java Servlets"));
		Book b45 = new Book("JSP Programming", "Wiley", 950, "English", new Author(145, "Ashok Verma", 44, "Male", "Indian", "JSP"));
		Book b46 = new Book("REST API Development", "O'Reilly", 1050, "English", new Author(146, "Shalini Gupta", 33, "Female", "Indian", "REST API"));
		Book b47 = new Book("Microservices", "Springer", 1400, "English", new Author(147, "Tarun Kumar", 41, "Male", "Indian", "Microservices"));
		Book b48 = new Book("Selenium WebDriver", "Packt", 1150, "English", new Author(148, "Divya Sharma", 29, "Female", "Indian", "Selenium WebDriver"));
		Book b49 = new Book("Test Automation", "Pearson", 1050, "English", new Author(149, "Anil Singh", 38, "Male", "Indian", "Test Automation"));
		Book b50 = new Book("Java Selenium", "Mc Graw Hill", 1250, "English", new Author(150, "Monika Verma", 34, "Female", "Indian", "Java Selenium"));
		Book b51 = new Book(b1);
		Book b52 = new Book(b2);
		Book b53 = new Book(b3);
		Book b54 = new Book(b4);
		Book b55 = new Book(b5);
		Book b56 = new Book(b6);
		Book b57 = new Book(b7);
		Book b58 = new Book(b8);
		Book b59 = new Book(b9);
		Book b60 = new Book(b10);
		Book b61 = new Book(b11);
		Book b62 = new Book(b12);
		Book b63 = new Book(b13);
		Book b64 = new Book(b14);
		Book b65 = new Book(b15);
		Book b66 = new Book(b16);
		Book b67 = new Book(b17);
		Book b68 = new Book(b18);
		Book b69 = new Book(b19);
		Book b70 = new Book(b20);
		Book b71 = new Book(b21);
		Book b72 = new Book(b22);
		Book b73 = new Book(b23);
		Book b74 = new Book(b24);
		Book b75 = new Book(b25);
		Book b76 = new Book(b26);
		Book b77 = new Book(b27);
		Book b78 = new Book(b28);
		Book b79 = new Book(b29);
		Book b80 = new Book(b30);
		Book b81 = new Book(b31);
		Book b82 = new Book(b32);
		Book b83 = new Book(b33);
		Book b84 = new Book(b34);
		Book b85 = new Book(b35);
		Book b86 = new Book(b36);
		Book b87 = new Book(b37);
		Book b88 = new Book(b38);
		Book b89 = new Book(b39);
		Book b90 = new Book(b40);
		
		System.out.println(b1);
		System.out.println(b2);
		System.out.println(b3);
		System.out.println(b4);
		System.out.println(b5);
		System.out.println(b6);
		System.out.println(b7);
		System.out.println(b8);
		System.out.println(b9);
		System.out.println(b10);
		System.out.println(b11);
		System.out.println(b12);
		System.out.println(b13);
		System.out.println(b14);
		System.out.println(b15);
		System.out.println(b16);
		System.out.println(b17);
		System.out.println(b18);
		System.out.println(b19);
		System.out.println(b20);
		System.out.println(b21);
		System.out.println(b22);
		System.out.println(b23);
		System.out.println(b24);
		System.out.println(b25);
		System.out.println(b26);
		System.out.println(b27);
		System.out.println(b28);
		System.out.println(b29);
		System.out.println(b30);
		System.out.println(b31);
		System.out.println(b32);
		System.out.println(b33);
		System.out.println(b34);
		System.out.println(b35);
		System.out.println(b36);
		System.out.println(b37);
		System.out.println(b38);
		System.out.println(b39);
		System.out.println(b40);
		System.out.println(b41);
		System.out.println(b42);
		System.out.println(b43);
		System.out.println(b44);
		System.out.println(b45);
		System.out.println(b46);
		System.out.println(b47);
		System.out.println(b48);
		System.out.println(b49);
		System.out.println(b50);
		System.out.println(b51);
		System.out.println(b52);
		System.out.println(b53);
		System.out.println(b54);
		System.out.println(b55);
		System.out.println(b56);
		System.out.println(b57);
		System.out.println(b58);
		System.out.println(b59);
		System.out.println(b60);
		System.out.println(b61);
		System.out.println(b62);
		System.out.println(b63);
		System.out.println(b64);
		System.out.println(b65);
		System.out.println(b66);
		System.out.println(b67);
		System.out.println(b68);
		System.out.println(b69);
		System.out.println(b70);
		System.out.println(b71);
		System.out.println(b72);
		System.out.println(b73);
		System.out.println(b74);
		System.out.println(b75);
		System.out.println(b76);
		System.out.println(b77);
		System.out.println(b78);
		System.out.println(b79);
		System.out.println(b80);
		System.out.println(b81);
		System.out.println(b82);
		System.out.println(b83);
		System.out.println(b84);
		System.out.println(b85);
		System.out.println(b86);
		System.out.println(b87);
		System.out.println(b88);
		System.out.println(b89);
		System.out.println(b90);
		
		System.out.println("======================================Main Method Ends=========================================");
	}

}
