package methodChaining;

public class ResumeBuilderDriver {

	public static void main(String[] args) {

		ResumeBuilder r1 = new ResumeBuilder();
		ResumeBuilder r2 = new ResumeBuilder();
		ResumeBuilder r3 = new ResumeBuilder();
		ResumeBuilder r4 = new ResumeBuilder();
		ResumeBuilder r5 = new ResumeBuilder();
		ResumeBuilder r6 = new ResumeBuilder();
		ResumeBuilder r7 = new ResumeBuilder();
		ResumeBuilder r8 = new ResumeBuilder();
		ResumeBuilder r9 = new ResumeBuilder();
		ResumeBuilder r10 = new ResumeBuilder();
		ResumeBuilder r11 = new ResumeBuilder();
		ResumeBuilder r12 = new ResumeBuilder();
		ResumeBuilder r13 = new ResumeBuilder();
		ResumeBuilder r14 = new ResumeBuilder();
		ResumeBuilder r15 = new ResumeBuilder();
		ResumeBuilder r16 = new ResumeBuilder();
		ResumeBuilder r17 = new ResumeBuilder();
		ResumeBuilder r18 = new ResumeBuilder();
		ResumeBuilder r19 = new ResumeBuilder();
		ResumeBuilder r20 = new ResumeBuilder();

		r1.setFullName("Arunendra Pratap Singh").setAge(32).setGender("Male").setEmail("aruprasin123@gmail.com").setPhoneNumber("9876543210").setAddress("Lucknow, Uttar Pradesh").setCareerObjective("To build a successful career in Software Testing and Automation").setHighestQualification("MA Economics").setUniversityName("Lucknow University").setGraduationYear("2016").setPercentage(75.00).setTechnicalSkills("Manual Testing, SDLC, STLC, Selenium, TestNG, Maven, Jenkins").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Postman").setDatabaseSkills("SQL").setProjectName("E-Commerce Automation Testing").setProjectDescription("Automated web application testing using Java, Selenium, TestNG and Maven").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software Test Engineer").setTotalExperience("Fresher").setCertifications("Java, Selenium Automation Testing").setLinkedinProfile("linkedin.com/in/arunendra-singh").setGithubProfile("github.com/ArunPratap-Singh").setResumeStatus("Ready");
		r2.setFullName("Rahul Sharma").setAge(24).setGender("Male").setEmail("rahul.sharma@gmail.com").setPhoneNumber("9876501234").setAddress("Noida, Uttar Pradesh").setCareerObjective("To start a career in Software Testing and contribute to quality software development").setHighestQualification("B.Tech Computer Science").setUniversityName("AKTU").setGraduationYear("2025").setPercentage(78.50).setTechnicalSkills("Manual Testing, STLC, SDLC, Selenium, TestNG, Jira").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jira").setDatabaseSkills("SQL").setProjectName("Banking Application Testing").setProjectDescription("Performed functional and automation testing of banking application").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Engineer").setTotalExperience("Fresher").setCertifications("Selenium Automation Testing").setLinkedinProfile("linkedin.com/in/rahul-sharma").setGithubProfile("github.com/rahul-sharma").setResumeStatus("Ready");
		r3.setFullName("Priya Verma").setAge(23).setGender("Female").setEmail("priya.verma@gmail.com").setPhoneNumber("9876512345").setAddress("Delhi, India").setCareerObjective("To develop expertise in Software Quality Assurance and Automation Testing").setHighestQualification("BCA").setUniversityName("Delhi University").setGraduationYear("2025").setPercentage(82.40).setTechnicalSkills("Manual Testing, Selenium, TestNG, API Testing, STLC").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, Postman, TestNG").setDatabaseSkills("SQL").setProjectName("E-Commerce Testing").setProjectDescription("Designed and executed test cases for an e-commerce web application").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software Tester").setTotalExperience("Fresher").setCertifications("Java, Selenium").setLinkedinProfile("linkedin.com/in/priya-verma").setGithubProfile("github.com/priya-verma").setResumeStatus("Ready");
		r4.setFullName("Amit Kumar").setAge(26).setGender("Male").setEmail("amit.kumar@gmail.com").setPhoneNumber("9876523456").setAddress("Gurgaon, Haryana").setCareerObjective("To build a professional career as an Automation Test Engineer").setHighestQualification("B.Tech IT").setUniversityName("MDU Rohtak").setGraduationYear("2024").setPercentage(76.80).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins, Git").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("CRM Automation Testing").setProjectDescription("Automated CRM workflows using Selenium WebDriver and TestNG").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Test Engineer").setTotalExperience("Fresher").setCertifications("Automation Testing").setLinkedinProfile("linkedin.com/in/amit-kumar").setGithubProfile("github.com/amit-kumar").setResumeStatus("Ready");
		r5.setFullName("Neha Singh").setAge(25).setGender("Female").setEmail("neha.singh@gmail.com").setPhoneNumber("9876534567").setAddress("Kanpur, Uttar Pradesh").setCareerObjective("To obtain a challenging position in Software Testing and Quality Assurance").setHighestQualification("MCA").setUniversityName("CSJMU").setGraduationYear("2024").setPercentage(80.20).setTechnicalSkills("Manual Testing, Selenium, TestNG, API Testing, Jira").setProgrammingLanguages("Java").setTestingTools("Selenium, Postman, Jira").setDatabaseSkills("MySQL").setProjectName("Healthcare Application Testing").setProjectDescription("Performed functional, regression and API testing for healthcare application").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Tester").setTotalExperience("Fresher").setCertifications("Java, API Testing").setLinkedinProfile("linkedin.com/in/neha-singh").setGithubProfile("github.com/neha-singh").setResumeStatus("Ready");
		r6.setFullName("Vikas Yadav").setAge(27).setGender("Male").setEmail("vikas.yadav@gmail.com").setPhoneNumber("9876545678").setAddress("Lucknow, Uttar Pradesh").setCareerObjective("To work in a growth-oriented organization as a Software Test Engineer").setHighestQualification("B.Tech").setUniversityName("AKTU").setGraduationYear("2023").setPercentage(74.60).setTechnicalSkills("SDLC, STLC, Manual Testing, Selenium, TestNG, Maven").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Maven").setDatabaseSkills("SQL").setProjectName("Online Shopping Automation").setProjectDescription("Created automated test scripts for online shopping workflows").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Test Engineer").setTotalExperience("Fresher").setCertifications("Selenium WebDriver").setLinkedinProfile("linkedin.com/in/vikas-yadav").setGithubProfile("github.com/vikas-yadav").setResumeStatus("Ready");
		r7.setFullName("Pooja Gupta").setAge(24).setGender("Female").setEmail("pooja.gupta@gmail.com").setPhoneNumber("9876556789").setAddress("Jaipur, Rajasthan").setCareerObjective("To begin my career in Quality Assurance and contribute to software quality").setHighestQualification("B.Sc Computer Science").setUniversityName("Rajasthan University").setGraduationYear("2025").setPercentage(79.30).setTechnicalSkills("Manual Testing, Selenium, TestNG, SDLC, STLC").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG").setDatabaseSkills("SQL").setProjectName("Travel Booking Testing").setProjectDescription("Tested travel booking workflows using manual and automation techniques").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Engineer").setTotalExperience("Fresher").setCertifications("Software Testing").setLinkedinProfile("linkedin.com/in/pooja-gupta").setGithubProfile("github.com/pooja-gupta").setResumeStatus("Ready");
		r8.setFullName("Rohit Mishra").setAge(28).setGender("Male").setEmail("rohit.mishra@gmail.com").setPhoneNumber("9876567890").setAddress("Varanasi, Uttar Pradesh").setCareerObjective("To establish a successful career in Automation Testing and Software Quality").setHighestQualification("MCA").setUniversityName("BHU").setGraduationYear("2023").setPercentage(81.10).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins, Git").setProgrammingLanguages("Java").setTestingTools("Selenium, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("CRM Automation Framework").setProjectDescription("Developed automated regression scripts using Java Selenium and TestNG").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Tester").setTotalExperience("Fresher").setCertifications("Selenium Automation").setLinkedinProfile("linkedin.com/in/rohit-mishra").setGithubProfile("github.com/rohit-mishra").setResumeStatus("Ready");
		r9.setFullName("Sneha Patel").setAge(23).setGender("Female").setEmail("sneha.patel@gmail.com").setPhoneNumber("9876578901").setAddress("Ahmedabad, Gujarat").setCareerObjective("To pursue a career in Software Testing and continuously improve my technical skills").setHighestQualification("B.Tech Computer Science").setUniversityName("GTU").setGraduationYear("2025").setPercentage(83.70).setTechnicalSkills("Manual Testing, Selenium, TestNG, API Testing, Git").setProgrammingLanguages("Java").setTestingTools("Selenium, Postman, TestNG").setDatabaseSkills("MySQL").setProjectName("Banking Portal Testing").setProjectDescription("Performed functional, regression and API testing of banking portal").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software Test Engineer").setTotalExperience("Fresher").setCertifications("Java, Postman").setLinkedinProfile("linkedin.com/in/sneha-patel").setGithubProfile("github.com/sneha-patel").setResumeStatus("Ready");
		r10.setFullName("Sandeep Singh").setAge(29).setGender("Male").setEmail("sandeep.singh@gmail.com").setPhoneNumber("9876589012").setAddress("Agra, Uttar Pradesh").setCareerObjective("To work as an Automation Test Engineer and contribute to reliable software delivery").setHighestQualification("BCA").setUniversityName("Agra University").setGraduationYear("2022").setPercentage(72.90).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("Retail Application Testing").setProjectDescription("Automated retail application test scenarios using Selenium and TestNG").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Engineer").setTotalExperience("Fresher").setCertifications("Selenium, TestNG").setLinkedinProfile("linkedin.com/in/sandeep-singh").setGithubProfile("github.com/sandeep-singh").setResumeStatus("Ready");
		r11.setFullName("Ankit Verma").setAge(25).setGender("Male").setEmail("ankit.verma@gmail.com").setPhoneNumber("9876590123").setAddress("Prayagraj, Uttar Pradesh").setCareerObjective("To join a progressive organization as a Software QA Engineer").setHighestQualification("MCA").setUniversityName("Allahabad University").setGraduationYear("2024").setPercentage(77.50).setTechnicalSkills("Manual Testing, SDLC, STLC, Selenium, TestNG").setProgrammingLanguages("Java").setTestingTools("Selenium, TestNG, Postman").setDatabaseSkills("SQL").setProjectName("Insurance Application Testing").setProjectDescription("Performed end-to-end testing of insurance application modules").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Engineer").setTotalExperience("Fresher").setCertifications("Software Testing, Selenium").setLinkedinProfile("linkedin.com/in/ankit-verma").setGithubProfile("github.com/ankit-verma").setResumeStatus("Ready");
		r12.setFullName("Kavita Sharma").setAge(26).setGender("Female").setEmail("kavita.sharma@gmail.com").setPhoneNumber("9876509876").setAddress("Chandigarh, India").setCareerObjective("To build a rewarding career in Software Quality Assurance and Automation").setHighestQualification("B.Tech IT").setUniversityName("Punjab Technical University").setGraduationYear("2024").setPercentage(84.20).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, API Testing").setProgrammingLanguages("Java").setTestingTools("Selenium, Postman, TestNG").setDatabaseSkills("SQL").setProjectName("E-Commerce Regression Testing").setProjectDescription("Designed automated regression test cases for an e-commerce application").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Automation Engineer").setTotalExperience("Fresher").setCertifications("Selenium Automation Testing").setLinkedinProfile("linkedin.com/in/kavita-sharma").setGithubProfile("github.com/kavita-sharma").setResumeStatus("Ready");
		r13.setFullName("Manish Kumar").setAge(27).setGender("Male").setEmail("manish.kumar@gmail.com").setPhoneNumber("9876510987").setAddress("Patna, Bihar").setCareerObjective("To utilize my testing knowledge to deliver high-quality software products").setHighestQualification("B.Tech Computer Science").setUniversityName("Patna University").setGraduationYear("2023").setPercentage(75.80).setTechnicalSkills("Manual Testing, Selenium, TestNG, Jenkins, Git").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("CRM Web Automation").setProjectDescription("Automated CRM web application using Selenium WebDriver and TestNG").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software Tester").setTotalExperience("Fresher").setCertifications("Java Selenium Automation").setLinkedinProfile("linkedin.com/in/manish-kumar").setGithubProfile("github.com/manish-kumar").setResumeStatus("Ready");
		r14.setFullName("Ritika Singh").setAge(24).setGender("Female").setEmail("ritika.singh@gmail.com").setPhoneNumber("9876521098").setAddress("Bhopal, Madhya Pradesh").setCareerObjective("To develop my career in Software Testing with strong automation skills").setHighestQualification("MCA").setUniversityName("Barkatullah University").setGraduationYear("2025").setPercentage(86.40).setTechnicalSkills("Manual Testing, Selenium, TestNG, API Testing, SQL").setProgrammingLanguages("Java").setTestingTools("Selenium, Postman, TestNG").setDatabaseSkills("MySQL").setProjectName("Healthcare Automation Testing").setProjectDescription("Automated healthcare web application scenarios using Selenium and TestNG").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Automation Tester").setTotalExperience("Fresher").setCertifications("Selenium, API Testing").setLinkedinProfile("linkedin.com/in/ritika-singh").setGithubProfile("github.com/ritika-singh").setResumeStatus("Ready");
		r15.setFullName("Deepak Joshi").setAge(30).setGender("Male").setEmail("deepak.joshi@gmail.com").setPhoneNumber("9876532109").setAddress("Dehradun, Uttarakhand").setCareerObjective("To pursue a challenging career in Software Testing and Automation Engineering").setHighestQualification("M.Tech Computer Science").setUniversityName("Uttarakhand Technical University").setGraduationYear("2022").setPercentage(79.60).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins, SQL").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("Banking Automation Framework").setProjectDescription("Built automated test scenarios for banking application using Java and Selenium").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Test Engineer").setTotalExperience("Fresher").setCertifications("Java, Selenium, Jenkins").setLinkedinProfile("linkedin.com/in/deepak-joshi").setGithubProfile("github.com/deepak-joshi").setResumeStatus("Ready");
		r16.setFullName("Anjali Gupta").setAge(25).setGender("Female").setEmail("anjali.gupta@gmail.com").setPhoneNumber("9876543211").setAddress("Mumbai, Maharashtra").setCareerObjective("To start my professional journey in Quality Assurance and Automation Testing").setHighestQualification("BCA").setUniversityName("Mumbai University").setGraduationYear("2024").setPercentage(81.70).setTechnicalSkills("Manual Testing, Selenium, TestNG, STLC, API Testing").setProgrammingLanguages("Java").setTestingTools("Selenium, Postman, TestNG").setDatabaseSkills("SQL").setProjectName("Online Booking Testing").setProjectDescription("Performed functional and automation testing for online booking workflows").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("QA Tester").setTotalExperience("Fresher").setCertifications("Software Testing, Selenium").setLinkedinProfile("linkedin.com/in/anjali-gupta").setGithubProfile("github.com/anjali-gupta").setResumeStatus("Ready");
		r17.setFullName("Nitin Raj").setAge(28).setGender("Male").setEmail("nitin.raj@gmail.com").setPhoneNumber("9876554321").setAddress("Ranchi, Jharkhand").setCareerObjective("To become a skilled Automation Test Engineer and contribute to software quality").setHighestQualification("B.Tech IT").setUniversityName("BIT Mesra").setGraduationYear("2023").setPercentage(73.40).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins, Git").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Jenkins").setDatabaseSkills("SQL").setProjectName("E-Commerce Automation Framework").setProjectDescription("Created reusable automation scripts for e-commerce application testing").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Test Engineer").setTotalExperience("Fresher").setCertifications("Selenium WebDriver, TestNG").setLinkedinProfile("linkedin.com/in/nitin-raj").setGithubProfile("github.com/nitin-raj").setResumeStatus("Ready");
		r18.setFullName("Shweta Mishra").setAge(23).setGender("Female").setEmail("shweta.mishra@gmail.com").setPhoneNumber("9876565432").setAddress("Indore, Madhya Pradesh").setCareerObjective("To obtain an entry-level position in Software Testing and grow as an Automation Engineer").setHighestQualification("B.Sc IT").setUniversityName("DAVV Indore").setGraduationYear("2025").setPercentage(80.90).setTechnicalSkills("Manual Testing, SDLC, STLC, Selenium, TestNG").setProgrammingLanguages("Java").setTestingTools("Selenium, TestNG, Postman").setDatabaseSkills("SQL").setProjectName("Food Delivery Testing").setProjectDescription("Tested food delivery application using manual and automation testing techniques").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software QA Engineer").setTotalExperience("Fresher").setCertifications("Java, Selenium Testing").setLinkedinProfile("linkedin.com/in/shweta-mishra").setGithubProfile("github.com/shweta-mishra").setResumeStatus("Ready");
		r19.setFullName("Rajesh Kumar").setAge(31).setGender("Male").setEmail("rajesh.kumar@gmail.com").setPhoneNumber("9876576543").setAddress("Hyderabad, Telangana").setCareerObjective("To leverage my technical knowledge in Software Testing and Automation to ensure quality products").setHighestQualification("MCA").setUniversityName("Osmania University").setGraduationYear("2021").setPercentage(76.30).setTechnicalSkills("Manual Testing, Selenium, TestNG, Maven, Jenkins, API Testing").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, Postman, Jenkins").setDatabaseSkills("SQL").setProjectName("FinTech Application Testing").setProjectDescription("Automated functional and regression test cases for a financial application").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Software Test Engineer").setTotalExperience("Fresher").setCertifications("Selenium, TestNG, API Testing").setLinkedinProfile("linkedin.com/in/rajesh-kumar").setGithubProfile("github.com/rajesh-kumar").setResumeStatus("Ready");
		r20.setFullName("Meena Kapoor").setAge(26).setGender("Female").setEmail("meena.kapoor@gmail.com").setPhoneNumber("9876587654").setAddress("Pune, Maharashtra").setCareerObjective("To build a successful career in Software Testing and become an expert in Test Automation").setHighestQualification("MCA").setUniversityName("Savitribai Phule Pune University").setGraduationYear("2024").setPercentage(85.10).setTechnicalSkills("Manual Testing, SDLC, STLC, Selenium, TestNG, Maven, Jenkins").setProgrammingLanguages("Java").setTestingTools("Selenium WebDriver, TestNG, Postman").setDatabaseSkills("SQL").setProjectName("E-Commerce Automation Framework").setProjectDescription("Developed automated test cases for web application using Java, Selenium, TestNG and Maven").setExperienceLevel("Fresher").setCompanyName("N/A").setJobTitle("Automation Test Engineer").setTotalExperience("Fresher").setCertifications("Java, Selenium Automation Testing").setLinkedinProfile("linkedin.com/in/meena-kapoor").setGithubProfile("github.com/meena-kapoor").setResumeStatus("Ready");		
		
		System.out.println("========================== RESUME ==========================");

		r1.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");
		
		r2.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r3.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r4.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r5.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r6.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r7.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r8.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r9.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r10.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r11.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r12.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r13.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r14.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r15.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r16.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r17.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r18.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r19.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

		r20.printFullName().printAge().printGender().printEmail().printPhoneNumber().printAddress().printCareerObjective().printHighestQualification().printUniversityName().printGraduationYear().printPercentage().printTechnicalSkills().printProgrammingLanguages().printTestingTools().printDatabaseSkills().printProjectName().printProjectDescription().printExperienceLevel().printCompanyName().printJobTitle().printTotalExperience().printCertifications().printLinkedinProfile().printGithubProfile().printResumeStatus();
		System.out.println("=============================================================");

	}

}
