package methodChaining;

public class SeleniumWebDriverConfigurationDriver {

	public static void main(String[] args) {

		SeleniumWebDriverConfiguration s1 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s2 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s3 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s4 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s5 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s6 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s7 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s8 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s9 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s10 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s11 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s12 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s13 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s14 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s15 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s16 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s17 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s18 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s19 = new SeleniumWebDriverConfiguration();
		SeleniumWebDriverConfiguration s20 = new SeleniumWebDriverConfiguration();

		s1.setBrowserName("Chrome").setBrowserVersion("140").setOperatingSystem("Windows 10").setDriverName("ChromeDriver").setDriverVersion("140.0").setDriverPath("C:\\WebDrivers\\chromedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("QA").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s2.setBrowserName("Firefox").setBrowserVersion("142").setOperatingSystem("Windows 10").setDriverName("GeckoDriver").setDriverVersion("0.36").setDriverPath("C:\\WebDrivers\\geckodriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("QA").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(10).setExplicitWait(15).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1366x768").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s3.setBrowserName("Edge").setBrowserVersion("140").setOperatingSystem("Windows 10").setDriverName("EdgeDriver").setDriverVersion("140.0").setDriverPath("C:\\WebDrivers\\msedgedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("QA").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s4.setBrowserName("Chrome").setBrowserVersion("139").setOperatingSystem("Windows 11").setDriverName("ChromeDriver").setDriverVersion("139.0").setDriverPath("C:\\WebDrivers\\chromedriver.exe").setBaseUrl("https://www.google.com/").setEnvironment("Development").setExecutionMode("Local").setHeadlessMode("True").setImplicitWait(10).setExplicitWait(15).setPageLoadTimeout(25).setScriptTimeout(25).setWindowSize("1366x768").setMaximizeWindow("No").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s5.setBrowserName("Firefox").setBrowserVersion("141").setOperatingSystem("Windows 11").setDriverName("GeckoDriver").setDriverVersion("0.35").setDriverPath("C:\\WebDrivers\\geckodriver.exe").setBaseUrl("https://www.flipkart.com/").setEnvironment("QA").setExecutionMode("Local").setHeadlessMode("True").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\TestDownloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s6.setBrowserName("Edge").setBrowserVersion("139").setOperatingSystem("Windows 11").setDriverName("EdgeDriver").setDriverVersion("139.0").setDriverPath("C:\\WebDrivers\\msedgedriver.exe").setBaseUrl("https://www.amazon.in/").setEnvironment("Production").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(20).setExplicitWait(30).setPageLoadTimeout(40).setScriptTimeout(40).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\AmazonDownloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s7.setBrowserName("Chrome").setBrowserVersion("140").setOperatingSystem("Ubuntu 22.04").setDriverName("ChromeDriver").setDriverVersion("140.0").setDriverPath("/usr/bin/chromedriver").setBaseUrl("https://www.saucedemo.com/").setEnvironment("QA").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("/home/tester/Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s8.setBrowserName("Firefox").setBrowserVersion("142").setOperatingSystem("Ubuntu 22.04").setDriverName("GeckoDriver").setDriverVersion("0.36").setDriverPath("/usr/bin/geckodriver").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Testing").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(10).setExplicitWait(20).setPageLoadTimeout(35).setScriptTimeout(35).setWindowSize("1600x900").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("/home/tester/Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s9.setBrowserName("Chrome").setBrowserVersion("138").setOperatingSystem("Windows 10").setDriverName("ChromeDriver").setDriverVersion("138.0").setDriverPath("C:\\Automation\\Drivers\\chromedriver.exe").setBaseUrl("https://www.crmexample.com/").setEnvironment("UAT").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(20).setExplicitWait(25).setPageLoadTimeout(40).setScriptTimeout(40).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Automation\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s10.setBrowserName("Edge").setBrowserVersion("140").setOperatingSystem("Windows 11").setDriverName("EdgeDriver").setDriverVersion("140.0").setDriverPath("C:\\Automation\\Drivers\\msedgedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Regression").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(15).setExplicitWait(25).setPageLoadTimeout(35).setScriptTimeout(35).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Automation\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s11.setBrowserName("Chrome").setBrowserVersion("137").setOperatingSystem("Windows 10").setDriverName("ChromeDriver").setDriverVersion("137.0").setDriverPath("C:\\TestAutomation\\chromedriver.exe").setBaseUrl("https://www.linkedin.com/").setEnvironment("Development").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(10).setExplicitWait(15).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1366x768").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\TestAutomation\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s12.setBrowserName("Firefox").setBrowserVersion("140").setOperatingSystem("Windows 11").setDriverName("GeckoDriver").setDriverVersion("0.35").setDriverPath("C:\\TestAutomation\\geckodriver.exe").setBaseUrl("https://www.github.com/").setEnvironment("Development").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\TestAutomation\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s13.setBrowserName("Edge").setBrowserVersion("138").setOperatingSystem("Windows 10").setDriverName("EdgeDriver").setDriverVersion("138.0").setDriverPath("C:\\Drivers\\msedgedriver.exe").setBaseUrl("https://www.example.com/").setEnvironment("Staging").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(12).setExplicitWait(18).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1600x900").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Downloads\\Staging").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s14.setBrowserName("Chrome").setBrowserVersion("140").setOperatingSystem("Windows 11").setDriverName("ChromeDriver").setDriverVersion("140.0").setDriverPath("C:\\Drivers\\chromedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Regression").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(20).setExplicitWait(30).setPageLoadTimeout(45).setScriptTimeout(45).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\RegressionDownloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s15.setBrowserName("Firefox").setBrowserVersion("139").setOperatingSystem("Ubuntu 20.04").setDriverName("GeckoDriver").setDriverVersion("0.34").setDriverPath("/usr/local/bin/geckodriver").setBaseUrl("https://www.saucedemo.com/").setEnvironment("QA").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(15).setExplicitWait(25).setPageLoadTimeout(35).setScriptTimeout(35).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("/home/qa/Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s16.setBrowserName("Chrome").setBrowserVersion("139").setOperatingSystem("Windows 10").setDriverName("ChromeDriver").setDriverVersion("139.0").setDriverPath("C:\\QA\\WebDrivers\\chromedriver.exe").setBaseUrl("https://www.demowebshop.com/").setEnvironment("UAT").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(15).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\QA\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s17.setBrowserName("Edge").setBrowserVersion("137").setOperatingSystem("Windows 11").setDriverName("EdgeDriver").setDriverVersion("137.0").setDriverPath("C:\\QA\\WebDrivers\\msedgedriver.exe").setBaseUrl("https://www.orangehrm.com/").setEnvironment("QA").setExecutionMode("Local").setHeadlessMode("True").setImplicitWait(10).setExplicitWait(20).setPageLoadTimeout(30).setScriptTimeout(30).setWindowSize("1366x768").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\QA\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s18.setBrowserName("Chrome").setBrowserVersion("140").setOperatingSystem("Windows 11").setDriverName("ChromeDriver").setDriverVersion("140.0").setDriverPath("C:\\Selenium\\Drivers\\chromedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Smoke").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(5).setExplicitWait(10).setPageLoadTimeout(20).setScriptTimeout(20).setWindowSize("1280x720").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Selenium\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s19.setBrowserName("Firefox").setBrowserVersion("138").setOperatingSystem("Windows 10").setDriverName("GeckoDriver").setDriverVersion("0.34").setDriverPath("C:\\Selenium\\Drivers\\geckodriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Smoke").setExecutionMode("Local").setHeadlessMode("False").setImplicitWait(8).setExplicitWait(15).setPageLoadTimeout(25).setScriptTimeout(25).setWindowSize("1440x900").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Selenium\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		s20.setBrowserName("Edge").setBrowserVersion("140").setOperatingSystem("Windows 11").setDriverName("EdgeDriver").setDriverVersion("140.0").setDriverPath("C:\\WebDrivers\\msedgedriver.exe").setBaseUrl("https://www.saucedemo.com/").setEnvironment("Production").setExecutionMode("Remote").setHeadlessMode("True").setImplicitWait(20).setExplicitWait(30).setPageLoadTimeout(45).setScriptTimeout(45).setWindowSize("1920x1080").setMaximizeWindow("Yes").setAcceptInsecureCertificates("No").setDownloadDirectory("C:\\Production\\Downloads").setScreenshotOnFailure("Yes").setConfigurationStatus("Configured");
		
		System.out.println("========== Selenium WebDriver Configuration ==========");

		s1.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s2.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s3.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s4.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s5.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s6.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s7.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s8.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s9.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s10.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s11.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s12.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s13.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s14.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s15.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s16.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s17.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s18.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s19.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		s20.printBrowserName().printBrowserVersion().printOperatingSystem().printDriverName().printDriverVersion().printDriverPath().printBaseUrl().printEnvironment().printExecutionMode().printHeadlessMode().printImplicitWait().printExplicitWait().printPageLoadTimeout().printScriptTimeout().printWindowSize().printMaximizeWindow().printAcceptInsecureCertificates().printDownloadDirectory().printScreenshotOnFailure().printConfigurationStatus();
		System.out.println("=======================================================");

		
	}

}
