package methodChaining;

public class SeleniumLoginPageDriver {

	public static void main(String[] args) {

		SeleniumLoginPage s1 = new SeleniumLoginPage();
		SeleniumLoginPage s2 = new SeleniumLoginPage();
		SeleniumLoginPage s3 = new SeleniumLoginPage();
		SeleniumLoginPage s4 = new SeleniumLoginPage();
		SeleniumLoginPage s5 = new SeleniumLoginPage();
		SeleniumLoginPage s6 = new SeleniumLoginPage();
		SeleniumLoginPage s7 = new SeleniumLoginPage();
		SeleniumLoginPage s8 = new SeleniumLoginPage();
		SeleniumLoginPage s9 = new SeleniumLoginPage();
		SeleniumLoginPage s10 = new SeleniumLoginPage();
		SeleniumLoginPage s11 = new SeleniumLoginPage();
		SeleniumLoginPage s12 = new SeleniumLoginPage();
		SeleniumLoginPage s13 = new SeleniumLoginPage();
		SeleniumLoginPage s14 = new SeleniumLoginPage();
		SeleniumLoginPage s15 = new SeleniumLoginPage();
		SeleniumLoginPage s16 = new SeleniumLoginPage();
		SeleniumLoginPage s17 = new SeleniumLoginPage();
		SeleniumLoginPage s18 = new SeleniumLoginPage();
		SeleniumLoginPage s19 = new SeleniumLoginPage();
		SeleniumLoginPage s20 = new SeleniumLoginPage();

		s1.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("QA").setImplicitWait(15).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s2.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("QA").setImplicitWait(10).setExplicitWait(15).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s3.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("QA").setImplicitWait(15).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s4.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("Development").setImplicitWait(10).setExplicitWait(15).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s5.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("Testing").setImplicitWait(15).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s6.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("Testing").setImplicitWait(20).setExplicitWait(30).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s7.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("UAT").setImplicitWait(15).setExplicitWait(25).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s8.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("UAT").setImplicitWait(10).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s9.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("Regression").setImplicitWait(15).setExplicitWait(25).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s10.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("Regression").setImplicitWait(20).setExplicitWait(30).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s11.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("Smoke").setImplicitWait(10).setExplicitWait(15).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s12.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("Smoke").setImplicitWait(10).setExplicitWait(15).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s13.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("Staging").setImplicitWait(15).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s14.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("Staging").setImplicitWait(15).setExplicitWait(25).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s15.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("Production").setImplicitWait(20).setExplicitWait(30).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s16.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("Production").setImplicitWait(15).setExplicitWait(20).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s17.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Firefox").setEnvironment("QA").setImplicitWait(12).setExplicitWait(18).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s18.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("QA").setImplicitWait(12).setExplicitWait(18).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s19.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Chrome").setEnvironment("Regression").setImplicitWait(20).setExplicitWait(30).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		s20.setPageName("Login Page").setPageUrl("https://www.saucedemo.com/").setUsernameField("Username").setPasswordField("Password").setLoginButton("Login").setForgotPasswordLink("Forgot Password").setRememberMeCheckbox("Remember Me").setUsernameLocator("id=user-name").setPasswordLocator("id=password").setLoginButtonLocator("id=login-button").setForgotPasswordLocator("xpath=//a[text()='Forgot Password']").setPageTitle("Swag Labs").setBrowserName("Edge").setEnvironment("Production").setImplicitWait(20).setExplicitWait(30).setAuthenticationType("Username and Password").setLoginStatus("Successful").setErrorMessage("No Error").setDashboardUrl("https://www.saucedemo.com/inventory.html");
		
		s1.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");
		
		s2.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s3.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s4.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s5.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s6.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s7.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s8.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s9.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s10.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s11.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s12.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s13.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s14.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s15.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s16.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s17.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s18.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s19.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");

		s20.printPageName().printPageUrl().printUsernameField().printPasswordField().printLoginButton().printForgotPasswordLink().printRememberMeCheckbox().printUsernameLocator().printPasswordLocator().printLoginButtonLocator().printForgotPasswordLocator().printPageTitle().printBrowserName().printEnvironment().printImplicitWait().printExplicitWait().printAuthenticationType().printLoginStatus().printErrorMessage().printDashboardUrl();
		System.out.println("==============================================");
	}

}
