package constructor.shallowCopy.House;

public class HouseDriver {
	
	public static void main(String[] args) {
		
		System.out.println("=====================================Main Method Starts========================================");
		
		House h1 = new House("Green Villa", "Lucknow", 8500000, "Independent House", new Owner(101, "Mohan Singh", 40, "Male", "Business Man", "Indian"));
		House h2 = new House("Sunrise Villa", "Delhi", 9500000, "Independent House", new Owner(102, "Ravi Kumar", 42, "Male", "Software Engineer", "Indian"));
		House h3 = new House("Royal Palace", "Mumbai", 15000000, "Luxury House", new Owner(103, "Amit Sharma", 45, "Male", "Doctor", "Indian"));
		House h4 = new House("Lake View House", "Bhopal", 7200000, "Independent House", new Owner(104, "Neha Verma", 36, "Female", "Teacher", "Indian"));
		House h5 = new House("Green Garden", "Pune", 6800000, "Duplex House", new Owner(105, "Suresh Patel", 50, "Male", "Business Man", "Indian"));
		House h6 = new House("Rose Villa", "Jaipur", 8200000, "Independent House", new Owner(106, "Priya Singh", 38, "Female", "Lawyer", "Indian"));
		House h7 = new House("Dream Home", "Kanpur", 5500000, "Bungalow", new Owner(107, "Rajesh Yadav", 47, "Male", "Government Officer", "Indian"));
		House h8 = new House("Blue Heaven", "Noida", 7800000, "Duplex House", new Owner(108, "Anjali Gupta", 34, "Female", "Accountant", "Indian"));
		House h9 = new House("Royal Garden", "Agra", 6200000, "Bungalow", new Owner(109, "Vikas Singh", 41, "Male", "Engineer", "Indian"));
		House h10 = new House("Peace Villa", "Varanasi", 5800000, "Independent House", new Owner(110, "Pooja Mishra", 39, "Female", "Professor", "Indian"));
		House h11 = new House("Silver Villa", "Gurgaon", 11000000, "Luxury House", new Owner(111, "Karan Mehta", 44, "Male", "Entrepreneur", "Indian"));
		House h12 = new House("Golden House", "Chandigarh", 12500000, "Luxury House", new Owner(112, "Ritu Kapoor", 43, "Female", "Architect", "Indian"));
		House h13 = new House("White Villa", "Indore", 6500000, "Independent House", new Owner(113, "Manish Jain", 46, "Male", "Business Man", "Indian"));
		House h14 = new House("Green Residency", "Lucknow", 7300000, "Duplex House", new Owner(114, "Kavita Singh", 37, "Female", "Doctor", "Indian"));
		House h15 = new House("Royal Residency", "Delhi", 13500000, "Bungalow", new Owner(115, "Deepak Verma", 49, "Male", "Civil Engineer", "Indian"));
		House h16 = new House("Happy Home", "Mumbai", 10500000, "Independent House", new Owner(116, "Sneha Rao", 35, "Female", "Designer", "Indian"));
		House h17 = new House("Green Palace", "Hyderabad", 8900000, "Duplex House", new Owner(117, "Arun Kumar", 40, "Male", "Manager", "Indian"));
		House h18 = new House("Sunshine Villa", "Bangalore", 11500000, "Luxury House", new Owner(118, "Meena Sharma", 42, "Female", "IT Manager", "Indian"));
		House h19 = new House("City View House", "Kolkata", 7600000, "Independent House", new Owner(119, "Rahul Das", 39, "Male", "Teacher", "Indian"));
		House h20 = new House("Beautiful Villa", "Patna", 6100000, "Bungalow", new Owner(120, "Nisha Kumari", 33, "Female", "Nurse", "Indian"));
		House h21 = new House("Royal Villa", "Ranchi", 6900000, "Independent House", new Owner(121, "Ajay Singh", 45, "Male", "Police Officer", "Indian"));
		House h22 = new House("Green Paradise", "Dehradun", 8400000, "Bungalow", new Owner(122, "Shweta Joshi", 37, "Female", "Professor", "Indian"));
		House h23 = new House("Modern Villa", "Noida", 9800000, "Duplex House", new Owner(123, "Nitin Agarwal", 41, "Male", "Business Man", "Indian"));
		House h24 = new House("Dream Villa", "Faridabad", 7100000, "Independent House", new Owner(124, "Rashmi Gupta", 36, "Female", "Bank Manager", "Indian"));
		House h25 = new House("Elegant House", "Amritsar", 6400000, "Bungalow", new Owner(125, "Harpreet Singh", 43, "Male", "Business Man", "Indian"));
		House h26 = new House("Peace Palace", "Shimla", 9200000, "Luxury House", new Owner(126, "Simran Kaur", 32, "Female", "Teacher", "Indian"));
		House h27 = new House("Mountain View", "Manali", 8800000, "Bungalow", new Owner(127, "Vivek Sharma", 40, "Male", "Photographer", "Indian"));
		House h28 = new House("River View Villa", "Haridwar", 6700000, "Independent House", new Owner(128, "Sunita Devi", 48, "Female", "Homemaker", "Indian"));
		House h29 = new House("Royal Enclave", "Jaipur", 10200000, "Duplex House", new Owner(129, "Mohit Gupta", 35, "Male", "Software Developer", "Indian"));
		House h30 = new House("Green Enclave", "Pune", 8300000, "Independent House", new Owner(130, "Aarti Shah", 38, "Female", "Chartered Accountant", "Indian"));
		House h31 = new House("Lake Palace", "Udaipur", 14500000, "Luxury House", new Owner(131, "Rohit Mehta", 46, "Male", "Entrepreneur", "Indian"));
		House h32 = new House("Heritage House", "Agra", 7500000, "Bungalow", new Owner(132, "Komal Singh", 34, "Female", "Lawyer", "Indian"));
		House h33 = new House("Modern Residency", "Ghaziabad", 7900000, "Duplex House", new Owner(133, "Sanjay Kumar", 44, "Male", "Engineer", "Indian"));
		House h34 = new House("Happy Villa", "Meerut", 5900000, "Independent House", new Owner(134, "Renu Sharma", 41, "Female", "Teacher", "Indian"));
		House h35 = new House("Royal Garden Villa", "Lucknow", 8700000, "Bungalow", new Owner(135, "Akash Singh", 31, "Male", "Software Engineer", "Indian"));
		House h36 = new House("Blue Residency", "Delhi", 10800000, "Luxury House", new Owner(136, "Monika Verma", 39, "Female", "Doctor", "Indian"));
		House h37 = new House("Golden Residency", "Mumbai", 12800000, "Duplex House", new Owner(137, "Vivek Patel", 47, "Male", "Business Man", "Indian"));
		House h38 = new House("Nature Villa", "Dehradun", 8100000, "Independent House", new Owner(138, "Divya Sharma", 35, "Female", "Architect", "Indian"));
		House h39 = new House("Comfort House", "Bhopal", 6300000, "Bungalow", new Owner(139, "Rakesh Mishra", 50, "Male", "Government Officer", "Indian"));
		House h40 = new House("Urban Villa", "Bangalore", 11800000, "Luxury House", new Owner(140, "Swati Rao", 33, "Female", "Software Developer", "Indian"));
		House h41 = new House("Classic House", "Kanpur", 5700000, "Independent House", new Owner(141, "Pankaj Singh", 45, "Male", "Business Man", "Indian"));
		House h42 = new House("Pearl Villa", "Hyderabad", 9600000, "Duplex House", new Owner(142, "Shalini Reddy", 37, "Female", "HR Manager", "Indian"));
		House h43 = new House("Elegant Villa", "Chandigarh", 11200000, "Luxury House", new Owner(143, "Gaurav Kapoor", 42, "Male", "Architect", "Indian"));
		House h44 = new House("Green View", "Nashik", 6000000, "Independent House", new Owner(144, "Preeti Jain", 36, "Female", "Accountant", "Indian"));
		House h45 = new House("Royal Heights", "Surat", 9000000, "Bungalow", new Owner(145, "Manoj Shah", 49, "Male", "Entrepreneur", "Indian"));
		House h46 = new House("Sunrise Residency", "Ahmedabad", 8500000, "Duplex House", new Owner(146, "Kiran Patel", 40, "Female", "Business Woman", "Indian"));
		House h47 = new House("Dream Residency", "Varanasi", 7000000, "Independent House", new Owner(147, "Ashish Mishra", 38, "Male", "Professor", "Indian"));
		House h48 = new House("Royal Paradise", "Kolkata", 10400000, "Luxury House", new Owner(148, "Neelam Das", 44, "Female", "Doctor", "Indian"));
		House h49 = new House("Green Heights", "Patna", 6600000, "Bungalow", new Owner(149, "Saurabh Kumar", 39, "Male", "Manager", "Indian"));
		House h50 = new House("Mohan Villa", "Lucknow", 9300000, "Luxury House", new Owner(150, "Mohan Verma", 46, "Male", "Business Man", "Indian"));
		House h51 = new House(h1);
		House h52 = new House(h2);
		House h53 = new House(h3);
		House h54 = new House(h4);
		House h55 = new House(h5);
		House h56 = new House(h6);
		House h57 = new House(h7);
		House h58 = new House(h8);
		House h59 = new House(h9);
		House h60 = new House(h10);
		House h61 = new House(h11);
		House h62 = new House(h12);
		House h63 = new House(h13);
		House h64 = new House(h14);
		House h65 = new House(h15);
		House h66 = new House(h16);
		House h67 = new House(h17);
		House h68 = new House(h18);
		House h69 = new House(h19);
		House h70 = new House(h20);
		House h71 = new House(h21);
		House h72 = new House(h22);
		House h73 = new House(h23);
		House h74 = new House(h24);
		House h75 = new House(h25);
		House h76 = new House(h26);
		House h77 = new House(h27);
		House h78 = new House(h28);
		House h79 = new House(h29);
		House h80 = new House(h30);
		House h81 = new House(h31);
		House h82 = new House(h32);
		House h83 = new House(h33);
		House h84 = new House(h34);
		House h85 = new House(h35);
		House h86 = new House(h36);
		House h87 = new House(h37);
		House h88 = new House(h38);
		House h89 = new House(h39);
		House h90 = new House(h40);
		
		System.out.println(h1);
		System.out.println(h2);
		System.out.println(h3);
		System.out.println(h4);
		System.out.println(h5);
		System.out.println(h6);
		System.out.println(h7);
		System.out.println(h8);
		System.out.println(h9);
		System.out.println(h10);
		System.out.println(h11);
		System.out.println(h12);
		System.out.println(h13);
		System.out.println(h14);
		System.out.println(h15);
		System.out.println(h16);
		System.out.println(h17);
		System.out.println(h18);
		System.out.println(h19);
		System.out.println(h20);
		System.out.println(h21);
		System.out.println(h22);
		System.out.println(h23);
		System.out.println(h24);
		System.out.println(h25);
		System.out.println(h26);
		System.out.println(h27);
		System.out.println(h28);
		System.out.println(h29);
		System.out.println(h30);
		System.out.println(h31);
		System.out.println(h32);
		System.out.println(h33);
		System.out.println(h34);
		System.out.println(h35);
		System.out.println(h36);
		System.out.println(h37);
		System.out.println(h38);
		System.out.println(h39);
		System.out.println(h40);
		System.out.println(h41);
		System.out.println(h42);
		System.out.println(h43);
		System.out.println(h44);
		System.out.println(h45);
		System.out.println(h46);
		System.out.println(h47);
		System.out.println(h48);
		System.out.println(h49);
		System.out.println(h50);
		System.out.println(h51);
		System.out.println(h52);
		System.out.println(h53);
		System.out.println(h54);
		System.out.println(h55);
		System.out.println(h56);
		System.out.println(h57);
		System.out.println(h58);
		System.out.println(h59);
		System.out.println(h60);
		System.out.println(h61);
		System.out.println(h62);
		System.out.println(h63);
		System.out.println(h64);
		System.out.println(h65);
		System.out.println(h66);
		System.out.println(h67);
		System.out.println(h68);
		System.out.println(h69);
		System.out.println(h70);
		System.out.println(h71);
		System.out.println(h72);
		System.out.println(h73);
		System.out.println(h74);
		System.out.println(h75);
		System.out.println(h76);
		System.out.println(h77);
		System.out.println(h78);
		System.out.println(h79);
		System.out.println(h80);
		System.out.println(h81);
		System.out.println(h82);
		System.out.println(h83);
		System.out.println(h84);
		System.out.println(h85);
		System.out.println(h86);
		System.out.println(h87);
		System.out.println(h88);
		System.out.println(h89);
		System.out.println(h90);
		
		System.out.println("=====================================Main Method Ends====================================");
	}

}
