package constructor.deepCopy.College;

public class CollegeDriver {
	
	public static void main(String[] args) {
		
		System.out.println("===================================Main Methods Starts========================================");
		
		College c1 = new College("Lucknow University", "Lucknow", 75000, "Government College", new Principal(101, "Mohan Singh", 55, "Male", "Ph.D. in Education", 25));
		College c2 = new College("Delhi University", "Delhi", 85000, "Government College", new Principal(102, "Ravi Kumar", 58, "Male", "Ph.D. in Physics", 30));
		College c3 = new College("Mumbai College", "Mumbai", 95000, "Private College", new Principal(103, "Anita Sharma", 52, "Female", "Ph.D. in Management", 24));
		College c4 = new College("Allahabad College", "Prayagraj", 68000, "Government College", new Principal(104, "Suresh Verma", 56, "Male", "Ph.D. in Chemistry", 28));
		College c5 = new College("Banaras Hindu College", "Varanasi", 72000, "Government College", new Principal(105, "Priya Singh", 50, "Female", "Ph.D. in History", 22));
		College c6 = new College("Kanpur University", "Kanpur", 78000, "Government College", new Principal(106, "Rajesh Yadav", 57, "Male", "Ph.D. in Mathematics", 29));
		College c7 = new College("Amity College", "Noida", 145000, "Private College", new Principal(107, "Neha Gupta", 49, "Female", "Ph.D. in Management", 21));
		College c8 = new College("Pune University", "Pune", 90000, "Government College", new Principal(108, "Amit Patel", 54, "Male", "Ph.D. in Computer Science", 26));
		College c9 = new College("Bangalore College", "Bangalore", 125000, "Private College", new Principal(109, "Kavita Rao", 51, "Female", "Ph.D. in Computer Science", 23));
		College c10 = new College("Kolkata University", "Kolkata", 70000, "Government College", new Principal(110, "Arun Das", 59, "Male", "Ph.D. in Economics", 32));
		College c11 = new College("Chandigarh College", "Chandigarh", 82000, "Government College", new Principal(111, "Ritu Kapoor", 53, "Female", "Ph.D. in English", 25));
		College c12 = new College("Jaipur University", "Jaipur", 76000, "Government College", new Principal(112, "Deepak Sharma", 55, "Male", "Ph.D. in Political Science", 27));
		College c13 = new College("Hyderabad College", "Hyderabad", 98000, "Private College", new Principal(113, "Meena Reddy", 48, "Female", "Ph.D. in Biotechnology", 20));
		College c14 = new College("Patna University", "Patna", 65000, "Government College", new Principal(114, "Vijay Kumar", 57, "Male", "Ph.D. in Sociology", 30));
		College c15 = new College("Indore College", "Indore", 73000, "Government College", new Principal(115, "Sunita Jain", 52, "Female", "Ph.D. in Commerce", 24));
		College c16 = new College("Gurgaon Institute", "Gurgaon", 135000, "Private College", new Principal(116, "Manish Mehta", 50, "Male", "Ph.D. in Management", 22));
		College c17 = new College("Dehradun University", "Dehradun", 88000, "Private College", new Principal(117, "Shweta Joshi", 47, "Female", "Ph.D. in Education", 19));
		College c18 = new College("Agra College", "Agra", 69000, "Government College", new Principal(118, "Rakesh Singh", 56, "Male", "Ph.D. in History", 28));
		College c19 = new College("Meerut College", "Meerut", 71000, "Government College", new Principal(119, "Pooja Verma", 49, "Female", "Ph.D. in Hindi", 21));
		College c20 = new College("Noida Institute", "Noida", 120000, "Private College", new Principal(120, "Nitin Agarwal", 53, "Male", "Ph.D. in Computer Science", 25));
		College c21 = new College("Bhopal University", "Bhopal", 79000, "Government College", new Principal(121, "Aarti Mishra", 51, "Female", "Ph.D. in Chemistry", 23));
		College c22 = new College("Ranchi College", "Ranchi", 67000, "Government College", new Principal(122, "Ajay Singh", 58, "Male", "Ph.D. in Mathematics", 31));
		College c23 = new College("Shimla University", "Shimla", 92000, "Government College", new Principal(123, "Simran Kaur", 46, "Female", "Ph.D. in English", 18));
		College c24 = new College("Amritsar College", "Amritsar", 74000, "Private College", new Principal(124, "Harpreet Singh", 54, "Male", "Ph.D. in Punjabi", 26));
		College c25 = new College("Surat University", "Surat", 83000, "Government College", new Principal(125, "Kiran Patel", 50, "Female", "Ph.D. in Commerce", 22));
		College c26 = new College("Ahmedabad College", "Ahmedabad", 87000, "Private College", new Principal(126, "Rajiv Shah", 55, "Male", "Ph.D. in Business Administration", 27));
		College c27 = new College("Nashik College", "Nashik", 68000, "Government College", new Principal(127, "Preeti Deshmukh", 48, "Female", "Ph.D. in Education", 20));
		College c28 = new College("Udaipur University", "Udaipur", 91000, "Government College", new Principal(128, "Mohit Jain", 52, "Male", "Ph.D. in History", 24));
		College c29 = new College("Mysore College", "Mysore", 77000, "Government College", new Principal(129, "Lakshmi Rao", 50, "Female", "Ph.D. in Mathematics", 23));
		College c30 = new College("Coimbatore Institute", "Coimbatore", 105000, "Private College", new Principal(130, "Sanjay Kumar", 56, "Male", "Ph.D. in Engineering", 29));
		College c31 = new College("Kochi University", "Kochi", 89000, "Government College", new Principal(131, "Anjali Menon", 47, "Female", "Ph.D. in Economics", 19));
		College c32 = new College("Bhubaneswar College", "Bhubaneswar", 73000, "Government College", new Principal(132, "Prakash Das", 58, "Male", "Ph.D. in Physics", 31));
		College c33 = new College("Guwahati University", "Guwahati", 81000, "Government College", new Principal(133, "Madhuri Sharma", 51, "Female", "Ph.D. in Education", 24));
		College c34 = new College("Nagpur College", "Nagpur", 76000, "Private College", new Principal(134, "Vivek Joshi", 53, "Male", "Ph.D. in Computer Science", 25));
		College c35 = new College("Vadodara University", "Vadodara", 84000, "Government College", new Principal(135, "Nisha Patel", 49, "Female", "Ph.D. in Commerce", 21));
		College c36 = new College("Visakhapatnam College", "Visakhapatnam", 93000, "Private College", new Principal(136, "Ramesh Rao", 57, "Male", "Ph.D. in Engineering", 30));
		College c37 = new College("Mangalore University", "Mangalore", 88000, "Government College", new Principal(137, "Deepa Shetty", 46, "Female", "Ph.D. in Chemistry", 18));
		College c38 = new College("Jodhpur College", "Jodhpur", 70000, "Government College", new Principal(138, "Ashok Singh", 59, "Male", "Ph.D. in History", 32));
		College c39 = new College("Ludhiana College", "Ludhiana", 78000, "Private College", new Principal(139, "Gurpreet Kaur", 50, "Female", "Ph.D. in Psychology", 22));
		College c40 = new College("Srinagar University", "Srinagar", 86000, "Government College", new Principal(140, "Farooq Ahmed", 55, "Male", "Ph.D. in Political Science", 27));
		College c41 = new College("Kota College", "Kota", 69000, "Government College", new Principal(141, "Rekha Sharma", 48, "Female", "Ph.D. in Mathematics", 20));
		College c42 = new College("Raipur University", "Raipur", 75000, "Government College", new Principal(142, "Vikas Verma", 54, "Male", "Ph.D. in Economics", 26));
		College c43 = new College("Thiruvananthapuram College", "Thiruvananthapuram", 97000, "Government College", new Principal(143, "Anita Nair", 52, "Female", "Ph.D. in Biology", 24));
		College c44 = new College("Vijayawada College", "Vijayawada", 80000, "Private College", new Principal(144, "Suresh Reddy", 56, "Male", "Ph.D. in Management", 29));
		College c45 = new College("Madurai University", "Madurai", 72000, "Government College", new Principal(145, "Priyanka Kumar", 45, "Female", "Ph.D. in English", 17));
		College c46 = new College("Aurangabad College", "Aurangabad", 74000, "Government College", new Principal(146, "Rajendra Patil", 58, "Male", "Ph.D. in Physics", 30));
		College c47 = new College("Gwalior University", "Gwalior", 68000, "Government College", new Principal(147, "Seema Gupta", 50, "Female", "Ph.D. in Sociology", 22));
		College c48 = new College("Jamshedpur College", "Jamshedpur", 82000, "Private College", new Principal(148, "Amit Sinha", 53, "Male", "Ph.D. in Computer Science", 25));
		College c49 = new College("Allahabad University", "Prayagraj", 78000, "Government College", new Principal(149, "Kavita Singh", 49, "Female", "Ph.D. in Education", 21));
		College c50 = new College("Lucknow Institute", "Lucknow", 110000, "Private College", new Principal(150, "Arun Pratap", 57, "Male", "Ph.D. in Management", 28));
		College c51 = new College(c1);
		College c52 = new College(c2);
		College c53 = new College(c3);
		College c54 = new College(c4);
		College c55 = new College(c5);
		College c56 = new College(c6);
		College c57 = new College(c7);
		College c58 = new College(c8);
		College c59 = new College(c9);
		College c60 = new College(c10);
		College c61 = new College(c11);
		College c62 = new College(c12);
		College c63 = new College(c13);
		College c64 = new College(c14);
		College c65 = new College(c15);
		College c66 = new College(c16);
		College c67 = new College(c17);
		College c68 = new College(c18);
		College c69 = new College(c19);
		College c70 = new College(c20);
		College c71 = new College(c21);
		College c72 = new College(c22);
		College c73 = new College(c23);
		College c74 = new College(c24);
		College c75 = new College(c25);
		College c76 = new College(c26);
		College c77 = new College(c27);
		College c78 = new College(c28);
		College c79 = new College(c29);
		College c80 = new College(c30);
		College c81 = new College(c31);
		College c82 = new College(c32);
		College c83 = new College(c33);
		College c84 = new College(c34);
		College c85 = new College(c35);
		College c86 = new College(c36);
		College c87 = new College(c37);
		College c88 = new College(c38);
		College c89 = new College(c39);
		College c90 = new College(c40);
		
		System.out.println(c1);
		System.out.println(c2);
		System.out.println(c3);
		System.out.println(c4);
		System.out.println(c5);
		System.out.println(c6);
		System.out.println(c7);
		System.out.println(c8);
		System.out.println(c9);
		System.out.println(c10);
		System.out.println(c11);
		System.out.println(c12);
		System.out.println(c13);
		System.out.println(c14);
		System.out.println(c15);
		System.out.println(c16);
		System.out.println(c17);
		System.out.println(c18);
		System.out.println(c19);
		System.out.println(c20);
		System.out.println(c21);
		System.out.println(c22);
		System.out.println(c23);
		System.out.println(c24);
		System.out.println(c25);
		System.out.println(c26);
		System.out.println(c27);
		System.out.println(c28);
		System.out.println(c29);
		System.out.println(c30);
		System.out.println(c31);
		System.out.println(c32);
		System.out.println(c33);
		System.out.println(c34);
		System.out.println(c35);
		System.out.println(c36);
		System.out.println(c37);
		System.out.println(c38);
		System.out.println(c39);
		System.out.println(c40);
		System.out.println(c41);
		System.out.println(c42);
		System.out.println(c43);
		System.out.println(c44);
		System.out.println(c45);
		System.out.println(c46);
		System.out.println(c47);
		System.out.println(c48);
		System.out.println(c49);
		System.out.println(c50);
		System.out.println(c51);
		System.out.println(c52);
		System.out.println(c53);
		System.out.println(c54);
		System.out.println(c55);
		System.out.println(c56);
		System.out.println(c57);
		System.out.println(c58);
		System.out.println(c59);
		System.out.println(c60);
		System.out.println(c61);
		System.out.println(c62);
		System.out.println(c63);
		System.out.println(c64);
		System.out.println(c65);
		System.out.println(c66);
		System.out.println(c67);
		System.out.println(c68);
		System.out.println(c69);
		System.out.println(c70);
		System.out.println(c71);
		System.out.println(c72);
		System.out.println(c73);
		System.out.println(c74);
		System.out.println(c75);
		System.out.println(c76);
		System.out.println(c77);
		System.out.println(c78);
		System.out.println(c79);
		System.out.println(c80);
		System.out.println(c81);
		System.out.println(c82);
		System.out.println(c83);
		System.out.println(c84);
		System.out.println(c85);
		System.out.println(c86);
		System.out.println(c87);
		System.out.println(c88);
		System.out.println(c89);
		System.out.println(c90);
		
		System.out.println("=========================================Main Method Ends====================================");
	}

}
